### DISCUSSION TITLE
1.8 Unit Testing Expected Result

### DISCUSSION THREAD

**Discussion by jenna-adams** [dbt-labs/dbt-core#10428] [Q&A] [answered]
Hi,
I have a query that will not return any rows when certain criteria are met. I want to use a unit test to test this sad path, but I don't know what to put in the 'expect' part of the schema. Does anyone know what to put here?

```yml
mau_unit_tests:
    -  name: test_mau_sad_path
       description: "shows all clients with more than 40 users"
       model: mau_model
       given:
         -  input: usage_events
            rows:
              -  {...}
         -  input: clients
            rows:
              - {...}
       expect: ????
```
