### DISCUSSION TITLE
Issue with Passing sources.yml Data to Model's Macro During Testing

### DISCUSSION THREAD

**Discussion by megetron3** [dbt-labs/dbt-core#10555] [Q&A]
I'm encountering an issue during a unit test on a model using the `create_canonic_table` macro. The `cookbook.schema` and `cookbook.name`, expected to be fetched from sources.yml, are returning null, causing a compilation error in `dbt test'` It seems the data from `sources.yml` isn't correctly passed to the model's macro during testing. Assistance to resolve this issue would be appreciated.

I want to conduct a unit test on this model that employs the macro `create_canonic_table` as follows:
```
{{- config(materialized='incremental',alias = 'klarna')-}}
{{- create_canonic_table(ref('pos_raw_dlt_klarna'),source( 'POS_CANONIC_DTD_DLT_COOKBOOK', 'DLT_KLARNA')) }}
```

```
{%- macro create_canonic_table(source_model, cookbook, add_metadata_cols = True) %}
    {% set cookbook_db =  cookbook.database %}
    {% set cookbook_schema =  cookbook.schema %}
    {% set cookbook_name =  cookbook.name %}

    {%- if execute %}
        {%- set _cookbook = run_query('select ORIGINAL_NAME,CANONICAL_NAME,CAST_METHOD from ' + cookbook_db + '.' + cookbook_schema + '.' + cookbook_name) %}
        ...
```
However, the cookbook.schema and cookbook.name are returning null, which leads to an error when executing 'dbt test':
Compilation Error in unit_test test_pos_canonic_dlt_klarna (models/pos/canonic_dlt/pos_canonic_dlt_klarna.yml) can only concatenate str (not "NoneType") to str 14:44:14 1 of 1 ERROR
The sources.yml file, located in the same directory as the unittest and model files, is as follows:
```
version: 2
sources:

    - name: POS_CANONIC_DTD_DLT_COOKBOOK
    database: COOK_BOOKS
    schema: POS
    tables:
      - name: DLT_KLARNA
```
The test is defined as:
```
  unit_tests:
  - name: test_pos_canonic_dlt_klarna
    description: "test example"
    model: pos_canonic_dlt_klarna

    given:
      - input: ref('pos_raw_dlt_klarna')
        rows:
          - {'adjustment_id': '1',}
      - input: source( 'POS_CANONIC_DTD_DLT_COOKBOOK', 'DLT_KLARNA')
        rows:
          - { 'ORIGINAL_NAME': 'adjustment_id', 'CANONICAL_NAME': 'ADJUSTMENT_ID', 'CAST_METHOD': None }

    expect:
      rows:
        - {'adjustment_id': '1'}
```
