### DISCUSSION TITLE
how to configure a models subdirectory

### DISCUSSION THREAD

**Discussion by AverageBeerEnjoyer** [dbt-labs/dbt-core#10676] [Q&A]
Hi! We have a dbt project that has a lot of teams working on it. We agreed not to touch dbt_project.yml. In order to divide the areas of responsibility, It was decided to allocate their own directories for each team. Therefore, we would like to configure the general configuration of the models of each directory inside this directory. In all the examples from the documentation ([click](https://docs.getdbt.com/reference/model-configs) [click](https://docs.getdbt.com/reference/resource-configs/resource-path)), the directory settings are defined only in dbt_project.yml.

When trying to do something like this
```
#models/directory/subdirectory/subdirectory_config.yml
version: 2

models:
  directory:
    subdirectory:
      +distributed_replicated: true
```

I get this error
```
Parsing Error
  The schema file at models/directory/subdirectory/subdirectory_config.yml is invalid because the value of 'models' is not a list
```

How do I configure a subdirectory correctly without changing dbt_project.yml? Or maybe I missed something?
