### DISCUSSION TITLE
Feature Request: Enable Config and/or Meta Access in Model Tests

### DISCUSSION THREAD

**Discussion by DominikGolebiewski** [dbt-labs/dbt-core#10900] [Ideas]
### Description
Currently, tests in dbt (both model-level and column-level) cannot directly access model configurations or meta configurations during runtime using `config.get()` or `config.meta.get()`. While the model SQL itself can access these configurations, this functionality is not available in any test context. This limitation requires developers to implement workarounds using custom macros to access model configurations in tests.

### Current Behavior
When trying to access model configurations in tests (both model and column-level), the config context is not available:

```yaml
version: 2

models:
  - name: example_model
    tests:
      # Model-level test - doesn't work
      - dbt_expectations.expect_table_row_count_to_be_between:
          max_value: "{{ config.get('max_rows') }}"  # Returns None
          threshold: "{{ config.meta.get('threshold') }}"  # Returns None

    columns:
      - name: amount
        tests:
          # Column-level test - doesn't work
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: "{{ config.get('min_amount') }}"  # Returns None
              max_value: "{{ config.meta.get('max_amount') }}"  # Returns None
```

Current workarounds require creating custom macros to access the graph object:

```sql
{% macro get_model_config_value(model_name, config_key, default_value=none) %}
    {% set model_relation = ref(model_name) %}
    {% set model = graph.nodes.values() | selectattr('name', 'equalto', model_relation.name) | first %}
    {% if config_key in model.config %}
        {{ return(model.config.get(config_key)) }}
    {% else %}
        {{ return(default_value) }}
    {% endif %}
{% endmacro %}

{% macro get_model_meta_value(model_name, meta_key, default_value=none) %}
    {% set model_relation = ref(model_name) %}
    {% set model = graph.nodes.values() | selectattr('name', 'equalto', model_relation.name) | first %}
    {% if meta_key in model.config.meta %}
        {{ return(model.config.meta.get(meta_key)) }}
    {% else %}
        {{ return(default_value) }}
    {% endif %}
{% endmacro %}
```

### Proposed Solution
Enable direct access to model configurations and meta configurations in all test contexts using the same syntax available in model SQL files. This would allow:

```yaml
version: 2

models:
  - name: example_model
    tests:
      # Model-level test - should work
      - dbt_expectations.expect_table_row_count_to_be_between:
          max_value: "{{ config.get('max_rows') }}"
          threshold: "{{ config.meta.get('threshold') }}"

    columns:
      - name: amount
        tests:
          # Column-level test - should work
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: "{{ config.get('min_amount') }}"
              max_value: "{{ config.meta.get('max_amount') }}"
```

### Use Cases
1. Dynamic threshold testing based on model configuration and meta data
2. Environment-specific test parameters stored in config/meta
3. Reusable tests that adapt to model-specific parameters
4. Centralized configuration management for data quality rules
5. Business logic thresholds stored in meta and accessed by tests

### Benefits
1. Consistency with how config is accessed in model SQL files
2. Elimination of boilerplate workaround code
3. More maintainable and readable test configurations
4. Reduced complexity in implementing dynamic tests
5. Better separation of concerns between test logic and test parameters

### Implementation Considerations
1. The config and meta contexts would need to be made available during test compilation
2. Backward compatibility with existing test implementations
3. Clear documentation on scope and availability of config/meta values
4. Potential impact on test execution performance

### Example Implementation
Model configuration:
```sql
{{ config(
    materialized='table',
    min_amount=0,
    max_amount=1000,
    meta={
        'threshold': 0.95,
        'validation_rules': {
            'amount': {
                'min': 0,
                'max': 1000
            }
        }
    }
) }}

select * from {{ ref('source_table') }}
```

Proposed test usage:
```yaml
version: 2

models:
  - name: example_model
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
          max_value: "{{ config.get('max_rows', 1000000) }}"
          threshold: "{{ config.meta.get('threshold', 0.95) }}"

    columns:
      - name: amount
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: "{{ config.meta.get('validation_rules').get('amount').get('min', 0) }}"
              max_value: "{{ config.meta.get('validation_rules').get('amount').get('max', 1000) }}"
```

### Alternative Approaches Considered
1. Using custom macros (current workaround)
2. Implementing a global configuration system for tests
3. Creating a new test context with different syntax
4. Using vars instead of config/meta

These alternatives either don't provide the same level of granularity or introduce unnecessary complexity.

### Additional Context
This feature would align with dbt's goal of making data testing more accessible and maintainable. It would reduce the need for custom macros and make test configurations more consistent across projects.
