### DISCUSSION TITLE
check-model-has-description and existing data models

### DISCUSSION THREAD

**Discussion by markdiaper** [dbt-labs/dbt-core#11058] [Q&A]
Hi just wanted to check to see whether the above DBT checkpoint, when added to existing data would cause issues for existing data without descriptions or whether there was a way to use this check for data post its addition only?

**Comment by aiwithwhitehat** [comment]
To ensure that the `check-model-has-description` hook in `dbt checkpoint` only checks new or updated models, you can configure it to run as a pre-commit hook. This way, it will only validate the models that have been changed in your commits. Here's how you can set it up:

1. **Install pre-commit**:
   ```shell
   pip install pre-commit
   ```

2. **Create a `.pre-commit-config.yaml` file** in your repository root with the following content:
   ```yaml
   repos:
     - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
       rev: v2.0.1  # Use the latest version
       hooks:
         - id: check-model-has-description
           args: [--manifest, path/to/manifest.json]
   ```

3. **Install the pre-commit hook**:
   ```shell
   pre-commit install
   ```

With this setup, the `check-model-has-description` hook will only run on the files that are staged for commit, effectively limiting the check to new or updated models.
