### DISCUSSION TITLE
Test factories / partial fixtures to allow for more DRY code?

### DISCUSSION THREAD

**Discussion by wasabigeek** [dbt-labs/dbt-core#11153] [Ideas]
When writing unit tests, we have to copy most of the input data across tests, even if only a few columns have different data. This is tedious but also makes the tests all implicitly coupled (e.g. changes in logic might mean having to change all the test inputs) and less obvious on what the critical changed columns are. Fixtures/YAML anchors work great if the inputs are exactly the same, but this feels rarely the case.

For example, given the below:
```
      - input: ref('model_a')
        rows:
          - { foo: bar, bar: foo, ... }
      - input: ref('model_b')
        rows:
          - { foo: foo, bar: foo, ... }
      - input: ref('model_b')
        rows:
          - { foo: hello, bar: foo, ... }
```
Is there a way to have a default set of values `foo: bar, bar: foo` where individual data can be overridden, something like YAML aliases:
```
yaml_definitions:
- base_model: &base_model
  - foo: bar
     bar: foo
     ...
     
   
- input: ref('model_a')
  rows:
    - << *base_model
       foo: foo
# etc
```
But ideally more flexible across the various data format types? I've mostly worked with test "[factories](https://github.com/thoughtbot/factory_bot)" for example.
