### DISCUSSION TITLE
How to use vars from private package into multiple dbt projects

### DISCUSSION THREAD

**Discussion by LPauzies** [dbt-labs/dbt-core#11267] [Q&A]
Hello, I'm currently trying to factorize our dbt project, to achieve this, I have created a dbt package which is private. It is working well with macros, but when I try to import variables into my "main" dbt projects, I'm blocked.

package_dbt/dbt_project.yml
```YAML
name: package_dbt
version: 1.0
config-version: 2

macro-paths:
  - "macros"

vars:
  variable1: 20
```

main_project/packages.yml
```YAML
packages:
  - local: ../../../libraries/package_dbt
```

main_project/dbt_project.yml
```YAML
name: main
version: 1.0
config-version: 2

model-paths:
  - models

models:
    project_data:  # project_name
        marts:
          analytics
```

main_project/marts.my_mart.sql
```SQL
select {{ var('variable1') }};
```

As macros, I have tried `{{ var('package_dbt.variable1') }}` but does not work, like `{{ package_dbt.var('variable1') }}`

Do you have any ideas about this ? Am I missing something ? It seems weird to have the possibility to create packages but not share the variables...

Regards
