### DISCUSSION TITLE
Configuring + managing `schemas`

### DISCUSSION THREAD

**Discussion by jtcohen6** [dbt-labs/dbt-core#5781] [Ideas]
_A more specific version of https://github.com/dbt-labs/dbt-core/discussions/5099_

### Philosophical premise

I am less inclined nowadays to say dbt should aspire to be "Terraform for data warehouses." Rather than a fully generic and extensible framework for managing data warehouse objects, where we take the existence of those object types (tables, schemas, tasks, streams, roles, UDFs, ...) as our starting point, I think we should _always_ take jobs-to-be-done in data as our starting point (models, sources, exposures, tests, descriptions, granting access, ...), and treat data warehouse objects as implementation details / backend mechanisms for achieving those jobs.

### Ok, but we need schemas

_paraphrasing from https://github.com/dbt-labs/dbt-bigquery/issues/289#issuecomment-1237948296_

We're missing a mechanism for users to truly configure schemas/datasets in dbt today. We can agree on that, _without_ necessarily implying that dbt should first / eventually become a totally generic and extensible framework for managing all types of database objects.

dbt is already in the business of creating schemas/datasets, as soon as you define and run a model in a schema/dataset that does not yet exist:
https://github.com/dbt-labs/dbt-core/blob/e95e36d63b8fb479078d7cc4eed2e3e8f3b37f43/core/dbt/task/run.py#L423

This has come up in the context of labels (https://github.com/dbt-labs/dbt-bigquery/issues/22), persisting descriptions/comments (https://github.com/dbt-labs/dbt-core/issues/1714), grants ([dev blog](https://docs.getdbt.com/blog/configuring-grants#granting-permissions-on-other-object-types)), and managing "orphaned" objects (https://github.com/dbt-labs/dbt-core/issues/4957).

```yml
# dbt_project.yml ?? I'd really prefer not to keep overloading this file though

databases: # 'projects'? 'catalogs'? what about data platforms that don't support this third level?
  - name: my_database
    schemas: # or 'datasets'
      - name: important_schema  # actual schema name? or schema config --> generate_schema_name?
        description: This is my very important schema
        persist_docs: true  # add this as a comment
        grants:
          usage: ['role_a', 'group_b', 'user_c']
        manage_action: drop # drop orphaned objects in this schema
        # adapter specific configs
        hours_to_expiration: 3 # default for all tables created in this schema
        ...
```

**Big ideas:**
- When dbt runs `create schema`, it would take adapter-specific configs into account, persist the description as a comment, and so on.
- dbt would manage grants on the schema just as it would for views/tables. If it runs `create schema` for the first time, it adds every grant. If the schema already exists, it runs an introspective query to figure the current grants, calculates diffs, and applies if needed.
- If we add a `dbt manage` task (as proposed in #4957 / #5392), it would take action to manage (warn or drop) orphaned objects in that schema

**Questions:**
- Should dbt create _logical databases_ if they're configured, and don't already exist? e.g. in Snowflake, where it's low-lift, versus other platforms where the third-level namespace is "real infrastructure"
- Should the `database` + `schema` names be the _actual_ database/schema names in the database? Or should they match the schema *config* which is passed into 'generate_schema_name', and naturally differ by environment? I lean toward the latter, though it could be tricky!

**Comment by Fleid** [comment]
I personally think that schemas/datasets are enough of a thing to deserve to be represented by a fully fledged object. 
There are enough knobs and settings exposed by all vendors at that level for that. I know this is a fuzzy criteria, we can certainly expand on that ;)

But we need to clearly articulate whether or not this object has any kind of **model collection** aspect in its semantics in dbt.
Or, if in dbt world, it's a thing in itself with no relationships to models.

Here I'm mostly concerned about the inheritance story between schemas and tables (in the database) versus schema and models (as could be added in the dbt project) versus folders and models (the current dbt way). I'm not concerned about the implementation, or have much doubt about how it should work. I'm concerned about the expectations that users will have, and how it can make the mental model (hu hu) of models more complex to grasp.

Or do you see that happening:
```YAML
# dbt_project.yml ?? I'd really prefer not to keep overloading this file though

databases: # 'projects'? 'catalogs'? what about data platforms that don't support this third level?
  - name: my_database
    schemas: # or 'datasets'
      - name: important_schema  # actual schema name? or schema config --> generate_schema_name?
      tables:
        - name: myTable1
```
