### DISCUSSION TITLE
How to fill owner in docs UI?

### DISCUSSION THREAD

**Discussion by silentsokolov** [dbt-labs/dbt-core#6062] [Q&A]
![image](https://user-images.githubusercontent.com/398939/195804753-fa4a1d4d-ac28-4430-8c0f-46ad5f2d2ef6.png)

I have tried everything

```yaml
---
version: 2

models:
  - name: my_model
    description: "Foo bar"
    owner: 'XXXX'  # not work
    config:
       owner: 'XXXX' # not work
    meta:
       owner: 'XXXX' # not work
```

dbt-core 1.2.2
