### DISCUSSION TITLE
How to disable specific test instances from package model configuration?

### DISCUSSION THREAD

**Discussion by cndiac** [dbt-labs/dbt-core#6458] [Q&A]
Hello!

I would like to know if there is a possibility to disable only specific test instances from a package model configuration.

Project named `my_project` with the following structure:
```
models
  assets
    assets.sql
    assets.yml
```
Having the above structure, I know I am able to disable all tests referenced in the `assets.yml`, by adding the below in `dbt_project.yml`
```
tests:
  my_project:
    assets:
      +enabled: false
```
Is there any possibility to enter inside the `.yml` configuration and disable only `not_null` test instances for example (something like shown below)? 
```
tests:
  my_project:
    assets:
      not_null:
        +enabled:false
```

Thank you.
