### DISCUSSION TITLE
Model groups & access

### DISCUSSION THREAD

**Discussion by jtcohen6** [dbt-labs/dbt-core#6730] [Ideas]
_Part of the larger initiative for **Multi-project collaboration** (https://github.com/dbt-labs/dbt-core/discussions/6725)_

A law of nature: DAGs get messier as they get bigger. We'd like to provide constructs that make it easier for dbt project developers and maintainers to manage, and reason about, large DAGs.

There are two big ideas at play here:

1. **Groups** of models, each representing a coherent business domain or sequence of transformations, should be demarcated explicitly.
2. **Access:** Some models ought to be "public," and other models "private." Public models bring with them an intentional set of guarantees; someone has consciously marked them final & ready to use. Private models are all the intermediate, modular steps along the way, often materialized ephemerally or as views.

By developing constructs for **groups** and **access** within one project, we aim to provide mechanisms for scaling monoliths more gracefully. At the same time, we believe these same capabilities will extend to deployments that span multiple projects—whether monorepo or polyrepo.

### dbt developers can mark a model as "public."

This is an enum attribute: `access: public | private`. (In the future, there could be additional options. We're taking inspiration by [access modifiers](https://en.wikipedia.org/wiki/Access_modifiers) in object-oriented programming languages. If this is your first time hearing these terms, that's totally okay: inspiration != prerequisite.)

This should be a model-level attribute, **not** a configuration set & inherited for many models at once in `dbt_project.yml`. Every public model must be consciously and individually marked as such. This adds a teensy bit of friction, with the aim of ensuring intentionality.

Our initial & primary intent for `access` control is models. I expect readers of this discussion, and dbt developers, to spend 90% of their time thinking about access control for models. As with every new feature, though, we need to ask: What about all the other resource types?
- Can **seeds** + **snapshots** be marked “public”? Or should we require that they be wrapped in a public model?
- **Exposures?** (What would a downstream developer **do** with a public exposure, except know that a given upstream model is being exposed?)
- **Metrics (& entities)?** In general, I’d expect these to be public. Still, it should probably be *possible* to define “private” metrics that aren’t directly accessible to the semantic layer, especially intermediate metrics that serve as building blocks for derived metrics.

### dbt developers can define groups.

A group may contain models ("public" & "private"), seeds, snapshots, tests, analyses, ~exposures~, entities, metrics.
- Each resource (each model) may only belong to one group.
- Source tables are already implicitly grouped by the `source` they belong to.
- Macros aren't grouped. Their namespace is the project.

**Update:** In the first cut, exposures cannot belong to groups, and can't reference private models _at all_. They can define an `owner`, which _could_ be the same as the `owner` of a resource group.

A model's `group` should be configured explicitly.
- dbt should not implicitly infer group membership on the basis of other model properties or file path.
- [TBD] Should it be possible to configure `group` in `dbt_project.yml`, e.g. for all models in a subdirectory?

Groups can be selected (`group:`), similar to the `tag:` or `fqn:` selection methods.

Groups must define an `owner` (`dict<name: str, email: str, …>`), which then applies to objects within the group.
- If you want to use someone else's public model, you should know who they are! If you want to use their _private_ model, you should know whom to ask.
- This is analogous to the `loader` field in `sources`, and equivalent to the `owner` property already defined for `exposures`.
- When defined, we should show this `owner` metadata in auto-generated project documentation, rather than what we show currently for models (the database user that created the model’s physical table).
- The `owner` field should appear in `node_info`, for relevant events & structured logs, which could eventually enable more granular notifications.

This could look like:
```yaml
# models/marts/github/github.yml

groups:
  - name: github
    owner:
      # only 'name' or 'email' is required
      name: Jeremy
      email: data@jer.co
      # anything else is optional metadata
      slack: talk-jerco-memes
      github: jtcohen6
      whatever_else: you want

models:
  - name: int__github_issue_label_history
    group: github  # explicit opt-in
    access: private
  - name: fct_github_issues
    group: github
    access: public
```

Groups are **not** intended as a mechanism for model namespacing. Resource names must still be globally unique within **one** project. (In a future with multi-project deployments, we should support multiple models with the same name, so long as they're defined in separate projects. That will mean finally tackling a longtime limitation: https://github.com/dbt-labs/dbt-core/issues/1269.)

### Only public models can be referenced outside their group.

In other words, private models can be `ref`'d within the same `group`, but they *cannot* be `ref`'d by resources outside of their `group`. This enables cleaner dependency chains, with fewer interwoven arrows.

What about models **not** in a group? My sense is, they should be neither public nor private. They can be `ref`'d elsewhere, and they also aren't held to the minimum standard for all public models in a project (see below). **Motivation:** Preserve status quo, and avoid creating lots of tech debt for existing projects.

As soon as a model is added to a group, it becomes private, until explicitly marked public.

More devilish details:
- A `ref` call to a private model in a different group should raise an error: `Model 'model.my_project.my_model' depends on a node named 'private_model’, which is private in a different group.`
- Specific instances of generic tests defined on a "grouped" model should also be members of that model's group. E.g. If a private model `int_payments_aggregated` belongs to the group "finance," a `unique` test on that private model also belongs to the "finance" group, and is allowed to `ref` the model it is testing. However, to define a `relationships` test between two private models, they do actually need to be in the same group!
- Exposures can depend on a private model, if (and only if) both the exposure and the model are in the same group. That said, exposing a private model isn't recommended!
- [Future] When we add support for cross-project `ref`, only models explicitly marked public can be "exported" and referenced from other projects. A `ref` call to a private model in a different project should raise an error: `Model 'model.my_project.my_model' depends on a node named 'other_project.private_model’ which was not found`

### Public models ought to be "contracted," with a reliable (minimum) set of guarantees.

_For more on model contracts, see https://github.com/dbt-labs/dbt-core/discussions/6726_

We should implement a sensible & opinionated default. In my opinion:
- Every public model should be "contracted," whereby all columns are explicitly named & typed.
- The public model and all its columns should have a `description`.
- The public model should have at least one `unique` test (= validated primary key)

Users may optionally define their own set of expectations, overriding the default, that would be checked against every public model in the project.
- These expectations should be defined in a separate file. (Teams can take advantage of `.CODEOWNERS` rules, e.g. to require reviews from repository maintainers any time these expectations are updated.)
- These rules would be validated during parsing. The idea is not for public models to *magically inherit* these configurations, but simply to make sure that they match up.
- For example, a data team may want to enforce that every public model has `persist_docs` enabled (for integration with an external data catalog), is materialized as a `view` (on top of an underlying private table), and has at least a certain number of data quality tests. Imagine something like:
```yaml
# public_models.yml
description: true  # every public model must be described
config:  # every public model must match these configs
  constraints_enabled: true
  persist_docs:
    relation: true
    columns: true
  materialized: view
columns:
  description: true  # every column must be described
tests:  # matches 'test_name', with optional package prefix
  unique: 1  # at least one unique test, on any column
  installed_package.totally_custom_test: 3  # at least 3 of whatever this is
```

For totally custom & complex validation logic (e.g. "every column named `email` should have a BigQuery policy tag, a dbt `pii` tag, and a `description` containing the word 'pseudonymized'"), these rules could, as they can today, be written in:
- Jinja macros, enforced at compile/runtime via hook (a la [`dbt_project_evaluator`](https://hub.getdbt.com/dbt-labs/dbt_project_evaluator/latest/) and [`dbt_meta_testing`](https://hub.getdbt.com/tnightengale/dbt_meta_testing/latest/))
- Custom scripts that parse dbt metadata artifacts (`manifest.json`)

### Groups can be visualized

One of the biggest eventual benefits of sorting models into groups, slowly but surely, is enabling users to make visual sense of large & complex DAGs.

Our team has not been able to meaningfully invest in new features for `dbt-docs`. While I don't anticipate that changing, there are a few low-effort & high-value additions we may want to shoot for:
- DAG viz selection by `group`. (Even if we can't "roll up" to groups, or demarcate multiple groups simultaneously, just viewing all resources in one group is a good start.)
- Within model view, show its `access` rule (public or private).
- Within the DAG viz, an option to visually distinguish between public and private models.
- A view of all public models with the same owner (grouped by `name`).

### [Future] More ergonomic configuration?

(This ["paper cut" issue](https://github.com/dbt-labs/dbt-core/issues/2955) has a lot of upvotes, and is never far from my mind!)

We _might_ want to add `groups` as a new rung in the configuration ladder. If users could set some group-level config that cascades down to member models, they would be able to move some of that config out of `dbt_project.yml`. This does risk additional confusion, though, in trying to figure out where a model's configuration is coming from. We could always add this later.

```yaml
# dbt_project.yml
models:
  marts:
    some_config: some_default_value
```
```yaml
# models/marts/github/github.yml

groups:
  - name: github
    config:
      +some_config: override_default_value

models:
  - name: int__github_issue_label_history
    group: github
    # no model-level config -- uses group-level 'override' defined above
  - name: fct_github_issues
    group: github
    config:
      some_config: override_again  # this one wins
```

### [Aside] What's the distinction between a "public model" and an "entity"?

If you've been following the discussion about adding more semantic information to dbt ([https://github.com/dbt-labs/dbt-core/discussions/6644](https://github.com/dbt-labs/dbt-core/discussions/6644)), and the proposal for entities as a new node type, you might be wondering: What makes a model worthy to be "public," and what makes it worthy to power an entity?

This is a subtle distinction! I expect many `entities` to be built on top of public models, and to leverage those public models' contracted metadata (column names + data types) as a way to provide richer dimensions for semantic queries. We had several conversations about whether these ought to be one & the same, but ultimately decided that they deserve to be two separate constructs. Why?

Entities represent the **canonical representation of a business concept** (customers, orders) for downstream querying ("semantic"). Public models represent a logical dataset with a set of guarantees and clear ownership. If you'll indulge me in a metaphor: Database tables are raw materials; models are the means of logical production; public models are finished goods; entities are the packaging (declared interface) for those goods; metrics their clearly defined directions for intended use.
