### DISCUSSION TITLE
Allow the ability to pass arguments that are defined in yaml, to `run-operation`

### DISCUSSION THREAD

**Discussion by binhnefits** [dbt-labs/dbt-core#6861] [Ideas]
dbt `run-operation` allow us to run a custom macro and pass `args`. But the command can be quite long if the macro takes in a lot of arguments. It would be nice to have the ability to predefine the arguments in a yaml config and call that 'operation'.

An example config would look like
```yaml
operations:
  copy_into_table_a:
    macro: copy_into
    args:
       schema: raw
       table: table_a
       src_path: s3://bucket/path
```

And then call it using the operation name
```
dbt run-operation copy_into_table_a
```
