### DISCUSSION TITLE
How to unset the +schema or set the default schema in nested model?

### DISCUSSION THREAD

**Discussion by funes79** [dbt-labs/dbt-core#7146] [General]
# My profile defines a schema to "DBT"
```
--profiles.yml
dbt_playground:
  outputs:
    dev:
      ....
      database: TEST_DB
      schema: DBT
      type: snowflake
  target: dev
  
```
```
  projectx:
    staging:
      +materialized: view
      +schema: WORK # so these views will be created in DBT_WORK schema
      staging_tmp:
        +schema: "??"  # I would like to unset the +schema above, so use a default value coming from the profile. 
        # If I leave this as an empty string, dbt tries to use "DBT_"
        # if I do not define anything here then everthing under staging_tmp is created in "DBT_WORK" what I do not want. 
        # if I set to "DBT" then it creates in "DBT_DBT", again not what I want
 ```
