### DISCUSSION TITLE
Allow selectors.yml to optionally define a `schedule` property for a selector

### DISCUSSION THREAD

**Discussion by bgajdzis-forto** [dbt-labs/dbt-core#9141] [Ideas]
Ignored by DBT but available for documentation and potential integrations. It's a significant enough bit of metadata that it deserves its own place.

**Comment by cnolanminich** [comment]
Out of curiosity, would defining it as a meta tag property not satisfy your use case? We've discussed documenting schedule in the past and the meta dictionary is the place we would do it

**Reply by bgajdzis-forto** [reply]
Maybe I'm doing something wrong, but it seems to me that `meta` is not an accepted property in the selectors.yml file either. If that were available, I'm sure it would work just as well as having the schedule as a top-level property. 
Could you share a link to that discussion you mentioned? I couldn't find it, and I'd like to catch up on it before I start trying to reinvent the wheel here.

**Reply by cnolanminich** [reply]
the following works for me the same:

```yaml
# dbt project.yml

models:
  my_project:
    my_folder:
      my_table:
        +meta:
          test_meta_flag: "my_value"
```

```bash
dbt ls -s +config.meta.test_meta_flag:'my_value'
```

```yaml
# selector.yml
selectors:
  - name: find_a_meta_tag
    definition:
      union:
        - method: config.meta.test_meta_flag
          value: 'my_value'
```

```bash
dbt ls --selector find_a_meta_tag 
```

both return `my_table` as a result
