### DISCUSSION TITLE
Model depends on a source named which was not found happened again

### DISCUSSION THREAD

**Discussion by dishkakrauch** [dbt-labs/dbt-core#9202] [Q&A]
Hi, I've been reading docs twice but still this noisy error with schema crashes.
All code is related to PostgreSQL database.

./dbt_project.yaml:

```
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  demo:
    # Config indicated by + and applies to all files under models/example/
    dev:
      +materialized: table
```

models/dev/schema.yaml:

```
version: 2

models:
  - name: test
    description: "A sample schema"
    database: dbt
    schema: dev
    tables:
      - name: sample
        description: "A sample table for testing purposes"
        columns:
          - name: id
            description: "The primary key for this table"
```

models/dev/t_sample.sql

```
{{ config(materialized='table') }}

with source_t_sample as (
    select * from {{ source('test', 'sample') }}
),

final as (
    select * from source_t_sample
)

select * from final
```

dbt compile fails with:

`Model 'model.demo.t_sample' (models\dev\t_sample.sql) depends on a source named 'test.sample' which was not found`

I understand that it's a newbie question, but tired to switch source and object names

**Comment by AllanMogley** [comment]
Try to add these to your schema.yml file:

```
sources:
  - name: test
    schema: dev
    database: dbt

    tables:
      - name: sample
```

You had not defined your sources in the schema and DBT cant find it
