### DISCUSSION TITLE
Relationships fail silently when model doesn't exist, is it expected behavior ?

### DISCUSSION THREAD

**Discussion by dnnane** [dbt-labs/dbt-core#9259] [Q&A]
I'm encountering an unexpected behavior while defining relationships between models in my configuration. I have two models: `stg_jaffle_shop__customers` and `stg_jaffle_shop__orders`. In my YAML configuration, I attempted to establish a relationship between the `customer_id` in `stg_jaffle_shop__orders` and the `id` in `stg_jaffle_shop__customers` using dbt (Data Build Tool) as shown below:

```yaml
models:
  - name: stg_jaffle_shop__orders
    columns:
      - name: order_id
      - name: customer_id
        tests:
          - relationships:
              field: id
              to: ref('stg_jaffle_shop_customers')
```

However, I mistakenly wrote `stg_jaffle_shop_customers` instead of `stg_jaffle_shop__customers`. Despite this error, instead of receiving an error message due to the non-existent model, I'm getting the following output:

```
15:37:16 Found 6 models, 3 tests, 0 snapshots, 1 analysis, 192 macros, 0 operations, 6 seed files, 4 sources, 0 exposures, 0 metrics
15:37:16  
15:37:16 [WARNING]: Nothing to do. Try checking your model configs and model specification args
```

Is this behavior expected? I anticipated an error due to referencing a non-existent model. 

I use dbt `1.1.5` and the plugin bigquery `1.1.0`.
