### ISSUE TITLE
[Feature] Display the model-level constraints in the documentation generated by dbt, also put multiple primary key constraint for dbt-bigquery 

### ISSUE THREAD

**Issue by salimmoulouel** [dbt-labs/dbt-core#10025]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When I run dbt docs generate, it fails to include constraints defined at the model level in the documentation. For instance, if I establish a primary key at the model level, this information isn't reflected in the documentation. Instead, it only appears when I define the primary key at the column constraint level. However, because I'm utilizing dbt-bigquery, I'm restricted to declaring only one primary key field at the column level. This necessitates the declaration of primary keys at the model level, thereby creating a discrepancy in the documentation.

### Describe alternatives you've considered

To enhance the documentation process in dbt for dbt-bigquery, consider implementing the ability to define multiple primary key constraints at the column level while also ensuring that primary key constraints established at the model level are accurately reported in the documentation. This improvement would streamline the documentation process and provide comprehensive information about the primary keys used in the data models.

**Comment by dbeatty10** [comment]
Thanks for reaching out @salimmoulouel !

It sounds like you have two asks (please correct me if I'm misunderstanding!):
1. Display the model-level constraints in the documentation generated by dbt
2. Ability to define multiple primary key constraints at the column level

Assuming that complete documentation is your main ask here, I'm going to transfer this issue to dbt-docs for further consideration.

### 1. Display the model-level constraints in the documentation generated by dbt

You want the documentation website (`dbt docs generate && dbt docs serve`) to display a "PK" label for each of those columns, possibly like this?

<img width="300" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/40cc5275-f440-476d-8ec2-737fc9eb0c70">

### 2. Multiple primary key constraints at the column level

I don't remember off the top of my head, but I think there are technical reasons for us not supporting this. Feel free to open up a separate issue for this one if you'd like, but I'm guessing we'd close as "won't do".

<details>
<summary>

### Reprex
</summary>

`models/my_model.sql`

```sql
select 1 as pk_1, 2 as pk_2
```

`models/_models.yml`

```yaml
models:
  - name: my_model
    
    config:
      materialized: table

      contract:
        enforced: true
    
    # model-level constraints
    constraints:
      - type: primary_key
        columns: [pk_1, pk_2]

    # column-level constraints
    columns:
      - name: pk_1
        data_type: int
        constraints:
          - type: not_null
      - name: pk_2
        data_type: int
        constraints:
          - type: not_null
```

Build and launch the dbt project docs:
```shell
dbt docs generate && dbt docs serve
```
</details>
