### ISSUE TITLE
[Feature] Use ancestor/descendant terminology in YAML selectors instead of parent/child

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#10028]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Here's essentially what our docs currently say for [YAML selectors](https://docs.getdbt.com/reference/node-selection/yaml-selectors#full-yaml):

```yaml
definition:
  method: tag
  value: nightly

  # The following optional keywords map to the `+` and `@` graph operators:
  parents: true | false
  children: true | false
  parents_depth: 1                    # + operator (left-hand side) -- degrees to include IFF parents: true
  children_depth: 1                   # + operator (right-hand side)-- degrees to include IFF children: true
  childrens_parents: true | false     # @ operator -- includes all ancestors of all descendants IFF true
```

This feature request is to replace:
- `parents` with `ancestors`
- `children` with `descendants`
- `parents_depth` with `ancestors_depth`
- `children_depth` with `descendants_depth`
- `childrens_parents` with `descendants_ancestors`

### Describe alternatives you've considered

Let sleeping dogs lie.

That's probably what we will do here! 🐶

### Who will this benefit?

Anyone confused by what "parents" or "children" actually includes (since it has a different meaning than the standard human parent/child relationship).

For example: https://github.com/dbt-labs/dbt-core/issues/7703#issuecomment-1611126164

We already updated some of the docs in https://github.com/dbt-labs/docs.getdbt.com/issues/3755 / https://github.com/dbt-labs/docs.getdbt.com/pull/5313
