### ISSUE TITLE
[Feature] Add a private package definition

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#10083]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

dbt-cloud is adding support to allow users to define private packages in their `dependencies.yml` or `packages.yml`. The format will be similar to git package definition except that the `git` field will be the `private` field and an additional optional provider field. Example:
```
packages:
  - private: dbt-labs/my-awesome-repo
    # optional configs - same as for 'git' packages
    revision: ... # tag, release, branch, or commit SHA
    subdirectory: ...
	provider: github (if there are multiple providers)
```
In dbt-core, when such a package is defined, we should provide clear error message and tell user to use git definition.
