### ISSUE TITLE
[Bug] Dynamic project name breaks access configuration

### ISSUE THREAD

**Issue by pgoslatara** [dbt-labs/dbt-core#10092]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I have a dynamic project name and set `access` for a subdirectory via `dbt_project.yml`, all models in the subdirectory have an `access` value of `protected` regardless of what is specified as the `access` value.

### Expected Behavior

The value passed to `access` in `dbt_project.yml` is respected in the parsed project.

### Steps To Reproduce

1. `requirements.txt`:
```bash
dbt-core==1.7.14
dbt-duckdb==1.7.4
```
2. `dbt_project.yml`:
```yaml
name: "{{ 'sales_' ~ target.name }}"
version: '1.0.0'
profile: 'test'

analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  "{{ 'sales_' ~ target.name }}":
    +access: public
```
3. `profiles.yml`:
```yaml
test:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ":memory:"
```
3. `./models/test_public.sql`:
```sql
select 1 as id
```
4. Run:
```bash
dbt build
```
5. Examine `manifest.json`:
```python
import duckdb

conn = duckdb.connect(":memory:")
df = conn.query("""
select
    nodes."model.sales_dev.test_public".access
from './target/manifest.json'
""")
print(df)
```
```bash
┌───────────┐
│  access   │
│  varchar  │
├───────────┤
│ protected │
└───────────┘
```
The model is `protected` even though the configuration in `dbt_project.yml` specifies that it should be `public`.
6. We can force the output we want via:
`./models/test_public.sql`
```sql
{{ config(access='public') }}

select 1 as id
```
Run:
```bash
dbt build
```
```python
import duckdb

conn = duckdb.connect(":memory:")
df = conn.query("""
select
    nodes."model.sales_dev.test_public".access
from './target/manifest.json'
""")
print(df)
```
```bash
┌─────────┐
│ access  │
│ varchar │
├─────────┤
│ public  │
└─────────┘
```

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.11.6
- dbt:
Core:
  - installed: 1.7.14
  - latest:    1.7.14 - Up to date!

Plugins:
  - duckdb: 1.7.4 - Up to date!
```

### Which database adapter are you using with dbt?

bigquery, other (mention it in "Additional Context")

### Additional Context

* I'm setting up a dbt Mesh at a client that uses `dbt-bigquery` and encountered this issue. I reported this in the dbt Slack [here](https://getdbt.slack.com/archives/C04FP5LQA15/p1714656211001139), you can find more about our setup there.
* This issue does not arise when the `name` in `dbt_project.yml` is not dynamic, but this would prevent us from properly referencing which environment to use in our cross-project references so we do want our `name` to be dynamic.
