### ISSUE TITLE
support merge_update_columns logic for unit_tests

### ISSUE THREAD

**Issue by rburke45** [dbt-labs/dbt-core#10115]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When a model with set `merge_update_columns` is unit tested all fields are updated, not just those listed in `merge_update_columns`.

### Expected Behavior

When a model with set `merge_update_columns` is unit tested only the fields listed in `merge_update_columns` should be updated.

### Steps To Reproduce

Minimal example:
`table.sql`
```
{{
    config(
        materialized='table'
    )
}}

SELECT
  1 AS col1,
  1 AS col2,
  8 AS col3
UNION ALL
SELECT
  2 AS col1,
  1 AS col2,
  9 AS col3
UNION ALL
SELECT
  3 AS col1,
  1 AS col2,
  5 AS col3
```

`update.sql`
```
{{
    config(
        materialized='incremental',
        unique_key='col1',
        merge_update_columns=['col2'],
    )
}}

SELECT
  col1,
  col2,
  col3
FROM
  {{ref('table')}}
-- this filter will only be applied on an incremental run
{% if is_incremental() %}
WHERE   
  col2 > (SELECT MAX(col2) FROM {{ this }})
{% endif %}
```

`unit_test.yml`
```
unit_tests:
  - name: merge_update_test
    model: update
    overrides:
      macros:
        # unit test this model in "incremental" mode
        is_incremental: true 
    given:
      - input: ref('table')
        rows:
          - {col1: 1, col2: 2, col3: 3}
          - {col1: 2, col2: 3, col3: 4}

      - input: this
        rows:
          - {col1: 1, col2: 1, col3: 8}
          - {col1: 2, col2: 1, col3: 9}
          - {col1: 3, col2: 1, col3: 5}
    expect:
      rows:
        - {col1: 1, col2: 2, col3: 8}
        - {col1: 2, col2: 3, col3: 9}
```

Running this unit test gives the log output below. Calling `dbt run` to replicate the same data produces the expected behavior.

### Relevant log output

```shell
actual differs from expected:

@@ ,col1,col2,col3
→  ,1   ,2   ,8→3
→  ,2   ,3   ,9→4
```

### Environment

```markdown
- OS: macOS 14.4.1 (23E224)
- Python: Python 3.12.2
- dbt-core: 1.8.0b1
```

### Additional Context

I'm still relatively new to DBT, so please let me know if there's additional information I can provide.
