### ISSUE TITLE
[Bug] <title>

### ISSUE THREAD

**Issue by mmyers5** [dbt-labs/dbt-core#10130]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We are using docker compose in GitHub Actions to generate dbt docs and publish them to an external storage location. When the CI/CD job runs `docker compose run dbt docs generate --target nondev`, it randomly fails with the error: `AuthByKeyPair.prepare() takes 1 positional argument but 3 were given`. Sometimes the CI/CD job succeeds, and I haven't been able to get the failure to trigger locally.

It is worth noting that the following CI/CD job always succeeds with the command: `dbt --warn-error debug --target nondev`.

### Expected Behavior

No flaky job results

### Steps To Reproduce

1. Here are the environment variables that exist:
    - SNOWFLAKE_ACCOUNT
    - SNOWFLAKE_USER
    - SNOWFLAKE_RSA_KEY_SECRET
    - SNOWFLAKE_RSA_KEY_PASSWORD
    - SNOWFLAKE_ROLE
    - SNOWFLAKE_DATABASE
    - SNOWFLAKE_WAREHOUSE
    - SNOWFLAKE_TARGET_SCHEMA
1. This is the profile that we are using:
    ```yml
    nondev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      authenticator: "{{ env_var('SNOWFLAKE_AUTHENTICATOR', 'snowflake') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', None) }}"
      private_key: "{{ env_var('SNOWFLAKE_RSA_KEY_SECRET', '') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_RSA_KEY_PASSWORD', '') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_TARGET_SCHEMA', 'dev') }}"
      threads: 8 # The number of models that can run concurrently in production
      client_session_keep_alive: False
      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false
    ```
1. Here is the docker image that we are using: `ghcr.io/dbt-labs/dbt-snowflake:1.7.3`. We have an entrypoint that prefixes any command being passed into the docker container with `dbt`, so `docker compose run dbt docs` will run `dbt docs`.
1. Upstream job that is being run in CI/CD successfully:
    - `docker compose build dbt`
    - `docker compose run dbt --warn-error parse --target nondev`
    - `docker compose run dbt --warn-error debug --target nondev`
1. Steps of the job that is failing:
    - `docker compose build dbt`
    - `docker compose run dbt_gc docs generate --target nondev`

### Relevant log output

```shell
2024-05-10 18:41:18 INFO     info                 Preparing dbt command to run
2024-05-10 18:41:18 INFO     info                 Running dbt command `dbt docs generate --target nondev`
18:41:20  Running with dbt=1.7.11
18:41:21  Registered adapter: snowflake=1.7.3
18:41:21  Unable to do partial parsing because saved manifest not found. Starting full parse.
18:41:32  Found 420 models, 2 analyses, 154 tests, 19 seeds, 351 sources, 33 exposures, 0 metrics, 1035 macros, 0 groups, 0 semantic models
18:41:32  
18:41:43  Encountered an error:
Database Error
  AuthByKeyPair.prepare() takes 1 positional argument but 3 were given
```

### Environment

```markdown
- OS: Ubuntu 22.04.4
- Python: 3.10.7
- dbt: 1.7.11
```

### Which database adapter are you using with dbt?

snowflake
