### ISSUE TITLE
[Bug] `flags.warn_error_options.silence` should be settable `dbt_project.yml`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#10160]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Missing `silence` here:

https://github.com/dbt-labs/dbt-core/blob/32a7f82772d90a4b9ab443908f5f4455d0aa2c73/core/dbt/cli/flags.py#L53-L62

### Expected Behavior

```python
def convert_config(config_name, config_value):
    """Convert the values from config and original set_from_args to the correct type."""
    ret = config_value
    if config_name.lower() == "warn_error_options" and type(config_value) == dict:
        ret = WarnErrorOptions(
            include=config_value.get("include", []),
            exclude=config_value.get("exclude", []),
            valid_error_names=ALL_EVENT_NAMES,
            silence=config_value.get("silence", []),  # this line is missing above
        )
    return ret
```

### Steps To Reproduce

1. Create a project with a test in it
```yml
# dbt_project.yml
flags:
  warn_error_options:
    silence:
      - TestsConfigDeprecation

tests:  # has been renamed to data_tests
  +enabled: true
```
2. `dbt parse` -> still see the deprecation warning ("The `tests` config has been renamed to `data_tests`")
3. Apply the patch shown above -> `dbt parse` -> no deprecation warning

### Environment

```markdown
- Python: 3.10.11
- dbt: 1.8.0
```
