### ISSUE TITLE
[Bug] unit tests' comparisons are sometimes sensitive to the order of records returned

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#10167]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Normally, dbt's unit tests don't care whether rows are ordered the same as the expect block or not. 

```
id 
---
1
2
3
```
is just as good as 
```
id
---
3
2
1
```
as far as 
```
...
expect: 
  rows:
    - {"id": 2}
    - {"id": 3}
    - {"id": 1}
```
is concerned. 

I have a use case which _is_ order dependent, but I don't know why. 

### Expected Behavior

Order to not matter

### Steps To Reproduce

Unit test yaml: 

```
unit_tests:
  - name: reworked_compare_identical_tables_multiple_null_pk_with_duplicate_rows
    description: All rows with a null ID are identical. They should be returned as individual rows instead of being combined
    model: unit_reworked_compare
    
    given:
      - input: ref('unit_test_model_a')
        rows:
          - { "id": , "col1": "abc", "col2": "def" }
          - { "id": , "col1": "abc", "col2": "def" }
          - { "id": 3, "col1": "nop", "col2": "qrs" }
      - input: ref('unit_test_model_b')
        rows:
          - { "id": , "col1": "abc", "col2": "def" }
          - { "id": , "col1": "abc", "col2": "def" }
          - { "id": , "col1": "abc", "col2": "def" }
          - { "id": 3, "col1": "nop", "col2": "qrs" }
        
    expect:
      rows:
        - {"dbt_audit_row_status": 'nonunique_pk', 'id': , dbt_audit_num_rows_in_status: 3}
        - {"dbt_audit_row_status": 'nonunique_pk', 'id': , dbt_audit_num_rows_in_status: 3}
        - {"dbt_audit_row_status": 'nonunique_pk', 'id': , dbt_audit_num_rows_in_status: 3}
        - {"dbt_audit_row_status": 'identical', 'id': 3, dbt_audit_num_rows_in_status: 1}

    overrides:
      vars:
        reworked_compare__columns: ['id', 'col1', 'col2']
        reworked_compare__event_time:
        reworked_compare__primary_key_columns: ['id']
```

The tested model (which is just a call to a macro)
```
--models/unit_reworked_compare.sql
{{ 
    audit_helper.reworked_compare(
        "select * from " ~ ref('unit_test_model_a'),
        "select * from " ~ ref('unit_test_model_b'),
        primary_key_columns=var('reworked_compare__primary_key_columns'),
        columns=var('reworked_compare__columns'),
        event_time=var('reworked_compare__event_time')
    ) 
}}
```

```
--models/unit_test_model_a
select 12 as id, 22 as id_2, 'xyz' as col1, 'tuv' as col2, 123 as col3, {{ dbt.current_timestamp() }} as created_at
```

```
--models/unit_test_model_b
select 12 as id, 22 as id_2, 'xyz' as col1, 'tuv' as col2, 123 as col3, {{ dbt.current_timestamp() }} as created_at
```
(Yes, unit_test_model_a and unit_test_model_b are identical! They're not used in production contexts, just to define the columns so they can be overridden by the actual test)

Log output when I run `dbt test -s : 
```
23:23:49  Failure in unit_test reworked_compare_identical_tables_multiple_null_pk_with_duplicate_rows (models/unit_test_wrappers/unit_reworked_compare.yml)
23:23:49    

actual differs from expected:

@@ ,DBT_AUDIT_ROW_STATUS,ID  ,DBT_AUDIT_NUM_ROWS_IN_STATUS
---,nonunique_pk        ,null,3
---,nonunique_pk        ,null,3
---,nonunique_pk        ,null,3
   ,identical           ,3   ,1
+++,nonunique_pk        ,null,3
+++,nonunique_pk        ,null,3
+++,nonunique_pk        ,null,3
```

But if I reorder the expect block so that the identical row is on top:

```
    expect:
      rows:
        - {"dbt_audit_row_status": 'identical', 'id': 3, dbt_audit_num_rows_in_status: 1}
        - {"dbt_audit_row_status": 'nonunique_pk', 'id': , dbt_audit_num_rows_in_status: 3}
        - {"dbt_audit_row_status": 'nonunique_pk', 'id': , dbt_audit_num_rows_in_status: 3}
        - {"dbt_audit_row_status": 'nonunique_pk', 'id': , dbt_audit_num_rows_in_status: 3}
```

The test passes. 

Compiled code: 
[reworked_compare_identical_tables_multiple_null_pk_with_duplicate_rows.txt](https://github.com/dbt-labs/dbt-core/files/15342181/reworked_compare_identical_tables_multiple_null_pk_with_duplicate_rows.txt)

### Environment

```markdown
00:08:41  dbt version: 1.8.0-b3
00:08:41  python version: 3.11.0
00:08:41  python path: /Users/joel/venvs/dbt-dev/bin/python3
00:08:41  os info: macOS-14.4.1-x86_64-i386-64bit
```

### Additional Context

I _think_ it's something to do with the fact that I'm only testing a subset of columns, or maybe that there are null values? Even though the tested columns are all identical, the extra columns that the results return do vary. I made a Loom of a [different unit test](https://github.com/joellabes/dbt-audit-helper/blob/df95fcae469a998b8098d3429daa3a6ed99d4e28/integration_tests/models/unit_test_wrappers/unit_reworked_compare.yml#L58-L83) which is easier to demonstrate with: https://www.loom.com/share/23b636f08019437eb2b09c912e9723fb

You can see [all of my assorted tests here](https://github.com/joellabes/dbt-audit-helper/blob/df95fcae469a998b8098d3429daa3a6ed99d4e28/integration_tests/models/unit_test_wrappers/unit_reworked_compare.yml).
