### ISSUE TITLE
[Impl] Allow generic tests to accept arbitrary configs

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#10197]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

Currently, we only support a specific set of named configurations for generic tests. That list is defined [here](https://github.com/dbt-labs/dbt-core/blob/09243d1e5d178c7e3051bc63d33816cafaa4c98b/core/dbt/parser/generic_test_builders.py#L83-L99) and accessed [here](https://github.com/dbt-labs/dbt-core/blob/09243d1e5d178c7e3051bc63d33816cafaa4c98b/core/dbt/parser/generic_test_builders.py#L135).

The context is that we support two syntaxes for passing configs into generic tests:
```yml
# recommended since dbt v0.20
models:
  - name: my_model
    columns:
      - name: colour
        tests:
          - accepted_values:
              values: ['blue', 'red']
              config:
                severity: warn
```
```yml
# legacy (supported for backwards compatibility)
models:
  - name: my_model
    columns:
      - name: colour
        tests:
          - accepted_values:
              values: ['blue', 'red']
              severity: warn                
```
In this example, `values` is an argument being passed into `accepted_values`, whereas `severity` is a configuration being set for the test.

In the legacy syntax, there is no distinction between "arguments" and "configurations." With the new recommended syntax, there is a distinction, because all configs are nested under `config`.

The desirable outcome is that:
- Users can pass whatever configs they want into `config:` (new syntax), e.g. `snowflake_warehouse`
- We continue to use the explicit list of named configs to provide backwards compatibility for the legacy syntax

### Acceptance criteria

1. Users can pass whatever configs they want into `config:` (new syntax), e.g. `snowflake_warehouse`
2. We continue to use the explicit list of named configs to provide backwards compatibility for the legacy syntax

To make it concrete: In the following example, `accepted_values_my_model_colour__blue__red` should end up with both configurations `severity: warn` and `custom_config: custom_value`.
```yaml
models:
  - name: my_model
    columns:
      - name: colour
        tests:
          - accepted_values:
              values: ['blue', 'red']
              severity: warn
              config:
                custom_config: custom_value
```

### Suggested Tests

In the example above, the test should be parsed to have both configs: `custom_config` via recommended syntax, and `severity` via old syntax.

It should be possible to write a unit test for this, but the logic is baked into `TestBuilder`, which is quite complicated. Refactoring that is out of scope for this particular issue.

The closest existing functional test case is [this one](https://github.com/dbt-labs/dbt-core/blob/09243d1e5d178c7e3051bc63d33816cafaa4c98b/tests/functional/schema_tests/test_schema_v2_tests.py#L418-L452).

As such, it might be best to create a new functional test instead.

### Impact to Other Teams

Adapters

### Will backports be required?

no

### Context

Original issue:
- https://github.com/dbt-labs/dbt-core/issues/5532
