### ISSUE TITLE
[Bug] Tests with severity: error is not throwing error

### ISSUE THREAD

**Issue by za-dorogoj** [dbt-labs/dbt-core#10210]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

On project level (dbt_project.yml) we have `severity: warn`, and on source yml file we have `severity: error` on not_null. But when we run in DAG dbt build test model etc, it doesn't fail at all, even didn't show warn. And in that source table we have one null value

### Expected Behavior

According to this page https://docs.getdbt.com/reference/data-test-configs yml tests have a precedence over generic tests and dbt_project.yml. So it is expected to throw error and not run any models after. 

### Steps To Reproduce

1. Put `severity: warn` in `dbt_project.yml`
2. Put `severity: error error_if: ">0"` on not_null tests where is 1 null exists (source.yml file)
like this:
    ```sql
                tests:
                  - not_null:
                      config:
                        severity: error
                        error_if: ">0"
    ```

3. Run in dag

    ```shell
    dbt build \
                --resource-types seed test model \
    ```

### Environment

```markdown
- OS: Linux/Ubuntu
- Python: 3.11
- dbt:1.7.3
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

From logs:
```
Running with dbt=1.7.3
Installing brooklyn-data/dbt_artifacts
Installed from version 2.6.3
Installing fivetran/fivetran_log
Installed from version 1.7.3
Installing dbt-labs/audit_helper
Installed from version 0.11.0
Installing entechlog/dbt_snow_mask
Installed from version 0.2.5
Installing fivetran/fivetran_utils
Installed from version 0.4.10
Installing dbt-labs/spark_utils
Installed from version 0.3.0
Installing calogica/dbt_date
Installed from version 0.10.1
Installing dbt-labs/dbt_utils
Installed from version 1.1.1
Installing calogica/dbt_expectations
Installed from version 0.10.3
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @za-dorogoj !

Do you see that source if you do a listing?

```shell
dbt list --resource-types source
```

And do you see that test also?

```shell
dbt list --resource-types test
```

**Comment by za-dorogoj** [comment]
Hello,
Yes, I see that source when I listed it, and test for it also.

Best regards,

Anastasiia Zadorozhna

Data Analyst



T +46 12 345 67 89

*M *

+31 6 43 54 11 22

E  ***@***.***

W easyparkgroup.com <http://www.easyparkgroup.com>

ParkNow Group B.V.

Wisselwerking 40, 1112 XR, Diemen, The Netherlands

EasyPark Group proudly presents EasyPark, Parkmobile, RingGo and Park-line

**Comment by dbeatty10** [comment]
But when you do the same exact command, but swap out `list` for `build` (or `test`) instead, then the test doesn't execute?

**Comment by za-dorogoj** [comment]
It works, but it shows warn instead of error. And according the documentation, source.yml file with severity error has to throw error, no matter what is in dbt_project.yml file.

**Comment by dbeatty10** [comment]
Could you try the following in a fresh stand-alone dbt project and see if it works for you or not?

When I tried it out, it used the `error` severity as desired.

`seeds/my_seed.csv`

```csv
id
1
""
```

`models/_sources.yml`

```yaml
sources:
  - name: my_source
    database: "{{ target.database }}"  
    schema: "{{ target.schema }}"  
    tables:
      - name: my_seed
        columns:
          - name: id
            tests:
              - not_null:
                  config:
                    severity: error
                    error_if: ">0"
```

`dbt_project.yml`

```yaml
name: "my_project"
version: "1.0.0"
config-version: 2
profile: "snowflake"

tests:
  my_project:
    +severity: warn
```

Run these commands:

```shell
dbt seed --full-refresh
dbt test
```

**Comment by za-dorogoj** [comment]
I created a stand-alone project, as described, and the test returns an error. This tells me that some configuration in our project is incorrect.
We have a layered setup (due to the same infrastructure existing in multiple regions, but additional sources also existing in some of those regions), which we have implemented as a "core" package that is included in all of our "regional" projects. The "core" package has all tests set to "warn" for the "regional" package and "error" in source.yml (which are in core). The test that is acting oddly is in "core", accessed from "region". We expect it to use severity "error", but it instead has severity "warn". 
How do we need implement it for core and regional to use warning for all tests, except the one where we put error?

**Comment by dbeatty10** [comment]
I think the key to successful layered setups is to apply config to [all tests _in your project_](https://docs.getdbt.com/reference/resource-configs/resource-path#apply-config-to-all-models-in-your-project) rather than applying config to [_all_ tests from _all_ packages](https://docs.getdbt.com/reference/resource-configs/resource-path#apply-config-to-all-models).

It sounds like you have the following layered setup:
- The `core` package has no dependencies
- The `regional` package depends on `core`
- The `final_dbt_project` package depends on `regional`

Did you try something like the following in your `dbt_project.yml` files?

### `core` package

```yaml
name: "core"  # 👇 put this package name in all the resource configurations below
version: "1.0.0"
config-version: 2
profile: "postgres"

tests:
  core:  # 👈 put the package name here
    +severity: warn
```

### `regional` package

```yaml
name: "regional"  # 👇 put this package name in all the resource configurations below
version: "1.0.0"
config-version: 2
profile: "postgres"

tests:
  regional:  # 👈 put the package name here
    +severity: warn
```

### `final_dbt_project` package

```yaml
name: "final_dbt_project"  # 👇 put this package name in all the resource configurations below
version: "1.0.0"
config-version: 2
profile: "postgres"

tests:
  final_dbt_project:  # 👈 put the package name here
    +severity: warn
```

### Example

I created example dbt packages and projects like described above with appropriate `packages.yml` and `dbt_project.yml` files along with a couple tests defined in the `core` package. Then I ran a series of dbt commands while in the `final_dbt_project` project.

I could see the two different tests I configured in my `core` package:

```shell
$ dbt list -s resource_type:test

14:43:10  Running with dbt=1.7.14
14:43:10  Registered adapter: postgres=1.7.14
14:43:10  Found 2 models, 1 seed, 2 tests, 2 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
core.source_not_null_source_1_my_seed_id
core.source_not_null_source_2_my_seed_id
```

And it also respected my test configurations, using warning for all tests, except the one where I put error:

```shell
$ dbt test

14:45:10  Running with dbt=1.7.14
14:45:11  Registered adapter: postgres=1.7.14
14:45:11  Found 2 models, 1 seed, 2 tests, 2 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
14:45:11  
14:45:11  Concurrency: 5 threads (target='postgres')
14:45:11  
14:45:11  1 of 2 START test source_not_null_source_1_my_seed_id .......................... [RUN]
14:45:11  2 of 2 START test source_not_null_source_2_my_seed_id .......................... [RUN]
14:45:11  2 of 2 FAIL 1 source_not_null_source_2_my_seed_id .............................. [FAIL 1 in 0.09s]
14:45:11  1 of 2 WARN 1 source_not_null_source_1_my_seed_id .............................. [WARN 1 in 0.10s]
14:45:11  
14:45:11  Finished running 2 tests in 0 hours 0 minutes and 0.61 seconds (0.61s).
```

### Summary

Since it looks like dbt is behaving correctly according to the documentation in the [resource path](https://docs.getdbt.com/reference/resource-configs/resource-path) page, I'm going to close this issue as not actually a bug.

But please let us know if it's not actually working that way.
