### ISSUE TITLE
[Feature] populate model['constraints'] even if the contract is not enforced

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#10219]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

From @kmarq in https://github.com/dbt-labs/dbt-core/issues/10195:

Recreated some previous testing of constraints. If you define a primary_key constraint on a column

```
    columns:
      - name: col_1
        data_type: string
        constraints:
          - type: not_null
          - type: primary_key
```
The constraint shows up in the model.columns
```
"columns": {
        "col_1": {
            "constraints": [
                {
                    "type": "not_null",
                    "warn_unenforced": true,
                    "warn_unsupported": true
                },
```
whether the contract enforcement is true or false.

If you define a composite primary_key on the model
```
models:
  - name: model_a
    config:
      contract:
        enforced: true
    description: description
    columns:
      - name: col_1
        data_type: string
        constraints:
          - type: not_null
          - type: primary_key
      - name: col_2
        data_type: string
        constraints:
          - type: not_null
    constraints:
      - type: primary_key
        columns: [col_1, col_2]
```

Then in the model.constraints you will see this ONLY if contract enforcement is true:
```
 "constraints": [
        {
            "columns": [
                "col_1",
                "col_2"
            ],
            "type": "primary_key",
            "warn_unenforced": true,
            "warn_unsupported": true
        }
    ],
 "contract": {
        "alias_types": true,
        "checksum": "65ba38db6e4dd6a88418461c76b805acd2e39a113404a8a9c3d556c020564ea4",
        "enforced": true
    },
```
compared to false:
```
"constraints": [],
"contract": {
        "alias_types": true,
        "enforced": false
    },
```
