### ISSUE TITLE
[Feature] Unit Tests Should Support ref & source statements when specifying rows with sql

### ISSUE THREAD

**Issue by ernestoongaro** [dbt-labs/dbt-core#10227]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Was speaking to Roberto Zagni. He has a table with some sample rows he'd like to easily reference, something like this:
```
given:
      - input: ref('stg_tpch_customers')
        format: sql
        rows: |
          select customer_key from {{ target.database ~ '.' ~ target.schema }}.stg_tpch_customers where is_testing_row = true
``` 
would like to use the `ref` or perhaps `source` statement instead

### Describe alternatives you've considered

{{ target.database ~ '.' ~ target.schema }}.<table_name>
