### ISSUE TITLE
[Bug] `dbt -v` doesn't know that adapters are decoupled from core

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#10230]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I installed dbt-core from the main branch, and ran `dbt -v`. 

I got this output: 

```
(dbt-dev) joel@Joel-Labes dbt-audit-helper % dbt -v
Core:
  - installed: 1.9.0-a1
  - latest:    1.8.1    - Ahead of latest version!

Plugins:
  - snowflake: 1.8.2   - Not compatible!
  - postgres:  1.9.0a1 - Ahead of latest version!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Expected Behavior

As of 1.8, the fact that the Snowflake adapter has a different minor version isn't a problem. dbt run etc works fine, it's just the warnings that are coming from the version checking code. 

### Steps To Reproduce

Install a version of dbt calling itself 1.9 alongside a 1.8 vintage of an adapter
run `dbt -v`

### Environment

```markdown
- OS: 
- Python:
- dbt: 1.9.0-a1
```
