### ISSUE TITLE
[Bug] the run_query macro causes unit tests to fail with a SQL Compilation error

### ISSUE THREAD

**Issue by kandji-stephen** [dbt-labs/dbt-core#10241]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm trying unit tests with a model that has a couple `run_query` macro calls. I found that this macro causes the unit test to fail with a SQL compilation error. This model can be run without the unit test and it will compile correctly. 
```
  002003 (42S02): SQL compilation error:
  Object '__DBT__CTE__BASE_TABLE' does not exist or not authorized.
```

Here's a simple model and unit test which will produce this error.

`simple_test_model.sql`:
```sql
{% set query %}
    SELECT max(created_at) 
    from {{ ref('base_table') }}
{% endset %}
{% set max_date = run_query(query) %}

select *
from {{ ref('base_table') }}
```

Unit test:
```yaml
unit_tests:
  - name: simple_test_model_test
    model: simple_test_model
    given:
      - input: ref('base_table')
        rows:
          - {created_at: "2024-01-05T10:10:10Z"}
    expect:
      rows:
        - {created_at: "2024-01-05T10:10:10Z"}
```

### Expected Behavior

Expect the unit test to succeed (or at least not crash)

### Steps To Reproduce

1. Setup the model `simple_test_model.sql` using example model above.
2. Configure unit like the example above.
3. Execute the test with `dbt test --select simple_test_model`

### Environment

```markdown
- OS: MacOS 14.3
- Python: 3.10.10
- dbt: 1.8.1
- dbt-snowflake: 1.8.2
```

### Which database adapter are you using with dbt?

snowflake

**Comment by pinkham-eh** [comment]
We are also experiencing this issue on 
```
MacOS 14.5
Python 3.9.16
dbt 1.8.1
dbt-snowflake 1.8.2
dbt-adapters 1.2.1
```

**Comment by rd-andreas-lay** [comment]
Same problem here

**Comment by kangshung** [comment]
Bump. Problem still exists, and also on BigQuery.

```
Running with dbt=1.8.7
Registered adapter: bigquery=1.8.3
```

**Comment by jomach** [comment]
1+

**Comment by vmtuan12** [comment]
experiencing this too

**Comment by MichelleArk** [comment]
Unfortunately the root cause of this issue is pretty entrenched into the overall approach dbt takes to build and compile unit tests via CTE injection of input models and then resolving refs to those CTEs. The run_query has its ref resolving to the mock CTE faithfully, but of course that CTE does not exist within the context of the run_query statement and so you get the error from the issue.

I think a fix would be pretty involved - we'd need a different strategy for building unit test nodes and mock inputs for models that make use of the 'run_query' macro. Either we'd need to inject CTEs into the run_query input statement itself, or try to inline the mock CTEs directly within the statement.

A workaround could be to override the run_query macro as part of the test definition and stub out its return value. I put together a small example of how that would look in a [test case here](https://github.com/dbt-labs/dbt-core/pull/11990/files#diff-eff928f1191043e982909b6ee300c13a6711f6aa1758f164bc6353af0792202cR24-R26).

**Comment by OSalama** [comment]
The suggestion by @MichelleArk above works great if you have a single `run_query` call in your macro, and here's a tweaked override value to allow you to access the results in "columns":
```
overrides:
      macros:
        run_query: {"columns":[['2026-04-04']]}
```

If you want to use multiple `run_query` statements in a single model then you can do something awful like this:

Model CTE:
```
WITH cte_one AS (
    SELECT *
    FROM {{ ref('my_ref_table') }}
    {% if is_incremental() %}
        WHERE
            {% if execute %}
                {% if var('IS_TEST', false) %}
                    {% set max_ingest_date = var('TEST_MAX_INGEST_DATE') %}
                    {% set max_id_value = var('TEST_MAX_ID_VALUE %}
                {% else %}
                    {% set max_ingest_date = run_query("SELECT MAX(ingest_date) FROM " ~ this).columns[0][0] %}
                    {% set max_id_value = run_query("SELECT MAX(id) FROM " ~ this).columns[0][0] %}
                {% endif %}
                ingest_date >= '{{ max_ingest_date }}'
                AND id > {{ max_id_value }}
            {% endif %}
    {% endif %}
),
...
```

Unit test entry:
```
  - name: test_my_table_incremental
    model: my_table
    overrides:
      macros:
        is_incremental: true
      vars:
        IS_TEST: true
        TEST_MAX_INGEST_DATE: '2026-01-01'
        TEST_MAX_ID_VALUE:  42
...
```
