### ISSUE TITLE
[Bug] `warn_error_options.silence` not working within `dbt_project.yml`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#10278]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

CLI flag works:
```shell
dbt --warn-error-options '{"error": "all", "silence": ["TestsConfigDeprecation"]}' test --no-partial-parse
```

Environment variable works:
```shell
export DBT_WARN_ERROR_OPTIONS='{"error": "all", "silence": ["TestsConfigDeprecation"]}'
dbt test --no-partial-parse
```

But project flag in `dbt_project.yml` is not working for me no matter what I try:

```yaml
flags:
  warn_error_options: {"error": "all", "silence": ["TestsConfigDeprecation"]}
```

```yaml
flags:
  warn_error_options:
    error: all
    silence:
      - TestsConfigDeprecation
```

```shell
dbt test --no-partial-parse
```

### Expected Behavior

I was expecting that the code example [here](https://docs.getdbt.com/reference/global-configs/warnings) would work to silence the warning. Instead, I get this:

```
[WARNING]: Deprecated functionality
The `tests` config has been renamed to `data_tests`. Please see
https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
information.
```

### Steps To Reproduce

Create these files:

`seeds/my_seed.csv`

```csv
id
1
```

`seeds/_seeds.yml`

```yaml
seeds:
  - name: my_seed
    columns:
      - name: id
        tests:
          - not_null
```

`dbt_project.yml`

```yaml
# Seems to ignore the "silence" configuration (but still recognizes the "error" configuration):
flags:
  warn_error_options: {"error": "all", "silence": ["TestsConfigDeprecation"]}
```

Run these commands:

```shell
dbt seed
```

This raises an error presumably because the `flags.warn_error_options.silence` in `dbt_project.yml` it not taking effect:
```shell
dbt test --no-partial-parse
```

But silence works if using the CLI instead:
```shell
dbt test --no-partial-parse --warn-error-options '{"error": "all", "silence": ["TestsConfigDeprecation"]}'
```

### Relevant log output

```shell
Compilation Error
  [WARNING]: Deprecated functionality
  The `tests` config has been renamed to `data_tests`. Please see
  https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
  information.
```

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Additional Context

Originally discovered here: https://github.com/dbt-labs/dbt-core/issues/10274#issuecomment-2155582205
