### ISSUE TITLE
[Feature] Jinja support in SQL fixtures for unit tests

### ISSUE THREAD

**Issue by megetron3** [dbt-labs/dbt-core#10316]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The potential benefits of incorporating Jinja support into the fixture input for unit tests are considerable. 

This could pave the way for the creation of models/macros that generate custom data, thereby enabling users to create dynamic input based on parameters passed to the macro.

Currently, the format is as follows:
```
unit_tests:
  - name: test_my_model
    model: my_model
    given:
      - input: ref('my_model_a')
        format: sql
        fixture: my_model_a_fixture
```
However, with Jinja support, it could look like this:
```
unit_tests:
  - name: test_my_model
    model: my_model
    given:
      - input: ref('my_model_a')
        format: sql
        fixture: my_jinja_model_a_fixture
        params: {param1: 1, param2: 2}
```
In this scenario, the input generated would be the output of the my_jinja_model_a_fixture model/macro.

This could provide users with the capability to write dynamic data, allowing for DRY (Don't Repeat Yourself) data as suggested in the Ideas group: https://github.com/dbt-labs/dbt-core/discussions/8275#discussioncomment-6613242
