### ISSUE TITLE
[Bug] DBT unit_tests don't work with empty JSON as expected result

### ISSUE THREAD

**Issue by yengibar-manasyan-sp** [dbt-labs/dbt-core#10342]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently, with DBT 1.8 when I want to expect no result, I can do the following:
```yml
expect:
  format: csv 
  rows: |
```

But with JSON it does not work. E.g.:
```yml
    expect:
      rows:
        - {}
```

### Expected Behavior

Support empty JSON as expected result meaning that no new records should be inserted into the model:
```yml
    expect:
      rows:
        - {}
```

### Steps To Reproduce

1. Create an incremental model
2. Create a unit test that in `this` (current table) has some data
3. Mock other tables in the test that has sooner modification date than the latest record in the current table
4. Expect zero result

### Relevant log output

```shell
001003 (42000): SQL compilation error:
```

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

snowflake
