### ISSUE TITLE
[Bug] Error thrown when using unit tests mock data with whitespace in column names

### ISSUE THREAD

**Issue by thatguysimon** [dbt-labs/dbt-core#10405]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When supplying unit tests with mock data of a source that has column names with whitespace:
```yaml
given:
  - input: source('my_source', 'my_source_table')
    rows:
      - "Row ID": 28
      - "Some Other Column": Some value
```
The column name is not wrapped in quotes and the DB throws an error:
```
Database Error
    syntax error at or near "id"
    LINE 24:  as row id, 
```

### Expected Behavior

The unit tests should be executed as with regular snake case column names.

### Steps To Reproduce

1. Define a source with whitespace in its column names:
    ```yaml
    sources:
      - name: my_source
        tables:
          - name: my_source_table
            columns:
              - name: "Row ID"
              - name: "Some Other Column"
    ```
2. Define a model called `my_model` that uses the source
3. Define a unit test for the model:
    ```yaml
    unit_tests:
      - name: test_thing
        model: my_model
        given:
          - input: source('my_source', 'my_source_table')
            rows:
              - "Row ID": 28
              - "Some Other Column": Some value
      ```
4. Run the test

### Relevant log output

```shell
...

-- Fixture for my_source
select 
    
    cast(28 as character varying)
 as row id, 
    
    cast('Some value' as character varying)
 as some other column

.
.
.

An error occurred during execution of unit test 'test_thing'. There may be an error in the unit test definition: check the data types.
  Database Error
    syntax error at or near "id"
    LINE 24:  as row id,
```

### Environment

```markdown
- OS: Debian 10
- Python: 3.10.9
- dbt: 1.8.3
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

1. Also tried to provide the values like so `'"Row ID"': 28` but then the column name doesn't match the available columns:
    ```
    Invalid column name: '"row id"' in unit test fixture for 'my_source'.
      Accepted columns for 'my_source' are: ['row id', ...
    ```
2. These column names with whitespace don't have any issues in other dbt features, just now with the introduction of unit tests.
