### ISSUE TITLE
[Regression] Unable to access environment variables on Windows using lowercase variable names

### ISSUE THREAD

**Issue by DanMawdsleyBA** [dbt-labs/dbt-core#10422]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Environment variables are no longer working. I was using dbt-core 1.7.3 previously where I use environment varaibles for my profiles.yml file. Since upgrading to 1.8.3 dbt is no longer able to access these same environement variables.

I have my environement varaibles setup in vscode under the settings json file example below:
```
    "terminal.integrated.env.windows": {
        "local_user":"dan")}
```
     

### Expected Behavior

Expect DBT to be able to read my environement variables like in the previous version of dbt 1.7 .

### Steps To Reproduce

Upgrade to dbt core 1.8 .
Use environment variables as part of dbt. In the profiles file example below:

```
dbt_profile:
  target: snowflake_local
  outputs:
    snowflake_local:
      type: snowflake
      account: ba.eu-west-1
      user: "{{ env_var('local_user') }}"
      authenticator: externalbrowser
      role: "{{ env_var('local_role') }}"
      database: "{{ env_var('local_database') }}"
      schema: "{{ env_var('local_schema') }}"
      threads: 1
      warehouse: DEVELOPER
```

### Relevant log output

```shell
dbt parse
10:16:51  Running with dbt=1.8.3
10:16:51  Encountered an error:
Parsing Error
  Env var required but not provided: 'local_user'
```

### Environment

```markdown
- OS: Windows
- Python: 3.11
- dbt: 1.8.3
```

### Which database adapter are you using with dbt?

snowflake
