### ISSUE TITLE
[Bug] DBT unit tests fail when source table and model name matches

### ISSUE THREAD

**Issue by yengibar-manasyan-sp** [dbt-labs/dbt-core#10433]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

One of my models had the same name as the source Snowflake table. They live in different schemas. `dbt run` works fine and generates all the data as expected. However, DBT unit tests fail because unit tests can not differentiate mocked source tables from these tables. Here is an example:
```yaml
unit_tests:
  - name: test_model_1
    description:
    model: MODEL_1
    overrides:
      macros:
        is_incremental: true

    given:
      - input: this
        rows:
          - { column_1: "1", column_2: "2" }

      - input: source('src', 'MODEL_1')
        rows:
          - { column_1: "1", column_2: "3" }

    expect:
      rows:
        - { column_1: "1", column_2: "3" }
```

When I checked the generated SQL query, I saw that it adds `__dbt__cte__` prefixes to the CTE names and replaced raws for `source('src', 'MODEL_1')` with values from `this`.

### Expected Behavior

Fix unit tests to support identical model and source table names in different schemas.

### Steps To Reproduce

1. Create a model that relies on a table with the table's exact name
2. Create an incremental unit test and add data both for the source table and `this` (the model itself)
3. Run the unit test and see its outcome

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reporting this @yengibar-manasyan-sp !

### Root cause

It appears that the root cause is that during unit testing, [`source`s](https://docs.getdbt.com/reference/dbt-jinja-functions/source) aren't guaranteed to have a CTE that is unique from other `source`s or [`ref`s](https://docs.getdbt.com/reference/dbt-jinja-functions/ref).

### Example

See below for a reproducible example ("reprex") of the issue you reported when a model and a source have the same name (`case_1`). It also includes a separate issue when two sources have the same name (`case_2`).

<details>
<summary>

### Reprex
</summary>

`dbt_project.yml`

```yaml
name: "my_project"
version: "1.0.0"
config-version: 2
```

`models/model_a.sql`

```sql
select -1 as id
```

`models/model_b.sql`

```sql
select -2 as id
```

`models/case_0.sql`

```sql
select * from {{ ref("model_a") }}

union all

select * from {{ ref("model_b") }}
```

`models/case_1.sql`

```sql
select * from {{ ref("model_a") }}

union all

select * from {{ source("src_2", "model_a") }}
```

`models/case_2.sql`

```sql
select * from {{ source("src_1", "model_a") }}

union all

select * from {{ source("src_2", "model_a") }}
```

Create some sources that just point to the database objects created by a couple of our models 😂  

`models/_sources.yml`

```yaml
sources:

  - name: src_1
    schema: "{{ target.schema }}"
    tables:
      - name: model_a

  - name: src_2
    schema: "{{ target.schema }}"
    tables:
      - name: model_a
```

`models/_unit_tests.yml`

```yaml

unit_tests:

  - name: test_case_0
    description: "Unit test SQL: target/run/my_project/models/_unit_tests.yml/models/test_case_0.sql"
    model: case_0
    given:
      - input: ref("model_a")
        rows:
          - { id: 1 }
      - input: ref("model_b")
        rows:
          - { id: 2 }
    expect:
      rows:
          - { id: 1 }
          - { id: 2 }

  - name: test_case_1
    description: "Unit test SQL: target/run/my_project/models/_unit_tests.yml/models/test_case_1.sql"
    model: case_1
    given:
      - input: ref("model_a")
        rows:
          - { id: 1 }
      - input: source("src_2", "model_a")
        rows:
          - { id: 2 }
    expect:
      rows:
          - { id: 1 }
          - { id: 2 }

  - name: test_case_2
    description: "Unit test SQL: target/run/my_project/models/_unit_tests.yml/models/test_case_2.sql"
    model: case_2
    given:
      - input: source("src_1", "model_a")
        rows:
          - { id: 1 }
      - input: source("src_2", "model_a")
        rows:
          - { id: 2 }
    expect:
      rows:
          - { id: 1 }
          - { id: 2 }
```

Commands:

```shell
dbt run -s model_a model_b
dbt build -s case_0
dbt build -s case_1
dbt build -s case_2
```

I get the following output:


```shell
$ dbt build -s case_0

20:42:08  1 of 2 START unit_test case_0::test_case_0 ..................................... [RUN]
20:42:08  1 of 2 PASS case_0::test_case_0 ................................................ [PASS in 0.21s]
20:42:08  2 of 2 START sql view model feature_456.case_0 ................................. [RUN]
20:42:08  2 of 2 OK created sql view model feature_456.case_0 ............................ [OK in 0.12s]
20:42:08  
20:42:08  Finished running 1 unit test, 1 view model in 0 hours 0 minutes and 0.54 seconds (0.54s).
20:42:08  
20:42:08  Completed successfully
```


```shell
$ dbt build -s case_1       

20:41:15  Failure in unit_test test_case_1 (models/_unit_tests.yml)
20:41:15    

actual differs from expected:

@@ ,id
---,1
   ,2
+++,2
```

```shell
$ dbt build -s case_2

20:42:57  1 of 2 START unit_test case_2::test_case_2 ..................................... [RUN]
20:42:57  1 of 2 ERROR case_2::test_case_2 ............................................... [ERROR in 0.03s]
20:42:57  2 of 2 SKIP relation feature_456.case_2 ........................................ [SKIP]
20:42:57  
20:42:57  Finished running 1 unit test, 1 view model in 0 hours 0 minutes and 0.23 seconds (0.23s).
20:42:57  
20:42:57  Completed with 1 error and 0 warnings:
20:42:57  
20:42:57    Compilation Error in unit_test test_case_2 (models/_unit_tests.yml)
  Unit_Test 'unit_test.my_project.case_2.test_case_2' (models/_unit_tests.yml) depends on a source named 'src_1.model_a' which was not found
```

</details>


Looking at the output files like the following helps highlight what is going wrong:
- `target/run/my_project/models/_unit_tests.yml/models/test_case_0.sql`
- `target/run/my_project/models/_unit_tests.yml/models/test_case_1.sql`

**Comment by dbeatty10** [comment]
### Acceptance criteria

The key outcome we'd need is:
- each node in the DAG to have a corresponding CTE name that is guaranteed to be unique from that of every other node in the DAG (regardless of node type like source, model, seed, snapshot, etc.).

### A possible building block

One thing that is already to be unique across the DAG is [`unique_id`](https://docs.getdbt.com/reference/artifacts/run-results-json), so possibly that could be transformed into a suitable CTE name.

### Relevant code
Some of the relevant code is described in https://github.com/dbt-labs/dbt-core/issues/5273#issuecomment-1131543844.

https://github.com/dbt-labs/dbt-adapters/pull/236 and https://github.com/dbt-labs/dbt-core/pull/10290 have proposed updates to the code that generates the CTE name, but I don't think either would fix this particular issue with unit tests.

**Comment by dbeatty10** [comment]
### Relevant code

https://github.com/dbt-labs/dbt-core/blob/c668846404c78ea7317dc0523b49703c61c9885f/core/dbt/context/providers.py#L1595-L1600

Specifically, we could generate some kind of `globally_unique_identifier` and then use it like this:

```python
            return self.adapter.Relation.add_ephemeral_prefix(globally_unique_identifier)
```

**Comment by dbeatty10** [comment]
## Implementation ideas

Here are a couple ideas of how to create the CTE in unit tests so that they are unique:

1. Use a quoted version of `unique_id` + quoted identifiers
2. Use a hexadecimal formatted hash of the `unique_id` + quoted identifiers

### 1. Use a quoted version of `unique_id` + quoted identifiers

Example:
```sql
with "__dbt__cte__source.my_project.src_1.model_a" as (
...
),
"__dbt__cte__model.my_project.model_a" as (
```

Pros:
- Retains and utilizes uniqueness of the `unique_id`
- Doesn't transform the `unique_id` at all -- just quotes it
- Preserves readability of the CTE name
- Would also solve the problem described in [dbt-core #5273](https://github.com/dbt-labs/dbt-core/issues/5273)

Cons:
- Not sure if data warehouses commonly allow CTE names to have quoted identifiers or not 🤷

### 2. Use a hexadecimal formatted hash of the `unique_id` + quoted identifiers

Examples:
```sql
with __dbt__cte__e83c5163316f89bfbde7d9ab23ca2e25604af290 as (
```

or

```sql
with __dbt__cte__dim_customers_e83c5163316f as (
```

Pros:
- Utilizes uniqueness of the `unique_id`
- Doesn't rely upon quoted identifiers

Cons:
- CTE name is either less readable or not readable at all
- Not 100% guaranteed to be unique after hashing

#### Details

We could hash the `unique_id` similar to `_create_sha1_hash`:

https://github.com/dbt-labs/dbt-core/blob/c668846404c78ea7317dc0523b49703c61c9885f/core/dbt/task/deps.py#L56

If we don't care about readability of the CTE name, then we could just use the hexdigest as-is which for SHA1 would be a 40-character value like this:
```
e83c5163316f89bfbde7d9ab23ca2e25604af290
```

If there are readability concerns, then we could combine an abbreviated version of the hash along with the node `name` (or `identifier`), which might look like this:
```
dim_customers_e83c5163316f
```

**Comment by larsstromholm** [comment]
We've just come across this issue ourselves. Are you planning contributing to this in the nearest future, @dbeatty10 ?

**Comment by jhoffland** [comment]
Did anyone find a workaround?

**Comment by devmessias** [comment]
There’s no workaround, @jhoffland. However, if you’re using dbt-core, you could modify the code to use the full path (source name + model) or hash like previous suggested

**Comment by BPilippG** [comment]
Hey all,

I'd like to raise attention to that the cause of this issue doesn't only affect sources.  The current implementation can lead to duplicate CTE names when a unit test contains models with the same alias and thus cause a syntax error.
Therefore, I don't think that [suggestion 3 & 4](https://github.com/dbt-labs/dbt-core/issues/10433#issuecomment-2248428619) by @dbeatty10 solve the root problem. However, [suggestion 1 & 2](https://github.com/dbt-labs/dbt-core/issues/10433#issuecomment-2241316864) would be a great improvement in my eyes.


<details>
  <summary><b>Reproducible Example</b></summary>
 
`models/model_a.sql`
  ```sql
  {{ config(alias="test_model", schema="schema_a") }} select 1 as example_value
  ```

`models/model_b.sql`
```sql
{{ config(alias="test_model", schema="schema_b") }} select 2 as example_value
```

`models/model_c.sql`
```sql
{{ config(schema="schema_c", materialized="table") }}
select *
from {{ ref("model_a") }}

union all

select *
from {{ ref("model_b") }}
```

`models/_unit_tests.sql`
```yaml
unit_tests:
  - name: unit_test_with_error
    description: Checks whether model_c is the union of model_a and model_b
    model: model_c
    given:
      - input: ref('model_a')
        rows:
          - {example_value: 1}

      - input: ref('model_b')
        rows:
          - {example_value: 2}
    expect:
      rows:
        - {example_value: 1}
        - {example_value: 2}
```

Running the test yields

```bash
Runtime Error in unit_test unit_test_with_error (models/_unit_tests.yaml)
  An error occurred during execution of unit test 'unit_test_with_error'. There may be an error in the unit test definition: check the data types.
   Database Error
    WITH query name "__dbt__cte__test_model" specified more than once
    LINE 22: ),  __dbt__cte__test_model as (
```

</details>

**Environment**
- OS: macOS Sonoma 14.0
- Python: 3.9.19
- dbt: dbt-code 1.9.1

**Which database adapter are you using with dbt?**
Postgres 1.9.0

**Comment by Govindarajan-D** [comment]
We recently faced the same issue in our unit test: 
We had two sources - let's say _source_1_ and _source_2_ but with same table names - _table_1_.  So ideally, _source_1.table_1_ and _source_2.table_1_ shouldn't have any collision, but unit test was throwing error saying it couldn't find source_2.table_1. 

The simplest workaround for this issue is: In one of the source files, use identifier as table_1 but for name - provide it as table_2_src2 (something like this). 

```
sources:
  - name: source_2
    database: db_2
    tables:
      - name: table_2_src_2
        identifier: table_2
```

Wherever you would need to refer in dbt, you would be referring as _source('source_2', 'table_2_src_2')_
