### ISSUE TITLE
Treate seeds like models

### ISSUE THREAD

**Issue by RalfKow** [dbt-labs/dbt-core#10435]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I could use the same options to define a seed as I can with a model. f. E. If I define a model I can define all columns and its constrains. 

# models

```yaml
version: 2

models:
  - name: user
    columns:
      - name: user_id
        data_type: varchar(16777216)
        constraints:
          - type: not_null
          - type: primary_key
      - name: usage_car_id
        data_type: number(38,0)
```

I could define seeds exactly the same

# Seeds

```yaml
seeds:
  - name: user
    columns:
      - name: user_id
        data_type: varchar(16777216)
        constraints:
          - type: not_null
          - type: primary_key
      - name: usage_car_id
        data_type: number(38,0)
```

### Describe alternatives you've considered

I write custom markdown files to emulate the wished behaviour

### Who will this benefit?

Everyone that uses seeds
