### ISSUE TITLE
[Bug] generic tests to accept arbitrary configs does not appear to be pulling in config options for certain tests

### ISSUE THREAD

**Issue by McKnight-42** [dbt-labs/dbt-core#10484]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

while trying respond to a slack conversation [thread](https://dbt-labs.slack.com/archives/C017GDLAF7D/p1721696763124499)

about implementing the new general config options for `data_tests`

found that local testing showed that some tests types are not accepting the `config` object it seems 
```
version: 2
models:
  - name: my_test_model  # Replace with your actual model name
    columns:
      - name: id
        data_tests:
          - not_null:
              config:
                snowflake_warehouse: analytics
```

logs test may pass but logs will not show `snowflake_warehouse` being set

best guess is tests that just trigger a macro without having any real additional config are for some reason now not able to pull in the general config.

### Expected Behavior

all test types should be able to have config options added based on the work done around https://github.com/dbt-labs/dbt-core/issues/10197

### Steps To Reproduce

create various simple models to test against

schema.yml

```
version: 2
models:
  - name: my_test_model # Replace with your actual model name
    columns:
      - name: color
        tests:
          - accepted_values:
              values: ['blue', 'red', 'green', 'yellow']
              config:
                snowflake_warehouse: analytics

# can sub out for a not_null test to match above

 - name: my_test_model  # Replace with your actual model name
    columns:
      - name: id
        data_tests:
          - not_null:
              config:
                snowflake_warehouse: analytics
            

  - name: child_table
    description: "Child table containing records referencing the parent table"
    columns:
      - name: parent_id
        data_tests:
          - relationships:
              to: ref('parent_table')
              field: id
              config:
                snowflake_warehouse: dbt_snowflake_warehouse
```

models
```
child_table.sql
select * from {{ ref('child') }}

parent_table.sql
select * from {{ ref('parent') }}

my_test_model.sql
select * from {{ ref('seed') }}
```
seeds
```
child.csv

id,parent_id,value
1,1,Value 1
2,1,Value 2
3,2,Value 3
4,3,Value 4  # Corrected parent_id to 3 which exists in parent_table

parent.csv

id,name
1,Parent A
2,Parent B
3,Parent C

seed.csv

id,color,value
1,blue,10
2,red,20
3,green,30
4,yellow,40
5,blue,50
6,red,60
7,blue,70
8,green,80
9,yellow,90
10,blue,100
```

### Environment

```markdown
- OS:
- Python:
- dbt:
```
