### ISSUE TITLE
[Feature] Support for `report` exposure type

### ISSUE THREAD

**Issue by menzenski** [dbt-labs/dbt-core#10493]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We have a large number of scheduled reporting jobs that produce and send CSV/XLSX/PDF files. We're actively migrating these from a legacy database to our new data platform that is built with dbt.

We've defined a number of dbt exposures already (for BI dashboards we've created), and I'd like to define exposures for these reports as well, as they're also downstream consumers of our dbt models. However, none of [the existing ExposureType values](https://github.com/dbt-labs/dbt-core/blob/c598741262cfa7ae46d80ea2d2af675ee65df07f/core/dbt/artifacts/resources/v1/exposure.py#L13-L18) feels accurate for this purpose.

It would be great to have support for a `report` ExposureType - either by adding that value to the existing ExposureType enum, or by adding support for custom/user-defined ExposureType values.

### Describe alternatives you've considered

The alternative we've considered is using one of the existing ExposureType values for our use case - `analysis` (since arguably the report is providing the results of some sort of analysis) or `application` (since the report is arguably produced by an application). However, that's not ideal as when we do add more prototypical `analysis` or `application` exposures, the meaning of those types will be diluted. We'd prefer to be able to have `report` exposures use a dedicated, specific exposure type.

### Who will this benefit?

Running a report against a data warehouse seems like it'd be a very common use case. I think this additional enum value would benefit a wide swath of dbt-core users.

### Are you interested in contributing this feature?

Yes, happy to contribute this.

**Comment by dbeatty10** [comment]
Thanks for reaching out about this @menzenski !

> We'd prefer to be able to have report exposures use a dedicated, specific exposure type.

If you had a dedicated `report` exposure type how would you plan on utilizing it? Would it be primarily for the most accurate categorization in the YAML source code? Or are you seeking something else like:
- showing that category in your [documentation website](https://docs.getdbt.com/reference/commands/cmd-docs)
- [`dbt list`](https://docs.getdbt.com/reference/commands/list)ing specific exposures based on their type
- etc.

**Comment by menzenski** [comment]
> If you had a dedicated report exposure type how would you plan on utilizing it?

Having accurate categorization in the YAML is important, but I think surfacing the `report` category in the dbt-docs site is probably the most important thing for us. In the legacy reporting system that we're migrating off of (to the new dbt-based platform), the code for a reporting job is colocated with the SQL queries that provide data to that report (same git repository). In our new platform, the SQL has moved into the dbt project repository, while the Python job code remains in the original repository. So having separated them, I want to be sure that we still maintain a clear link between them. Being able to define a `report` exposure type and being able to show in the docs site that "model A is depended on by report B" is something that we'd like.

I think the `dbt list` command is something I don't expect us to be running a ton, but it would be nice to have the option (we have several hundred reports, anything that can help us manage them all is a plus IMO).

FWIW I think there's also some additional automation/configuration we'd be interested to build (in-house - this seems much more specific to our organization) on top of the report exposure type - for example, defining a YAML selector for "all models directly referenced as a dependency of an exposure of type report", so that we could more easily `dbt build` all models that reporting needs, etc.

**Comment by dbeatty10** [comment]
### Documentation

For the documentation portion, there's some configs that come to mind that offer a lot of flexibility and show up in the documentation website:
- [`tags`](https://docs.getdbt.com/reference/resource-configs/tags)
- [`description`](https://docs.getdbt.com/reference/resource-properties/description)
- [`meta`](https://docs.getdbt.com/reference/resource-configs/meta)

### Selection methods

There's a handful of [selection methods](url) that could _potentially_ be useful here too:
- [`tag`](https://docs.getdbt.com/reference/node-selection/methods#the-tag-method)
- [`resource_type`](https://docs.getdbt.com/reference/node-selection/methods#the-resource_type-method)
- [`exposure`](https://docs.getdbt.com/reference/node-selection/methods#the-exposure-method)
- [`config`](https://docs.getdbt.com/reference/node-selection/methods#the-config-method)

The selection method that seems most likely to be useful for the use-cases you mentioned is `tag`. The `config` method has the caveats mentioned in https://github.com/dbt-labs/docs.getdbt.com/pull/5856, which would currently preclude using it with exposures.

### Example

Here's an example:

```yaml
version: 2

exposures:

  - name: exposure_name_3
    tags: ['report']
    description: Example analysis exposure
    type: analysis
    meta:
      exposure_type: anything_you_want
      something: else
    depends_on:
      - ref("my_model")
    owner:
      email: data@jaffleshop.com
```

To build everything directly referenced as a dependency of the "report" tag:
```shell
dbt build --select "1+tag:report"
```

If you do `dbt docs generate` and `dbt docs serve`, you'd see the following documentation which shows both the **tags** as well as an **meta** attributes you define:

<img width="1028" alt="image" src="https://github.com/user-attachments/assets/f593105d-6aab-47e0-b488-e4d80f02bdba">

### Summary

We'd prefer not to add any new exposure types if we don't need to.

It looks like [tags](https://docs.getdbt.com/reference/resource-configs/tags) fit the use-cases you mentioned, so I'm going to close this issue as "not planned" in favor of using them instead.

Even though we're closing this issue, we're still open to hearing your feedback like if the proposed workaround doesn't work or if there's something we overlooked, etc.

**Comment by menzenski** [comment]
Thanks @dbeatty10 - I appreciate the context you've provided. We will likely end up categorizing these models as `analysis` and using tags to distinguish `report` vs `analysis` (non-report analysis).

**Comment by menzenski** [comment]
Actually, one more question if that's alright, regarding this screenshot from the docs site:

<img width="258" alt="Screenshot 2024-07-30 at 10 10 30 AM" src="https://github.com/user-attachments/assets/e3a94525-ad4c-4557-b5d6-402b77dc8103">

Is there a way to add "subdirectories" underneath Analysis there? We'll end up having >300 "report" exposures and a much smaller number of "non-report" analyses - I am interested in strategies to keep the latter from being lost in the sheer number of the former.

**Comment by dbeatty10** [comment]
There isn't a way add "subdirectories", but there's a couple ways keep things from getting lost in the shuffle:
1. Add a meaningful prefix to the exposure name
2. Add a tag to enable searching by tag name

### Example

```yaml
version: 2

exposures:

  - name: report__exposure_1
    tags: ['report']
    type: analysis
    depends_on:
      - ref("my_model")
    owner:
      email: data@jaffleshop.com

  - name: report__exposure_2
    tags: ['report']
    type: analysis
    depends_on:
      - ref("my_model")
    owner:
      email: data@jaffleshop.com

  - name: report__exposure_3
    tags: ['report']
    type: analysis
    depends_on:
      - ref("my_model")
    owner:
      email: data@jaffleshop.com

  - name: report__exposure_4
    tags: ['report']
    type: analysis
    depends_on:
      - ref("my_model")
    owner:
      email: data@jaffleshop.com

  - name: report__exposure_5
    tags: ['report']
    type: analysis
    depends_on:
      - ref("my_model")
    owner:
      email: data@jaffleshop.com

  - name: report__exposure_6
    tags: ['report']
    type: analysis
    depends_on:
      - ref("my_model")
    owner:
      email: data@jaffleshop.com

  - name: other__exposure_7
    tags: ['other']
    type: analysis
    depends_on:
      - ref("my_model")
    owner:
      email: data@jaffleshop.com
```

Since the analysis exposures are sorted alphabetically, adding a prefix will separate the different prefixes from each other. See below to see how `report__` and `other__` prefixes would display visually. 

And / or you can add a tag like "report" or "other" that would enable searching by tag name:

<img width="1033" alt="image" src="https://github.com/user-attachments/assets/c6ca007f-f5ad-4e1a-b825-4312fb769874">
