### ISSUE TITLE
[Bug] Unit tests don't defer to environment-aware source tables

### ISSUE THREAD

**Issue by katieclaiborne-duet** [dbt-labs/dbt-core#10513]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

A unit test is failing during a slim CI build, because dbt is using the location of an input (external) source table as defined in the active project manifest (`target/manifest.json`). The external source table does not exist in that location, because it hasn't been staged as part of the CI job.

I suspect that the behavior may be the result of environment-aware logic.

### Expected Behavior

I expected dbt to defer to the external source table's location as defined in the manifest passed to the `--state` flag.

### Steps To Reproduce

1. Create a profile containing two targets with different values for `dataset` / `schema`.
2. Define an external source table with environment-aware logic. Ours looks something like this:
```yaml
version: 2

sources:
  - name: my_source
    schema: "{{ target.dataset }}_scratch"
    tables:
      - name: TABLENAME
        external:
          location: "gs://path/to/files/*"
          options:
            format: PARQUET
```
3. Configure that source table as an input to a model's unit test.
4. Stage the external source table, using the first target defined in your profile.
5. Copy the resulting manifest to the root of the dbt project.
6. Run the unit test with deferral, using the second target defined in your profile.
```
dbt test --select <unit_test_name> --defer --state . --target <second_target_name>
```
### Relevant log output
```
Compilation Error in model PATIENTINSURANCE (models/stg/athena/_athena__unit_tests.yml)
  Not able to get columns for unit test 'PATIENTINSURANCE' from relation `vital-ensign-388617`.`dbt_pr_367_scratch`.`PATIENTINSURANCE` because the relation doesn't exist
  
  > in macro get_fixture_sql (macros/unit_test_sql/get_fixture_sql.sql)
  > called by model PATIENTINSURANCE (models/stg/athena/_athena__unit_tests.yml)
```

### Environment

```markdown
- OS: Ubuntu 22.04.4
- Python: 3.10.12
- dbt: 1.8.4
```

### Which database adapter are you using with dbt?

bigquery
