### ISSUE TITLE
[Bug] Unit Test fails when using a versioned model as an input

### ISSUE THREAD

**Issue by kbrock91** [dbt-labs/dbt-core#10528]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Unit tests fail if an input reference is a versioned model and the version is not explicitly defined in both the model AND the unit test. 

### Expected Behavior

The unit test should default to the latest version specified in the yml config for the input versioned model.

### Steps To Reproduce

1. In the dbt Cloud IDE, create a versioned mode (e.g. `stg_tpch_orders`, with versions `1` and `2`)  and second model (e.g. `customer_tier`) that references that versioned model, and a unit test on that second model (`customer_tier`) that references that versioned model as an input
2. Run a `dbt build --select customer_tier`

- If the `customer_tier` model **does not** reference a specific version, the unit test will always fail, regardless if a version is specified or not. For this scenario, see code below.
- If the `customer_tier` model **does** reference a specific version, the unit test will fail if no version is specified. The unit test does work if you explicitly specify `ref('stg_tpch_orders', v =2)`  in both places

Code for reference

schema.yml for stg_tpch_orders
```
- name: stg_tpch_orders
    description: staging layer for orders data
    versions:
      - v: 1
        columns:
          - include: all
            exclude: [comment]
        deprecation_date: 2024-8-31 00:00:00.00+00:00
      - v: 2
        columns:
          - include: all
    latest_version: 2
```

customer_tier.sql 
```
{{
    config(
        materialized='table'
    )
}}

with customer as (
    select * from {{ ref('stg_tpch_customers') }}
),

orders as (
    select * from {{ ref('stg_tpch_orders') }}
),
final as (
    select
        customer.customer_key,
        sum(orders.total_price) as lifetime_value,
        case 
            when lifetime_value <= 200000 then 'tier1'
            when lifetime_value > 2000000 then 'tier2'
            when lifetime_value between 1000000 and 1999999 then 'tier3'
            when lifetime_value between 0 and 999999 then 'tier4' 
        end as tier_name, 
        max(orders.comment) as comment
    from customer
        inner join orders
            on customer.customer_key = orders.customer_key
    group by 1
)

select * from final
```
unit test: 
```
unit_tests:
  - name: tiers_are_working
    description: "check if the logic for tiering is working correctly"
    model: customer_tier
    given:
      - input: ref('stg_tpch_customers')
        format: dict
        rows:
          - {customer_key: 629}
          - {customer_key: 4}
          - {customer_key: 1}
          - {customer_key: 26}

      - input: ref('stg_tpch_orders') 
        format: dict
        rows:
          - {customer_key: 629, total_price: 163443}
          - {customer_key: 4, total_price: 4134568}
          - {customer_key: 1,  total_price: 1428872}
          - {customer_key: 26, total_price: 418512}

    expect:
      rows:
        - {customer_key: 629,  tier_name: tier1}
        - {customer_key: 4,    tier_name: tier2}
        - {customer_key: 1,    tier_name: tier3}
        - {customer_key: 26,   tier_name: tier4}    
```

### Relevant log output

```shell
14:20:52 Compilation Error in unit_test tiers_are_working (models/marts/intermediate/intermediate.yml)
  Unit_Test 'unit_test.analytics.customer_tier.tiers_are_working' (models/marts/intermediate/intermediate.yml) depends on a node named 'stg_tpch_orders' which was not found
```

### Environment

```markdown
- OS:
- Python:
- dbt: Latest Version in dbt Cloud IDE
```
