### ISSUE TITLE
[Feature] Unit test support for macros

### ISSUE THREAD

**Issue by jas-grover** [dbt-labs/dbt-core#10547]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

dbt unit tests only support SQL models which leaves a gap in testing coverage for models that utilise macros. It would be beneficial to be able to write unit tests for macros in a similar fashion to SQL models and be able to assert the output they produce.

### Describe alternatives you've considered

- Creating dummy SQL models that call the macros as an alternative to testing the macros directly. The value(s) returned by the macro could be asserted as the output of the dbt model and checked against the defined expected value in the model yml.
- However, this seems a bit cumbersome and would require these test models to be created in the `models/` directory in the dbt project which would not be desirable as they could conflict with real models and make discoverability harder. A dedicated testing project could be created to house these test models but would introduce a lot of overhead.

### Who will this benefit?

- Testing macros that are used across several models and contain key pieces of logic.
- Testing overridden macros such as `ref` and `source`. These macros are foundational to the project and having a mechanism to assert the relations produced based on different inputs and environment configurations would be beneficial.

**Comment by james-johnston-thumbtack** [comment]
Here are some more ideas of how unit test support for macros could be used...

I am working on a collection of macros in a shared utility project that:
- Will be used across multiple database engines.
- As such, several cross-database macros designed similar to the [one's bundled with dbt](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros) are added to the utility project.  These macros need to be unit tested.
- A final macro or two that consists of a few hundred lines of very gnarly looking Jinja code, which involves macro recursion and extensive use of the cross-database macros.  There's no way to reasonably trust this code to be doing the right thing without doing a lot of testing.

It's obvious to me that these macros need to be thoroughly tested.  Manually testing all the different code branches would be a lot of throwaway work that isn't code reviewable - writing permanent automated tests would be preferred.

Some requirements:
- So, they need to be unit tested.  The concept of a "dbt data test" doesn't really seem to apply here.  I want to assert on expected outputs given some test input data into the macro.
- These macros generate advanced SQL expressions, or even entire subqueries.  As such, I need them to run against the actual data warehouse.  I'd want to be able to write some sort of `SELECT {{ call_my_macro(input1, input2, etc) }}` statement or whatever, and then assert the expected output rows.
  - This is to be contrasted with simply asserting on the rendered output text/SQL of a macro without actually running any SQL of consequence.  That might be more appropriate for simpler macros that just involve some basic Jinja logic (e.g. imagine unit testing a macro like `concat_strings` which concatenates two Jinja strings using `return(a ~ b)`... simply asserting the return value would be enough)
- Advanced SQL data types like arrays, structs, and maps are used - therefore, I imagine I may end up writing the expected output using SQL, similar to today's model unit tests.  But I suppose for some simpler use cases, the CSV/YAML options for specifying rows today for model unit tests could also work.
- The macros use [multiple adapter dispatch](https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch) and as such, the expected output _will vary_ between database engines.  To adequately test the cross-database macros, I for sure will need to be able to specify different expected outputs for different database adapters.  (e.g. imagine a different fixture file for each database adapter)
  - The few larger gnarly complex macros that call into the cross-database macros could also be written with different expected outputs for different database engines.  Alternatively, if it was possible to call Jinja from SQL fixtures (#10316) then I could reuse the cross-database macros to write my fixtures... this way, only the unit tests for cross-database macros themselves have to be updated when adding support for a new database engine.
- In some cases, the documented contract for a macro promises to generate SQL that will fail if some input data is invalid.  So it would be nice to be able to write a unit test where we can assert that the query fails with a particular error.  For example, my cross-database `json_to_map` macro promises to fail if given input that is not a JSON object... so it should be tested to failure by giving it JSON array, JSON scalar values, etc.

@jas-grover proposed "Creating dummy SQL models that call the macros as an alternative to testing the macros directly" as an alternative.  I think this could almost work for me, albeit with the downsides they gave.  However, the problem is that I need to vary the expected outputs by database adapter, and if Jinja isn't allowed in the expected output per #10316...

**Comment by amr-abouelleil-ic** [comment]
+1, would like to see this feature as well

**Comment by AmiriMc** [comment]
+1 for this feature

**Comment by aidanradford** [comment]
+1 for this feature

**Comment by LoranZerbe** [comment]
+1, this would be nice.

**Comment by graciegoheen** [comment]
Yes! This is such a great idea.

I'd love if people could share their specific use cases for unit testing macros. It will help us brainstorm a spec that is flexible enough for as many as possible.

As one example, @macks22 shared a use case for testing an override of the `generate_schema_name` macro over here -> #12086 

Here was my rough brainstorm for what a spec might look like to solve that use case!
```
unit_tests:
  - name: generate_schema_name_in_ci_no_custom_schema
    macro: generate_schema_name
    overrides:
      env_vars:
        BUILDKITE_BRANCH: feature/test-branch
        BUILDKITE_BUILD_NUMBER: '123'
      macros:
        our_package_name.is_running_in_ci: true
      target: # alt. maybe nested under something like globals:
        schema: test_schema
    given:
      - argument: custom_schema_name
        value: None # implied if you don't pass in anything
      - argument: node # not needed for your macro logic, but I could imagine other use cases that would want this
        value: 
          resource_type: model
          package_name: our_package_name
    expect:
      returns:
        value: PR_FEATURE_TEST_BRANCH_123_test_schema
```

Though, maybe this is a better syntax for supply arguments:
```
    given:
      arguments: 
        custom_schema_name: None # None is implied if you don't pass in anything
        node: # dict of attributes of node, None is implied for missing attributes
          resource_type: model
          package_name: our_package_name
```
Very curious to hear folks' feedback and ideas!

**Comment by graciegoheen** [comment]
Another use case from @macks22 for being able to test that a macro will fail/error when you expect it to -> https://github.com/dbt-labs/dbt-core/issues/12092

**Comment by macks22** [comment]
@graciegoheen thanks for pointing me to this issue. Agree it would satisfy many of the needs I've been raising in other issues. Let me give a bit more context on how my team is testing macros to clarify requirements relevant to this feature request.

## Categorizing macros for testing purposes

We categorize macros into three broad buckets: (1) generic test macros, (2) pure jinja and (3) everything else.
- The pure jinja macros are the main group I'd look to unit test.
- It would also be great to come up with some kind of unit testing support for generic test macros.
   - Fully testing may still require testing through a model, or else require special argument compatibility verification to ensure they can be used in generic data test cases. More thoughts on this below.
- Everything else requires integration tests, i.e. testing through a model.
   - In many cases, this is because unit tests don't currently support testing the materialization or hooks.
   - In others, you just end up simulating too much of what the database would more reliably do anyways.

Note: Macros whose sole purpose are to output SQL snippets are in a bit of a grey area. They can technically be unit tested by checking the SQL strings they output. However, that often doesn't mean a lot semantically, and it doesn't scale to longer, more complex SQL outputs.

## Requirements for unit testing pure jinja macros

### Must-haves
1. **Must be able to specify macro arguments in compatible formats, ideally using either jinja or literal values.**
    - We currently test macros via an intermediate model. A `var` is specified for each macro argument in the model. This allows overriding those vars in unit tests on the macro, i.e. indirectly passing macro arguments.
    - Limitations of this: overrides must be specified as literal values. So it's not possible to pass specialized objects like Relation.
    - Being able to specify argument values via jinja would solve this.
2. **Must be able to override macros.**
    - While possible, this is currently limited in two ways:
        1. A macro called more than once cannot be overridden to return different values for each call, either based on call sequence or based on inputs.
        2. Cannot override macros from builtin packages, e.g.`exceptions` or `adapter`
    - In an ideal world, the override could be specified either as a literal value (like it is now), or as jinja, i.e. with a replacement, anonymous macro.
    - While our use cases are limited to a single engine (Snowflake), I'd imagine there's some specific behavior related to adapter dispatch control that would help with cross-DB compatibility testing.
3. **Must be able to make assertions about arguments passed to overridden macros.**
    - Basically looking for something closer to mocks in typical unit tests, vs. simple overrides available today
    - Not currently possible. No workarounds known.
4. **Must be able to make assertions about exceptions and warnings raised, including their messages.**
    - Not currently possible. Workaround described in [#12092](https://github.com/dbt-labs/dbt-core/issues/12092) is quite hacky and doesn't allow testing error messages.
5. **Must be able to override global context variables.**
    - E.g. `target`, `execute`, `graph`, `selected_resources`, etc.
    - Not currently possible. Current workaround is to define wrapper macros that return these, then override the wrappers.

### Nice-to-haves
(probably not worth pursuing in the first implementation)
1. **Parametrization of macro arguments, and support for fixtures, similar to what pytest provides.**
    - Parametrization: E.g. specify a list of inputs to generate multiple test cases where everything else is the same.
    - Fixtures: Specify reusable unit test inputs in a fixtures section common to a particular macro, i.e. share data across unit tests for the same macro.

## Unit testing generic test macros

In a lot of ways, these tests would just look like unit tests on models. We specify some expected input data, one for each argument that takes a relation. Then we specify the other macro arguments. Finally, we assert expected output rows and error status + message.

The extra requirements here are we need to verify:
1. the test configuration, e.g. `fail_calc`, `where`, `severity`, `error_if`
2. the pass/fail status
3. that the macro is compatible with the scope(s) it can be used at (e.g. model, column, seed, source)

## Initial thoughts on specification format

I really like the basic format @graciegoheen laid out [above](https://github.com/dbt-labs/dbt-core/issues/10547#issuecomment-4026249337). With the requirements I mentioned above in mind, I think the three key sections (`overrides`, `given`, `expect`) need to support the following.

### `overrides`

`env_vars`, `vars`, `globals`, `config`, and `macros`, with `macros` of type `literal` (default) or `jinja`
```yml
    ...
    overrides:
      env_vars:
        BUILDKITE_BRANCH: feature/test-branch
      globals:
        target:
          schema: test_schema
      config:  # for testing generic test macros and maybe materializations in the future
      macros:
        our_package_name.is_running_in_ci: true
        our_package_name.relation_exists:
          type: jinja
          value: {{ true if target.schema == 'some_value' else false }}
```

### `given`

`arguments`, which can be of type `literal` (default), `jinja`, or `data`

example with just literal arguments:
```yml
    given:
      arguments:
        - custom_schema_name: None  # implied if you don't pass in anything
        - node:
            resource_type: model
            package_name: our_package_name
```
example showing jinja-specified argument:
```yml
    given:
      arguments:
        - relation:
            type: jinja
            value: {{ api.Relation.create("test_db", "test_schema", "test_identifier") }}
```
`data` typed arguments would be just like inputs in unit tests for models, except with no extra schema inference logic

### `expect`

one of: `returns`, `error`, or `warning`, with the latter two supporting some kind of message matching syntax

for generic test macros:
1. must specify `rows` instead of `returns`, along with either `error` or `warning`
2. not sure how best to specify expected supported scopes

standard usage would use `returns`:
```yml
    expect:
      returns:
        value: PR_FEATURE_TEST_BRANCH_123_test_schema
```
exception verification (including for generic test macros) would use `error` or `warning`, with message type of `literal` (default) or `jinja`
```yml
    expect:
      error:
        message: "invalid input argument; `relation` is not of type Relation."
```
alternative showing jinja specification
```yml
    expect:
      error:
        message:
          type: jinja
          value: {{ "`relation` is not of type Relation." in message }}
```
