### ISSUE TITLE
[Feature] Add Constraints to Seeds

### ISSUE THREAD

**Issue by cboethigtrellance** [dbt-labs/dbt-core#10551]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As of DBT Core 1.8 Model contracts and constraints are not supported for **seeds**

As requested in another [feature ](https://github.com/dbt-labs/dbt-core/issues/7742) requesting contracts for seeds there was no reason given other than setting data types for the columns which the column types config already provides.

Currently with seeds there are no ways to define constraints. Most data platforms do not ENFORCE constraints specified in the [documentation](https://docs.getdbt.com/docs/collaborate/govern/model-contracts#platform-constraint-support). Like models, I believe seeds should be able to specify constraints such as primary & surrogate key and not null.

Adding constraints to a seed file could either follow the standard of model contracts
```
seeds:
  - name: seed_name
    config:
      schema: seed_schema
      tags: seed
      column_types:
        seed_id: int
      contract:
        enforced: true
    columns:
      - name: seed_id
        constraints:
         - type: primary_key
```

Or allow the configuration of constraints outside the declaration of a contract
```
seeds:
  - name: seed_name
    config:
      schema: seed_schema
      tags: seed
      column_types:
        seed_id: int
      constraints:
        seed_id: [primary_key, not_null]
```

This could apply at the table level, as well as the column level

### Who will this benefit?

This will benefit seeds by allowing defined constraints on individual columns or the table itself for data governance to determine relationships between primary, surrogate keys and not nullable columns because seeds are materialized as tables

**Comment by dbeatty10** [comment]
Thanks for proposing this @cboethigtrellance!

We're planning to continue supporting constraints only for [models](https://docs.getdbt.com/docs/build/models) at this time (in conjunction with [model contracts](https://docs.getdbt.com/docs/collaborate/govern/model-contracts)) and not extend them to other resource types like [seeds](https://docs.getdbt.com/docs/build/seeds) or [snapshots](https://docs.getdbt.com/docs/build/snapshots). So I'm going to close this as "not planned". See below for a couple alternatives instead.

### `dbt_constraints` package

If your database is Snowflake, PostgreSQL, Oracle, Redshift, or Vertica, the [`dbt_constraints`](https://github.com/Snowflake-Labs/dbt_constraints) would be something to take a look at. (If you are not using one of those databases, see [here](https://github.com/Snowflake-Labs/dbt_constraints?tab=readme-ov-file#dependencies-and-requirements) for notes how to add support for your database.)

Example:

`packages.yml`

```yaml
packages:
  - package: Snowflake-Labs/dbt_constraints
    version: [">=1.0.0", "<1.1.0"]
```

```yaml
seeds:
  - name: seed_name
    columns:
      - name: id
        tests:
          - not_null
```

Install the package and execute the seeds (which will automatically add constraint based off the `not_null` test above):

```shell
dbt deps
dbt seed
```

### Post hook to add constraints

Alternatively, you can use a [post-hook](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook) to add constraints as well.

Example:

`dbt_project.yml`

```yaml
seeds:
  my_project:
    seed_name:
      +post-hook:
        - "alter table {{ this }} alter column id set not null"
```
