### ISSUE TITLE
[Bug]  wild card doesn't work with tags

### ISSUE THREAD

**Issue by AsimpleCommit** [dbt-labs/dbt-core#10570]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt wildcards do not work with tag selectors for example the outcome of 

 dbt ls --select tag:lightdash_* 
 zsh: no matches found: tag:lightdash_*

### Expected Behavior

ideally it searches using the wild card

### Steps To Reproduce

 dbt ls --select tag:lightdash_* 
 zsh: no matches found: tag:lightdash_*

### Relevant log output

```shell
dbt ls --select tag:lightdash_* 
 zsh: no matches found: tag:lightdash_*
```

### Environment

```markdown
- OS:
- Python:
- dbt:1.8.4
```

### Additional Context

https://getdbt.slack.com/archives/C01UM2N7814/p1690794161643919

pain has a been here for a a year +!

**Comment by joellabes** [comment]
If they're all lightdash-related, could you add two tags? i.e. 
```yml
models:
  - name: my_first_model
    config: 
      tags: 
        - lightdash_all
        - lightdash_first_tag
  - name: my_second_model
    config: 
      tags: 
        - lightdash_all
        - lightdash_another_tag
```

Then you could run `dbt build --select tag:lightdash_all`. 

The linked Slack thread is talking about a wildcard with no prefix, e.g. `dbt build --exclude tag:*` which would be in line with something like the already-supported `dbt build --exclude +exposure:*`. By contrast, there's not really precedent for wildcards after a prefix in dbt at the moment.
