### ISSUE TITLE
dbt_profile vars not parsing derived variable correctly when used in a yml file

### ISSUE THREAD

**Issue by petertjmills** [dbt-labs/dbt-core#10589]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Unfortunately I’ve got some sources with different date formats at the end of their table names. I’d like to specify vars in my dbt_project.yml like this:
```yaml
…
vars:
  date: “2024-06-30”
  year: “{{ modules.datetime.datetime.strptime(var(‘date’), ‘%Y-%m-%d’).year }}”
…
```
The year variable works fine when I use it in an sql query, but if I use it in my sources.yml like so:

```yaml
…
sources:
 - name: xyz
   schema: abc
   tables:
    - name: table_x
      identifier: “{{ ‘table_identifier_’ ~ var(‘year’) }}”
…
```

However when I try and use this with `{{ source(‘xyz’, ‘table_x’) }}` dbt renders, as a table name, `abc.table_identifier_{{ modules.datetime…}}` obviously throwing an error. 

If I hardcode the value for year it works fine. 

### Expected Behavior

Expecting `{{ source(‘xyz’, ‘table_x’) }}` to resolve to `abc.table_identifier_2024`

### Steps To Reproduce

1. Define dbt_profiles.yml as above
2. Define sources in `models/*.yml`, referencing a derived variable
3. Run `dbt show —inline “select * from {{ source(‘xyz’, ‘table_x’) }}”`
4. `Unhandled error while executing`

### Environment

```markdown
- OS: macOS Monterey 
- Python: 3.9.6
- dbt: 1.7.3
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

I’m using a custom built adapter for our data infrastructure but I don’t believe this to have an impact. It seems the issue is in how the variables are rendered before any adapter code is run.
Happy to be wrong if this isn’t the case!

**Comment by dbeatty10** [comment]
What if you use a [Jinja filter](https://jinja.palletsprojects.com/en/3.1.x/templates/#builtin-filters) to cast it to a string?

i.e.

```yaml
…
vars:
  date: "2024-06-30"
  year: "{{ modules.datetime.datetime.strptime(var('date'), '%Y-%m-%d').year  | string }}"
…
```

Or:

```yaml
…
sources:
 - name: xyz
   schema: abc
   tables:
    - name: table_x
      identifier: "{{ 'table_identifier_' ~ var('year') | string }}"
…
```

**Comment by petertjmills** [comment]
Thanks for getting back!
Tried all of these, in various combinations, including on the `{{ source() }}` statement with no luck. 😕

**Comment by dbeatty10** [comment]
Ah, I see!

Here's what's going on: Jinja is [not supported](https://docs.getdbt.com/docs/build/project-variables#defining-variables-in-dbt_projectyml) within the `vars` config in `dbt_project.yml`.

<img width="600" alt="image" src="https://github.com/user-attachments/assets/df1d02fd-08cd-42ce-ae1d-e17362d4ff50">

There's more information [here](https://github.com/dbt-labs/dbt-core/issues/3105#issuecomment-779761596) and [here](https://github.com/dbt-labs/dbt-core/issues/4314#issuecomment-979259394). (The proposal in https://github.com/dbt-labs/dbt-core/issues/2955 mentions being "strict about accepting only literal values", so I don't think it would fit what you're after.)

I understand that the way you defined the `year` variable works the way you want within a `.sql` model file, but I believe that is an accidental side effect of the way we render those files rather than a purposeful feature.

Since we're not planning on supporting Jinja within the `vars` config, I'm going to close this as "not planned".

### Alternative approach

If you want to keep it as close to your example as possible, you'd need to do this:

`dbt_project.yml`

```yaml
vars:
  date: "2024-06-30"
```

```yaml
sources:
 - name: xyz
   schema: abc
   tables:
    - name: table_x
      identifier: "{{ 'table_identifier_' ~ modules.datetime.datetime.strptime(var('date'), '%Y-%m-%d').year }}"
```

instead of this:

`dbt_project.yml`

```yaml
vars:
  date: "2024-06-30"
  year: "{{ modules.datetime.datetime.strptime(var('date'), '%Y-%m-%d').year }}"
```

```yaml
sources:
 - name: xyz
   schema: abc
   tables:
    - name: table_x
      identifier: "{{ 'table_identifier_' ~ var('year') }}"
```

**Comment by petertjmills** [comment]
Understood, have missed that! 

Thanks for your help.

For anyone else looking I stumbled across a more succinct solution. Yaml will parse a date like this with no quotation marks, so there's no need to use modules.datetime:
`dbt_project.yml`
```yaml
...
vars:
  date: 2024-06-30
...
```

`sources.yml`
```
...
    identifer: "{{ 'table_' ~ vars('date').year }}"
...
```
