### ISSUE TITLE
[Bug] empty inputs have incorrect datatypes in dbt unit tests

### ISSUE THREAD

**Issue by mchonofsky** [dbt-labs/dbt-core#10586]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In dbt unit tests, the `given:` section contains `input:` entries with `rows:`. Fields that are not defined in the `rows:` are set to `null`. If the row is defined as `row: []` i.e., an empty dataset, the datatype of `null` values is set to `INT64`, not the datatype of the field in the database. Since this compiles to `SELECT ... LIMIT 0`, this causes problems for the model under test, for example if it uses `COALESCE()` to test for the null

### Expected Behavior

The datatype of the null should match the datatype of the column

### Steps To Reproduce

This model will trigger the error:

```
create or replace table tableX (null_col date, id int64) as select null, 1;
create or replace table tableY (notnull_col date, id int64) as select date(2024,1,1), 1;
with x as ( select * from {{ ref("tableX") }})
, y as ( select * from {{ ref("tableY") }}
select coalesce(x.null_col, y.notnull_col) from y left join x using (id)
```

if tested with
```
given:
  - input: ref("tableX")
    rows: []
  - input: ref("tableY")
    - notnull_col: 2024-01-01
      id: 1
```

### Environment

```markdown
- dbt:1.8.2
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thanks for reaching out @mchonofsky !

I altered your example slightly so that I could run it on multiple platforms and see if it only affected dbt-bigquery or other adapters as well.

But I wasn't able to reproduce the issue you reported. Could you try tweaking the example below to see if you can generate the same error you were experiencing?

`models/table_x.sql`

```sql
select cast(null as date) as null_col, 1 as id
```

`models/table_y.sql`

```sql
select cast('2024-01-01' as date) as notnull_col, 1 as id
```

`models/table_z.sql`

```sql
with
x as ( select * from {{ ref("table_x") }} ),
y as ( select * from {{ ref("table_y") }} )

select coalesce(x.null_col, y.notnull_col) as notnull_col
from y left join x on x.id = y.id
```

`models/_unit_tests.yml`

```yaml
unit_tests:
  - name: test_10586

    model: table_z

    given:
      - input: ref("table_x")
        rows: []
      - input: ref("table_y")
        rows:
          - {notnull_col: 2022-02-02, id: 2}

    expect:
        rows:
          - {notnull_col: 2022-02-02}
```
