### ISSUE TITLE
Allow setting of `event_time` as a top-level property of a model with a `field_name` attribute

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#10634]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

In #10624 we're building a new type of incremental model strategy, `microbatch`. This will be an awesome system wherein we do reads and writes for incremental via partitions. As part of that, we need a column to partition by. We're gonna call the key for defining that column `field_name`, and it should live under a top level config property `event_time`. To specify an event time field name in a model's yaml, it would look something like the following
```yaml
models:
 - name: my_model
   config:
     event_time: 
       field_name: my_time_field # <-- This is the key/value we're talking about
       ...
   columns: 
     - name: my_time_field
       data_type: timestamp
```
If you were to specify it in the model's .sql, it would look something like the following
```sql
{{
    config(
        materialized = 'incremental',
        event_time = {"field_name": "my_time_field"}, # <-- This is the key/value we're talking about
    )
}}
...
```

### Acceptance criteria

The `event_time.field_name` configuration is setable via `.sql` and `.yml` for models, and this propagates to the eventual node in the manifest

### Suggested Tests

* Set `event_time.field_name` in the configuration of a model `.sql` file and ensure it propagates to the eventual node in the manifest
* Set `event_time.field_name` in a model `.yml` file and ensure it propagates to the eventual node in the manifest

### Impact to Other Teams

Affects CA: New optional property on model nodes

### Will backports be required?

No
