### ISSUE TITLE
[Feature] Allow setting of `batch_size` as a top-level property of a model

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#10637]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

In #10624 we're building a new type of incremental model strategy, `microbatch`. To support that we need a concept an `batch_size`. The `batch_size` is essentially how "big" the incrementing of the model is. It should support the values `day`, `month`, and `year`. The effect in practice is that if your `batch_size` is `day` then when the `event_start_time` is generated in #10636, we can properly calculate what the "start" of a batch should be. Additionally, the `lookback` which is introduced in #10662 will essentially offset the `event_start_time` by an integer multiple of the `batch_size`

If defining it in the model sql it'd look like
```jinja
-- my_model.sql
{{ config(
     materialization='incremental',
     incremental_strategy='microbatch',
     event_time='my_time_field',
     batch_size='day', -- supported values: day, month, year
   )
}}
...
```

If defining it in the model yaml it'd look like:
```yaml
models:
  - name: my_model
     config:
       event_time: my_time_field
       incremental_strategy: microbatch
       batch_size: day # supported values: day, month, year
```

### Acceptance criteria

- `batch_size` can be set as `day`, `month`, or `year` for an incremental microbatch model

### Suggested Tests

- the `batch` size makes it into the python representation of the model

### Impact to Other Teams

Cloud artifacts, new property in the config of models

### Will backports be required?

No
