### ISSUE TITLE
[Bug] grants does not ignore models that are execluded by --exclude

### ISSUE THREAD

**Issue by RomanPreuss** [dbt-labs/dbt-core#10647]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I define grants in my `dbt_project.yml` and then exclude this part in a build run, dbt still tries to execute the grant statement.

### Expected Behavior

When I run `dbt build --exclude +my_project.base` I don't want that dbt still tries to execute grant statements.

### Steps To Reproduce

1. In the `dbt_project.yml` define grants:
```yml
# ...
models:
    my_project:
        base:
            # ...
            schema: base
            +grants:
                select: ['my_user']
# ...
```
2. Run `dbt build --exclude +my_project.base`

This will result in the error message shown below

### Relevant log output

```shell
09:20:21    on-run-start failed, error:
 Schema "base" does not exist.
```

### Current workaround
I can "disable" the grants (aka generate empty strings) based on some variable in the `dbt_project.yml` which works in my case, because I don't want to build anything in base when I run it using the target `dev` by default.

```yml
# ...
models:
    my_project:
        base:
            # ...
            schema: base
            +grants:
                select: "{{ ['my_user'] if target.name == 'dev' else [] }}"
# ...
```

### Environment

```markdown
- OS: MacOS 14.6.1 (23G93)
- Python: 3.9.18
- dbt: 1.8.1
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

I'm not sure if it's relevant but I'm using custom schemas and the macro described here: https://docs.getdbt.com/docs/build/custom-schemas#how-does-dbt-generate-a-models-schema-name.
