### ISSUE TITLE
accepted_values doesn't work properly when some of the values has the <'> (single quote) special character

### ISSUE THREAD

**Issue by nicods-fr** [dbt-labs/dbt-core#10654]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

accepted_values doesn't work properly when some of the values has the <'> (single quote) special character

### Expected Behavior

```sql
SELECT 'Valeur avec l''apostrophe' AS col_avec_bug
```
This test doesn't work, but it should:

```yml
- models:
-   name: model_buggy
    columns:
      - name: col_avec_bug
        tests:
          - accepted_values:
            values:
              - "Valeur avec l'apostrophe"
              - "Autre valeur enum"
```

### Steps To Reproduce

Same as expected behavior

### Environment

```markdown
- OS: All
- Python: 3.10
- dbt: 1.7.8 (I will test 1.8 later today)
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
Thanks for reporting this @nicods-fr !

### Easiest workaround

The easiest way to solve this: just use the syntax of your database to escape the quotes. In your particular case with Postgres:

```yaml
models:
  - name: my_model
    columns:
      - name: status
        tests:
          - accepted_values:
              values:
                - "will"
                - "won''t"
```

### Possible solution

A possible way to solve this (but it looks like it would break anyone using the workaround above) would be to use the [`escape_single_quotes`](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#string-literal-functions) macro [here](https://github.com/dbt-labs/dbt-adapters/blob/4fd2d9a06522f0ca0548c82ede844755c227de07/dbt/include/global_project/macros/generic_test_sql/accepted_values.sql#L19) like:

```sql
        {{ dbt.string_literal(dbt.escape_single_quotes(value)) }}
```

<details>
<summary>

Full version of `accepted_values` test with that modification (click to toggle visibility)
</summary>

```sql
{% macro default__test_accepted_values(model, column_name, values, quote=True) %}

with all_values as (

    select
        {{ column_name }} as value_field,
        count(*) as n_records

    from {{ model }}
    group by {{ column_name }}

)

select *
from all_values
where value_field not in (
    {% for value in values -%}
        {% if quote -%}
        {{ dbt.string_literal(dbt.escape_single_quotes(value)) }}
        {%- else -%}
        {{ value }}
        {%- endif -%}
        {%- if not loop.last -%},{%- endif %}
    {%- endfor %}
)

{% endmacro %}
```

</details>

I tried this out, and it worked for me with the following YAML:

```yaml
          - accepted_values:
              values:
                - will
                - won't
```
