### ISSUE TITLE
[Bug] Macro and `{{ this }}` variable in post hook sql statement of seeds `properties.yml` don't work properly

### ISSUE THREAD

**Issue by teddyzhu** [dbt-labs/dbt-core#10650]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

As the title said, macro and this variable in post hook sql statement  of seed properties.yml don't works.  But they works when defined in dbt_project.yml. 

For example:
 ```yml
version: 2

seeds:
  - name: dbt_seed_test
    config:
      post-hook:
        - "update {{ this }} set load_ts = '{{ run_started_at }}'::timestamp where load_ts is null"
```
will compile to 
```
 update  set load_ts = '2024-09-02 07:18:30.963611+00...
```

and caused following error:
```
syntax error at or near "="
  LINE 3:         update  set load_ts = '2024-09-02 05:51:15.403332+00...
```
Here, variable {{this}} is blank that caused the error. And if I defined this statement in a macro suppose seed_load_ts,  the error seed_load_ts not found will occur.

### Expected Behavior

I want dbt will parse the variables and macros in seeds's properties.yml correctly .

### Steps To Reproduce

1. my environment as following information.
```sh
Core:
  - installed: 1.8.6
  - latest:    1.8.6 - Up to date!

Plugins:
  - postgres: 1.8.2 - Up to date!
 ```

2. add seeds properties.yml and using post_hoot to add timestamp field load_ts.
3. run dbt seed --full-refresh

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

postgres
