### ISSUE TITLE
[Feature] Allow setting of a `lookback` as top level model property

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#10662]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

In #10624 we're building a new type of incremental model strategy, `microbatch`. To support that we need a concept of `lookback`. The `lookback` is essentially how far to look back in multiples of the `batch_size` when automatically setting the `event_time_start`. So if `event_time_end="2024-09-04 13:44:00"`, `batch_size="day"`, and `lookback=4`, then the `event_start_time` would be set to `2024-08-31 00:00:00`. 
If defining it in the model sql it'd look like
```jinja
-- my_model.sql
{{ config(
     materialization='incremental',
     incremental_strategy='microbatch',
     event_time='my_time_field',
     batch_size='day',
     lookback=0, -- int, defaults to 0 if not specified
   )
}}
...
```

If defining it in the model yaml it'd look like:
```yaml
models:
  - name: my_model
     config:
       event_time: my_time_field
       incremental_strategy: microbatch
       batch_size: day
       lookback: 0 # int, defaults to 0 if not specified
```

### Acceptance criteria

- a `lookback` value can be specified in a model's config
- the `lookback` value should default to `0` if not specified
- the `lookback` value alters the _generated_ `event_time_start` by a multiple of the `batch_size`

### Suggested Tests

- a `lookback` value can be specified in a model's config (via yaml and sql)
- the `lookback` value is default to `0` if not specified
- the `lookback` value alters the _generated_ `event_time_start` by a multiple of the `batch_size`

### Impact to Other Teams

Cloud artifacts, new property in the config of models

### Will backports be required?

No
