### ISSUE TITLE
[Bug] Lineage Graph Ignore Sources Declared From `graph.sources.values()`

### ISSUE THREAD

**Issue by ghilman27** [dbt-labs/dbt-core#10665]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

GIVEN THAT my sources.yml
```yaml
version: 2
sources:
  - name: load
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('BQ_DATASET_LOAD') }}"
    tables:
      - &masked-source-schema
        name: api_masked_1746
        tags: ["source.masked"]
        config:
          meta:
            id: 1746
            ads_is_used: false
            ...other_meta
      - <<: *masked-source-schema
        name: api_masked_2892
        config:
          meta:
            id: 2892
            ads_is_used: false
            ...other_meta
      - <<: *masked-source-schema
        name: api_masked_10002
        config:
          meta:
            id: 10002
            ads_is_used: false
            ...other_meta
      - <<: *masked-source-schema
        name: api_masked_10005
        config:
          meta:
            id: 10005
            ads_is_used: false
            ...other_meta
      - <<: *masked-source-schema
        name: .....other_source_names
        ....
```

And my model definition looks like this
```yaml
{{
  config(
    materialized = 'incremental',
    incremental_strategy = 'insert_overwrite',
    partition_by = {
      "field": "partition_date",
      "data_type": "date",
      "granularity": "day",
      "time_ingestion_partitioning": true,
      "copy_partitions": true
    }
  )
}}

{# WITH graph.sources #}
{%- set graph_tables = ["api_masked_10002", "api_masked_10005"] -%}
{%- for node in graph.sources.values() -%}
  {% if node.name in graph_tables %}
    SELECT * FROM {{ source('load', node.name) }}
    UNION ALL
  {% endif %}
{%- endfor -%}

{# Using ordinary variables #}
{% set ordinary_tables = ['api_masked_1746', 'api_masked_2892'] %}
{% for ordinary_table in ordinary_tables %}
  SELECT * FROM {{ source('load', ordinary_table) }}
  {% if not loop.last %}
  UNION ALL
  {% endif %}
{% endfor %}
```

I then got the compiled query like this
```sql





    SELECT * FROM `my_bq_project`.`my_bq_dataset.`api_masked_10002`
    UNION ALL
  
    SELECT * FROM `my_bq_project`.`my_bq_dataset`.`api_masked_10005`
    UNION ALL
  


  SELECT * FROM `my_bq_project`.`my_bq_dataset`.`api_masked_1746`
  
  UNION ALL
  

  SELECT * FROM `my_bq_project`.`my_bq_dataset`.`api_masked_2892`
  

```

But the lineage graph only shows `api_masked_1746` and `api_masked_2892`.
`api_masked_10002` and `api_masked_10005` are ignored

### Expected Behavior

See all sources including `api_masked_10002` and `api_masked_10005` on Lineage Graph

### Steps To Reproduce

put the same config as mine using the same environment, then you are set

### Relevant log output

![image](https://github.com/user-attachments/assets/f1102c76-4150-4b32-855e-802d43797207)

```shell
no screenshot is available due to its confidentiality
```

### Environment

* I am using a dockerized [dbt-bigquery meltano plugins](https://hub.meltano.com/transformers/dbt-bigquery/). The meltano docker tag is `meltano/meltano:v3.4.2-python3.10`. The full version output of `dbt --version`
![image](https://github.com/user-attachments/assets/e97cd6e9-16ac-427e-bd76-564da5d4d43d)
* OS
![image](https://github.com/user-attachments/assets/63df4c6e-3aba-473f-b571-33a80c22bd21)
* Output of `python --version` inside the docker: 3.10.14

### Which database adapter are you using with dbt?

bigquery

### Additional Context

I haven't tried using the ordinary dbt (not the meltano dockerized version one). I'll update if I have time to check that.
