### ISSUE TITLE
[Bug] Column level test naming doesn't allow to define `error` and `warn` tests on the same column

### ISSUE THREAD

**Issue by siljamardla** [dbt-labs/dbt-core#10693]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

A configuration that adds two column level tests that test the same thing, but have a different severity level:
```
models:
  - name: some_dbt_model
    description: Some dbt model
    columns:
      - name: some_column
        description: Some column that I want to test with different severity in different contexts
        tests:
          - not_null:
              config:
                severity: warn
          - not_null:
              config:
                severity: error
```
results in a compilation error similar to this:
```
Compilation Error
  dbt found two data_tests with the name "not_null_some_dbt_model_some_dbt_column" defined on column "some_column" in "models.some_dbt_model".
  
  Since these resources have the same name, dbt will be unable to find the correct resource
  when running tests.
  
  To fix this, change the name of one of these resources:
  - test.my_dbt_project.not_null_some_dbt_model_some_dbt_column.1bec695ea8 (models/some_dbt_model.yml)
  - test.my_dbt_project.not_null_some_dbt_model_some_dbt_column.1bec695ea8 (models/some_dbt_model.yml)
```

Context: I will need the test to have different severity in different context. I plan to execute the test via
```
dbt test --select test.my_dbt_project.not_null_some_dbt_model_some_dbt_column
```

### Expected Behavior

Being able to define two different tests with different configs and use them according to need. 

### Steps To Reproduce

See above

### Environment

```markdown
- OS: Mac
- Python: 3.11
- dbt: 1.8
```

### Which database adapter are you using with dbt?

spark

**Comment by siljamardla** [comment]
After stumbling on https://github.com/dbt-labs/dbt-core/issues/9740 I realised that I can use custom names on tests. This solves my problem.

```
models:
  - name: some_dbt_model
    description: Some dbt model
    columns:
      - name: some_column
        description: Some column that I want to test with different severity in different contexts
        tests:
          - not_null:
              name: not_null_some_dbt_model_some_column_warn
              config:
                severity: warn
          - not_null:
              name: not_null_some_dbt_model_some_column_error
              config:
                severity: error
```

**Comment by jeremyyeo** [comment]
Just a passer by but seems pretty atypical to want the same test "do I have a null or not" to be simultaneously warn AND error like written:

```yaml
models:
  - name: some_dbt_model
    description: Some dbt model
    columns:
      - name: some_column
        description: Some column that I want to test with different severity in different contexts
        tests:
          - not_null:
              config:
                severity: warn
          - not_null:
              config:
                severity: error
```

It's, imho more typical to have a test be warn OR error if things exceed a threshold. In this scenario - we would use the `warn_if` / `error_if` [configs](https://docs.getdbt.com/reference/resource-configs/severity):

```yaml
models:
  - name: some_dbt_model
    description: Some dbt model
    columns:
      - name: some_column
        description: Some column that I want to test with different severity in different contexts
        tests:
          - not_null:
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">0"
```

So we get a:
* warn if there's more than 0 violations.
* error if there's more than 1000 violations.

This means you know if you get an error - you cannot ignore it and you must fix things asap. But if you get a warning - perhaps this can be fixed tomorrow. (example usefulness of having threshold based warn OR error).

----

Curious how useful things are if "as long as there's more than 0 violation error AND warn at the same time". If I see both a warn AND error every time - then really, what would be the point of differentiating between them? :P Seems not so useful perhaps compared to the threshold via warn_if / error_if described above.
