### ISSUE TITLE
[Bug] unit tests with incremental required mock table to exist

### ISSUE THREAD

**Issue by GiorgiModebadzeW** [dbt-labs/dbt-core#10695]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When creating unit test for the new incremental table and running it ,it fails if we test model in incremental mode.
This is because after mocking "this"  dbt before running the unit test tries to check if the table exists and if it does not fails. 
(For snowflake it runs DESCRIBE statement as the first step)

```yaml
- input: this 
        # contents of current my_incremental_model
        rows:
          - {event_id: 1, event_time: 2020-01-01}
```

This is strange and cumbersome because unit tests are supposed to run before the model is run and because those tests can not pass model is never created. This created some kind of deadlock.
 
currently we need to first create table with (run) and then run unit tests- which defeats purpose of test in the first place and adds overhead for production

### Expected Behavior

In the unit tests we already mock this. So there is no particular need why dbt needs to check if the table already exists. (maybe allow bypass?) 

```yaml
- input: this 
        # contents of current my_incremental_model
        rows:
          - {event_id: 1, event_time: 2020-01-01}
```

### Steps To Reproduce

Create incremental table
add unit test for the incremental check  with 

```yaml
overrides:
      macros:
        is_incremental: true
```
Run dbt build for this table and unit test will fail
Run dbt run for this table and then dbt test or dbt build and unit test will pass.

### Relevant log output

```shell
09:51:10  
09:51:10    Compilation Error in model my_model (models/data/intermediate/schema/unit_tests/my_unit_test.yml)
  Not able to get columns for unit test 'my_model' from relation db.schema.my_model because the relation doesn't exist
  
  > in macro get_fixture_sql (macros/unit_test_sql/get_fixture_sql.sql)
  > called by model my_model (models/data/intermediate/schema/unit_tests/my_unit_test.yml)
```

### Environment

```markdown
- OS: macOS-14.6.1-arm64-arm-64bit
- Python:  3.11.7
- dbt: dbt version: 1.8.5, adapter type: snowflake
11:27:36  adapter version: 1.8.3
```

### Which database adapter are you using with dbt?

snowflake
