### ISSUE TITLE
[Bug] "dbt compile" is giving Compilation Error

### ISSUE THREAD

**Issue by techwithshadab** [dbt-labs/dbt-core#10757]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

**_dbt compile_ is giving Compilation Error**

  dbt found two macros named "group_by" in the project "media_datalake".
   To fix this error, rename or remove one of the following macros:
      - dbt_packages/dbt_expectations/macros/utils/groupby.sql
      - dbt_packages/dbt_utils/macros/sql/groupby.sql

### Expected Behavior

dbt compile should run successfully without giving the above error

### Steps To Reproduce

**Package Version**
dbt-core==1.8.6
dbt-snowflake==1.8.3

**Packages YML file**

```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.3.0
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: dbt-labs/audit_helper
    version: 0.12.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.13.2
  - package: dbt-labs/dbt_external_tables
    version: 0.9.0
  - package: calogica/dbt_expectations
    version: 0.10.3
```

### Environment

```markdown
- OS: MacOS Sonoma 14.6.1
- Python:3.9.6
```

### Which database adapter are you using with dbt?

snowflake
