### ISSUE TITLE
[Bug] Parse incorrectly succeeds when dependency is not installed

### ISSUE THREAD

**Issue by davidharting** [dbt-labs/dbt-core#10760]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`dbt parse` succeeds when a package specified in packages.yml is not installed

### Expected Behavior

`dbt parse` should fail and instruct me to run dbt deps

### Steps To Reproduce

You can watch along with the reproduction in [this Zoom clip](https://dbtlabs.zoom.us/clips/share/D2pILi-xG8o4PMsYyqj8tQDrbhXMLbp8vAGHeB_7Zy3g9hllc1sY9fajjEiHGM84b_n2FiRSn17p4V_qW9cH6xgf.YpYHWs2cXHpKGNxh).

1. Clone https://github.com/dbt-labs/jaffle_shop_duckdb and follow instructions to install dependencies and activate virtual environment
2. Run `dbt parse`. Notice that it succeeds.
3. Create a `packages.yml`. Make it look like this:

```yml
packages:
  - package: dbt-labs/codegen
    version: ["<1.0.0"]
```

4. Run `dbt deps`
6. Update `packages.yml` to add another package:

```yml
packages:
  - package: dbt-labs/codegen
    version: ["<1.0.0"]
  - package: fivetran/salesforce 
    version: [">=1.1.0", "<1.2.0"]
```

7. Run `dbt parse` _(Do **not** run `dbt deps` first)_
**8. Notice that dbt parse succeeds 🐛** when it should actually fail due to missing fivetran/salesforce

### Environment

```markdown
- OS: MacOS 14.16.1
- Python: 3.12.5
- dbt: 1.8.1
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

dbt-duckdb 1.8.1

Looks like Feature Request #4557 would be one way of resolving this bug?
