### ISSUE TITLE
Schema test macro returns error when referencing a model 

### ISSUE THREAD

**Issue by clausherther** [dbt-labs/dbt-core#1077]
When using a reference to a model in a schema test macro, dbt returns an error re: the use of the reference.
For example, this macro:
```
{% macro test_recency_special(model, interval) %}

{% set column_name = kwargs.get('column_name', kwargs.get('field')) %}

with most_recent_date as 
(
    select max(d.calendar_date) as the_date
    from 
        {{ ref('d_date') }} d
    where 
        calendar_date between dateadd('day', -{{ interval }}, current_date) and dateadd('day', -1, current_date)
        and 
        d.some_condition = true
)
select
    case when count(*) > 0 then 0
    else 1
    end as error_result
from 
    {{model}}
where {{column_name}} >=
    (select the_date from most_recent_date)

{% endmacro %}
```
Used like this in `schema.yml`
```
- name: f_table_name
      tests:
          - recency_special:
                field: date_column
                interval: 3
```
Returns this error, even though there is no conditional block:

```
dbt was unable to infer all dependencies for the model "recency_special_f_table_name_date_column__3".
  This typically happens when ref() is placed within a conditional block.
```
