### ISSUE TITLE
[Feature] Add keyword "description" to all tests

### ISSUE THREAD

**Issue by moseleyi** [dbt-labs/dbt-core#10881]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I would like to be able to add description to tests regardless of whether they are built-in or from dbt_utils or audit_helper

```
    data_tests:
      - dbt_utils.expression_is_true: 
          description: "test"
          expression: "gross_amount > net_amount"
```

### Describe alternatives you've considered

There's no alternative

### Who will this benefit?

More explicit documentation of why tests have been added, especially tests that are not self-explanatory like "unique" or "not_null"
