### ISSUE TITLE
[Regression] Quoting behavior for sources

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#10892]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In dbt-core 1.7 and earlier, quoting behavior for sources was not controlled by the quoting configuration in dbt_project.yml, but newer versions of dbt also apply those settings to sources.

In older versions of dbt, this was rendered without quotes around the schema name. The change seems to be unintentional, and we would like to return to the previous behavior.

### Steps To Reproduce

```yaml
# dbt_project.yml
quoting:
  schema: True
```

```yaml
# models/sources.yml
sources:
  - name: <sourcename>
...
```

Create a model that references the source, and note that source(<sourcename>, <tablename>) is rendered in recent versions as:

```
with source as (

    select * from <database>."<schema>".<tablename>

)
```

We can work around with a source which specifically overrides this setting:

```yaml
# models/sources.yml
sources:
  - name: <sourcename>
    quoting:
      schema: False
...
```

### Relevant log output

```shell
.
```

### Environment

```markdown
- OS: Ubuntu/macos
- Python: 3.11
- dbt: 1.8.latest
```

### Which database adapter are you using with dbt?

snowflake
