### ISSUE TITLE
[Feature] Support Jinja within custom `dbt_valid_to_current` configurations

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#10922]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As originally proposed within https://github.com/dbt-labs/dbt-core/issues/10187, allow config for `dbt_valid_to_current` to contain Jinja:

- macro that returns a SQL statement `{{ dbt.date(9999, 12, 31) }}`
- project variable that returns a SQL statement `{{ var('my_future_date') }}`

Examples:

#### Macro that returns a SQL statement

`models/my_model.sql`

```sql
select 1 as id, {{ dbt.current_timestamp() }} as updated_at
```

`snapshots/_snapshots.yml`

```yaml
snapshots:
  - name: my_snapshot
    relation: "ref('my_model')"
    config:
      unique_key: id
      strategy: check
      check_cols: all
      dbt_valid_to_current: "{{ dbt.date(9999, 12, 31) }}"
```

#### Project variable that returns a SQL statement

`dbt_project.yml`

```yaml
vars:
  # SQL expression that is specific to a particular database
  my_future_date: "date('9999-12-31')"
```

`snapshots/_snapshots.yml`

```yaml
snapshots:
  - name: my_snapshot
    relation: "ref('my_model')"
    config:
      unique_key: id
      strategy: check
      check_cols: all
      dbt_valid_to_current: "{{ var('my_future_date') }}"
```

#### Project variable that returns a Jinja expression

In my personal ideal world, this would **also** work, but we officially do **not** support Jinja within vars. However, I seem to recall that it **may** actually work in certain cases. So we may choose for or against this (or allow it to "accidentally" work rather than be intentionally supported).

`dbt_project.yml`

```yaml
vars:
  # Macro that yields a SQL expression when rendered downstream
  my_future_date: "{{ dbt.date(9999, 12, 31) }}"
```
