### ISSUE TITLE
[Bug] Unittests Fail with Quoted Source Table Columns in dbt Framework

### ISSUE THREAD

**Issue by megetron3** [dbt-labs/dbt-core#11015]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We have encountered an issue with the dbt unittests framework where our source table columns are quoted. During unit testing, these cases fail due to the unquoted column name being labeled as an "invalid identifier."

### Expected Behavior

Unittests should pass successfully.
The framework should correctly identify and use quoted column names as specified in the source tables.
There should be no "invalid identifier" errors due to quoting issues.

### Steps To Reproduce

Source Table:
```
CREATE TABLE "source_table" (
    "column1" INTEGER,
    "column2" VARCHAR(255)
);
```

Model:
```
SELECT
    "column1",
    "column2"
FROM
    {{ ref('source_table') }}
```

Test:
```
unit_tests:
  - name: test_quoted_columns
    description: "Ensure columns of a given input will be quoted."
    model: source_table
    given:
      - input: ref('source_table')
        rows:
          - {"column1": 1, "column2": 'value1'}
          - {"column1": 2, "column2": 'value2'}
    expect:
      rows:
        - {"column1": 1, "column2": 'value1'}
        - {"column1": 2, "column2": 'value2'}
```

### Environment

```markdown
- OS: iOS
- Python:
- dbt: 1.8.7
```
