### ISSUE TITLE
[Bug] Unit tests don't recognize versioned sources

### ISSUE THREAD

**Issue by gnilrets** [dbt-labs/dbt-core#11039]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have a test that depends on a model that is versioned, but when I run the test, I get an error that the node cannot be found.

For example, in my unit test I have:
```
unit_tests:
  - name: test_fct_nerc_core__unpatched
    model: fct_nerc_core__unpatched

    given:
      - input: ref('fct_outage')
        # blah....
```

The `fct_outage` model is versioned, and I removed the `v1` version a while ago, so I just have:
```
fct_outage_v2.sql
fct_outage.yml
```

The `fct_outage.yml` model is defined as
```
models:
  - name: fct_outage
    latest_version: 2
   #....
    versions:
      - v: 2
```

When I run the unit test, I get:
```
23:22:59    Compilation Error in unit_test test_fct_nerc_core__unpatched (models/marts/customer/int/fct_nerc_core__unpatched.yml)
  Unit_Test 'unit_test.eta_wh.fct_nerc_core__unpatched.test_fct_nerc_core__unpatched' (models/marts/customer/int/fct_nerc_core__unpatched.yml) depends on a node named 'fct_outage' which was not found
```

However, if I remove versions from `fct_outage.yml` and rename `fct_outage_v2.sql` to `fct_outage.sql`, the unit test works.

### Expected Behavior

We should be able to run unit tests that depend on models that are versioned.

### Steps To Reproduce

1. Create a unit test for a model that depends on a versioned model.
2. Run the unit test.

### Environment

```markdown
- OS: Debian GNU/Linux 12 (bookworm)
- Python: Python 3.10.15
- dbt: 1.8.5
```

### Which database adapter are you using with dbt?

snowflake
