### ISSUE TITLE
[Feature] Add a behaviour change flag to disallow the legacy target_* configs on snapshots

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#11102]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I was just trying to create a YAML snapshot for the first time, and I accidentally went with the old `target_schema` config: 
```
snapshots:
  - name: a_slightly_bad_snapshot
    relation: ref('my_excellent_model')
    config:
      target_schema: snapshots

      strategy: timestamp
      updated_at: modified_at
      unique_key: unique_key
```

Which meant that when I ran `dbt snapshot`, my snapshot was built into `snapshots` instead of `dbt_jlabes_snapshots` as I expected. 

To fix it, I had to use `schema` instead:

```
snapshots:
  - name: my_excellent_snapshot
    relation: ref('my_excellent_model')
    config:
      schema: snapshots 

      strategy: timestamp
      updated_at: modified_at
      unique_key: unique_key
```

I think we should let people block usage of the old target_schema and target_database configs (in YAML-based snapshots at minimum - this isn't available in the classic jinja ones right?) with a behaviour flag.

### Who will this benefit?

- People using the autocomplete from the JSON Schema, who pick a sensible-looking option 
- Admins at large orgs who want to enforce consistent behaviour across all their snapshots without only picking it up in code review
- Fans of environmental separation

### Are you interested in contributing this feature?

👎
