### ISSUE TITLE
[Regression] Jinja templating not working in dependencies.yml

### ISSUE THREAD

**Issue by H-Max** [dbt-labs/dbt-core#11109]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

`packages.yml` file supports jinja templating, at least to read environment variables with `env_var()`.

For instance:
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: '{{ env_var("DBT_UTILS_VERSION", "1.3.0") }}'
```

This **does not work anymore** when renaming the file to `dependencies.yml` and this will be an issue in the future.

We use this to pull private dbt packages from gitlab repositories using a syntax like that:
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.3.0
  - git: "https://{{ ('gitlab-ci-token:' ~ env_var('CI_JOB_TOKEN') ~ '@') if env_var('CI_JOB_TOKEN', '') }}gitlab.com/path/to/my/package"
    revision: 1.1.1
``` 

### Expected/Previous Behavior

Jinja templating should be re-enabled in the file dependencies.yml

### Steps To Reproduce

Simply add jinja templating trying to read an existing (or not) environment variable in dependencies.yml and you'll get a syntax error.

### Environment

```markdown
- OS: MacOS
- Python: 3.11.9
- dbt (working version): whatever the version if you're using packages.yml
- dbt (regression version): whatever the version if you're switching to dependencies.yml
```

### Which database adapter are you using with dbt?

bigquery
