### ISSUE TITLE
[Feature] UnitTests: Mocking the run_query macro to retrieve data from a given Mocked Source/Reference

### ISSUE THREAD

**Issue by megetron3** [dbt-labs/dbt-core#11126]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The macros/models are executing the run_query function, but instead of querying the database, I would like run_query to query the mocked source defined in the unit tests.
Instead of doing this in the test:

```
overrides:
  macros:
    run_query:
      rows:
        - { id: 1 }
```

I want to mock the data directly in the ref model, such as ref('model_a'), and use it with run_query.
Example Model Code:

```
-- model_b.sql
run_query("select * from {{ ref('model_a') }}")
```

Example Unit Test:

```
unit_tests:
  - name: my_unit_test
    model: model_b
    given:
      - input: ref('model_a')
        rows:
          - {id: 1, name: "example"}
    expect:
      rows:
        - {id: 1, name: "example"}
```

By defining the test inputs directly in the ref model, we avoid the need to override run_query using macros, providing a clearer and more maintainable testing strategy.
