### ISSUE TITLE
[Adaptive Job] Add freshness spec to model

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#11123]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

Introduce new configuration on the model to support adaptive job

```
models:
  - name: stg_orders
    freshness:
      # build this model after X amount of time, as long as it has new data
      build_after: 
        count: 4
        period: hour
        depends_on: all
```

### Acceptance criteria

The new configuration will be parsed and represented on the model node after the parsing phase.

### Suggested Tests

1. Test valid freshness config, parsing works
2. Test invalid freshnees config, user should get a clear parsing error.

### Impact to Other Teams

This involve adding new fields to model node, so it will impact metadata team when it is done.

### Will backports be required?

No
