### ISSUE TITLE
[Feature] Allow for real data in unit tests

### ISSUE THREAD

**Issue by mvgijssel** [dbt-labs/dbt-core#11130]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I work for a company called HackerOne and we have a use case for running unit tests without mocking the inputs. There are a couple of models which are fairly complicated which we currently test with a singular data test. The test basically does the following using SQL:

- Does the table contain a row with properties "title: foo, state: 2, amount: 99"
- Does the table contain a row with properties "title: bar, state: 9, amount: 50"
- ...

Because this test passes if there are 0 rows, we have to write the tests in an inverse manner which is hard to understand and debug. When it fails it's unclear why exactly.

So something like the following would be amazing

```yaml
unit_tests:
  - name: the_test
    model: complicated_model # name of the model I'm unit testing
    given: # the mock data for your inputs
      - input: ref('accounts') # use a regular dbt model
      - input: ref('users') # use a regular dbt model
    expect: 
      rows:
        - { title: foo, state: 2, amount: 99 }
        - { title: bar, state: 9, amount: 50 }
```

### Describe alternatives you've considered

Singular data test, which is not very developer friendly

### Who will this benefit?

I think this would be beneficial for folks with complicated models that want to do "row" based testing.

### Are you interested in contributing this feature?

If possible, sure why not!
