### ISSUE TITLE
[Bug] Docs markdown not working with versioned model 

### ISSUE THREAD

**Issue by harshjets** [dbt-labs/dbt-core#11151]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

` versions:`
  `    - v: 1`
  `      description: '{{ doc("dim_customer_v1") }}'`
       
       
   On save get this error 
```
Encountered an error:
Compilation Error
Could not render {{ doc("dim_customer_v1") }}: 'doc' is undefined
```

### Expected Behavior

No error should occur as the doc md has be defined

### Steps To Reproduce

1. Add a markdown to the description of a versioned model
2. Error of doc not defined will show up 

### Environment

```markdown
- OS:mac
- Python:
- dbt:1.9
```

### Additional Context

![Screenshot 2024-12-13 at 10 27 30 AM](https://github.com/user-attachments/assets/747813bc-6391-426d-8bf7-a9ca92283cfe)

**Comment by dbeatty10** [comment]
Thanks for reporting this @harshjets !

I see what you are saying. See below for full details to reproduce this along with the (imperfect!) workarounds in the meantime.

### Reprex

Create these files:

`models/dim_customers_v1.sql`

```sql
select 1 as id
```

`models/dim_customers.md`

```md
{% docs dim_customers %}

# docs
- go
- here
 
{% enddocs %}
```

`models/_models.yml`

```yaml
models:
  - name: dim_customers
    latest_version: 1
    versions:
      - v: 1
        description: "{{ doc('dim_customers') }}"
```

Run this command:

```shell
dbt docs generate
```

Get this error:

```
Compilation Error
  Could not render {{ doc('dim_customers') }}: 'doc' is undefined
```

### Implementation

I think we'll need to make sure that `docs` blocks are in the context when rendering any Jinja that is within the `description` field underneath `v:` keys.

### Workaround

The only workaround in the meantime is either of these two options:

### 1. Use a shared top-level docs block for all versions of the model
```yaml
models:
  - name: dim_customers
    description: "{{ doc('dim_customers') }}"
    latest_version: 1
    versions:
      - v: 1
```

### 2. Exclude Jinja / `docs` blocks from the version description
```yaml
models:
  - name: dim_customers
    latest_version: 1
    versions:
      - v: 1
        description: "Docs for v1"
```
