### ISSUE TITLE
[Bug] Setting model-level `deprecation_date` does not apply to model `versions`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#11176]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If I set:
```
models:
  - name: my_model
    config:
      contract: {enforced: false}
    deprecation_date: "2024-12-21"
    columns: [...]
    versions:
      - v: 1
```

Then `model.my_project.my_model.v1` has a `deprecation_date` of `null`:
```
{"unique_id": "model.testy.my_model.v1", "deprecation_date": null}
```
But if I move the `deprecation_date` property down to the model `versions` property:
```
models:
  - name: my_model
    config:
      contract: {enforced: false}
    deprecation_date: "2024-12-21"
    columns: [...]
    versions:
      - v: 1
        deprecation_date: "2024-12-21"
```

Then:
```
% dbt ls -q -s my_model --output json --output-keys unique_id deprecation_date
{"unique_id": "model.testy.my_model.v1", "deprecation_date": "2024-12-21T00:00:00+01:00"}
```

This is confusing and unexpected behavior.

Specifically, this came up in the context of disabling/removing versioned contracted models (most recently #11161). That should raise an error _unless_ the model has passed its deprecation date. Users were continuing to see the error, even after configuring a passed (past?) `deprecation_date`, because they were configuring it on the top-level model rather than the nested `versions`. (#version

### Expected Behavior

Setting `deprecation_date` for the top-level model should apply that value as default for all `versions`, unless they set a different `deprecation_date`. (I believe this would be the effect if `deprecation_date` were a node-level config.)

### Steps To Reproduce

1. Create a model with a `deprecation_date`
2. Configure `versions` on that model with a single version (`v: 1`)
3. Suddenly the `deprecation_date` "disappears" on that model in `dbt ls` output / manifest

### Environment

```markdown
dbt: 1.10.0-a1 (main)
```
