### ISSUE TITLE
[Feature] Enable persist_docs to automatically inherit descriptions from upstream columns (like dbt Cloud Explorer can)

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#11209]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Filing this on behalf of a customer - they would like the native dbt-core persist_docs functionality to be able to propagate upstream column descriptions to downstream ones as well without having to copy the descriptions multiple times. For example:

```sql
-- models/foo.sql
select 1 id

-- models/bar.sql
select * from {{ ref('foo') }}
```

```yaml
# dbt_project.yml
...
models:
  +persist_docs: 
    columns: true

# models/schema.yml
models:
  - name: foo
    columns:
      - name: id
        description: The id.
```

^ Right now, this means that only `foo.id` will have a description be applied to it - but it would be useful if dbt also automatically added col descriptions for `bar.id` as well.

dbt Cloud Explorer currently is able to propagate column descriptions with it's CLL.
