### ISSUE TITLE
[Bug] Specifying `databricks_compute` doesn't work in models imported via dbt packages

### ISSUE THREAD

**Issue by jelstongreen** [dbt-labs/dbt-core#11240]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When a dbt package is installed in a project that contains a model with a [`databricks_compute`](https://docs.getdbt.com/reference/resource-configs/databricks-configs#specifying-the-compute-for-models) config assigned , that compute is not used by the invoking dbt project. 

### Expected Behavior

Compute should be used regardless of if the model is imported or native to the invokinf project. 

### Steps To Reproduce

Create a test model with a Databricks compute specified in the model level config different to the default compute to the rest of the project. Run it as part of a dbt project and verify it runs on its specified compute. Now move the model to an imported package and try again. It will run on the default compute instead of the specified compute. 

### Relevant log output

```shell

```

### Environment

```markdown
- OS:
- Python:
- dbt: 1.8.8
```

### Which database adapter are you using with dbt?

spark

**Comment by amychen1776** [comment]
@jelstongreen Are you using a package built for dbt-databricks with the dbt-spark adapter? Also could you provide a package example?

**Comment by johnnyC9000** [comment]
I'm having this issue as well with the Elementary package.  It uses pre and post hooks to capture and store performance data.  I've assigned a compute resource in my target to use for it's models, but it ends up using the default compute assigned instead:

dbt_project.yml
```
models:
  elementary:
    ## elementary models will be created in the schema '<your_schema>_elementary'
    +schema: "elementary"
    +databricks_compute: 'elementary'
```

**Comment by dbeatty10** [comment]
Hey @jelstongreen and @johnnyC9000 sorry it took so long to reply to you!

Are you still running into this problem?

I tried to reproduce this, but I wasn't able to -- see "reprex" section below for details. Can you try tweaking the details below to reproduce what you are seeing?

### Reprex

Create these files to configure [`compute:` in `profiles.yml`](https://docs.getdbt.com/reference/resource-configs/databricks-configs#selecting-compute-per-model) and [`databricks_compute` in `dbt_project.yml`](https://docs.getdbt.com/reference/resource-configs/databricks-configs?version=1.12#specifying-the-compute-for-models):

#### Root dbt project

`profiles.yml`
```yaml
databricks:
  target: databricks
  outputs:
    databricks:
      type: databricks
      host: "{{ env_var('DBT_DATABRICKS_HOST_NAME') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH') }}"
      schema: "{{ env_var('DATABRICKS_USER_SCHEMA') }}"
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      threads: 10
      compute:
        native_model_compute:
          http_path: "<alternate_http_path>"
```

`dbt_project.yml`
```yaml
name: 'core_11240_reprex'
profile: 'databricks'

models:
  my_package:
    +databricks_compute: 'native_model_compute'
```

`packages.yml`
```yaml
packages:
  - local: local_package
```

`models/my_model.sql`
```sql
select 1 as id
```

#### Local package

`local_package/dbt_project.yml`
```yaml
name: 'my_package'
version: '1.0.0'
```

`local_package/models/package_model.sql`
```sql
select 1 as id
```

Run these commands:
```shell
dbt deps
dbt ls --output json -q | jq .
```

See this as part of the output:

```json
{
  "name": "package_model",
  "package_name": "my_package",
  "config": {
    "materialized": "view",
    "databricks_compute": "native_model_compute"
  }
}
```

```shell
dbt run --debug
```

After running, `logs/dbt.log` shows the adapter using the correct compute for each model:

```
model.core_11240_reprex.my_model, compute-name=)
  - using default compute resource for model '...my_model'

model.my_package.package_model, compute-name=native_model_compute)
  - using compute resource 'native_model_compute' for model '...package_model'
```
