### ISSUE TITLE
[Feature] Enable `dict` format for ephemeral model inputs in a unit test

### ISSUE THREAD

**Issue by fbertsch** [dbt-labs/dbt-core#11263]
### Is this your first time submitting a feature request?

- [x] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [x] I have searched the existing issues, and I could not find an existing issue for this feature
- [x] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Allow ephemeral models to define unit tests using `dict` format. The rows for the unit tests could be written as YAML, easing both writability and readability.

### Describe alternatives you've considered

Follow-up from https://github.com/dbt-labs/dbt-core/issues/9686.

The `sql` format for unit tests allow us to define unit tests for ephemeral models, but are far less convenient than `dict` format:

- Unable to use anchors and references, which are especially useful for fields repeated in many/all unit tests
- Must supply data for all rows
- Linting/formatting is difficult

### Who will this benefit?

Everyone who unit tests ephemeral models. This might make ephemeral models more useful.

### Are you interested in contributing this feature?

If someone gives a rough pointer of where to contribute, I can do it

**Comment by graciegoheen** [comment]
@fbertsch Thanks for opening! We do document this current limitation here -> https://docs.getdbt.com/docs/build/unit-tests#unit-testing-a-model-that-depends-on-ephemeral-models

But I agree, that enabling users to define inputs for ephemeral models in their unit tests using dict format would be a nice feature.

### Acceptance criteria

- I can use the `dict` format for defining inputs for an ephemeral model within a unit test

```
unit_tests:
  - name: my_unit_test
    model: model_to_test
    given: 
      - input: ref('my_ephemeral_model')
        rows:
          - {a: 1,     b: hello}
          - {a: 2,     b: hi}
          - {a: 3,     b: howdy}
          - {a: 4,     b: goodmorning}
```
