### ISSUE TITLE
deprecation warning for duplicate keys in profiles.yml

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#11296]
### Housekeeping

- [x] I am a maintainer of dbt-core

### Short description

Currently, if you have duplicate keys in your profiles.yml, dbt just uses the last one.

```yaml
my_profile:
  ...
  
my_profile:
  ...
```

This pattern - duplicated yaml keys that silently overwrite - is not one we want to continue to support. 

We should throw a deprecation warning with associated telemetry for this in dbt-core `v1.10`, and then eventually remove support entirely.

### Acceptance criteria

If you have duplicate top-level keys in `profiles.yml` - throw a deprecation warning.

**Comment by jeremyyeo** [comment]
Similarish - https://github.com/dbt-labs/dbt-core/issues/5114

**Comment by FishtownBuildBot** [comment]
Opened a new issue in dbt-labs/docs.getdbt.com: https://github.com/dbt-labs/docs.getdbt.com/issues/7212

**Comment by liorash-targetboard** [comment]
Hi. 
The deprecation warnings is thrown even if the duplicate key is not a top level key. for example:

```
vars:
  accounts_config: 
    client1:
      jira_sprint_table: empty 
      dev_items_model: monday
      tasks_model: monday
    client2:
      jira_sprint_table: sprint
      incident_model: pagerduty
```

I'm getting a deprecation warning for `jira_sprint_table` - which is not the top level key.
Can this be fixed please?

Thank you,
