### ISSUE TITLE
[Feature] Allow for groups to have a description and/or meta field

### ISSUE THREAD

**Issue by ttusing** [dbt-labs/dbt-core#11319]
### Is this your first time submitting a feature request?

- [x] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [x] I have searched the existing issues, and I could not find an existing issue for this feature
- [x] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Groups do not allow additional properties, like descriptions. This seems like a very obvious and helpful field to have. If there is no reason not to, why shouldn't groups support a meta property with whatever is helpful to save as well?

### Describe alternatives you've considered

Not documenting my groups.

### Who will this benefit?

Users of groups.

### Are you interested in contributing this feature?

Yes

**Comment by graciegoheen** [comment]
Thanks for opening! I'm in support of this.

### Acceptance criteria
- I can add `description` to my group
- I can add `meta` to my group

```
groups:
  - name: finance
    description: for the finance team 
    config:
      meta:
        whatever_is_helpful: here
...
```
