### ISSUE TITLE
[Bug] dbt build : run tests on selected model with tags

### ISSUE THREAD

**Issue by seuf** [dbt-labs/dbt-core#11325]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hi,

I would like to build a dbt model + tests according to the tags I have defined for each tests

For example I have a model:

```yaml
version: 2

models:
  - name: orders
    config:
      tags:
        - staging
        - production
    columns:
      - name: order_id
        tests:
          - unique:
              tags:
                - production
      - name: customer_id
        tests:
          - not_null:
              tags:
                - staging
                - production
```

Here I want to run the model + the test "not_null" on the column "customer_id" only when I run the model on the target "staging"

But it seems that tags are herited from the model.

When I run the following command, it runs the model + all the tests (not only the ones with the tag "staging")

```bash
dbt build --target staging --select 'orders,tag:staging'
13:16:07  Running with dbt=1.9.0
13:16:09  Registered adapter: bigquery=1.9.0
13:16:17  Found 956 models, 2133 data tests, 797 sources, 186 exposures, 870 macros
13:16:18  
13:16:18  Concurrency: 4 threads (target='staging')
13:16:18  
13:16:20  1 of 4 START sql table model bigquery-project-redacted.dbt.orders  [RUN]
13:16:30  1 of 4 OK created sql table model bigquery-project-redacted.dbt.orders  [CREATE TABLE (8.0 rows, 1.4 GiB processed) in 10.54s]
13:16:30  3 of 4 START test not_null_orders_customer_id . [RUN]
13:16:30  4 of 4 START test unique_orders_order_id ...... [RUN]
13:16:31  3 of 4 PASS not_null_orders_customer_id ....... [PASS in 1.07s]
13:16:31  4 of 4 PASS unique_orders_order_id ............ [PASS in 1.16s]
13:16:31  
13:16:31  Finished running 1 table model, 3 data tests in 0 hours 0 minutes and 13.72 seconds (13.72s).
13:16:31  
13:16:31  Completed with 1 error, 0 partial successes, and 0 warnings:
```

The test unique_orders_order_id is executed event it don't have the staging tag.

Is there a way to run only the tests with the selected tags on s selected model ?

If I run `dbt build -t staging --select "orders tags:staging"` it will execute eveything that have the tag staging.

If I remove the tags on on model config, nothing is executed.

Thanks

### Expected Behavior

Only the tests having the selected tag:staging are executed.

### Steps To Reproduce

Create a model with 2 tags, and tests with only one tag like in the description ⬆ 

### Relevant log output

```shell

```

### Environment

```markdown
- OS: Ubuntu 24.04
- Python: 3.11
- dbt: 1.9.0
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
> This means that tests are still selected indirectly because the tag select the parent.

Yep, you're spot-on @seuf 🎯

The key insight is that if the parent model is selected, then all of its data tests will be **also** selected indirectly during dbt build.

I'm going to close this as not a bug, but there's a few workarounds which I will describe below. (The first one might be the easiest for you with your current setup.)

### 1. Enable data tests based on the target

Use the [`empty`](https://docs.getdbt.com/reference/global-configs/indirect-selection#empty-mode) mode for `--indirect-selection`:

```shell
dbt build --select 'tag:staging' --indirect-selection empty
```

This says:
- do **not** indirectly select any data tests
- but still select any data tests based on the tag

### 2. Enable data tests based on the target

Alternatively, you could try using [`enabled`](https://docs.getdbt.com/reference/resource-configs/enabled) config using the [`target.name`](https://docs.getdbt.com/reference/dbt-jinja-functions/target) variable:

```yaml
models:
  - name: orders
    config:
      tags:
        - staging
        - production
    columns:
      - name: order_id
        tests:
          - unique:
              enabled: "{{ target.name == 'production' }}"
      - name: customer_id
        tests:
          - not_null:
              enabled: "{{ target.name == 'production' or target.name == 'staging' }}"
```

### 3. Use a unique tag name

When using the default indirect selection of [`eager`](https://docs.getdbt.com/reference/global-configs/indirect-selection#eager-mode),  the only way to run _only_ the `not_null_orders_customer_id` test (and _not_ also the `unique_orders_order_id`) is to give the test a tag that does **not** also exist on the model.

e.g., add a `staging_test` tag like this:

```yaml
      - name: customer_id
        tests:
          - not_null:
              tags:
                - staging
                - staging_test
                - production
```

Then run only the tests with that tag:
```
dbt test --select 'tag:staging_test'
```
