### ISSUE TITLE
[Feature] make header row optional for dbt seeds

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#11334]
### Is this your first time submitting a feature request?

- [x] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [x] I have searched the existing issues, and I could not find an existing issue for this feature
- [x] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

If I've configured my column names in a yml file, I don't want to also keep a header row up-to-date in my csv seed file. 

```yaml
seeds:
  - name: my_seed
    columns:
      - name: country_code
        data_type: varchar(2)
      - name: country_name
        data_type: varchar(32)
```

```csv
country_code,country_name
US,United States
CA,Canada
GB,United Kingdom
```

Instead, I should be able to configure my seed to not need a header row _if_ I've configured my column names in yml already. 

```yaml
seeds:
  - name: my_seed
    config:
      header_row: false
    columns:
      - name: country_code
        data_type: varchar(2)
      - name: country_name
        data_type: varchar(32)
```

```csv
US,United States
CA,Canada
GB,United Kingdom
```
