### ISSUE TITLE
[Bug] constraints not shown in docs

### ISSUE THREAD

**Issue by frankivo** [dbt-labs/dbt-core#11416]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

defined not_null, pk and fk in model yml. generated static docs.
docs do not show anything in the "constraints" column for said model.

tried both dbt-databricks and dbt-duckdb

### Expected Behavior

expecting constraints in generated documentation.

### Steps To Reproduce

```  
constraints:
        - type: primary_key
          name: pk__fact_contract_hrm
          columns: [EmployeeContractKey]
        - type: not_null
          columns: [EmployeeContractKey]
        - type: foreign_key
          name: fk__fact_contract_hrm__employee
          columns: [EmployeeKey]
          to: ref("dim_employee_hrm")
          to_columns: [EmployeeKey]
```
dbt docs generate --static
dbt serve

### Relevant log output

```shell

```

### Environment

```markdown
- OS: win11
- Python: 3.12.9
- dbt: 1.9.3
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Plugins:
  - databricks: 1.9.7 - Up to date!
  - duckdb:     1.9.2 - Up to date!
