### ISSUE TITLE
[Feature] Add exclude_currenttime Parameter for Microbatch Incremental Models

### ISSUE THREAD

**Issue by SGA-taichi-kato** [dbt-labs/dbt-core#11448]
### Is this your first time submitting a feature request?

- [x] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [x] I have searched the existing issues, and I could not find an existing issue for this feature
- [x] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

**Background**
When using microbatch incremental models with lookback=1, dbt processes two partitions:

1. Day-based batch size example:
    - For an execution at 2025-04-01 UTC:
      - Partition ①: 2025-03-31 <= event_time < 2025-04-01
      - Partition ②: 2025-04-01 <= event_time < 2025-04-02

Partition ② corresponds to the current execution time period.

2. Month-based batch size example:
    - For an execution at 2025-04-01 UTC:
      - Partition ①: 2025-03-01 <= event_time < 2025-04-01
      - Partition ②: 2025-04-01 <= event_time < 2025-05-01

Again, Partition ② corresponds to the current execution time period.

In many scenarios, processing the current execution time partition (Partition ②) is unnecessary because:

- The data for this partition is incomplete.
- The partition will need to be reprocessed in subsequent runs when more data becomes available.
- This results in wasted computational resources and unnecessary complexity in downstream workflows.

**Proposed Solution**
Introduce a new parameter called exclude_currenttime in dbt's microbatch configuration. When set to true, this parameter excludes the batch corresponding to the current execution time period from being processed.

**Expected Behavior**
When exclude_currenttime=true:

1. Day-based batch size example:
    - Execution at 2025-04-01 UTC:
      - Only Partition ① (2025-03-31 <= event_time < 2025-04-01) is processed.

2. Month-based batch size example:
    - Execution at 2025-04-01 UTC:
      - Only Partition ① (2025-03-01 <= event_time < 2025-04-01) is processed.

When exclude_currenttime=false (default behavior):
Both Partition ① and Partition ② are processed as they currently are

### Describe alternatives you've considered

Currently, users can manually exclude the current execution time partition by specifying explicit ranges using --event-time-start and --event-time-end. However, this approach is cumbersome and error-prone, especially for automated workflows.

### Who will this benefit?

all users using microbatch strategy

**Comment by MatthewWagnerPEP** [comment]
This would be a fantastic addition to micro batching. It currently is difficult to automate jobs with micro batch models.

**Comment by charlie-mollin** [comment]
^^ agreed!

**Comment by graciegoheen** [comment]
Thanks for opening. While, you're correct, you could workaround this by explicitly passing in an `--event-time-end`, I agree it would be a nice improvement to automatically handle the use case where you want to "never process the current batch".

A few ideas for how this could be configured:
```
models:
  - name: my_microbatch_model
    config:
      # boolean config to determine if current batch should be processes
      include_current_batch: true | false # where true is the default
```

```
models:
  - name: user_sessions
    config:
      # similar to begin config, the "end of time" for your microbatch model
      end: "DATEADD(day, -1, current_timestamp())" # where default is None
```

The latter is similar to `stop_date` in this custom materialization https://gist.github.com/jessedobbelaere/6fdb593f9e2cc732e9f142c56c9bac87
