### ISSUE TITLE
[Feature] Pre-hooks in `profiles.yml`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#11453]
### Is this your first time submitting a feature request?

- [x] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [x] I have searched the existing issues, and I could not find an existing issue for this feature
- [x] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Generalizing [this feature request](https://github.com/dbt-labs/dbt-adapters/issues/965), we could enable many different settings to be configurable at the session level. These would be applied at the start of every session and persist throughout.

It might look like this:

`profiles.yml`

```yaml
profile-to-my-RS-target:
  target: dev
  outputs:
    dev:
      type: redshift
      ...
      pre_hook:
            - set enable_case_sensitive_identifier to true
            - set datestyle to 'SQL,DMY'
```

### Describe alternatives you've considered

Here's an alternative that is specific to `dbt-redshift`:
- https://github.com/dbt-labs/dbt-adapters/issues/965

We could imagine similar case-by-case profile settings for things like `timezone`, etc.

### Who will this benefit?

This would benefit any users that want to set database settings / parameters for the duration of their session.

It would be a more generalized alternative to using [pre-hooks or `sql_header`](https://docs.getdbt.com/reference/resource-configs/sql_header#comparison-to-pre-hooks) for setting things like `timezone`.

It would also benefit users of `dbt-redshift` that want ANSI standard behavior for quoted identifiers and JSON but can't change their Redshift cluster settings.
