### ISSUE TITLE
[Bug] unit-tests: case-sensitive json keys are not found even with "set enable_case_sensitive_identifier to true"

### ISSUE THREAD

**Issue by HansBambel** [dbt-labs/dbt-core#11452]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Could be that this is Redshift-specific.

I have a dbt-table that contains a SUPER-type with the key `outputContentIds` which contains a list of strings. (Example to follow). In the model's sql I set the pre-hook in the config (taken from this [comment](https://github.com/dbt-labs/dbt-core/issues/1557#issuecomment-963222118)).

The unit-tests fail as the JSON's (super-type in redshift) key `outputContentIds` is called as `outputcontentids` and therefore not found:
```shell
actual differs from expected:

@@,session_id   ,plugin_output_successful,plugin_runs
→ ,session_all  ,2→0                     ,2
→ ,session_mixed,2→0                     ,4
  ,session_none ,0                       ,3
```

### Expected Behavior

The unit-tests pass as the model's pre-hook is used.

In the redshift editor I can use the compiled unit-test and just add `SET enable_case_sensitive_identifier TO true;` in front of the query to make it pass:
```sql
SET enable_case_sensitive_identifier TO true;

with my_temp as (
   select 'session_all' as log_id, json_parse('{"outputContentIds":["Unit 1"]}') as value union all
select 'session_all' as log_id, json_parse('{"outputContentIds":["Unit 2"]}') as value union all
select 'session_mixed' as log_id, json_parse('{"outputContentIds":["Unit 2"]}') as value union all
select 'session_mixed' as log_id, json_parse('{"outputContentIds":[]}') as value union all
select 'session_mixed' as log_id, json_parse('{"outputContentIds":[]}') as value union all
select 'session_mixed' as log_id, json_parse('{"outputContentIds":["Unit 2"]}') as value union all
select 'session_none' as log_id, json_parse('{"outputContentIds":[]}') as value union all
select 'session_none' as log_id, json_parse('{"outputContentIds":null}') as value union all
select 'session_none' as log_id, null as value
)
select
    log_id as session_id,
    sum(case when value."outputContentIds"[0] is not null then 1 else 0 end) as plugin_output_successful,
    count(*) as plugin_runs
FROM my_temp
GROUP by log_id
```

### Steps To Reproduce

1. My model:
```sql
{{
    config(
        materialized="table",
        pre_hook="set enable_case_sensitive_identifier to true",
        dist="session_id",
        alias="session_plugin_output"
    )
}}

select
    log_id as session_id,
    sum(case when value."outputContentIds"[0] is not null then 1 else 0 end) as plugin_output_successful,
    count(*) as plugin_runs
from {{ source("redshift", "my_source_table") }}
group by log_id
```

2. My unit test:
```yaml
unit_tests:
  - name: check_aggregation
    description: "Check that only those plugin runs that produced output are counted in the plugin_output_successful column."
    model: session_plugin_output
    given:
      - input: source('redshift', 'my_source_table')
        format: sql
        rows: |
          select 'session_all' as log_id, json_parse('{"outputContentIds":["Unit 1"]}') as value union all
          select 'session_all' as log_id, json_parse('{"outputContentIds":["Unit 2"]}') as value union all
          select 'session_mixed' as log_id, json_parse('{"outputContentIds":["Unit 2"]}') as value union all
          select 'session_mixed' as log_id, json_parse('{"outputContentIds":[]}') as value union all
          select 'session_mixed' as log_id, json_parse('{"outputContentIds":[]}') as value union all
          select 'session_mixed' as log_id, json_parse('{"outputContentIds":["Unit 2"]}') as value union all
          select 'session_none' as log_id, json_parse('{"outputContentIds":[]}') as value union all
          select 'session_none' as log_id, json_parse('{"outputContentIds":null}') as value union all
          select 'session_none' as log_id, null as value
    expect:
      rows:
        - {session_id: session_all, plugin_output_successful: 2, plugin_runs: 2}
        - {session_id: session_mixed, plugin_output_successful: 2, plugin_runs: 4}
        - {session_id: session_none, plugin_output_successful: 0, plugin_runs: 3}
```
3. `dbt test --select check_aggregation`
4. The target compiled is missing the `set enable_case_sensitive_identifier to true`:
```sql
with __dbt__cte__my_source_table as (
set enable_case_sensitive_identifier to true;
select 'session_all' as log_id, json_parse('{"outputContentIds":["Unit 1"]}') as value union all
select 'session_all' as log_id, json_parse('{"outputContentIds":["Unit 2"]}') as value union all
select 'session_mixed' as log_id, json_parse('{"outputContentIds":["Unit 2"]}') as value union all
select 'session_mixed' as log_id, json_parse('{"outputContentIds":[]}') as value union all
select 'session_mixed' as log_id, json_parse('{"outputContentIds":[]}') as value union all
select 'session_mixed' as log_id, json_parse('{"outputContentIds":["Unit 2"]}') as value union all
select 'session_none' as log_id, json_parse('{"outputContentIds":[]}') as value union all
select 'session_none' as log_id, json_parse('{"outputContentIds":null}') as value union all
select 'session_none' as log_id, null as value
) select
    log_id as session_id,
    sum(case when value."outputContentIds"[0] is not null then 1 else 0 end) as plugin_output_successful,
    count(*) as plugin_runs
from __dbt__cte__my_source_table
group by log_id
```

### Environment

```markdown
- OS: MacOS
- Python: 3.12.2
- dbt: 1.9.3
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

I would also be fine with the possibility to add to the unit-test this identifier specifically.

In `dbt_project.yml` `+pre-hook: "RESET enable_case_sensitive_identifier"` is set for all tables and it needs to be set/overridden explicitly again for those that need it.

**Comment by dbeatty10** [comment]
Thanks for reaching out @HansBambel !

This is not a bug with dbt-core or dbt-redshift, so I'm going to close this in favor of the 💡 feature ideas  mentioned below.

## Recommendation

👉 To get standard behavior, we recommend setting `enable_case_sensitive_identifier` to `true` within your Redshift cluster itself.

See below for more details.

## Root cause and suggested fix

I believe the root issue is Redshift's non-standard behavior when `enable_case_sensitive_identifier` is `false` (unfortunately Redshift's default behavior!) [[1](https://docs.aws.amazon.com/redshift/latest/dg/r_names.html?utm_source=chatgpt.com)][[2](https://docs.aws.amazon.com/redshift/latest/dg/r_enable_case_sensitive_identifier.html)]. In this case, Redshift does not use case-sensitivity even when quoted identifiers are used 🤯  Same thing for JSON (which is _supposed_ to be inherently case-sensitive, even without quoted identifiers).

To get standard behavior, we recommend setting `enable_case_sensitive_identifier` to `true` within your Redshift cluster (rather than trying to band-aid with session-level overrides of `enable_case_sensitive_identifier`). If there are any users relying on the behavior of `enable_case_sensitive_identifier` is `false`, then you can migrate _them_ to apply `set enable_case_sensitive_identifier to false`. You may even find that _nobody_ needs the `false` behavior (and everyone is working around an unfortunate default configuration)!

## Example where `enable_case_sensitive_identifier` is `true`

Here's a slightly simplified version of your example along with the output when `enable_case_sensitive_identifier` is `true`.

Create these files:

`models/my_source_table.sql`

```sql
{{ config(materialized="ephemeral") }}

select 'session_all' as log_id, json_parse('{"outputContentIds":["Unit 1"]}') as value union all
select 'session_none' as log_id, null as value
```

`models/session_plugin_output.sql `

```sql
{{ config(materialized="table") }}

with

redshift__my_source_table as (

    select * from {{ ref("my_source_table") }}

)

select
    log_id as session_id,
    sum(case when value."outputContentIds"[0] is not null then 1 else 0 end) as plugin_output_successful,
    count(*) as plugin_runs
from redshift__my_source_table
group by log_id
```

`models/_unit_tests.yaml`

```yaml
unit_tests:
  - name: check_aggregation
    description: "Check that only those plugin runs that produced output are counted in the plugin_output_successful column."
    model: session_plugin_output
    given:
      - input: ref('my_source_table')
        format: sql
        rows: |
          select 'session_all' as log_id, json_parse('{"outputContentIds":["Unit 1"]}') as value union all
          select 'session_none' as log_id, null as value
    expect:
      rows:
        - {session_id: session_all, plugin_output_successful: 1, plugin_runs: 1}
        - {session_id: session_none, plugin_output_successful: 0, plugin_runs: 1}
```

Run this command:

```shell
dbt build -s +session_plugin_output
```

✅ Get this output:

```
$ dbt build -s +session_plugin_output

13:27:23  Running with dbt=1.9.3
13:27:24  Registered adapter: redshift=1.9.2
13:27:24  Found 2 models, 500 macros, 1 unit test
13:27:24  
13:27:24  Concurrency: 5 threads (target='blue')
13:27:24  
13:27:30  1 of 3 START unit_test session_plugin_output::check_aggregation ................ [RUN]
13:27:34  1 of 3 PASS session_plugin_output::check_aggregation ........................... [PASS in 4.55s]
13:27:34  2 of 3 START sql table model dbt_dbeatty.session_plugin_output ................. [RUN]
13:27:39  2 of 3 OK created sql table model dbt_dbeatty.session_plugin_output ............ [SUCCESS in 5.12s]
13:27:40  
13:27:40  Finished running 1 table model, 1 unit test in 0 hours 0 minutes and 16.54 seconds (16.54s).
13:27:40  
13:27:40  Completed successfully
13:27:40  
13:27:40  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
```

## Potential workarounds

### Hooks

One possible way to workaround a default `enable_case_sensitive_identifier` setting is to use [hooks](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook) like you mentioned.

But this will **not** work for dbt unit tests, because pre- and post- hooks are not executed -- all inputs are mocked using a CTE-based approach in which hooks can't be executed. We have considered a seed-based approach (https://github.com/dbt-labs/dbt-core/issues/8499) which would enable running hooks (https://github.com/dbt-labs/dbt-core/issues/9683). But we don't have immediate plans for either (although we always welcome comments on those issues!).

### 💡 New feature for `dbt-redshift` for session-level `enable_case_sensitive_identifier` setting

To empower folks that can't change their cluster settings but want the behavior of `enable_case_sensitive_identifier` is `true` for all their dbt work, we could enable a  (similar to [these](https://docs.getdbt.com/docs/core/connect-data-platform/redshift-setup#redshift-notes
)):

`profiles.yml`

```yaml
profile-to-my-RS-target:
  target: dev
  outputs:
    dev:
      type: redshift
      ...
      enable_case_sensitive_identifier: True
```

### 💡 New feature for `dbt-core` for session-level settings

Generalizing the idea above, we could enable many different settings to be configurable at the session level. These would be applied at the start of every session and persist throughout.

It might look like this:

`profiles.yml`

```yaml
profile-to-my-RS-target:
  target: dev
  outputs:
    dev:
      type: redshift
      ...
      pre_hook:
            - set enable_case_sensitive_identifier to true
            - set datestyle to 'SQL,DMY'
```
