### ISSUE TITLE
[Bug] DBT deps modifying lock file

### ISSUE THREAD

**Issue by DustinMoriarty** [dbt-labs/dbt-core#11468]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Actual behavior: Changes to packages.yml cause package updates when only `dbt deps` is run and when pacakges-lock.yml version is inside the version range in pacakges.yml.  The same behavior is also observed when `dbt deps --lock` is run.

### Expected Behavior

Expected behavior: packages-lock.yml and the installed packages in dbt_packages will not change unless `--upgrade` is provided. If the packages.yml file is changed in a way that is compatible with packages-lock.yml, then no change is made to installed packages. If it is changed in a way that is incompatible and --upgrade is not provided, then the tool should raise an error.  

### Steps To Reproduce

1. Create a DBT project. 
2. Create a `packages.yml` file with the following content.
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: [">=1.3.0", "<1.4.0"]
  - package: elementary-data/elementary
    version: [">=0.16.1", "<0.16.2"]
  - package: fivetran/salesforce_formula_utils
    version: [ ">=0.10.0", "<0.11.0" ]
  - package: fivetran/fivetran_utils
    version: [ ">=0.4.10", "<0.5.0" ]
```
3. Run `dbt deps`.  This results in the following packages-lock.yml file.
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.3.0
  - package: elementary-data/elementary
    version: 0.16.1
  - package: fivetran/salesforce_formula_utils
    version: 0.10.0
  - package: fivetran/fivetran_utils
    version: 0.4.10
sha1_hash: 3f09d83c18baf09928333399cf82923a14c04dbf
```
4. Change `packages.yml` to increase the range for one of the packages. 
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: [">=1.3.0", "<1.4.0"]
  - package: elementary-data/elementary
    version: [">=0.16.1", "<0.17.0"]
  - package: fivetran/salesforce_formula_utils
    version: [ ">=0.10.0", "<0.11.0" ]
  - package: fivetran/fivetran_utils
    version: [ ">=0.4.10", "<0.5.0" ]
```
5. Run `dbt deps`. This results in the version being upgraded in packages-lock.yml and in the installed versions. The elementary-data/elementary package is upgraded even though I did not tell dbt to look for upgraded versions. The package-lock.yml mechanism is bypassed.
```shell
packages:
  - package: dbt-labs/dbt_utils
    version: 1.3.0
  - package: elementary-data/elementary
    version: 0.16.4
  - package: fivetran/salesforce_formula_utils
    version: 0.10.0
  - package: fivetran/fivetran_utils
    version: 0.4.10
sha1_hash: b24a6e406024079fb8e7abf65fd202caf02fd087
```

As an alternative step (3), run `dbt deps --lock`. The same behavior is observed.

### Relevant log output

```shell

```

### Environment

```markdown
- OS: MacOS 15.3.2
- Python: 3.11.9
- dbt: Reproduced in 1.9.4 and 1.8.8
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

According to the [documentation](https://docs.getdbt.com/reference/commands/deps#predictable-package-installs), dbt deps is supposed to only install the packages pegged by the lock file. However, it appears the dbt deps is effectively running with the `--upgrade` option even when it is not provided. The documented behavior makes sense. This is a use case similar to NPM, python poetry and many other package management tools where there is a user configurable file for the requested ranges and a lock file for pegging the machine generated dependency resolution results for predictable installations. However, the tool does not appear to be matching the documented behavior. The actual installation is not deterministic.

I suspect that part of the problem is that the packages.yml file is included in the hash. Therefore, any changes to the packages.yml file result in changes to the lock file and the installed packages. There is no way for the user to modify this file without allowing all dependency resolution to rerun. The user is back to having to peg the version in packages.yml, which defeats the purpose of packages-lock.yml.
