### ISSUE TITLE
[Bug] dbt-sqlite (v1.9.1): Persistent Profile Parsing Errors and Incorrect Path Generation for main Schema

### ISSUE THREAD

**Issue by allenday** [dbt-labs/dbt-core#11467]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using `dbt-sqlite` v1.9.1 with `dbt-core` v1.9.4, there are persistent and contradictory errors related to parsing the `profiles.yml` file and incorrect path generation when targeting the default SQLite main schema. This prevents successful execution of `dbt run` or `dbt test`.

**Problems Encountered:**

1. **Incorrect Profile Validation (`dbt debug`):** `dbt debug` inconsistently and incorrectly reports missing required properties in `profiles.yml`. Depending on minor configuration changes or even just re-running the command, it might complain about 'schema', 'schemas_and_paths', or 'schema_directory' being missing, even when the file is correctly formatted according to documentation and visibly contains the specified key. This occurred across dbt versions 1.9.4 and 1.5.x.
2. **Incorrect Path Generation (main_main.db Error):** When attempting to build models configured to target the `main` schema (using default schema from profile or explicit `+schema: main`), `dbt run` fails with unable to open database: <schema_directory_path>/main_main.db. It appears the adapter incorrectly attempts to create/access a new database file using the `schema_directory` path combined with a mangled main_main name, instead of correctly using the database file explicitly mapped to the `main` schema via the `schemas_and_paths` setting in `profiles.yml`.
3. **Cross-Schema Complexity:** While documented that views cannot reference attached databases, attempts to work around this by materializing staging models as tables and using explicit schemas (`staging`, `core`) also failed due to the incorrect path generation bug (e.g., trying to create `main_core.db` instead of `core.db` in the `schema_directory`).

**Steps To Reproduce**

1. Set up a dbt project using `dbt-sqlite`.
2. Configure `~/.dbt/profiles.yml` (or a project-local profile) similar to the following (ensure paths are valid for your setup):
```yaml
    # profiles.yml
    your_profile_name:
      target: dev
      outputs:
        dev:
          type: sqlite
          threads: 1
          database: your_db # Arbitrary, as per docs
          schema: main     # Default schema target
          attach: []
          schemas_and_paths:
             main: /path/to/your_actual_database.db # Path to the main db file
          schema_directory: '/path/to/where_new_schemas_would_go' # Path for dbt to create staging.db, core.db etc.
```
3. Configure `dbt_project.yml` to default models to the `main` schema (remove explicit `+schema` settings under `models:`). Ensure staging models are materialized as tables (`+materialized: table` under `staging:`).
```yaml
    # dbt_project.yml snippet
    profile: 'your_profile_name'
    ...
    models:
      your_project_name:
        staging:
          +materialized: table
        core:
          +materialized: table
```
4. Have at least one staging model that reads from a source table defined in the `main` schema (e.g., `{{ source('your_source_group', 'your_table') }}`).
5. Run `dbt run --profiles-dir /path/to/profile/dir`.

### Expected Behavior

`dbt run` should successfully execute, creating staging and core tables directly within the single `/path/to/your_actual_database.db` file, as specified by the `schemas_and_paths` mapping for the default `main` schema. `dbt debug` should correctly validate the profile.

### Steps To Reproduce

`dbt run` fails with `Runtime Error: Database Error: unable to open database: /path/to/where_new_schemas_would_go/main_main.db`.

`dbt debug` inconsistently fails, claiming required profile keys (`schema`, `schemas_and_paths`, or `schema_directory`) are missing, even when they are present and correctly formatted.

### Relevant log output

```shell

```

### Environment

Operating system:
- macOS (Specify version, e.g., Ventura 13.x, Sonoma 14.x)
- Architecture: arm64 (Apple Silicon)

Python version:

- e.g., 3.10.14

dbt versions:
- dbt-core: 1.9.4
- dbt-sqlite: 1.9.1
- (Note: Similar profile parsing inconsistencies observed with dbt-core 1.5.11 / dbt-sqlite 1.5.11)

### Which database adapter are you using with dbt?

- [x] SQLite

### Additional Context

Issue was reproduced both locally and within various Docker container setups (custom Dockerfile, official ghcr.io/dbt-labs/dbt-core base image) using volume mounts for the project, database file, and profile. The file your_actual_database.db exists and contains the source tables. The path specified in schema_directory exists and is writable. The issue seems specifically tied to how dbt-sqlite handles profile parsing and path resolution when the target schema is main.
