### ISSUE TITLE
[Bug] Persisting documentation fails when column names have mixed-case in .sql models

### ISSUE THREAD

**Issue by sebvln** [dbt-labs/dbt-core#11463]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When a column is defined with mixed-case letters in a `.sql` model, the documentation for that column will not persist unless the column is declared in **only lowercase** or **only uppercase** in the corresponding `.yml` file.  

- If a column name in a `.sql` model contains both lowercase and uppercase letters, and it is documented in the `.yml` file using the same mixed-case format, the documentation is not persisted.  
- However, if the column is defined in the `.yml` file using **all uppercase** or **all lowercase**, the documentation works as expected.  

**Example:**  
| `.sql` Model  | `.yml` File   | Documentation Persisted? |
| ------------- | ------------- | ------------------------ |
| `ca_net_ht_N` | `ca_net_ht_N` | ❌ No                     |
| `ca_net_ht_N` | `CA_NET_HT_N` | ✅ Yes                    |
| `ca_net_ht_N` | `ca_net_ht_n` | ✅ Yes                    |

### Expected Behavior

I believe the persist doc function is case sensitive but:
- Column documentation should persist in this case as there is no difference between the `.sql` model and `.yml` file.  
- If dbt enforces a specific case convention, this should be documented clearly, or a warning should be raised when a mismatch is detected.  

#### Environment 

Both from local & inside a container, see the details below

#### With this config

```yml
# dbt_project.yml
models:
  my_dbt_project:
    +persist_docs:
      relation: true
      columns: true
```

```sql
-- models/debug_doc.sql
{{
    config(
        materialized='table'
    )
}}

SELECT 1 AS ca_net_ht_N
```

```yml
# models/debug_doc.yml
version: 2

models:
  - name: debug_doc
    description: This is the table description

    columns:
      - name: ca_net_ht_N
        description: This should be the description of the column
```

#### Run

```bash
dbt build -s models/debug_doc.sql --full-refresh
```

#### See error

The created DDL in snowflake:  
<img width="827" alt="Image" src="https://github.com/user-attachments/assets/9dbfa4d4-1fc0-435d-a64c-c99164a0d1a4" />

The same DDL but with a lower case `- name: ca_net_ht_n ` in the `.yml` file:

<img width="833" alt="Image" src="https://github.com/user-attachments/assets/83820708-910d-4e23-8336-8f5dc675c1d9" />

### Relevant log output

```shell

```

### Environment

```markdown
- OS: MacOS 14.5
- Python: Python 3.11.10
- dbt: `dbt-snowflake v1.9.0` & `dbt-core v1.9.2`
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for opening this @sebvln !

This looks like expected behavior to me. You already saw how all using either all uppercase or all lowercase in your YAML behaves the way you want. See below for an example of how to use the [`quote`](https://docs.getdbt.com/reference/resource-properties/columns#quote) config for mixed-case docs persistence for `dbt-snowflake`.

### Example

Create these files:

`models/debug_doc.sql`

```sql
{{ config(materialized='table') }}

-- Note the addition of double quotes for the column name below!
select 1 as "ca_net_ht_N"
```

`models/debug_doc.yml`

```yaml
models:
  - name: debug_doc
    description: This is the table description

    columns:
      - name: "ca_net_ht_N"
        description: This should be the description of the column
        quote: true
```

Run these commands:

```shell
dbt build -s models/debug_doc.sql --full-refresh
```

Open the logs at `logs/dbt.log` and see the following:

```
alter table analytics.dbt_dbeatty.debug_doc alter
  "ca_net_ht_N" COMMENT $$This should be the description of the column$$;
```

### Summary

Since this doesn't look like a bug to me, so I'm going to close it. But we're definitely open to making an update in the docs if that would be helpful. Do you have any suggestions?
