### ISSUE TITLE
[Bug] When using the inline rows syntax for a unit test, case is not preserved in the resulting auto-generated fixture.

### ISSUE THREAD

**Issue by M4Al** [dbt-labs/dbt-core#11477]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

While exploring the unit-test feature I created a unit test like this:

```yaml
unit_tests:
  - name: test_does_the_incremental_load_works
    model: stg_Orders
    given:
      - input: source('bronze', 'Input001') #We canonly use enitites that exist in the
        rows:
          - {"env":"Antwerp","No":"001","VesselNo":"V001","VoyageNo":"Voy001","systemCreatedBy":"user1","systemId":"sys001", "OperationalStatus":"Operational"}
          - {"env":"Antwerp","No":"001","VesselNo":"V001","VoyageNo":"Voy001","systemCreatedBy":"user1","systemId":"sys001", "OperationalStatus":"Operational"}
    expect:
      rows:
      - {"env":"Antwerp","No":"001","VesselNo":"V001","VoyageNo":"Voy001","systemCreatedBy":"user1","systemId":"sys001", "OperationalStatus":"Operational"}
    overrides:
      vars:
        locations: ['ENT1', 'ENT2']
```

iIn th resulting fixture file file that I located in target/compiled/.... i notice this:

(removed parts that are not relevant, as the entity has many more fields)

```sql
-- Fixture for Input001
select 
    try_cast('V001' as varchar(8000))
 as vesselno, 
    try_cast('Voy001' as varchar(8000))
 as voyageno, try_cast(null as int) as ordermovementtype, try_cast(null as smallint) as quickfreightinsert, 
    try_cast('sys001' as varchar(8000))
 as systemid, 
    try_cast('user1' as varchar(8000))
 as systemcreatedby, try_cast(null as datetime2) as lastmodifiedat, try_cast(null as varchar(8000)) as customeraccountownerid, try_cast(null as int) as purchaseporderagent
```

As you can see the case in the fieldnames is not preserved.

This evidently generates a `Invalid column name 'OperationalStatus'.` error.

### Expected Behavior

Maintain capitalisation

### Steps To Reproduce

Create any unit test using the in-line rows syntax, and try to run it.

### Relevant log output

```shell

```

### Environment

```markdown
- OS: Windows 11
- Python: 3.8.xx
- dbt: 1.10.0-b2
- dbt-fabric=1.9.4
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Microsoft Fabric
