### ISSUE TITLE
move `freshness` under `config` so you can configure defaults for all sources / models

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#11506]
### Housekeeping

- [x] I am a maintainer of dbt-core

### Short description

Freshness is currently a property, which means defaults can't be configured in the `dbt_project.yml`:

```
sources: 
  - name: ecom
    schema: raw
    description: E-commerce data for the Jaffle Shop
    freshness:
      warn_after:
        count: 24
        period: hour
```

```
models:
  - name: stg_orders
    freshness:
      build_after: 
        count: 4
        period: hour
```

### Acceptance criteria

- We should move `freshness` (for `sources` and `models`) under `config`

```
sources: 
  - name: ecom
    schema: raw
    description: E-commerce data for the Jaffle Shop
    config:
      freshness:
        warn_after:
          count: 24
          period: hour
```

```
models:
  - name: stg_orders
    config:
      freshness:
        build_after: 
          count: 4
          period: hour
```

- And add a deprecation warning for `freshness` as a property (not nested)
