### ISSUE TITLE
"{{ env_var('DBT_PASSWORD') }}" is not interpreted for password in trino connection profile

### ISSUE THREAD

**Issue by cpassnat** [dbt-labs/dbt-core#11500]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

For password attribute, the jinga `{{ env_var('DBT_PASSWORD') }}` is not converted and the password is passed to the trino client is the string `{{ env_var('DBT_PASSWORD') }}` instead of the value of the env var `DBT_PASSWORD`.
For user attribute, `{{ env_var('DBT_USER') }}` is correcty converted.

### Expected Behavior

`{{ env_var('DBT_PASSWORD') }}` shoudl be converted the value of this environement variable `DBT_PASSWORD` for password connection attribute.

### Steps To Reproduce

create a dbt projet (name `trino_hybrid_01` in this case)

Use the connection profile as below (`profiles.yml`):

```yaml
trino_hybrid_01:
  outputs:

    dev:
      type: trino
      method: ldap  # optional, one of {none | ldap | kerberos}
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      database: system
      schema: metadata
      host: startburst
      port: 443
      threads: 2
      cert: True
```

set `DBT_USER` with the user login
set `DBT_PASSWORD` with the password of the user. BTW you can see that the var is not used as there are no error 
 _Env var required but not provided: 'DBT_PASSWORD '_ when not DBT_PASSWORD is not set

run a `dbt debug`
Connection will faill as the password is not passed to trino client but `{{ env_var('DBT_PASSWORD') }}` instead.

### Relevant log output

I modified the file `trino/auth.py` of the trino client to display which nformations are passed to the client (see below)

```python
class BasicAuthentication(Authentication):
    def __init__(self, username: str, password: str):
        self._username = username
        # DEBUG
        print("USER = {}".format(username))
        # DEBUG       
        self._password = password
        # DEBUG
        print("PASSWORD = {}".format(password))
        # DEBUG     
```

When I run dbt debug, the output below shows clearly that the jinja for password attribute is not interpreted correctly

```
14:41:50  Connection:
14:41:50    host: startburst
14:41:50    port: 443
14:41:50    user: myaccount
14:41:50    database: system
14:41:50    schema: metadata
14:41:50    cert: True
14:41:50    prepared_statements_enabled: True
14:41:50  Registered adapter: trino=1.9.1
USER = myaccount
PASSWORD = {{ env_var('DBT_PASSWORD') }}
```

### Operating System

Windows 11

### dbt version

1.9.3

### Trino Server version

462-e.1

### Python version

Python 3.12.9

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Trino adapter
