### ISSUE TITLE
[Bug] CTE name for unit test fixture is duplicated when source table `identifier` matches another source or model

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#11515]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

As reported in https://github.com/dbt-labs/dbt-core/issues/11480#issuecomment-2808488394 and similar to https://github.com/dbt-labs/dbt-core/issues/10433, the CTE name for unit test fixture is duplicated when source table `identifier` matches another source or model.

It gives an error like the following:

```
21:10:29    Runtime Error in unit_test unit_test_name_here (models/_unit_tests.yml)
  An error occurred during execution of unit test 'unit_test_name_here'. There may be an error in the unit test definition: check the data types.
   Runtime Error
    Parser Error: Duplicate CTE name "__dbt__cte__same_identifier"
```

Where `same_identifier` is replaced with the name of whatever identifier is duplicated.

### Expected Behavior

I expected / assumed / hoped(!) that using the `identifier` capability of dbt sources could be a nice workaround for TODO, and suggested as much here: https://github.com/dbt-labs/dbt-core/issues/11480#issuecomment-2805317753. I _thought_ I had tested it fully, but I didn't recreate the duplicated identifier correctly, so it worked, giving me false confidence.

### Steps To Reproduce

Create two different environments, one to contain the source table, and the other for the dbt models:

`profiles.yml`

```yaml
duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'db.db'
      database: db
      schema: dev
    source:
      type: duckdb
      path: 'db.db'
      database: db
      schema: source
```

`dbt_project.yml`

```yaml
seeds:
  dbt_project:
    +enabled: "{{ true if target.name == 'source' else false }}"

sources:
  dbt_project:
    +enabled: "{{ false if target.name == 'source' else true }}"

models:
  dbt_project:
    +enabled: "{{ false if target.name == 'source' else true }}"

unit_tests:
  dbt_project:
    +enabled: "{{ false if target.name == 'source' else true }}"
```

Create these files:

`seeds/same_name.csv`

```csv
id,source_unique_column
5,9
```

`models/same_name.sql`

```sql
select
    src.id,
    src.source_unique_column as model_unique_column

from {{ source("source", "SOURCE_WITH_UNIQUE_NAME_HERE") }} as src
```

`models/_properties.yml`

```yaml
sources:
  - name: source
    database: "{{ target.database }}"
    schema: source
    tables:
      - name: SOURCE_WITH_UNIQUE_NAME_HERE  # what I want to call it in dbt
        identifier: same_name  # actual name in the database

unit_tests:
  - name: unit_test_name_here
    model: same_name
    given:
      - input: source("source", "SOURCE_WITH_UNIQUE_NAME_HERE")
        rows:
          - {id: 5, source_unique_column: 9}

      - input: this
        rows:
          - {id: 5, model_unique_column: 9}

    expect:
      rows:
        - {id: 5, model_unique_column: 9}
```

Run these commands:

Use a dbt seed to create the source data in a separate schema:

```shell
dbt seed --target source --full-refresh
```

The build the project, including unit tests:

```shell
dbt build
```

Get this error:

```
21:45:45    Runtime Error in unit_test unit_test_name_here (models/_properties.yml)
  An error occurred during execution of unit test 'unit_test_name_here'. There may be an error in the unit test definition: check the data types.
   Runtime Error
    Parser Error: Duplicate CTE name "__dbt__cte__same_name"
21:45:45  
21:45:45  Done. PASS=0 WARN=0 ERROR=1 SKIP=1 TOTAL=2
```

### Relevant log output

```shell

```

### Environment

```markdown
- OS:
- Python:
- dbt:
```
