### ISSUE TITLE
[Bug] Adding a INFORMATION_SCHEMA source for BigQuery makes all catalog calls to use that source definition

### ISSUE THREAD

**Issue by rloredo** [dbt-labs/dbt-core#11513]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If I create a source file
```yaml
version: 2

sources:
  - name: information_schema
    schema: region-europe-west4.INFORMATION_SCHEMA
    tables:
      - name: column_field_paths
        identifier: COLUMN_FIELD_PATHS
```

And run `dbt docs generate` I get the error

```
Encountered an error while generating catalog: Database Error
  Invalid project ID 'my-project-id.region-europe-west4'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
```

### Expected Behavior

It shouldn't use that defined source, and there should be a way of referencing information schema tables with `source()` macro that doesn't collide with the catalog generation.

### Steps To Reproduce

Add a source file 
```yaml
version: 2

sources:
  - name: information_schema
    schema: region-europe-west4.INFORMATION_SCHEMA
    tables:
      - name: column_field_paths
        identifier: COLUMN_FIELD_PATHS
```

run `dbt docs generate`

### Relevant log output

```shell

```

### Environment

```markdown
- OS: MacOS, Ubuntu 24
- Python: ">=3.10,<3.11"
- dbt-bigquery = ">=1.8.0,<1.8.1"
- dbt-core = ">=1.8.0,<1.8.1"
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thanks for reaching out about this @rloredo !

This appears to only affect `dbt-biquery` -- I also tried it out with `dbt-snowflake`, and it worked fine.

I'm going to transfer this to the team that maintains the `dbt-adapters`, and they can take a closer look.

### Reprex

I got the same error as you when I defined a source for `INFORMATION_SCHEMA.tables` using my BQ region (`region-us`):

```yaml
sources:
  - name: information_schema
    schema: region-us.INFORMATION_SCHEMA
    tables:
      - name: tables
```

### Related code

The error you got is originating here:
https://github.com/dbt-labs/dbt-adapters/blob/53d7e320e0baf733b07a453412074e1b3b5a3524/dbt-bigquery/src/dbt/include/bigquery/macros/catalog/catalog.sql#L86

This was added in https://github.com/dbt-labs/dbt-bigquery/pull/1063/ as the BigQuery-specific implementation of https://github.com/dbt-labs/dbt-core/pull/8648/.

Other related portions of code:

https://github.com/dbt-labs/dbt-adapters/blob/53d7e320e0baf733b07a453412074e1b3b5a3524/dbt-adapters/src/dbt/adapters/base/relation.py#L454

https://github.com/dbt-labs/dbt-adapters/blob/53d7e320e0baf733b07a453412074e1b3b5a3524/dbt-adapters/src/dbt/adapters/base/relation.py#L492-L506

https://github.com/dbt-labs/dbt-adapters/blob/53d7e320e0baf733b07a453412074e1b3b5a3524/dbt-bigquery/src/dbt/adapters/bigquery/relation.py#L201

### Mimicking the current behavior

We can mimic the current behavior with an analysis file defined like this:

`analyses/column_field_paths.sql`

```sql
{%
        set information_schema = api.Relation.create(
            database=target.database,
            schema="region-us.INFORMATION_SCHEMA",
            identifier="COLUMN_FIELD_PATHS",
            quote_policy={database: true, schema: true, identifier: true},
        ).information_schema()
%}

information_schema:
{{ information_schema }}

information_schema.replace(information_schema_view='COLUMN_FIELD_PATHS'):
{{ information_schema.replace(information_schema_view='COLUMN_FIELD_PATHS') }}
```

Then run this command:

```shell
dbt compile -s analyses/column_field_paths.sql
```

See this output:

```
Compiled node 'column_field_paths' is:

information_schema:
`dbt-test-env`.INFORMATION_SCHEMA

information_schema.replace(information_schema_view='COLUMN_FIELD_PATHS'):
`dbt-test-env`.`region-us.INFORMATION_SCHEMA`.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS
```
