### ISSUE TITLE
[Feature] Resource path using wildcards or pattern matching

### ISSUE THREAD

**Issue by moseleyi** [dbt-labs/dbt-core#11546]
### Is this your first time submitting a feature request?

- [x] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [x] I have searched the existing issues, and I could not find an existing issue for this feature
- [x] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In a small companies I usually have a simple folder structure:

```
- models
  - base
  - transformations
  - dictionaries
```

but in some bigger companies, I am having a bit of a problem. I need to repeat this structure inside business domains that are not mapped to schemas.

```
- models
  - business1
    - base
    - transformations
  - business2
    - base
    - transformations
```

The problem is that my regular configuration in `dbt_project.yml`:

```yml
models:
  <project_name>: 
    base:
      +schema: base
      materialized: view
    dictionaries:
      +schema: dictionaries
      materialized: table
    transformations:
      +schema: transformations
      materialized: table 
```

Is not going to work. I don't want to have to repeat the configuration since for some companies, there may be many.

It would be good to be able to do something like:

```
models:
  pinnamin_hopper_analytics: 
    *:
      base:
        +schema: base
        materialized: view
      dictionaries:
        +schema: dictionaries
        materialized: table
      transformations:
        +schema: transformations
        materialized: table
      aggregations:
        +schema: aggregations
        materialized: table
```

### Describe alternatives you've considered

Not-DRY repetition of the code

### Who will this benefit?

Projects that need a bit more dynamic configuration in regards to mapping physical structure to schemas/datasets.

### Are you interested in contributing this feature?

yes
