### ISSUE TITLE
update build_after model freshness

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#11606]
### Housekeeping

- [x] I am a maintainer of dbt-core

### Short description

update `build_after` for model `freshness` from the existing:

```
      build_after: 
        count: 4
        period: hour
        depends_on: all
```

to 

```
      build_after: 
        count: 4
        period: hour
        updates_on: all
```

### Acceptance criteria

- rename `depends_on` to `updates_on`
- default for `updates_on` should be `any`
