### ISSUE TITLE
[Feature] Specify data type of snapshot generated columns

### ISSUE THREAD

**Issue by rschack-cedar** [dbt-labs/dbt-core#11650]
### Is this your first time submitting a feature request?

- [x] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [x] I have searched the existing issues, and I could not find an existing issue for this feature
- [x] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently in Snowflake, if I create a dbt snapshot, the `dbt_valid_from`, `dbt_valid_to`, and `dbt_updated_at` columns are created as a UTC timestamp but stored as a `TIMESTAMP_NTZ` type (exact SQL below):

```sql
to_timestamp_ntz(convert_timezone('UTC', current_timestamp()))
```

This can cause discrepancies in downstream usage for teams that primarily use `TIMESTAMP_TZ`. For example all `TIMESTAMP_NTZ` columns are evaluated using the session/account timezone (default is `America/Los Angeles`). That means `'2020-01-01 00:00:00'::TIMESTAMP_NTZ` is treated as _greater than_ `'2020-01-01 00:00:00 +0000'::TIMESTAMP_TZ`.

When creating a snapshot, users should have the ability to specify the data type of the dbt-generated columns.

- Snowflake:  Choose from `TIMESTAMP_TZ`, `TIMESTAMP_NTZ`, or `TIMESTAMP_LTZ`
- BigQuery:  Choose from `TIMESTAMP` or `DATETIME`
- Databricks:  Choose from `TIMESTAMP` or `TIMESTAMP_NTZ`
- Redshift:  Choose from `TIMESTAMP` or `TIMESTAMPTZ`

### Describe alternatives you've considered

In the meantime, this requires one of four solutions:

- Manually override dbt snapshots to enable the above functionality (not desired)
- Create a view on top of every snapshot to change the data type
- Let each downstream model decide if the data type should be updated
- Let downstream consumers handle it

### Who will this benefit?

Any users that work downstream of snapshots that require consistency in their timestamp data types. That should cover most users of dbt + dashboard users

### Are you interested in contributing this feature?

No

**Comment by graciegoheen** [comment]
Thanks for opening. To brainstorm...

Perhaps we could create a new config, similar to `snapshot_meta_column_names` that controls the data types of the meta columns. 

```
snapshots:
  - name: orders_snapshot
    relation: ref("orders")
    config:
      unique_key: id
      strategy: check
      check_cols: all
      hard_deletes: new_record
      snapshot_meta_column_names:
        dbt_valid_from: start_date
        dbt_valid_to: end_date
        dbt_scd_id: scd_id
        dbt_updated_at: modified_date
        dbt_is_deleted: is_deleted
     snapshot_meta_column_data_types:
        dbt_valid_from: TIMESTAMP_TZ
        dbt_valid_to: TIMESTAMP_TZ
        dbt_scd_id: STRING # open issue for using an integer instead of a string -> https://github.com/dbt-labs/dbt-core/issues/10300
        dbt_updated_at: TIMESTAMP_TZ
        dbt_is_deleted: BOOL # any reason people would want this to be a different data type? 0/1 vs. true/false?
```

Or maybe that's too granular, and really we want to always use the same data type for `dbt_valid_from`, `dbt_valid_to`, and `dbt_updated_at`. In that case, it could be a more specific config (more like `dbt_valid_to_current`):
```
snapshots:
  - name: orders_snapshot
    snapshot_time_meta_column_data_type: TIMESTAMP_TZ # this naming is rather verbose :/
```

One other idea - we could use the existing `data_type` property within `columns`, but use it for creating the table for snapshots:
```
snapshots:
  - name: my_snapshot
    columns:
      - name: dbt_valid_from
        data_type: TIMESTAMP_TZ
      - name: dbt_valid_to
        data_type: TIMESTAMP_TZ
      - name: dbt_updated_at
        data_type: TIMESTAMP_TZ
```
^though, then you wouldn't be able to set a project-level default (since it's not a config) which doesn't feel ideal.
