### ISSUE TITLE
`meta` and `tags` should be `config`s under `columns:` (not properties)

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#11651]
### Housekeeping

- [x] I am a maintainer of dbt-core

### Short description

`tags` and `meta` are all being deprecated as _properties_ and moved under `config:`

```
models:
  - name: <model_name>
    config:
      tags: ...
      meta: ...
```

we should do the same thing for `tags` and `meta` under `columns:` property with _actual inheritance_

![Image](https://github.com/user-attachments/assets/97c1b21a-39f0-4c0a-92cd-9748ff7da58b)

### Acceptance criteria

**1. I can define `tags` and `meta` under new `config:` property under `columns:`**

```
models:
  - name: <model_name>
    columns:
      - name: <column_name>
        config:
          tags: ...
          meta: ...
```

**2. project -> model -> column inheritance should work the same way it does for `tags` and `meta` in other places**

from our [docs](https://docs.getdbt.com/reference/define-configs#combining-configs):

> - [tags](https://docs.getdbt.com/tags) are additive. If a model has some tags configured in dbt_project.yml, and more tags applied in its .sql file, the final set of tags will include all of them.
> - [meta](https://docs.getdbt.com/reference/resource-configs/meta) dictionaries are merged (a more specific key-value pair replaces a less specific value with the same key)

3. deprecation warning for `tags` and `meta` under `columns:` as _properties_

**Comment by MichelleArk** [comment]
closed by https://github.com/dbt-labs/dbt-core/pull/11671

**Comment by FishtownBuildBot** [comment]
Opened a new issue in dbt-labs/docs.getdbt.com: https://github.com/dbt-labs/docs.getdbt.com/issues/7357

**Comment by mcasara** [comment]
Maybe others have been affected by this, this feature had a breaking change on how `dbt_artifacts` parsed our yaml. An already existing `config:` on column level is being overwritten:

YAML:

```
- name: column_a
   type: varchar
   description: ""
   config:
       deprecated:
           alternative_column: column_b
```

Parsing before the change:

```
  "columns": {
    "column_a": {
      "config": {
        "deprecated": {
          "alternative_column": "column_b"
        }
      },
      ..
      "meta": {},
      ..
      "tags": [],
      ...
    },
}
```

Parsing after the change:

```
  "columns": {
    "column_a": {
      "config": {
        "meta": {},
        "tags": []
      },
      ..
      "meta": {},
      ..
      "tags": [],
      ..
    },
}
```

The solution is to store `deprecated` into `config.meta` instead of `config`. This seems to be the [preferred approach](https://github.com/dbt-labs/dbt-core/issues/11337).
