### ISSUE TITLE
`group.owners` and `exposure.owners` should ONLY support `name` and `email`, NO additional properties

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#11652]
### Housekeeping

- [x] I am a maintainer of dbt-core

### Short description

today, we document:
```
groups:
  - name: finance
    owner:
      # 'name' or 'email' is required; additional properties allowed
      email: finance@jaffleshop.com
      slack: finance-data # custom additional property
      github: finance-data-team # custom additional property
```

having “additional properties allowed” within owner property (not nested under `meta`) is misaligned with our goals for “stricter validation”

### Acceptance criteria

**1. add config [meta to groups](https://github.com/dbt-labs/dbt-core/issues/11319) (_not_ nested in owners)**
**2. add deprecation warning for group.owners additional properties - only support `name` and `email` (no additional properties allowed) in the future**

```
groups:
  - name: finance
    owner:
      # 'name' or 'email' is required; additional properties NOT allowed in the future
      email: finance@jaffleshop.com
    config:
     # groups.config.meta is where all additional info should go
      meta: ...
```

**3. do the ^same for exposure owner ([docs](https://docs.getdbt.com/reference/exposure-properties))**
