### ISSUE TITLE
[bug] do NOT allow users to define incomplete freshness config at different places and try to resolve them

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#11669]
### Housekeeping

- [x] I am a maintainer of dbt-core

### Short description

Currently, we allow people to define incomplete `freshness` config at different places and try to resolve them. 

Example:

```yaml
# dbt_project.yml
models:
  jaffle_shop:
    +freshness:
      build_after:
        period: hour

```

```yaml
# orders.yml
models:
  - name: orders
    freshness:
      build_after:
        count: 1
```

### Acceptance criteria

- Each `freshness` AS A CONFIG setting will need to be "complete" — can be validated independently, with both `count` and `period` set
- no merge behavior
- Either `freshness` is `null` or you must set BOTH `count` and `period`
- this should apply for all types - `freshness.warn_after`, `freshness.error_after`, `freshness.build_after`
