### ISSUE TITLE
[Bug] Quoting (source, identifier) ignored with Exasol adapter

### ISSUE THREAD

**Issue by nagyrob** [dbt-labs/dbt-core#11679]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Quoting is not applied although being declared in sources.yml (or dbt_project.yml for that matter).

Model gets compiled to
```
[...] from AIRBYTE._airbyte_raw_email_events
````

### Expected Behavior

Quoting is applied at compilation.

Valid statement for Exasol:
```
[...] FROM AIRBYTE."_airbyte_raw_email_events"
```

### Steps To Reproduce

dbt run --select debug

debug.sql
```
{{ config(materialized='table') }}

with extracted as (
    select
        "_AIRBYTE_AB_ID" AS airbyte_ab_id
    from {{ source('AIRBYTE', 'raw_emails') }}
)

select
    airbyte_ab_id

from extracted
```

sources.yml
```
version: 2

sources:
  - name: AIRBYTE
    tables:
      - name: raw_emails
        identifier: _airbyte_raw_email_events
        quoting:
          identifier: true
```

profiles.yml
```
dbt_wh:
  outputs: <DB name>
  dsn: <Host>:<Port>
  password: <password>
  schema: <target schema>
  threads: 1
  type: exasol
  user: <user name>
target: dev
```

dbt_project.yml
```
name: 'dbt_wh'
version: '1.0.0'

profile: 'dbt_wh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_marketing_wh:
    example:
      +materialized: view
```

yields
```
CREATE OR REPLACE TABLE staging.debug__dbt_tmp
          AS 
          
  
  with extracted as (
      select
          "_AIRBYTE_AB_ID" AS airbyte_ab_id
      from AIRBYTE._airbyte_raw_email_events
  )
  
  select
      airbyte_ab_id
  
  from extracted
          with no data
  )
```

### Relevant log output

```shell
Runtime Error in model debug (models/staging/debug.sql)
  
  (
      message     =>  syntax error, unexpected invalid token, expecting IDENTIFIER_PART_ or '*' [line 11, column 18] (Session: <session ID>)
      dsn         =>  <Host>:<Port>
      user        =>  <User name>
      schema      =>  
      session_id  =>  <session ID>
      code        =>  42000
      query       =>  /* {"app": "dbt", "dbt_version": "1.8.7", "profile_name": "dbt_wh", "target_name": "dev", "node_id": "model.dbt_wh.debug"} */
```

### Environment

```markdown
- OS: Mac OS 15.5
- Python: 3.12.10
- dbt-core: 1.8.7
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

- exasol: 1.8.2
