### ISSUE TITLE
[Bug] Unhandled error while executing after moving freshness to config

### ISSUE THREAD

**Issue by akirilenko95** [dbt-labs/dbt-core#11697]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`dbt source freshness` takes a few minutes to start and then it results in an error: `Unhandled error while executing`

### Expected Behavior

`dbt source freshness` to run successfully in seconds 

### Steps To Reproduce

1. dbt Latest version running with Redshift adaptor 
2. Configuration
Schema level configuration: 
```
 - name: name
    database: db_name
    schema: schema_name
    config: 
      freshness:
        warn_after: {count: 24, period: hour}
      loaded_at_field: load_date
```
Model level configuration: 
```
- name: model_name
  config:
   freshness:
     error_after:
       count: 6
       period: hour
   loaded_at_field: load_date
```
3. run `dbt source freshness`
4. Output -  `Unhandled error while executing `

### Relevant log output

```shell

```

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

redshift
