### ISSUE TITLE
[Bug] Showing unnecessary warning for legacy time spine with non-day grain

### ISSUE THREAD

**Issue by courtneyholcomb** [dbt-labs/dbt-core#11690]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

- I had a metricflow_time_spine.sql model
- I configured a metricflow_time_spine.ymlfile appropriately with time_spine config using hour grain
- I got expected deprecation warnings
- I just renamed model and configs to all_days and no more deprecation warnings

### Expected Behavior

There should be no warning once a `time_spine` config is added for the model

### Steps To Reproduce

Add a model like this:
```
models:
- name: metricflow_time_spine
  time_spine:
    standard_granularity_column: date_hour
  columns:
  - name: date_hour
    granularity: hour
```
And run a dbt parse

### Relevant log output

```shell

```

### Environment

```markdown
- OS:
- Python:
- dbt:
```
