### ISSUE TITLE
[Bug] Bad model freshness definitions shouldn't break parsing

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#11709]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

For a long time, we didn't support model freshness. Despite this, some users defined model freshness, in a source freshness way, on their models. In dbt-core, we've historically _ignored_ those freshness definitions. However, we've been working to _add_ model freshness in over the past few months. The problem is that _model freshness_ has a different spec from _source freshness_. This leads us to four (4) possible states of model freshness
1. Model freshness isn't defined
2. Model freshness is defined with just the model freshness spec
3. Model freshness is defined with just the source freshness spec
4. Model freshness is defined with _both_ model freshness and source freshness specs

Until recently all four states worked. However, recently we changed the model freshness spec to require that the model freshness spec properties are defined if model freshness is defined. This breaks a model freshness state of (3) and we get an error that looks like
```
Parsing Error
  Invalid models config given in models/marts/merchant/merchant.yml @ models: {'name': 'my_model', 'freshness': {'warn_after': {'count': 2, 'period': 'hour'}, 'error_after': {'count': 3, 'period': 'hour'}}, 'loaded_at_field': 'materialized_timestamp', 'original_file_path': 'models/marts/schema.yml', 'yaml_key': 'models', 'package_name': 'narrativ'} - at path ['freshness']: {'warn_after': {'count': 2, 'period': 'hour'}, 'error_after': {'count': 3, 'period': 'hour'}} is not valid under any of the given schemas
```

### Expected Behavior

State (3) should not cause a parsing error, instead, the model freshness definition should just be ignored

### Steps To Reproduce

Add freshness to a model via
```
models:
  - name: my_model
    freshness:
      warn_after: {count: 1, period: "hour"}
      error_after: {count: 1, period: "hour"}
```
then run a dbt parse

### Relevant log output

```shell
Parsing Error
  Invalid models config given in models/marts/merchant/merchant.yml @ models: {'name': 'my_model', 'freshness': {'warn_after': {'count': 2, 'period': 'hour'}, 'error_after': {'count': 3, 'period': 'hour'}}, 'loaded_at_field': 'materialized_timestamp', 'original_file_path': 'models/marts/schema.yml', 'yaml_key': 'models', 'package_name': 'narrativ'} - at path ['freshness']: {'warn_after': {'count': 2, 'period': 'hour'}, 'error_after': {'count': 3, 'period': 'hour'}} is not valid under any of the given schemas
```

### Environment

```markdown
- OS: MacOS 15.1
- Python: 3.10.14
- dbt: 1.10.0rc2
```

### Which database adapter are you using with dbt?

postgres

**Comment by jeremyyeo** [comment]
Can we move this into config?

```yaml
models:
  - name: foo
    config:
      freshness: ...
```

^ Most folks probably dont have this pattern... since `config.freshness` is a newish thing compared to `freshness` at the top level.

**Comment by graciegoheen** [comment]
Yes, this should be a config!

```
models:
  - name: my_model
    config:
      freshness:
        warn_after: {count: 1, period: "hour"}
        error_after: {count: 1, period: "hour"}
```
