### ISSUE TITLE
[Bug] Moving Freshness to config causes error

### ISSUE THREAD

**Issue by tuday2** [dbt-labs/dbt-core#11706]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently if you move freshness to config it throws an error when trying to build the model

Encountered an error:
Argument for dbt.artifacts.resources.v1.components.FreshnessThreshold.__mashumaro_from_dict__ method should be a dict instance

### Expected Behavior

Deprecated error is removed from Freshness and it functions correctly

### Steps To Reproduce

1. Setup Source.YML:

```
version: 2
sources:
  - name: xxxxx
    description: source data
    database: XX_RAW
    loader: Airbyte
    loaded_at_field: _AIRBYTE_EXTRACTED_AT
    schema: AIRBYTE
    config:
      freshness:
        warn_after: { count: 24, period: hour }
        error_after: { count: 48, period: hour }
```
2. Build Model that uses that source YML

### Relevant log output

```shell
Encountered an error:
Argument for dbt.artifacts.resources.v1.components.FreshnessThreshold.__mashumaro_from_dict__ method should be a dict instance
```

### Environment

```markdown
- dbt:Cloud Latest
```

### Which database adapter are you using with dbt?

snowflake
