### ISSUE TITLE
[Bug] souce.table.column[x].config = None breaks parsing

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#11712]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Recently, we added support of `config` on source table columns in #11671 in service of #11651. Prior to that work, setting `config` on source table columns was simply ignored during parsing. Now that we've introduced `config` on source table columns it's becoming an issue when previously ignored definitions of `config` on source table columns don't match the expected shape, and thus cause a parsing issue. Specifically we're seeing that when config is null like in the following example
```YAML
sources:
  - name: ecom
    schema: raw
    description: E-commerce data for the Jaffle Shop
    tables:
      - name: raw_supplies
        description: One record per supply per SKU of items sold in stores
        columns:
          - name: id
            config:
            data_tests:
              - not_null
```
we then get an error like
```
Parsing Error
  Invalid sources config given in models/staging/__sources.yml @ sources: {'name': 'ecom', 'schema': 'raw', 'description': 'E-commerce data for the Jaffle Shop', 'tables': [{'name': 'raw_supplies', 'description': 'One record per supply per SKU of items sold in stores', 'columns': [{'name': 'id', 'config': None, 'data_tests': ['not_null']}]}]} - at path ['tables'][5]['columns'][0]['config']: None is not of type 'object'
```

### Expected Behavior

Having
```YAML
sources:
  - name: ecom
    schema: raw
    description: E-commerce data for the Jaffle Shop
    tables:
      - name: raw_supplies
        description: One record per supply per SKU of items sold in stores
        columns:
          - name: id
            config:
            data_tests:
              - not_null
```
doesn't raise a parsing error

### Steps To Reproduce

1. Add `config:` to a source table column
2. run `dbt parse`

### Relevant log output

```shell

```

### Environment

```markdown
- OS:
- Python:
- dbt:
```
