### ISSUE TITLE
[Bug] Moving Freshness to config causes error

### ISSUE THREAD

**Issue by tuday2** [dbt-labs/dbt-core#11710]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently if you move freshness (NOT NULL, actual config with time(s) to config it throws an error when trying to build the model

```shell
Encountered an error:
Argument for dbt.artifacts.resources.v1.components.FreshnessThreshold.__mashumaro_from_dict__ method should be a dict instance
```

There is no way to fix this, and I've followed the exact syntax from the documentation. This is in dbt-cloud on the latest version.

### Expected Behavior

Deprecated error is removed from Freshness and it functions correctly

### Steps To Reproduce

1. Setup Source.YML:

```
version: 2
sources:
  - name: xxxxx
    description: source data
    database: XX_RAW
    loader: Airbyte
    loaded_at_field: _AIRBYTE_EXTRACTED_AT
    schema: AIRBYTE
    config:
      freshness:
        warn_after: { count: 24, period: hour }
        error_after: { count: 48, period: hour }
```
2. Build Model that uses that source YML

### Relevant log output

```shell
Encountered an error:
Argument for dbt.artifacts.resources.v1.components.FreshnessThreshold.__mashumaro_from_dict__ method should be a dict instance
```

### Environment

```markdown
- dbt:Cloud Latest
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

@jtcohen6 This is NOT related to the other issue, this is an error when I try to move source freshness to the config: block as described in the documentation. Please see my example above.

**Comment by jtcohen6** [comment]
@tuday2 I'm not able to reproduce this error, given the reproduction case above.

I am able to reproduce the error by changing the code to have `freshness: null` explicitly under config:
```
version: 2
sources:
  - name: xxxxx
    description: source data
    database: XX_RAW
    loader: Airbyte
    loaded_at_field: _AIRBYTE_EXTRACTED_AT
    schema: AIRBYTE
    config:
      freshness: null
    tables:
      - name: my_table
```

The error goes away if I:
- move `freshness: null` back to a top-level property (though I get the deprecation warning)
- set `freshness.warn_after` / `error_after`
- run on a newer version of dbt Core

> run on a newer version of dbt

I'm still seeing `2025.5.27+006a4ba` in dbt ~Cloud~ Latest, which is last week's release. This week's release has the fix (#11698) and should be rolling out to accounts now.
