### ISSUE TITLE
[Regression] state:modified false positive due to source freshness key differences in the manifest in 1.10.0rc2 (vs 1.10.0b3)

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#11732]
### Is this a regression in a recent version of dbt-core?

- [x] I believe this is a regression in dbt-core functionality
- [x] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

On 1.10.0rc2, there are a few differences in the `manifest` for sources with freshness compared to 1.10.b2. This results in a false positive that selects the sources as being modified... a consequence of that is "state:modified+" will build everything downstream of that source - which can be very many models.

### Expected/Previous Behavior

No false positive.

### Steps To Reproduce

1. Create 2 virtual envs and install 1.10.0b3 in one and 1.10.0rc2 in the other.

2. Project setup:

```yaml
# dbt_project.yml
name: my_dbt_project
profile: sf
version: "1.0.0"

models:
  my_dbt_project:
    +materialized: table

# models/sources.yml
sources:
  - name: sch
    config:
      freshness:
        warn_after: { count: 12, period: hour }
        error_after: { count: 24, period: hour }
    loaded_at_field: updated_at
    tables:
      - name: customer
```

```sql
-- models/foo.sql
select * from {{ source('sch', 'customer') }}

-- models/bar.sql
select * from {{ ref('foo') }}
```

3. Let's generate a "production" state with 1.10.0b3 and then store that manifest:

```sh
$ rm -rf target target_old
$ source venv_dbt_1.10.0b3/bin/activate
$ dbt compile 
04:02:14  Running with dbt=1.10.0-b3
04:02:14  Registered adapter: snowflake=1.9.4
04:02:14  Found 2 models, 1 source, 588 macros
04:02:14  
04:02:14  Concurrency: 1 threads (target='ci')
04:02:14
$ mv target target_old
```

4. Without changing any user code, let's switch to 1.10.0rc2 and do a state modified build:

```sh
$ source venv_dbt_1.10.0rc2/bin/activate
$ dbt ls -s state:modified+ --defer --state target_old
04:04:48  Running with dbt=1.10.0-rc2
04:04:48  Registered adapter: snowflake=1.9.4
04:04:48  Unable to do partial parsing because saved manifest not found. Starting full parse.
04:04:49  Found 2 models, 1 source, 588 macros
my_dbt_project.bar
my_dbt_project.foo
source:my_dbt_project.sch.customer
```

^ Notice how the source and it's downstream models were listed? This will build everything from the source onwards in the CI job with no modifications.

### Relevant log output

```shell

```

### Environment

```markdown
- OS: macOS
- Python: 3.11.9
- dbt (working version): 1.10.0b3
- dbt (regression version): 1.10.0rc2
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

On dbt Cloud, customers on "Latest" experienced this issue... all of a sudden, their CI runs started building everything because the sources were determined to be "modified" even though it wasn't simply because of the manifest format changes.

![Image](https://github.com/user-attachments/assets/bbef5f3a-9091-484a-911e-b3b50eaa3558)
