### ISSUE TITLE
[Bug] Duplicate records created with DBT Snapshot command on Redshift

### ISSUE THREAD

**Issue by AidanHarveyNelson** [dbt-labs/dbt-core#11747]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running DBT Snapshots using DBT core for Redshift I am seeing duplicate rows being created when the source table has a unique column.

Current Config

```
  - name: members_snapshot
    relation: ref('members')
    config:
      unique_key: member_id
      strategy: timestamp
      updated_at: updated_at
      dbt_valid_to_current: "to_timestamp('9999-12-31', 'YYYY-MM-DD')"
      persist_docs:
        relation: true
        columns: true
      tags:
        - hourly
```

Member ID is a unique column on the source table as its a primary key and cannot be duplicate. When a record changes with that id. The previous records `dbt_valid_to` is not updated to be end dated and the new record is inserted.

Then each new snapshot the new record is then duplicated and multiplies each time. This is cause a massive number of duplicate records occurring and the previous records are not being correctly updated. Making the snapshot table completely unusable.

Based on the logic from reviewing the DEBUG queries I am assuming the duplicate is happening since the merge does not correctly update the old records `dbt_valid_to` to the correct value.

### Expected Behavior

Previous record is updated with the correct `dbt_valid_to` and new record is inserted only once.

### Steps To Reproduce

1. Run DBT Snapshot
2. Change updated_at field for a record
3. Re-Run Snapsoht
4. See previous record `dbt_valid_to` does not updated.
5. Run again with no change and duplicates occur

### Relevant log output

```shell

```

### Environment

```markdown
- OS: AWS Linux
- Python: 3.12.2
- dbt: 1.9.8
```
