### ISSUE TITLE
[Feature] Allow custom aliasing of column data types within contracts

### ISSUE THREAD

**Issue by fitzgibbons-hc** [dbt-labs/dbt-core#11771]
### Is this your first time submitting a feature request?

- [x] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [x] I have searched the existing issues, and I could not find an existing issue for this feature
- [x] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As the use cases around arrays and structs become more prevalent, it would be nice to have a way of defining a custom data type for a column that represents a more native construct where you want to ensure that there is consistent use across all of the models within your project.  

For example, let's say your company stores address as a struct of type -- struct<number: int, street: string, city: string, state: string, zip: string> -- from a consistency perspective it would be better to allow the model developers to utilize 'address' as the column data type where necessary and allow the project to define a list of column data type alias mappings that exist.  Since this is just mapping from an alias to existing types, its scope of impact would hopefully be fairly narrow

Just an example below to help better visualize the description above - 

```
schema.yml

models:
  - name: sample_model
    columns:
      - name: home_addr
        data_type: address
        description: "Home address of the person"

dbt_project.yml

models:
  jaffle_shop:
    +column_types:
      address: struct<number: int, street: string, city: string, state: string, zip: string>
```

It could also work well if it was implemented as a macro that the dispatcher looks for on every column type before further processing so something like default__column_data_type(column, data_type) or similar where you would then return the value for that column

This would be used from a contract consistency, contract enforcement, schema drift perspective and documentation.  

### Describe alternatives you've considered

- looked at creating a macro for the type but then users have to know to use {{ address() }} vs just using the term address which would be easier
- just having the users use Struct but then we lose information on the contract
- having all of the models that need to use a repeated Struct structure just implement it themselves which becomes harder to govern at scale when we want the contract enforcement to be against a centralized definition of 'address' specifically
- overriding the adapter logic but the column data types / contract enforcement doesn't appear to have an easy way to override or hook into

### Who will this benefit?

- Governance Teams from being able to maintain the logic that they want for their models consistently at scale
- Data Teams as they are building out models from a simplicity perspective

### Are you interested in contributing this feature?

perhaps?

### Anything else?

thanks for considering!

**Comment by fitzgibbons-hc** [comment]
bump

**Comment by jtcohen6** [comment]
@fitzgibbons-hc Thanks for opening the issue, and sorry for the delay!

Per https://github.com/dbt-labs/dbt-bigquery/pull/738

I see two potential goals here:
1. Developer ergonomics (DRY) - define once in `dbt_project.yml`, then reuse throughout the project
2. Introduce a new concept ("column" or ["term"](https://github.com/dbt-labs/dbt-core/discussions/12500) - defined once (canonically), semantically meaningful (perhaps usable as an entity/dimension/filter for metrics queries?)

Given that the use case here is about nested data types (long to type, easy to typo) - I think the goal here is more narrowly about (1) dev ex. And this narrow use case is already possible, with `vars`:

```yml
# dbt_project.yml

vars:
  data_type_address: "struct<number int, street string, city string, state string, zip string>"
```
```yaml
# schema.yml

models:
  - name: sample_model
    columns:
      - name: home_addr
        data_type: "{{ var('data_type_address') }}"
        description: "Home address of the person"
```
```sql
-- models/sample_model.sql
select
    struct(
        123 as number,
        'Sesame Street' as street,
        'New York' as city,
        'NY' as state,
        '10128' as zip
    ) as home_addr
```

It works!
```
> dbt build                     
17:19:53  Running with dbt=1.11.7
17:19:54  Registered adapter: bigquery=1.11.1
...
17:20:04  1 of 1 START sql view model dbt_jcohen.sample_model ............................ [RUN]
17:20:08  1 of 1 OK created sql view model dbt_jcohen.sample_model ....................... [CREATE VIEW (0 processed) in 4.34s]
```

I'm going to close this issue, since the narrow use case is already possible — but always open to thinking about how we might teach dbt about complex data types, or canonical column concepts.

---

Note: This reuse via `vars` _wouldn't_ be possible if you want to add constraints or descriptions on those nested fields, using the syntax implemented in https://github.com/dbt-labs/dbt-bigquery/pull/738, because the column name is also included in the schema declaration — unless the column is also named the same in every model.

```yml
models:
  - name: sample_model
    config:
      contract: {enforced: true}
    columns:
      - name: home_addr.number
        data_type: integer
      - name: home_addr.street
        data_type: string
      - name: home_addr.city
        data_type: string
      - name: home_addr.state
        data_type: string
      - name: home_addr.zip
        data_type: string
```
