### ISSUE TITLE
[BUG] Fusion allows defining both a `private_key_path` and `private_key` in `profiles.yml` for Snowflake

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-core#13189]
**Describe the bug**
Fusion allows defining both a `private_key_path` and `private_key` in `profiles.yml` for Snowflake.

When running dbt-core, we get an error:
```
  >Database Error
  Runtime Error
    Cannot specify both `private_key`  and `private_key_path`
```

When running Fusion, `dbt debug` works without error (but we don't know if it used the string or the path)

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
```
dbt-fusion 2.0.0-beta.12
```

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**
Create a profile like this:

```
snowflake-pem:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: myaccount
      user: myuser
      role: myrole

      # Keypair config
      private_key_path: /mypath/key.pem
      private_key: |
        -----BEGIN ENCRYPTED PRIVATE KEY-----
        mykey
        -----END ENCRYPTED PRIVATE KEY-----
      private_key_passphrase: mypassphrase

      database: mydb
      warehouse: mywarehouse
      schema: myschema
      threads: 8
      client_session_keep_alive: False
```

- with dbt-core `dbt debug` returns the error mentioned above
- with Fusion, `dbt debug` tried to connect to the data warehouse

**Expected behavior**
I'd expect Fusion to raise an errors that we can't have both fields

**Screenshots**

** Operating System and CPU Type (please complete the following information):**
* Mac/Windows/Linux?
* X86 or ARM?
