### ISSUE TITLE
[BUG] dbt1013: YAML error: invalid type: sequence, expected struct ProjectModelConfig

### ISSUE THREAD

**Issue by ya7010** [dbt-labs/dbt-core#13187]
**Describe the bug**
I tried dbt fusion and the projects that worked with dbt did not work.

`dbt_project.yml` load failed.

Perhaps the type definition in `struct DbtProject` is incorrect.

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
dbt-fusion 2.0.0-beta.12

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [] NO

**To Reproduce**
dbt_project.yml

```yaml
name: 'my_sample'
version: '1.0.0'
config-version: 2

profile: 'my_sample'

models:
  my_dbt:
    +persist_docs:
      relation: true
      columns: true
    +dbt-osmosis: 'schema.yml'
    sandbox:
      database: CDP
      schema: SANDBOX
      tags: ['sandbox']
      materialized: view
```

**Expected behavior**
Build success.

`models: Option<ProjectModelConfig>` -> `models: Option<HashMap<String, ProjectModelConfig>>` on DbtProject?

https://github.com/dbt-labs/dbt-fusion/blob/53281e5a0722b938b3efe3785057ad461fc6ebd8/crates/dbt-schemas/src/schemas/project/dbt_project.rs#L85

**Screenshots**

<img width="938" alt="Image" src="https://github.com/user-attachments/assets/1b407fad-c458-4e43-b70c-aa6d19c63738" />

** Operating System and CPU Type (please complete the following information):**
* Mac
* ARM

**Comment by joellabes** [comment]
Hey @ya7010! At a glance, I suspect that this is because you need to move the dbt-osmosis setting into a config.meta block. 

It is no longer possible to include arbitrary configs outside of config.meta: https://github.com/dbt-labs/dbt-core/discussions/11493

~Handwritten on mobile, so indentation and pluses might not be exactly correct, but you're looking for something like this 👇~ Use Benoit's one below!

```
models:
  my_dbt:
    +persist_docs:
      relation: true
      columns: true
    +config:
      meta:
        dbt-osmosis: 'schema.yml'

    sandbox:
      database: CDP
      schema: SANDBOX
      tags: ['sandbox']
      materialized: view
```
