### ISSUE TITLE
[BUG] Snowflake: dbt1005: In file `profiles.yml`, field `warehouse` is required

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#13285]
**Describe the bug**
I got the following error when using the dbt Fusion engine, but I don't get the same error when using `dbt-core`.

```
$ dbt build -s my_model --target dev
dbt-fusion 2.0.0-beta.21
   Loading profiles.yml
error: dbt1005: In file `profiles.yml`, field `warehouse` is required.
  Finished 'build' target 'dev' with 1 error in 22ms 784us
```

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
dbt-fusion 2.0.0-beta.21

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**

1. Open [this workspace](https://github.com/dbt-labs/scratch/tree/main/repros/fusion-211)
2. Follow the instructions in the `README`, or:

I have a profile that does **not** include `warehouse:`, like this:

```yaml
    dev:
      type: snowflake
      account: something
      database: something
      schema: something
      role: something
      user: something
      authenticator: externalbrowser
```

Then when I run a command like `dbt run`, I get the error reported above.

**Expected behavior**
I thought if I can omit it with dbt-core that I'd be able to in Fusion also.

**Screenshots**

**Operating System and CPU Type (please complete the following information):**
* Mac/Windows/Linux? N/A
* X86 or ARM? N/A
