### ISSUE TITLE
[BUG] Snowflake externalbrowser auth on a shared development machine opens too many auth windows

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#13355]
**Describe the bug**
[Original Slack thread](https://getdbt.slack.com/archives/C088YCAB6GH/p1750814257404899). Given a profile that looks like this: 
```
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      warehouse: query_wh
      authenticator: externalbrowser
      schema: "{{ env_var('SNOWFLAKE_TRANSFORM_SCHEMA') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      database: "{{ env_var('SNOWFLAKE_DB') }}"
      threads: 1
      role: xxxxxxxxxx
      account: XXXXX-XXXX
```

A community member gets 3-4 login prompts when running `dbt run`, which is strange because they have 1 thread configured. It seems that the models are running serially, but every model needs to reconnect instead of using the cached token. 

We tried ensuring the `HOME` env var was set and this maybe removed one popup, but it wasn't a slam dunk. 

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
beta 28 

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**Expected behavior**
The prompt to only be created once 

**Screenshots**
Call recordings [here](https://dbtlabs.zoom.us/clips/share/DhJYXeueRjCVAnp-COJ84Q) and [here](https://dbtlabs.zoom.us/clips/share/Uh1v6uszQGauhsEIRom_Hw) (dbt Labs access only) 

**Operating System and CPU Type (please complete the following information):**
* Mac/Windows/Linux? SSHing into a Linux box from a Mac
* X86 or ARM? Not sure, suspect x86
