### ISSUE TITLE
Provide a way to update documentation for BigQuery datasets

### ISSUE THREAD

**Issue by heisencoder** [dbt-labs/dbt-core#1714]
### Describe the feature
Allow a dbt project to contain documentation on BigQuery datasets (i.e., 'schemas' in other databases), and update this documentation within BigQuery whenever dbt creates or updates datasets.  As a bonus feature, it should be possible to update the dbt documentation website to also provide a description for the dataset (somewhat similar to how it's possible to describe sources).

This is somewhat similar to the "Persisting model descriptions" feature that was released in 0.14:

https://docs.getdbt.com/docs/bigquery-configs#section-persisting-model-descriptions

Also see slack discussion: https://getdbt.slack.com/archives/CBSQTAPLG/p1567096074037600

**Comment by drewbanin** [comment]
Thanks for the feature request @heisencoder! I think this is a reasonable thing for dbt docs to support for sure

**Comment by heisencoder** [comment]
Thanks for the thoughts Drew!  The first part of the problem is to update the yml file layout to allow specifying the documentation (which could then be used by the dbt doc generator in addition to the BigQuery adapter).  Maybe we could somewhat follow the example provided by the "Persisting model descriptions".

The main issue is that there's not really a first-class way to describe datasets/schemas on their own. One thought would be to add a top-level 'schemas' key to the dbt_project file, which would allow setting information about the schema/dataset:

dbt_project.yml:
```yaml
  schemas:  # or datasets
    my_schema:
      description:  A description of the schema/dataset that would be persisted in the appropriate folder in the dbt documentation website and could also be published to BigQuery
      persist_docs:
        relation: true  # persist this in BigQuery
      materialized: view  # Can provide default for all models that use this schema/dataset.
```

An alternative would be to put this information into the `schema.yml` files.  The format would potentially look the same as the example for dbt_project.yml above.

dbt would set these descriptions when the schema/dataset is first created, and would update it if the schema/dataset already exists.
