### ISSUE TITLE
Allow non-dict test config if only one argument is required.

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/dbt-core#1913]
### Describe the feature
Currently, when adding tests that require an argument, it needs to look something like this:
```
version: 2

models:
  - name: orders
    tests:
      - dbt_utils.expression_is_true:
          expression: "net_price + tax = total"
    columns:
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
```
For tests that only have a single (required) argument, it would be cool to remove the extra key:
```
version: 2

models:
  - name: orders
    tests:
      - dbt_utils.expression_is_true: "net_price + tax = total"
    columns:
      - name: status
        tests:
          - accepted_values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
```

Currently, if you try to compile this, you'll get:
```
Compilation warning: Invalid test config given in models/staging/jaffle_shop/jaffle_shop.yml:
	test arguments must be dict, got <class 'list'> (value ['placed', 'shipped', 'completed', 'return_pending', 'returned'])
```

### Who will this benefit?
Minor quality of life improvement
