### ISSUE TITLE
Give profiles some love

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/dbt-core#1958]
I recently rewrote some docs on connecting to your data warehouse when using dbt Core.

In doing so, I started to thing pretty hard about whether the names/structure we've used so far are still a good fit.

Some random thoughts:
- I think folks sometimes think that because targets are named a “target”, there’s also somewhere to define a “source”. Is “target” a misleading word? Is `envs` a better word instead?
- The current structure has some weirdness in it, e.g. “targets” are listed under the “outputs” key.
- The keys “schema” and “default” are not descriptive enough — is “schema” the schema I’m reading from or writing to? “default” what? Oh, ~default output~ default target.
- When defining multiple targets for a profile, you have to repeat connection details

Here's my proposed new schema:
```yaml
version: 2

profiles: # should this be connections instead?
- name: jaffle_shop
  default_env: dev
  connection_details: # this isn’t the right key name... yet, but this is the default connection details, which you can override in a particular target. 
    type: redshift
    host: xyz
    ....
    user: abc
    pw: pas55w0rd
  envs:
    - name: dev
      target_schema: dbt_claire
      connection_details: # here you can override/add to anything defined above
        user: claire
        password: pa55w0rd
    - name: prod
      target_schema: analytics
      connection_details: 
        user: claire_super
        password: pa55w0rd
```
