### ISSUE TITLE
Rename the `alias` config to `identifier`

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/dbt-core#2209]
### Describe the feature
We generally use  the word `identifier` to refer to the view/table name (which is consistent with database terminology).

However, to change the `identifier`, you use the `alias` config.

In order to make things more intuitive going forward, we should:
1. Make `identifier` the main config
2. Rename `generate_alias_name` to `generate_identifier_name`
3. Provide backwards compatibility for the next version or so

### Describe alternatives you've considered
Just not doing it

### Additional context
N/A

### Who will this benefit?
New users as we can have more consistent terminology

**Comment by dbeatty10** [comment]
I bumped into this today.

I forgot that to [overwrite the model `identifier`](https://docs.getdbt.com/docs/build/custom-aliases) with a custom value, the model config needs to be this:

```sql
{{ config(
    alias="my_custom_alias",
) }}
```

rather than this:

```sql
{{ config(
    identifier="my_custom_alias",
) }}
```

Interestingly, sources do allow an [`identifier`](https://docs.getdbt.com/reference/resource-properties/identifier) config:
```yaml
sources:
  - name: jaffle_shop
    tables:
      - name: orders
        identifier: orders_table_with_a_super_duper_long_name_that_you_will_probably_want_to_shorten
```

Regardless, I'm leaving this issue as "closed as stale".
