### ISSUE TITLE
Store the unresolved form of source database representations

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#2744]
_extension of #2713_

### Describe the feature

Let's say a project has a source defined like:
```yml
sources:
  - name: my_postgres_db
    database: "{{ 'raw' if target.name == 'prod' else 'raw_sampled' }}"
```

Today, if running in `dev` and comparing to a manifest generated by a `prod` target, `state:modified+` will include _all_ models that depend on `source:my_postgres_db` because the `database` differs. Ideally, we'd be able to tell that the unresolved `database` (Jinja statement) is identical.

I'm most interested in **sources** and **database representations** (`database`, `schema`, `identifier`). If it made sense, though, we could broaden this issue to the matter of storing unresolved:
* database representations
* resource properties (will the distinction between node configs and resource properties even make sense in a post-#2401 world?)

### Describe alternatives you've considered
- The proposal for `state:modified` subselectors gives decent user-side answers by letting people "switch off" the intersection of `state:modified.database_representations` and specific sources.

### Who will this benefit?
- Users who develop, test, and deploy against genuinely different source datasets. While this isn't something we recommend in the general case, it's the norm at organizations of a certain size + maturity.

**Comment by fabrice-etanchaud** [comment]
You are totally right, @jtcohen6 . That 's exactly our use case, here @maif-vie (life insurance). We have a kind of environment notion (we call that a 'track') that groups data sources for a given project/feature. I ended up adding a extra credential parameter called 'environment' to use as a prefix for source's databases. That way I can configure separately the source version and the target database. This enhancement would be of great help here.
Best regards from french west coast ;-)

**Comment by jtcohen6** [comment]
- This will be improved by the introduction of sub-selectors (#2704)
- Let's revisit after #2401, since that may have implications for how source `database`/`schema`/`identifier` are stored on the source node (`node.config` vs. node-level properties)

**Comment by katieclaiborne** [comment]
Would it be possible to revive this issue?

Our (BigQuery) project defines sources that are [implicitly different across environments](https://github.com/dbt-labs/dbt-core/issues/2744#issuecomment-811046508).

We're using `state:modified` sub-selectors as a workaround, but because this is the general pattern for our sources, creating a YAML selector with the intersection of each one is unsustainable.

**Comment by wjhrdy** [comment]
> Would it be possible to revive this issue?
> 
> Our (BigQuery) project defines sources that are [implicitly different across environments](https://github.com/dbt-labs/dbt-core/issues/2744#issuecomment-811046508).
> 
> We're using `state:modified` sub-selectors as a workaround, but because this is the general pattern for our sources, creating a YAML selector with the intersection of each one is unsustainable.

can I ask how exactly you do this?

I have a source that is defined like this.

```yaml
version: 2
sources:
  - name: data1
    database: data
    schema: "{{ target.name }}_schema"
    tables:
```

this source gives me false positives when i compare across target environments.

how would I write a YAML selector or just CLI selector to select all changed models but ignore the false positives that are from this target-aware source definition?

**Comment by katieclaiborne** [comment]
Sure thing! Here's what our `selectors.yml` file looks like.

```yaml
selectors:
  - name: modified_plus
    description: >
      All state:modified subselectors except relation (database/schema/alias), and their children
    definition:
      union:
        - method: state
          value: modified.body
          children: true
        - method: state
          value: modified.configs
          children: true
        - method: state
          value: modified.persisted_descriptions
          children: true
        - method: state
          value: modified.macros
          children: true
        - method: state
          value: modified.contract
          children: true
        - exclude:
            - method: package
              value: dbt_project_evaluator
            - method: fqn
              value: dbt_project_evaluator_exceptions

**Comment by wjhrdy** [comment]
Thanks for this I've created our version of this where you can specify sources that are target aware. 

```yaml
selectors:
  - name: target_aware_sources
    description: >
      All sources that are target-aware
    definition:
      union:
        - "@source:source1"
        - "@source:source2"
        - "@source:source3"
        - "@source:source4"

  - name: modified_minus_relation
    description: >
      All state:modified subselectors except relation (database/schema/alias), and their children
    definition:
      union:
        - method: state
          value: modified.body
          children: true
        - method: state
          value: modified.configs
          children: true
        - method: state
          value: modified.persisted_descriptions
          children: true
        - method: state
          value: modified.macros
          children: true
        - method: state
          value: modified.contract
          children: true

  - name: modified_target_aware
    description: >
      All state:modified subselectors except relation (database/schema/alias), and their children intersected with sources that need this
    definition:
      intersection:
        - method: selector
          value: target_aware_sources
        - method: selector
          value: modified_minus_relation

  - name: modified_minus_target_aware
    description: >
      All state:modified minus target_aware_sources
    definition:
      - method: state
        value: modified
        children: true
        exclude:
          - method: selector
            value: target_aware_sources

  - name: modified_plus
    description: >
      All state:modified accounting for target_aware_sources
    definition:
      union:
        - method: selector
          value: modified_minus_target_aware
        - method: selector
          value: modified_target_aware
```
