### ISSUE TITLE
Better package dependency resolution

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/dbt-core#2842]
### Describe the feature
Currently, when there are conflicting package versions it's hard to debug / manually fix.

Take this packages.yml for example:
```
packages:
  - package: fishtown-analytics/segment
    version: 0.5.1
  - package: fishtown-analytics/dbt_utils
    version: 0.6.2
  - package: fivetran/fivetran_log
    version: 0.2.0
  - package: fivetran/linkedin_source
    version: 0.1.0
  - package: fivetran/salesforce
    version: 0.1.0
```

This creates the error:
```
Version error for package fishtown-analytics/dbt_utils: Could not find a satisfactory version from options: ['>=0.1.22', '>=0.6.0', '<0.7.0', '>=0.6.1', '<0.7.0', '=0.3.0']"
```

A more useful error would be something like:
```
Version error for package fishtown-analytics/dbt_utils: could not find a satisfactory version
>=0.4.0,<0.7.0 required by fishtown-analytics/segment 
0.6.2          required by dbt-learn-demo
>=0.6.0,<0.7.0 required by fivetran/fivetran_log
0.3.0          required by fivetran/salesforce


```
☝️  It's much easier to now see that the problem here is the `fivetran/salesforce` dependency.

Even more useful would be the ability to override the dependency, something like this perhaps?
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.2
  - package: fivetran/salesforce
    version: 0.1.0
    override_dependency:
       - package_name: dbt_utils
         package: fishtown-analytics/dbt_utils
         version: 0.6.2
```

or this:
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.2
  - package: fivetran/salesforce
    version: 0.1.0
    override_dependency:
       - package_name: dbt_utils
```
(And then dbt would remove the range for this package from the version resolution, and end up using `0.6.2` since it's specified above)

### Describe alternatives you've considered
@jtcohen6 — not sure if you've given any thought to this yourself?

### Additional context
--

### Who will this benefit?
Users of multiple packages

But also package maintainers, as it:
- gives you more leeway when making dependency upgrades
- also lets you test out changes on a branch in a dependent package by overriding the installation method with the `git` syntax
