### ISSUE TITLE
Add the ability to define a terms section or glossary

### ISSUE THREAD

**Issue by datGnomeLife** [dbt-labs/dbt-core#2860]
### Describe the feature
With the introduction of exposures I think there is a great opportunity to expand on some more of the “meta data” capabilities in dbt docs. I think a great addition would be a terms glossary. This could be for business terms or some other terms that are often repeated. I think this could be best achieved with a new yaml schema, something to the effect of:

```yaml
version: 2

terms:
  - name: Congestion Revenue Rights
    description: "a brief description or a more detailed one using doc blocks: {{ doc('link_to_doc') }}"
    meta: 
      sme: contact@your.company
    alias: ["CRR", "CRs"]
    indentifier: "crr"
```

Then could be used referenced in doc macros:

```
{ % docs mydoc %}
This is a table contains data related to {{ term("crr") }} # would render name and link
{% enddocs %}
```
Then Ideally in the dbt docs, in the description, it would render a link to the item in the glossary being referenced or render a preview on hover.

### Describe alternatives you've considered
Could be achieved via a `terms` macro or extending the docs macro functionality.

### Additional context
This is database agnostic and purely for informational purposes

### Who will this benefit?
I think this could benefit all DBT users or consumers of DBT docs. The ability to define terms provides valuable context. Even a well detailed catalog isn't as useful if the descriptions make references to terms that assume user knows what they mean. This would help keep things DRY by allowing dbt users to define terms once and reference elsewhere. 

### Are you interested in contributing this feature?
I'm definitely interested in contributing to this feature, might need help in the frontend department.
