### ISSUE TITLE
Add test groups

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-core#2884]
### Describe the feature
Create a feature to specify "test groups" such that there is a shorthand for specifying several related tests on a model at once. Currently, Fishtown best practices recommend that you specify `unique` and `not_null` tests on the primary key of each of your models - these tests are logically related. This feature would allow you specify just a primary key test group on a single field, and would automatically generate and compile both a `unique` and `not_null` test for that model on a `dbt test` invocation. This could be extended to other logically grouped tests on single fields. 

### Describe alternatives you've considered
Alternatives include explicitly calling each test, as it works today! This is still absolutely a viable approach, and has the benefit of forcing analysts to explicitly declare their assumptions about their data. 

### Additional context

**Example:**

current state:

```
version: 2

models:
    - name: cool_data_model
      columns:
          - name: id
            tests:
                - unique
                - not_null
```

proposed:

```
version: 2

models:
    - name: cool_data_model
      primary_key: id
```

Obviously the example is up for debate - might be worth keeping column-level definitions in there, and maybe something that explicitly says the word `test` but generally, a single specification could make the definition of these tests more concise. 

### Who will this benefit?
This is primarily for analytics engineers to clean up the definitions in a `schema.yml` file. 

### Are you interested in contributing this feature?
For sure!

**Comment by jtcohen6** [comment]
Neat idea @dave-connors-3! What you're proposing sounds along the lines of a built-in YAML anchor, i.e.
```
models:
  - name: cool_data_model
    columns:
      - name: id
        tests: &primary_key
          - unique
          - not_null
  - name: my_other_model
    columns:
      - name: id
        tests: *primary_key
```
Without, of course, having to define the initial `&primary_key` in each file.

I heard a related idea the other day, with a slightly different angle, and I'm now convinced that the two might be connected.

Right now, dbt runs separate queries for each of `unique`, `not_null`, etc, even if they're all defined on the same column in the same table. What if there was a way for dbt to consolidate those tests into a single query?

Essentially, I'm thinking of a genuinely different custom schema that acts as a "combo" of existing builtin tests:

```yml
models:
  - name: cool_data_model
    columns:
      - name: id
        tests:
          - primary_key
```

Then:
```sql
{% macro test_primary_key(model, column_name) %}

    with potential_dupes as (

        select
        
            {{ column_name }},
            count(*) as num_rows
        
        from {{ model }}
        group by 1
        
    )
    
    select sum(num_rows)
    from potential_dupes
    where {{ column_name }} is null   -- not_null
      or num_rows > 1                 -- unique
    
{% endmacro %}
```

Hypothetically, it would be more efficient in terms of database time and resources. The downside is ambiguity: should the test should fail, it could have been because the column was null, or not unique, or null _and_ not unique.

What do you think?

**Comment by dave-connors-3** [comment]
I think this largely is what I was going for! The only other thought I had is that making this more geared towards defining groups of tests that could be defined in bundles could be more extensible. i.e. `primary_key` test bundling includes unique and not null, but this could allow end users to define their own bundles in their projects (which yes, now that I'm typing it, is essentially just a more complicated YAML anchor). Another argument against myself is that I don't have any clear examples of logically bundled tests off the top of my head, so maybe it wouldn't really be all that widely used.  

If we were going to simplify and just define the new `primary_key` test, I think there'd be a way to write the sql such that the results would surface which of the failure modes a test failed on - especially if we could print the results of the query to the terminal. 

```
13:10:46 | 1 of 1 START test_cool_data_model_primary_key........... [RUN]
13:10:48 | 1 of 1 FAIL test_cool_data_model_primary_key................. [FAIL in 1.77s]

| type | count |
----------------
| null |   9   |
| dupe |   4   |
| both |   0   |
```

But wrangling that SQL might be complex enough that we lose the efficiency gains on DB time and resources. Curious to get your thoughts!

**Comment by noel** [comment]
I'm all for creating new macros that are more explicit and compile to a combination of macros like the `primary_key` example, but not recommending custom generic groups like `my_group`

``` yml
models:
  - name: cool_data_model
    columns:
      - name: id
        tests:
          - my_group
```

This starts obscuring what is really going on.  The more indirection the harder it is to know what is happening, more magic.
Imagine I create a group with 3 tests and a new user comes into my team and just sees `my_group` everywhere.  It will take more mental cycles and discovery to understand what that means.  Today you know exactly what is going on.

Something like this is simple to understand
``` yml
models:
  - name: cool_data_model
    tests:
      - primary_key:
        - col_1
        - col_2
```
