### ISSUE TITLE
Make complex tests’ purposes clearer in compiled SQL and dbt docs 

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#2959]
### Describe the feature
- When a custom schema test fails, the first thing I do is to download the compiled sql and run it myself to see what’s gone wrong. 
- backsolving from the file’s name and contents of the query is more complex than it needs to be -what exactly does `dbt_utils_expression_is_true_paypal__subscribers_is_trial_or_sub_active_is_true__is_trial_expired_is_false_and_is_subscription_expired_is_false` mean?
- I currently include a comment in the yaml file explaining in English what the test does, but that’s not where I’m looking when a test fails. 
```yaml

        # active accounts can't have expired
        - dbt_utils.expression_is_true:
            expression: 'is_trial_expired is false and is_subscription_expired is false'
            condition: 'is_trial_or_sub_active is true'
        
        # inactive accounts must have expired
        - dbt_utils.expression_is_true:
            expression: 'is_trial_expired or is_subscription_expired'
            condition: 'is_trial_or_sub_active is false'
        
        # inactive accounts may only have been a trial or a subscription
        - dbt_utils.expression_is_true:
            expression: 'not (is_trial_expired and is_subscription_expired)'

```
- Instead of it being a yaml comment, I can add a `description` argument to the test macro and include that as a comment in the compiled SQL

I then got to thinking about how custom tests display in dbt docs, and thought it would be nice to also display that nice comment instead of the [stringified kwargs](https://github.com/fishtown-analytics/dbt-docs/blob/8422d4c67f6ca532cad8fa73c81567f4de453f18/src/app/services/project_service.js#L195). 

### Describe alternatives you've considered
- stopping at “include the description in the sql query”, which wouldn’t require any changes to dbt itself, but would mean needing to maintain our own fork of the dbt-utils tests
-  waiting for #1173 which looks like it might be a relative to this, albeit much broader scope

### Who will this benefit?
- If appropriate, a description property could be exposed to the built-in dbt tests as well as the dbt-utils ones, in which case it would help everyone who wants to debug their failing tests. Admittedly, `not_null` doesn’t need a lot of explanation, but perhaps it’s useful to say _why_ it shouldn’t be null. 
- People consuming dbt docs (in fact, this might better live under the dbt-docs repo, but I’m not sure about the interplay before it gets to doc-rendering time - I assume that a description property would need to be explicitly added to the manifest, but not sure if that’s true given that I could already add arbitrary params to this macro...)

### Are you interested in contributing this feature?
The docs test suite and I are close personal friends at this point, let’s do it.
