### ISSUE TITLE
dbt docs is unable to refocus on a node that has a name with spaces

### ISSUE THREAD

**Issue by aaronraff** [dbt-labs/dbt-core#2970]
### Describe the bug

When running `dbt docs generate` with an exposure name that has spaces, the dag visualization does not work properly. The visualization is unable to refocus on the exposure that has a space in its name.

### Steps To Reproduce

- Clone the [jaffle_shop repo](https://github.com/fishtown-analytics/jaffle_shop)
- Add the following exposure to `models/staging/schema.yml`:
```
exposures:
  - name: "test exposure"
    type: dashboard
    maturity: medium

    depends_on:
      - ref('stg_orders')
     
    owner:
      name: name
      email: email
```
- Run `dbt docs generate`
- Run `dbt docs serve`
- Open up the lineage graph visualization
- Right click on the "test exposure" node and select "Refocus on node"

### Expected behavior

I would expect one of two things:
- I am able to refocus on the node that contains spaces
- dbt validates that my exposure name does not have spaces

### Screenshots and log output

<img width="1210" alt="Screen Shot 2020-12-21 at 12 10 05 PM" src="https://user-images.githubusercontent.com/16910064/102802965-80782180-4385-11eb-856b-787301a775f5.png">

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - postgres: 0.18.1
  - spark: 0.18.1.1
```

**The operating system you're using:**
macOS Catalina
Version 10.15.7

**The output of `python --version`:**
Python 3.7.7

### Additional context

N/A
