### ISSUE TITLE
Extend render_test_update to all builtin schema tests

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#3048]
### Background

See [this thread](https://github.com/fishtown-analytics/dbt/pull/3034/files/6b7e1db18659b60c96b0d3777a6960fd7f718a49#r564751530) in #3034. We're adding a "shortcut" parse path for builtin versions of commonly used macros: `unique` and `not_null`. Let's extend it to the slightly larger category of builtin schema tests.

It's possible that `accepted_values` and `relationships` tests will be more complex because they accept arguments, which could be Jinja expressions that require rendering. As it is, the builtin versions of `unique` and `not_null` also accept an argument—`severity`—that _could_ be set to a Jinja expression, like this one:

```yml
models:
  - name: my_model
    columns:
      - name: id
        tests:
          - unique:
              severity: "{{ var('warn_or_error', 'warn') }}"
          - not_null:
              severity: "{{ 'error' if target.name == 'prod' else 'warn' }}"
```

dbt needs to render those Jinja expressions in order to return the correct value during parsing, especially if the user has supplied a `config`-based selection method:
```bash
$ dbt test -m config.severity:warn
```

To my slight surprise, this works with the latest code in #3034 :) That gives me a good feeling about our ability to extend this work to `test_accepted_values`, `test_relationships`, and other commonly used builtin macros.

### Investigate

- Extending the new "shortcut" MacroManifest for commonly used / built-in macros
- Initial steps in statically analyzing Jinja templates for schema test construction
