### ISSUE TITLE
Way to have test pass if compile error raised

### ISSUE THREAD

**Issue by MarkMacArdle** [dbt-labs/dbt-core#3060]
### Describe the feature
A method of specifying that a test should pass if a compile error is raised.

I wanted this when working on modifying the equality test in dbt-utils. There was two places I thought it'd be useful:

#### Validating inputs
The current equality test will [raise a compile error](https://github.com/fishtown-analytics/dbt-utils/blob/bbba960726667abc66b42624f0d36bbb62c37593/macros/schema_tests/mutually_exclusive_ranges.sql#L17)  to validate inputs but there isn't a way of making an integration test that confirms the compile error is raised when expected.

#### Tests involving metadata
The modification I was working on was to check if two tables had the same columns. I added optional arguments for checking column order, capitalisation of names and data types ([PR here](https://github.com/fishtown-analytics/dbt-utils/pull/298)). The information schema is used to pull the column metadata and if the specified parts don't match compile errors are raised. With four optional arguments and many possible combinations I would have loved a way to write integrations tests to check the compile errors where being raised when they should have been.

#### Proposal
I like the discussion of having a wrapper test that would consume another test in #2982 so I could have something like:
```
models:
  - name: model_name
    tests:
      - test_fail:
          - expect: compile_error
          - test_macro: dbt_utils.equality:
              compare_model: ref('other_table_name')
              column_metadata_tests:
                - all_columns_present_in_both_tables
                - case_sensitive_names
                - matching_order
                - matching_data_type
```

Some time could be saved by not actually running the query as once it compiles successfully the test can be passed.

### Describe alternatives you've considered
Using a bash/python script to expect getting an error as suggested by @jtcohen6 [here](https://github.com/fishtown-analytics/dbt/issues/2982#issuecomment-775854481). I think you could get something working that way but wouldn't be as nice defining everything in normal tests. You'd need some way of differentiating between tests that should be run by the expecting-failure-script and those that can be run normally. Could maybe use tags for that.

### Additional context
Somewhat related to #2982 which requests a way to specify a test should fail. Differs in that that issue would react to a returned result whereas this one would need to react to a compile error.

### Who will this benefit?
Anyone using compile errors

### Are you interested in contributing this feature?
Yes. Don't know where to start or if this should be a feature of an external library.
