### ISSUE TITLE
Configurable description in yaml config for generic tests

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt-core#3249]
### Describe the feature
Add the ability to define descriptions in yaml files. Support the ability to use the rendered values of the test args (`{{ model }}` and `{{ column_name }}` by default)

Consider the following example:
```
# macros/reusable_tests.sql
{% test not_null(model, column_name), adapter = 'default' %}

    select * from {{ model }}
    where {{ column_name }} is null

{% endtest %}

# macros/schema.yml
tests:
 - name: not_null
   adapter: default
   description: "Assert that {{ column_name }} is not null in {{ model }}"
   args:
     - name: model
       description: "The model to test"
     - name: column_name
       description: "The column or expression to test"
```

Additional context in #1173.
