### ISSUE TITLE
Specific instances of generic tests should inherit configs from the nodes they're defined under

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#3256]
### Describe the feature

Both of the tests instantiated below should inherit the tag `my_tag`. Today, neither of them does.

(updated to use v0.21 syntax)

```yml
models:
  - name: model_a
    config:
      tags: ["my_tag"]
    tests:
      - my_custom_generic_test
    columns:
      - name: id
        tests:
          - unique
```

The main configs I have in mind:
- `enabled`: Currently, a test that depends on a disabled node won't run but will raise a warning. Instead, I think the test should just be disabled, too! (Prerequisite: #3252)
- `tags`: Tests should additively inherit tags on their parent nodes. This is actually how tags work for tests-on-sources today, but it _isn't_ how tags work for tests-on-models, unless it's a column-level tag. Oof—let's make that more consistent!
- Adapter-specific configs that could apply to multiple node types (e.g. https://github.com/fishtown-analytics/dbt/issues/3255)

Some configs, such as `severity`, are totally unique to tests—there's no such thing as a warning-severity model. It wouldn't make sense to inherit these from the parent node. Instead, users who want to configure a whole bunch at once could set default values or pass from `dbt_project.yml` (https://github.com/fishtown-analytics/dbt/issues/3253).
