### ISSUE TITLE
Exposures are not disable when disabling an entire folder

### ISSUE THREAD

**Issue by alepuccetti** [dbt-labs/dbt-core#3493]
### Describe the bug
When I disable an entire folder in the `dbt_project.yml` the exposures inside don't get disabled along side the models causing failure because a model dependencies.

### Steps To Reproduce
1. Disable models in your project:
```yml
models:
  project_name:
      # Applies to all files under models/example/
      folder_a:
        +enabled: false
      folder_b:
        +enabled: false 
```
2. Execute `dbt_ compile`
```bash
Running with dbt=0.19.1
Encountered an error:
Compilation Error in exposure North East Derbyshire (models/folder_b/exposures.yml)
  Exposure 'exposure.project_name.exposure_name' (models/folder_b/exposures.yml) depends on a node named 'my_model' which is disabled
```

### Expected behavior
This should not trigger an error because the exposure should be disable along with the models.

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - bigquery: 0.19.1
  - snowflake: 0.19.1
  - redshift: 0.19.1
  - postgres: 0.19.1
```

**The operating system you're using:** Mac OS X 10.15.7

**The output of `python --version`:** Python 3.9.5

**Comment by jtcohen6** [comment]
@alepuccetti Thanks for opening! Could you say a little more about your use case, such that you're disabling a large number of "exposed" models?

The fact of the matter is that exposures cannot be disabled today, because:
- they do not support the `enabled` config (or any configs, for that matter)
- they cannot be configured from `dbt_project.yml`

Ultimately, you should be able to include this config in your project file:
```yml
exposures:
  project_name:
      # Applies to all files under models/example/
      folder_a:
        +enabled: false
      folder_b:
        +enabled: false 
```

There's prior art here for sources, which support the `enabled` config and can be configured from `dbt_project.yml` ([docs](https://docs.getdbt.com/reference/source-configs)). It's reasonable to expect that `exposures` should work in exactly the same way.

This will require reaching slightly further into dbt internals than usual for a `good first issue`, though I'd be happy to work with a dedicated community member who'd be interested in giving it a shot. I don't think this is something we're going to be able to prioritize in the near term.
