### ISSUE TITLE
dbt 0.20.0 tries to create two tables with the same name when --store-failures is used with similar-looking expression_is_true tests

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#3626]
### Describe the bug
This schema.yml file: 
```yml     
version: 2

sources:
    - name: crm
      database: reporting
      schema: crm
      loader: Amazon DMS

      tables: 
        - name: schoolattributevalues
          tests:
          - dbt_utils.expression_is_true:
              expression: "not (len(memovalue) > 0 and len(value) > 0)" #only one of memovalue and value can be populated
          - dbt_utils.expression_is_true:
              expression: "not (len(memovalue) = 0 and len(value) = 0)" #... but, one of them does have to be
```

gives an error when running `dbt test --store-failures`:

```
Encountered an error:
Compilation Error
  dbt found two resources with the database representation ""reporting"."dev_jlabes_dbt_test__audit"."dbt_utils_source_expression_is_d74da5f62da07f2223c634b4409dd71d"".
  dbt cannot create two resources with identical database representations. To fix this,
  change the configuration of one of these resources:
  - test.educationperfect.dbt_utils_source_expression_is_true_crm_schoolattributevalues_not_len_memovalue_0_and_len_value_0_.77167f5215 (models\staging\crm\other\crm_sources.yml)
  - test.educationperfect.dbt_utils_source_expression_is_true_crm_schoolattributevalues_not_len_memovalue_0_and_len_value_0_.c19220b2a8 (models\staging\crm\other\crm_sources.yml)
```
I guess the problem comes from the only difference between the expressions being the `>` vs `=`, which both get turned into `_`s. However, the `.77167f5215` and `.c19220b2a8` suffixes provide deduplication for the tests' FQNs (I think those are the FQNs?)

### Expected behavior
Both tests to be given different DB representations. 

### Screenshots and log output
See above

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] other (specify: ____________)

- [ ] bigquery
- [ ] snowflake

**The output of `dbt --version`:**
```
installed version: 0.20.0
   latest version: 0.20.0

Up to date!

Plugins:
  - bigquery: 0.18.2
  - postgres: 0.20.0
  - redshift: 0.20.0
  - snowflake: 0.18.2
```

**The operating system you're using:**
Win10 

**The output of `python --version`:**
`Python 3.8.0`

**Comment by jtcohen6** [comment]
@joellabes Thanks for the report!

dbt does try to create a unique hashed alias of <64 characters for tests with too-long names. The issue is that we're _first_ substituting all special characters for underscores, _then_ hashing the flattened arguments into a unique identifier:

https://github.com/dbt-labs/dbt/blob/72722635f275666b34efc9baf8485be79dfcaa88/core/dbt/parser/schema_test_builders.py#L41-L58

Since the two tests only differ by a special character, both get stringified to `dbt_utils_source_expression_is_true_crm_schoolattributevalues_not_len_memovalue_0_and_len_value_0_`, then hashed and suffixed to `dbt_utils_source_expression_is_d74da5f62da07f2223c634b4409dd71d`.

### fix

The most obvious fix here is to hash `flat_args` _before_ flattening into `clean_flat_args`. I think the code change for that is fairly straightforward, so I'm going to call this a good first issue.

There's one issue I can foresee: If a test name (including all arguments and underscores) is <64 characters, we aren't including a hashed suffix at all. Special characters would still be substituted out for underscores, causing a collision. Should we start adding hash suffixes for all tests with arguments, regardless of length? Frankly, I don't know how common it is for two tests to both have very few/concise arguments _and_ differ by only special characters between them. We will have at least narrowed this edge case into an even rarer occasion.

### workaround

In the meantime, you could certainly work around this by adding an extra condition to one of the tests, and "salting" the hash:
```yml
          tests:
          - dbt_utils.expression_is_true:
              expression: "not (len(memovalue) > 0 and len(value) > 0)" #only one of memovalue and value can be populated
          - dbt_utils.expression_is_true:
              expression: "not (len(memovalue) = 0 and len(value) = 0) and true" #... but, one of them does have to be
```

### longer-term options

Tests already support an `alias` config, just not yet as a test-specific modifier (defined in the same `.yml` file where the test is defined). We could add support for that, giving users the option of overriding whatever default behavior dbt is attempting around argument flattening and hashing:
```yml
          tests:
          - dbt_utils.expression_is_true:
              expression: "not (len(memovalue) > 0 and len(value) > 0)" #only one of memovalue and value can be populated
              alias: test_only_one_of_memovalue_and_value
          - dbt_utils.expression_is_true:
              expression: "not (len(memovalue) = 0 and len(value) = 0)" #... but, one of them does have to be
              alias: test_at_least_one_of_memovalue_and_value
```

We've also got some broader thinking in the works about node naming + identification: https://github.com/dbt-labs/dbt/issues/3348, https://github.com/dbt-labs/dbt/issues/3548

**Comment by joellabes** [comment]
Thanks for all the options! 
>Should we start adding hash suffixes for all tests with arguments, regardless of length?

Feels like a lot of uglification on the happy path to protect against an edge case of edge cases, so I'd go 👎 until it becomes a clearer issue. 

I worked around it by flipping the order of the clauses on the second test! It was nice to have them in the same order to make it easy to visually diff, but not a big deal. (Made for a fun code review though 
![image](https://user-images.githubusercontent.com/7335046/127063772-c19c4c15-3867-4860-b17e-7ed3342c17a3.png)
)

**Comment by joellabes** [comment]
@jtcohen6 I've just spent some time looking into this, and have found another wrinkle: 
```
    columns:
      - name: total_unweighted
        tests:
          - not_null
          - accepted_range:
              where: "is_resub_adjustment is false"
              min_value: 0
              tags: 
                - hubspot_bad_revenue
          - accepted_range:
              where: "is_resub_adjustment is true"
              max_value: 0
```

The args dict for the latter is 
```
{'max_value': 0, 'column_name': 'total_unweighted', 'model': "{% if config.get('where') %}(select * from {{ ref('hubspot_revenue__revenue_lines') }} where {{config.get('where')}}) hubspot_revenue__revenue_lines{% else %}{{ ref('hubspot_revenue__revenue_lines') }}{% endif %}"}
```

and the `where` clause is nowhere to be found. That means that I wind up with `total_unweighted__0` as the entirety of even the unclean flat args. 

Should I be passing `config` into `get_nice_schema_test_name` as well? Is it even available at that point? I haven't gone looking, figured I'd check in before going too far down the rabbit hole.
