### ISSUE TITLE
[CT-201] Reconcile configs + properties for sources

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#3662]
Follow-up to #2401, #3616

Let's convert some `source` properties into **configs** that can be set inside `config:` blocks and within `dbt_project.yml`:

```yml
# models/src_whatever.yml
version: 2
sources:
  - name: my_source
    description: ... # not a config
    config:
      enabled: ...
      quoting: {dict}
      freshness: {dict}
      loader: ...
      loaded_at_field: ...
      database: ... # or 'project' in dbt-bigquery
      schema: ... # or 'dataset' in dbt-bigquery
      identifier: ... # this is like an alias for alias
      meta: {dict}
      tags: ...
    tables:
      - name: my_src_table
        config: # all the same stuff as above. these take precedence for specific tables
        description: ... # not a config
        tests: ... # not a config
        columns: ... # not a config
```

```yml
# dbt_project.yml
sources:
  project_name:
    subdirectory:
      +database: raw
      +loader: fivetran
      another_subdirectory:
        +enabled: false
```

For backwards compatibility, we should still support setting these as top-level properties:
```yml
sources:
  - name: my_source
    loaded_at_field: updated_at
```

But raise an error if the same config is set in both places (even if it's with the same value):
```yml
sources:
  - name: my_source
    loaded_at_field: updated_at
    config:
      loaded_at_field: updated_at
```

### Notes

- We're thinking that descriptions shouldn't be configs. They're rendered with a different context (docs), and they don't make sense to set hierarchically. The same goes for `tests` and `columns`—this would be quite tricky to figure out, since `tests` actually generate _new_ nodes, rather than adding properties to the existing node.

- As far as the manifest / `graph.sources` context, I'm open to suggestions. For backwards compatibility, we'd want to store things like `loaded_at_field` in both `node.config` _and_ node-level keys. But I think there's a valid argument for removing this as a top-level key and only storing it in `node.config`, so long as we communicate clearly that such a move is taking place.

- For better `state:modified` comparisons, we'd want to store the un-rendered version of these configs in `node.unrendered_config`, regardless of whether they're set in `dbt_project.yml` or `models/src_whatever.yml`. Original issue for this is https://github.com/dbt-labs/dbt/issues/2744.

**Comment by alexrosenfeld10** [comment]
This is great! Just commenting here to show my support of this feature.

**Comment by leahwicz** [comment]
Minimal config for sources so needs to be expanded. No SQL for them. Only defined in YAML

Complications:
Can override sources in other projects.
Where are the configs are? Source level?
Lots of testing will be involved (matrix of scenarios)

**Comment by jtcohen6** [comment]
Context:
- We already support _one_ configuration for sources, the `enabled` config in `dbt_project.yml`
- Sources support `override`, which allows users to redefine a source, with new properties, that take precedence over the same properties for the source with the same name defined in a package.

In summary, the goal of this issue:
- Make it possible to define source properties in `dbt_project.yml`.
- Make it possible to enable/disable a source table within its `.yml` file definition

**Main exit criteria:**
- Sources and source tables, defined in `.yml` files, accept a new property, `config:`
- That `config` property accepts `enabled: true|false`, which has the effect of enabling or disabling the source
- It's also possible to define existing properties within that `config` property, i.e. as configs as instead. These configs can be defined at the project, source, and source-table level—and they are inherited/overridden in that order of specificity.
- All source configs that currently exist as node-level attributes, are copied over to those node-level attributes in `manifest.json`. This offers backwards compatibility for metadata use cases (such as `dbt-docs`) that depend on accessing those attributes at the top-level. If users want fine-grained control over config resolution, they should define these as configs.

---

Totally fair question around how to handle a source `override`; this might be out of scope for the initial effort. I think configurations should be resolved first, and then `override` second, but that's not a strongly held view—as long as we can document consistent behavior. To make this concrete:
```yml
# dbt_project.yml
sources:
  my_package:
    my_src_name:
      +database: db_one
```
```yml
sources:
  - name: my_src_name
    overrides: my_package
    database: db_two
```
I would expect both configurations to be resolved, _then_ the override applied, such that `my_src_name` ends up pointing to `db_two`.
