### ISSUE TITLE
Support `config:` in `dbt_project.yml`, in loco +

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#3663]
Users find [the `+` prefix](https://docs.getdbt.com/reference/resource-configs/plus-prefix) very confusing. Its significance is unclear, it looks more special than it is, and many configs work equally well with and without it:
```yml
# dbt_project.yml
models:
  +materialized: view    # works
  installed_package:
    materialized: table  # also works
```

I don't want to _get rid of_ the `+` prefix, since it's prevalent in our docs and across. Everything above should keep working. Instead, I'd like to make this the documented standard:
```yml
# dbt_project.yml
models:
  config:
    materialized: view
  installed_package:
    config:
      materialized: table
```

That would establish real consistency between `dbt_project.yml` and the syntax proposed in #2401 / added in #3616:
```yml
# models/whatever.yml
models:
  - name: my_model
    config:
      materialized: view
```

### Questions
- Since `config` is a dictionary, do we need it to be `+config`?
- What if someone has a subdirectory or project named `config`? I'm willing to say... pick a different name.
