### ISSUE TITLE
Run all state:modified models up until the first occurrence of a table

### ISSUE THREAD

**Issue by danieldiamond** [dbt-labs/dbt-core#3670]
### Describe the feature
Some type of _circuit breaker_ within the node selection framework to run all models up until the first occurrence of something
e.g. If I have the following DAG configuration and I modify `view_2`
```
view_1 --> view_2* --> table_1 --> view_3 --> table_2
```
I would like to be able to run `dbt run -m state:modified+1st_occurrence_of_a_table` such that dbt builds `view_2` and `table_1`

### Describe alternatives you've considered
Attempting all types of wild selections, this is the closest that seems to accomplish the job
```
dbt run -m state:modified+,config:materialized:view+1
```
Unfortunately, this is _almost_ perfect, as when considering the above DAG framework, `view_3` gets included in this selection.

### Additional context
No additional context. Simply looking for some advanced `selector` capabilities/suggestions here.

### Who will this benefit?
I feel like _everyone_ would significantly benefit from this. If you have a lineage of views and want to run state:modified, typically you have to include any downstream tables i.e. `dbt run -m state:modified+`. With complex DAG frameworks, this would significantly reduce run time.

### Are you interested in contributing this feature?
Sure, if I can get an onboarding into the relevant code, I'm happy to contribute

**Comment by jtcohen6** [comment]
@danieldiamond This is a fun one! It's the first time I've heard a request for a selection "circuit breaker," but I think I follow what you mean: If the only modifications are to views, the first downstream table might be the only thing you really need to run to verify that the upstream changes are non-breaking, depending on the database you're using (e.g. Snowflake, late-binding views on Redshift).

Of course, it's possible that the table succeeds in running, but logic changes in the upstream view still cause far-downstream tests to fail. So I'm not convinced that this is a best practice we want to start recommending: CI is better safe than too-slim & sorry. All the same, I'm interested insofar as this may be a gap in the expressiveness of our node selection syntax.

After some time turning this over, I think the essential missing piece is the ability to select "tables that are not themselves the children of tables." Bearing in mind that [yaml selectors](https://docs.getdbt.com/reference/node-selection/yaml-selectors) offer more powerful and expressive set logic than CLI syntax, especially for in-group exclusion, I was playing around with:
```yml
selectors:
  - name: modified_views_only
    description: "All modified views and their children, up to and including the first table"
    definition:
      union:
        # all modified views, excluding tables and their children
        - intersection:
            - method: state
              value: modified
              children: true
            - method: config.materialized
              value: view
              children: true
            - exclude:
                - method: config.materialized
                  value: table
                  children: true
        # any model, regardless of materialization, that is the first-order child of a modified view
        - intersection:
            - method: state
              value: modified
              children: true
            - method: config.materialized
              value: view
              children: true
              children_depth: 1
```
This works for your example above—it includes `table_1`, excludes `view_3` + `table_2`—but it doesn't work for all cases. E.g. if `view_1` were to be modified, it would include `view_2` but fail to include `table_1`, since that isn't the first-order child of a modified view.

I think what we really want is some way to exclude all children of tables, without excluding all tables:
```yml
    definition:
      intersection:
        - method: state
          value: modified
          children: true
        - method: config.materialized
          value: view
          children: true
        - exclude:
            - method: config.materialized
              value: table
              children: true
              # exclude anything with a table ancestor, except for the progenitor table itself
              # how could we express that? some (bad) ideas:
              children_only: true
              include_self: false
```

If someone is able to give this a bit more thought, I'd love to hear what I'm missing :)

Otherwise, this issue feels less related to `state` and more to `selection`—a tag we don't yet have, and one which I can surely create.
