### ISSUE TITLE
Number and size of log files can be set by configuration parameters

### ISSUE THREAD

**Issue by gyandor** [dbt-labs/dbt-core#3795]
### Describe the feature
I would like to have configuration options to control the number and size of log files instead of having maximum 6 files 10MB each.

### Describe alternatives you've considered
Periodic backup of current files to a different folder.

### Who will this benefit?
We work with tons of models and log for 1 run exceeds 60 MB. If something goes wrong, we don't have the full log for investigation.

**Comment by sungchun12** [comment]
@gyandor if you don't want to open a pull request for this, is it okay if I do?

**Comment by gyandor** [comment]
@sungchun12 It's okay. Thank you in advance.

**Comment by sungchun12** [comment]
Approach Notes: 
- Validate the variables used to assign `max_size` and `backup_count` are integers, raise a specific error that the value must be an integer
- Create new `__init__` variables for the logger `DelayedFileHandler` class https://github.com/dbt-labs/dbt/blob/9e796671dd55d4781284d36c035d1db19641cd80/core/dbt/logger.py#L386
- Set default arguments in the above class for `max_size` and `backup_count`
- Add profile configs to the specific section below
```yaml
config:
  partial_parse: <true | false>
  use_colors: <true | false>
  printer_width: <integer>
  send_anonymous_usage_stats: <true | false>
  dbt_logger_max_size: <integer> # in megabyte increments only, the logic will handle the multiplication behind the scenes
  dbt_logger_backup_count: <integer>
```
- Need to create priority conditions for: CLI flag > env var > profile config. I may be able to piggyback off existing logic.
- Use `BAR = os.environ.get('BAR') # None` to prevent key errors

**Open Questions**
- Should I put a max limit on `max_size` and `backup_count`?
- Do I add to an existing test or build a new one?
