### ISSUE TITLE
PostgreSQL index configs are not merged

### ISSUE THREAD

**Issue by moltar** [dbt-labs/dbt-core#3816]
### Describe the bug

I have a model level config (`*.sql`):

```
{{
  config(
    indexes=[
      { 'type': 'hash', 'columns': ['foo'] },
    ]
  )
}}
```

And a `dbt_project.yml` config:

```yml
models:
  prj:
    staging:
      +materialized: table
      +indexes:
        - columns: ['bar']
          type: hash
        - columns: ['baz']
          type: hash
```

The `foo` index is created, but `bar` and `baz` are not.

If I remove the inline config for `foo`, the `dbt_project.yml` config creates `bar` and `baz`.

### Steps To Reproduce

See above code samples.

### Expected behavior

Index definitions to be merged, and all 3 indexes created.

### Screenshots and log output

N/A

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
❯ dbt --version
installed version: 0.20.1
   latest version: 0.20.1

Up to date!

Plugins:
  - bigquery: 0.20.1
  - snowflake: 0.20.1
  - redshift: 0.20.1
  - postgres: 0.20.1
```

**The operating system you're using:**

macOS

**The output of `python --version`:**

```
Python 3.9.6
```

### Additional context

https://docs.getdbt.com/reference/resource-configs/postgres-configs#indexes
