### ISSUE TITLE
docs generate no longer works with dummy profile

### ISSUE THREAD

**Issue by franciscojavierarceo** [dbt-labs/dbt-core#3947]
### Describe the bug
Previously I was able to generate dbt docs using a dummy profile, now I am receiving an error from Snowflake suggesting a password is empty.

### Steps To Reproduce
my profiles.yml file:

```
name: 'snowflake'
profile: 'snowflake'
fast-snowflake-db:
  target: myschema
  outputs:
    dev:
      type: SNOWFLAKE
      account: FAKEACCOUNTID
      user: FAKE_USER
      role: FAKE_ROLE 
      database: FAKE_DATABASE 
      warehouse: FAKE_WAREHOUSE
      schema: FAKE_SCHEMA
      threads: 1
      client_session_keep_alive: False
      query_tag: FAKE-TAG
```

### Expected behavior

Successfully generate docs using:

```
dbt docs generate --profiles-dir ./profiles.yml
```

Previously running the code above used to successfully generate docs. Now I receive the error below: 
```
Running with dbt=0.19.1
Found X models, X tests, X snapshot, X analyses, X macros, X operations, X seed files, X sources, X exposures

ERROR: Database Error
  251006: Password is empty
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.20.2

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.19.1
  - snowflake: 0.19.1
  - redshift: 0.19.1
  - postgres: 0.19.1
```

**The operating system you're using:**
Mac

**The output of `python --version`:**
```
Python 2.7.16
```

**Comment by jtcohen6** [comment]
@franciscojavierarceo In what version of dbt was this previously working? The `docs generate` command does run metadata queries against the database, in order to generate `catalog.json`, so it isn't surprising to hear that it raises an authentication error when you try to connect with phony credentials.

I'd also be curious to hear more about your use case for generating docs without a real database connection.If it's just an ability to visualize your project's DAG lineage, I think there may be workarounds—but as a primary feature of `docs generate`, I'm not sure this is something we need to support.

**Comment by franciscojavierarceo** [comment]
@jtcohen6 currently I'm structuring a github action to generate the lineage and docs. For security reasons, we don't want to  require a live connection.

**Comment by jtcohen6** [comment]
@franciscojavierarceo Would it be possible to include `docs generate` as a step in your production deployments, and upload the artifacts from that deployment into external storage? Then, the job of your GitHub action can simply be to grab `manifest.json`, `catalog.json`, and `index.html` from that storage, and serve them at a stable URL.

That's the [recommended workflow](https://docs.getdbt.com/docs/building-a-dbt-project/documentation#deploying-the-documentation-site): separate steps for _generating documentation_ and _deploying documentation_. The former should happen in your dbt deployment, where you're comfortable connecting to the database. The latter should be able to access artifacts from the former, in lieu of its own live database connection.

**Comment by chlirre** [comment]
I'm in the middle of setting up a "github action to generate the lineage and docs" myself.
I'm surprised to find that it requires a _profile_ (connection).

I am currently using dbt Cloud to `run` (deploy) my configuration. And that doesn't allow for much control over what happens with the documentation.

I'm basically looking for a place to point people in my org where they can find the descriptions of my models without having to request (read-only) access to dbt Cloud.

**Comment by atbee** [comment]
I also don't want to connect to the actual database for security concerns. Currently, the simplest connection for generating **docs** I use is [dbt-duckdb](https://github.com/jwills/dbt-duckdb).

Here's a sample target in the `profiles.yml` file.

```yaml
sample_project:
  outputs:
    docs:
      path: /tmp/dbt.duckdb
      type: duckdb
  target: docs

```
