### ISSUE TITLE
Snapshot config doesn't work in schema.yml

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#4000]
Validation is performed on SnapshotConfig objects when the snapshot node is parsed/created. This validation means that config must be set in the sql file and can't be set in the schema file.

To allow setting in schema files we would need to defer validation until after schema file parsing.

**Comment by jtcohen6** [comment]
@gshank Ah! I now remember noticing this at one point, too. Thanks for keeping track of it and opening the issue.

The validation currently occurs within the [`validate` method of `SnapshotConfig`](https://github.com/dbt-labs/dbt/blob/3789acc5a7b3f71b4e333ac6e235c62ee0c957f5/core/dbt/contracts/graph/model_config.py#L509), and I'm guessing that occurs before patching. Do you have a sense of where we could move the validation so that it happens post-patching?

**Comment by gshank** [comment]
It would have to happen as a post-schema-file parsing step, at about the same place in the manifest parser where we handle updating docs and refs.

**Comment by jtcohen6** [comment]
Reopening this one as it's still relevant. Possibly related to the work Emily was just doing around models set to `enabled: false` in config `.yml` files (https://github.com/dbt-labs/dbt-core/issues/5869)

**Comment by jtcohen6** [comment]
Workaround that functions, but doesn't feel great:
```yml
# dbt_project.yml
snapshots:
  # set defaults here to avoid validation errors during first parse
  strategy: check_cols
  unique_key: id
  target_schema: "{{ target.schema }}"
```
Then all snapshots will have the default values set when first parsed, allowing me to set snapshot-specific properties in other `.yml` files instead.
```sql
-- snapshots/my_snap.sql
{% snapshot my_snapshot() %}

    select
        1 as specific_id,
        current_timestamp as updated_at
        
{% endsnapshot %}
```
```yml
# snapshots/config.yml
version: 2
snapshots:
  - name: my_snapshot
    config:
      target_schema: specific_schema
      unique_key: specific_id
      strategy: timestamp
      updated_at: updated_at
```
