### ISSUE TITLE
dbt cannot create two resources with identical database representations with --store-failures

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [dbt-labs/dbt-core#4042]
### Describe the bug

I'm executing `dbt test` with `--store-failures` and I'm seeing the following:
```
Running with dbt=0.20.2
Encountered an error:
Compilation Error
  dbt found two resources with the database representation ""stg"."dbt_test__audit"."states_state_id"".
  dbt cannot create two resources with identical database representations. To fix this,
  change the configuration of one of these resources:
  - test.dwh.dbt_utils_at_least_one_core__states_state_id.f79036c904 (models/l4_core/model_info/info_core__states.yml)
  - test.dwh.not_null_core__states_state_id.1d4ba1b947 (models/l4_core/model_info/info_core__states.yml)
```

### Steps To Reproduce

The model (info_core__states.yml from above) looks like
```
---
version: 2

models:
  - name: core__states
    description: Reference table for state descriptions
    columns:
      - name: state_id
        description: TODO
        tests:
          - dbt_utils.at_least_one
          - not_null
          - unique
      - name: abbreviation
        description: TODO
      - name: name
        description: TODO
```

When I remove the test `dbt_utils.at_least_one` I get
```
Running with dbt=0.20.2
Encountered an error:
Compilation Error
  dbt found two resources with the database representation ""stg"."dbt_test__audit"."states_state_id"".
  dbt cannot create two resources with identical database representations. To fix this,
  change the configuration of one of these resources:
  - test.dwh.not_null_core__states_state_id.1d4ba1b947 (models/l4_core/model_info/info_core__states.yml)
  - test.dwh.unique_core__states_state_id.0172f0c31b (models/l4_core/model_info/info_core__states.yml)
```

When I remove yet another test (`not_null` in this case) I find issues with _another_ model:
```
Running with dbt=0.20.2
Encountered an error:
Compilation Error
  dbt found two resources with the database representation ""stg"."dbt_test__audit"."users_user_id"".
  dbt cannot create two resources with identical database representations. To fix this,
  change the configuration of one of these resources:
  - test.dwh.dbt_utils_at_least_one_core__users_user_id.6d46e6a661 (models/l4_core/model_info/info_core__users.yml)
  - test.dwh.not_null_core__users_user_id.f93f821f1a (models/l4_core/model_info/info_core__users.yml)
```

### Expected behavior
For test results to properly get stored.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.2
   latest version: 0.21.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.20.2
  - snowflake: 0.20.2
  - redshift: 0.20.2
  - postgres: 0.20.2
```

**The operating system you're using:**
maxOS Big Sur

**The output of `python --version`:**
```
Python 3.9.7
```
