### ISSUE TITLE
Selection method based on source freshness: new `max_loaded_at`, new data

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#4050]
See also: https://github.com/dbt-labs/dbt/issues/2465#issuecomment-763776415,  https://github.com/dbt-labs/dbt/issues/2743#issuecomment-841230958, https://github.com/dbt-labs/dbt/issues/3804#issuecomment-921115079, https://github.com/dbt-labs/dbt/issues/3862#issuecomment-916828824, [Benn's tweet](https://twitter.com/bennstancil/status/1433959272891785216)

Use the `sources.json` artifact to determine which sources have new data since the last dbt build.

Imagine:
```
$ dbt source freshness
$ dbt build -s sources:fresh+ --state my/previous/run/artifacts
```

This would require handling _multiple_ `sources.json`:
- the version from the last run in the `--state` directory
- the one from just now in the `target/` directory

Then, dbt would compare the high watermarks recorded in each, and select all source tables with a greater/changed `max_loaded_at`.

### Questions

- Should we reconsider the inclusion of the `freshness` task within `dbt build`? I think it would be _tricky_ to check source freshness _and_ perform dynamic selection _and_ build those now-selected resources, all in one invocation. It would require blurring lines that are pretty well delineated today (selection &rarr; execution &rarr; artifacts).
- Should we reconsider the consolidation of `sources.json` into `run_results.json`? It seems like the separation would actually be a plus, for the sake of this feature, but I'm sure we could manage either way
- Would it be better to perform this comparison _outside_ dbt-core (e.g. dbt Cloud metadata API), and then simply pass the set of sources that have new data? If we know that `source:stripe` and `source:salesforce.account` have new data, it's easy enough to then define a job with `dbt build -s source:stripe+ source:salesforce.account+`.

### Big idea

Coupled with `state:modified` and `result:<status>` (https://github.com/dbt-labs/dbt/pull/4017), you could dynamically select the part of your DAG that's relevant by comparing the current state of your sources/project and the artifacts from your last run.

```yml
selectors:
  - name: one_selector_to_rule_them_all
    default: true
    description: Select sub-DAG based on new source data, changed logic, &/or failure in last run
    definition:
      union:
      
        # check freshness + test all sources
        - 'source:*'
      
        # new source data + table/incremental
        - intersection:
            - union:
                - 'config.materialized:table'
                - 'config.materialized:incremental'
            - method: source
              value: fresh  # imagine
              children: true
      
        # changed logic (need this for views + MVs too)
        - method: state
          value: modified
          children: true

        # failed last time
        - union:
            - 'result:error'
            - 'result:skipped'
```
```
$ export DBT_ARTIFACT_STATE_PATH=my/previous/run/artifacts
$ dbt source freshness
$ dbt build
```

Schedule that to run every 5 minutes, set up solid slack notifications on failures, and put on a good album.

While this is very cool, it does take its cue from the source data loaders—whenever they've ingested new rows, we're going to build downstream tables. This is the inverse of defining freshness / latency expectations for specific "final" models, and using that as the primary input to deployment/scheduling. That still seems like a cool and important thing to do... perhaps via `exposures`??
