### ISSUE TITLE
[Feature] dbt should know about `Attributes` (foundation for Metrics/Dimensions)

### ISSUE THREAD

**Issue by aaronsteers** [dbt-labs/dbt-core#4090]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Following from https://github.com/dbt-labs/dbt-core/issues/4071, I called out in my comment that I believe metrics would be better established on top of "attributes" instead of building directly on "columns" and "models" abstractions in dbt.

As a foundation for deeper metadata understandings within dbt and to unify the documentation effort for existing dbt projects, we should first establish some type of ontological definition of what columns "mean", as they relate to an analytical framing.

## Proposal

1. **We add top-level configurability for "attributes" within dbt core.**
    1. An attribute maps to one or more columns in one or more tables (models), and it defines the nature of the column in an ontological manner.
    2. An attribute may have an "attribute type", such as `dimension_key`, `dimension_property`, `fact`, etc.
    3. An attribute definition can define how a table interacts with the time dimension, which is needed for certain metric-related applications. (For instance, if a table has an attribute `as_of_date` marked as the primary temporal attribute for the table, this will inform how metrics calculations can be performed - and at what grain they are possible.)
    4. An attribute may have a text description, which will appear in the docs on any tables (models) where it is referenced.
    5. Attributes may take part in an attribute hierarchy (day->month->year, city->state->country, etc.)
    6. Users may use dbt docs (or other tools) to find references to tables. (I want to see all the tables that contain the "sales_revenue" attribute.)
2. We provide easy ways to auto-map attributes to columns. For instance, for an attribute called  `sales_revenue`, we could set an `auto_map_by_name: true` property to find and map all references of the column `sales_revenue`, or we could explicitly map to models and column references.

## Benefits

1. Over time, best practices will emerge related to column namings to reduce the work needed for attribute mapping, which in turn improves the readability of the project overall. (For instance, this discourages "sales_region" on one table to have an integer ID and "sales_region" on another table to contain the string with the name of the region.)
1. We can build metrics (#4071) more easily on top of attributes. For example, "customers per region" can be more easily defined once "customer_id", "number of customers", "region_id", and "number of regions" are already known and clearly defined attributes.

## Sample Code

Adapted from [my comment](https://github.com/dbt-labs/dbt-core/issues/4071#issuecomment-944698753) on the related metrics topic.

```yml
attributes:
- name: customer_id
  label: Customer ID
  attribute_type: dimension_key
  column_names:
  - customer_id
  models:
  # as much or as little constraint to get ontologically the right column mappings
  - marts.*
  - !marts.the_weird_one
- name: customer_count
  label: Customer Count
  description: A pre-aggregated count of customers.
  attribute_type: entity_count
  column_names:
  - customer_id
  models:
  # everywhere we see this column in the `marts` folder, map it to this attribute
  - marts.*
- name: country
  label: Country Name
  attribute_type: dimension_key
  models:
  # everywhere we see this column in the `marts` folder, map it to this attribute
  - marts.*
  column_names:
  - country
  - country_name
- name: sales_revenue
  label: Sales Revenue
  attribute_type: amount
  column_names:
  - sales_revenue
  models:
  - marts.*
```

### Describe alternatives you've considered

Metrics: The alternatives for metrics is to create mappings directly over all tables and columns. The greater the number of tables of different aggregation levels, and/or projections for query optimization, the larger the redundancy of those metrics mappings will be.

Documentation: This is actually stemming from another inquiry I ran into a couple years ago: how to document all columns in all models, without having to put the same text description on every single instance. (And then, how to keep them up to date as you want to update how "sales revenue" is calculated on all of them.) As far as I'm aware, there isn't yet a good solution for this documentation problem, and so my general guidance has been "don't worry about descriptions on columns" - because it's just too much work and no single-source-of-truth to keep them in sync across tables.

Adding attributes would hopefully change that, since the many places the column exists, it will always carry (or link to) the same text description for users of the project.

### Who will this benefit?

This would benefit teams who want column-level descriptions for themselves and their users.

This benefits users, because they can better documentation on columns, and better understand equivalency (or lack thereof) of similarly named column across a project.

### Are you interested in contributing this feature?

Sure!

## Prior art

Inspired by OLAP platforms and BI layers which support ROLAP capabilities:

- MicroStrategy (called "facts" there)
- Mondrian ("attributes" / "dimensions")
- SSAS ("attributes" / "properties" / "dimensions")
