### ISSUE TITLE
[Feature] Allow multiple `unique` tests for the same column

### ISSUE THREAD

**Issue by ilmari-aalto** [dbt-labs/dbt-core#4102]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Enable more than one `unique` test for the same column.

I think there are usecases where you'd like to have several `unique` tests. For example, here's an example related to MRR. In this example, there can only be one conversion record per account, and separately, just one current record per account:
```yaml
      - name: account_id
        tests:
          # There should be just one is_new_biz record per account
          - unique:
              where: "is_new_biz"
          # There should be just one is_current record per account
          - unique:
              where: "is_current"
```

### Describe alternatives you've considered

* In some cases several tests could be combined using multiple conditions in `where`
* Writing a singular test would always work, but it's disconnected from the rest of the model configuration, and an extra effort
* Also `dbt_utils.unique_combination_of_columns` could work but the intention of that test would be less clear

### Who will this benefit?

Enabling more than one `unique` test per column would allow users combine existing tests in novel ways - users would have added flexibility with the same building blocks. A beginner dbt user will not even need to know of the possibility so it wouldn't need to confuse them.

### Anything else?

From the technical point of view, multiple `unique` tests are currently not possible because config is not part of the test name, and all tests get the same name. Perhaps a test order number (1, 2, ..), hash, or test config could be added to the test name to work past this. (Perhaps extended test naming would only kick in when more than one test of the same type exists for the same column.)

More discussion and examples in this [Slack thread](https://getdbt.slack.com/archives/C016X6ABVUK/p1634151813050300).

**Comment by judahrand** [comment]
This is a rather annoying behaviour for us. We've just upgraded to 1.0 from 0.19 and had assumed that with the addition of the Test Config we'd be able to get rid of our custom recency test. However, due to this behaviour we cannot. Our use case looks like this:

```yaml
- recency:
    datepart: day
    field: date
    interval: 2
    where: "connection_type_code = 'tiktok'"
- recency:
    datepart: day
    field: date
    interval: 2
    where: "connection_type_code = 'twitter'"
- recency:
    datepart: day
    field: date
    interval: 2
    where: "connection_type_code = 'awin'"
- recency:
    datepart: day
    field: date
    interval: 2
    where: "connection_type_code = 'reddit'"
- recency:
    datepart: day
    field: date
    interval: 2
    where: "connection_type_code = 'pinterest'"
```

The reason for defining the tests separately is to make it clear where the failure is coming from. For this case it seems pretty clear (to me at least) that these are different tests but they all collide due to not including the the config (or just the where clause) in the name. It would also be unhelpful to include the where in the hash but not in the name.

We are currently using the workaround of a a custom test with `condition` as an argument instead of `where` (this actually used to be `where` but that obviously broke when the test configs came in and everything started colliding!) but this seems like a silly required workaround.

**Comment by jtcohen6** [comment]
@judahrand Appreciate the comment!

Rather than hoping to perfect the logic for auto-generating test names (a losing proposition), we think the longer-term fix might look like what's proposed in https://github.com/dbt-labs/dbt-core/issues/3348#issuecomment-1031840405 and attempted in https://github.com/dbt-labs/dbt-core/pull/4898. Namely:

```yml
- recency:
    name: tiktok_recent_within_2_days
    datepart: day
    field: date
    interval: 2
    where: "connection_type_code = 'tiktok'"
- recency:
    name: twitter_recent_within_2_days
    datepart: day
    field: date
    interval: 2
    where: "connection_type_code = 'twitter'"
- recency:
    name: awin_recent_within_2_days
    datepart: day
    field: date
    interval: 2
    where: "connection_type_code = 'awin'"
- recency:
    name: reddit_recent_within_2_days
    datepart: day
    field: date
    interval: 2
    where: "connection_type_code = 'reddit'"
- recency:
    name: pinterest_recent_within_2_days
    datepart: day
    field: date
    interval: 2
    where: "connection_type_code = 'pinterest'"
```
What do you think of that?
