### ISSUE TITLE
[FEATURE] Set all macro namespace by default to `['<name_of_your_root_project>', '<macro_namespace>']`

### ISSUE THREAD

**Issue by JCZuurmond** [dbt-labs/dbt-core#4106]
As suggested by @jtcohen6 in [comment](https://github.com/dbt-labs/dbt-core/issues/4098#issuecomment-947678409), change this https://github.com/dbt-labs/dbt-core/blob/280e9ad9c9bf914b5bbd1aa14629a6708c921546/core/dbt/context/providers.py#L146-L147

to:

``` python
            if not search_packages and namespace in self._adapter.config.dependencies:
                search_packages = [self.config.project_name, namespace]
```

With this change, by default we prefer macro overwrites for packages (like `spark__create_table_as`) defined in the root project over the ones defined in the package. The user can change the preference behavior by defining the search order explicitly:

``` yml
# dbt_project.yml
dispatch:
  - macro_namespace: dbt
    search_order: ['<package name>, '<root project name>']
```

In the old behavior the macros for packages in the root folder are not preferred over the ones in the packages, needing the user to explicitly set the search order to:

``` yml
# dbt_project.yml
dispatch:
  - macro_namespace: dbt
    search_order: ['<root project name', '<package name>]
```

We think that the proposed change is a more sensible default.
