### ISSUE TITLE
[Bug] Prerelease versions of packages appear to be unavailable to dbt deps (again)

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

#3578 appears to have regressed as of dbt 1.0.0-b2. 

### Expected Behavior

Being able to install prerelease versions of dbt packages

### Steps To Reproduce

With this packages.yml:

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.4-b1
```
run `dbt deps`

output: 
```
Running with dbt=1.0.0-b2
* Deprecation Warning: The `source-paths` config has been deprecated in favor of
`model-paths`. Please update your `dbt_project.yml` configuration to reflect
this change.
Encountered an error:
Could not find a matching version for package dbt-labs/dbt_utils
  Requested range: =0.7.4-b1, =0.7.4-b1
  Available versions: ['0.0.1', '0.1.0', '0.1.1', '0.1.2', '0.1.3', '0.1.4', '0.1.5', '0.1.6', '0.1.7', '0.1.8', '0.1.9', '0.1.10', '0.1.11', '0.1.12', '0.1.13', '0.1.14', '0.1.15', '0.1.16', '0.1.17', '0.1.18', '0.1.19', '0.1.20', '0.1.21', '0.1.22', '0.1.23', '0.1.24', '0.1.25', '0.2.0', '0.2.1', '0.2.2', '0.2.3', '0.2.4', '0.2.5', '0.3.0', '0.4.0', '0.4.1', '0.5.0', '0.5.1', '0.6.0', '0.6.1', '0.6.2', '0.6.3', '0.6.4', '0.6.5', '0.6.6', '0.7.0', '0.7.1', '0.7.2', '0.7.3']
```

dbt-utils was [only bumped a couple of minutes ago](https://github.com/dbt-labs/hub.getdbt.com/commit/05fe781db5f0e2cf09abefc3874b936407ff0019) so I thought I should try with the version of dbtvault that caused #3578 as well in case it's just a caching thing. 

```yml
packages:
  # - package: dbt-labs/dbt_utils
  #   version: 0.7.4-b1

  - package: Datavault-UK/dbtvault
    version: 0.7.6-b1
```

`dbt deps`

```
Running with dbt=1.0.0-b2
* Deprecation Warning: The `source-paths` config has been deprecated in favor of
`model-paths`. Please update your `dbt_project.yml` configuration to reflect
this change.
Encountered an error:
Could not find a matching version for package Datavault-UK/dbtvault
  Requested range: =0.7.6-b1, =0.7.6-b1
  Available versions: ['0.4.1', '0.6.1', '0.6.2', '0.7.0', '0.7.1', '0.7.2', '0.7.3', '0.7.4', '0.7.5', '0.7.6', '0.7.7', '0.7.8']
```

### Environment

```markdown
- OS: macOS 11.6
- Python: Python 3.8.10
- dbt:

installed version: 1.0.0-b2
   latest version: 0.21.0

Your version of dbt is ahead of the latest release!

Plugins:
  - snowflake: 1.0.0b2
  - postgres: 1.0.0b2
```

### What database are you using dbt with?

snowflake

**Comment by joellabes** [comment]
A potentially interesting fact: I originally had my package version as `0.7.4b1` and when I ran dbt deps with that, it still went looking for `0.7.4-b1` ("`Requested range: =0.7.4-b1, =0.7.4-b1`"). not sure why!

**Comment by jtcohen6** [comment]
@joellabes In v0.20.1, we introduced a new package property, `install-prerelease` (#3624, the fix for #3578).

This is working for me locally:
```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.4-b1  # also works as 0.7.4b1, no hyphen
    install-prerelease: true
```

Docs are here: https://docs.getdbt.com/docs/building-a-dbt-project/package-management#prerelease-versions

There are some fair questions coming out of this:
- If you explicitly specify your version as 0.7.4-b1, shouldn't that be enough to indicate that you want to install a prerelease version?
- Could we add support for a `dbt deps --pre` flag (like `pip --pre`) that turns on `install-prerelease: true` for all packages?
- How to specify prereleases for upstream dependencies, not explicitly specified in `packages.yml`?

Those all feel like legitimate enhancements for the future. For the time being, while the current version isn't perfect, I do think it's serviceable. For the third point in particular, if I depend on `dbt-external-tables` _and_ I want it to install a specific prerelease of `dbt-utils`, I'll just have to specify both:
```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.4b1
    install-prerelease: true
  - package: dbt-labs/dbt_external_tables
    version: 0.7.1
```
Given that package dependency trees tend to be 1-2 levels deep today, and the upstream packages are almost always `dbt_utils` or `fivetran_utils`, that doesn't feel unreasonable.
