### ISSUE TITLE
[Feature] Pass Materialization config to tests 

### ISSUE THREAD

**Issue by ismailsimsek** [dbt-labs/dbt-core#4228]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

i have following setting for a materialization, i like to remove repetitive `pk_cols`  and use `unique_key` to validate primary key(`validate_pk`).

but it seems config section is not passed to test? is there a way to access materialization config variables from test? i need to access `unique_key: ['my_table_id']` and use it in `validate_pk` test 

```
  - name: my_table
    config:
      unique_key: ['my_table_id']
      cluster_by: ['my_table_id']
    tests:
      - validate_pk:
          pk_cols: ["my_table_id"]
```

**Comment by jtcohen6** [comment]
@ismailsimsek Thanks for opening!

### larger ask

I agree, and I'd actually make the proposal much broader: We need _much_ better ways to tie a specific instance of a generic test back to the model/column it's defined on. Currently, the test compilation context just includes `{{ model }}` and `{{ column_name }}`, and really just for the purposes of templating out their string values.

This goes one step further than the proposal in #3256, which would have the test "inherit" the `unique_key` config of the model it's defined on (even if it does nothing with it). This proposal feels much clearer in its intended purpose.

I see a need to significantly rework the `model` context variable, available to the generic test macro context. The question is how to preserve current behavior for backwards compatibility. One approach may look like:
- When templated as a string, it returns `{{ get_where_subquery(model) }}` (current behavior)
- When used as a context variable in the template, it returns the full node specification for the parent model (as much as is then available), including access to `model.config`
- We should also seek to make this information available in the test materialization, to support %-based `warn_if` + `error_if` thresholds. That will be tricky insofar as `model` already means "this resource" in any materialization context (i.e. the _test_). For that reason, plus the fact that generic tests can be defined on non-models, we may want to rename `{{ model }}` to something much more general (`parent`). That should be fine so long as there's backwards compatibility for the current behavior of `{{ model }}`.

### workaround

There's a janky way to approximate today what I described above, by performing a [`graph`](https://docs.getdbt.com/reference/dbt-jinja-functions/graph)-based lookup:
```sql
{% test validate_pk(model) -%}
    
    {% if execute %}
      {% set parent_model = (graph.nodes.values() | selectattr('name', 'equalto', model.name) | list)[0] %}
      {% set unique_key = parent_model['config']['unique_key'] %}
    {% else %}
      {% set unique_key = '' %}
    {% endif %}
    
    select {{ unique_key }} from {{ model }}

{%- endtest %}
```

### specific use case

All of that being said—for the specific example you mention in your issue—this is totally possible today:
```yml
  - name: my_table
    config:
      unique_key: ['my_table_id']
      cluster_by: ['my_table_id']
    columns:
     - name: my_table_id
       tests:
          - validate_pk
```

I totally get the hesitation at the duplication that requires. A totally different approach to this problem could look like enabling columns to define configurations on behalf of their parent model, and expressing the same model this way:
```yml
  - name: my_table
    columns:
     - name: my_table_id
       config:
         unique_key: true
         cluster_by: true
       tests:
          - validate_pk
```

Then, the model's `unique_key` and `cluster_by` configurations could be synthesized out of its columns' configurations. That feels pretty compelling to me, too!
