### ISSUE TITLE
[Bug] Table-level freshness should inherit from schema-level freshness when schema-level is null and table-level is missing

### ISSUE THREAD

**Issue by jtalmi** [dbt-labs/dbt-core#4245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given the set of four sources seen below:

```
version: 2

sources:
  - name: my_src
    tables:
      - name: src_freshness_default
      - name: src_freshness_disabled
        freshness: null

  - name: my_src2
    freshness: null
    tables:
      - name: src_freshness_default
 
```

The resulting freshness will be:

**my_src.src_freshness_default**: `{'warn_after': None, 'error_after': None, 'filter': None}`
**my_src.src_freshness_disabled**: `None`
**my_src2.src_freshness_default**: `{'warn_after': None, 'error_after': None, 'filter': None}`
**my_src2.src_freshness_disabled**: `None`

my_src2.src_freshness_default does not inherit the `freshness: null`  property from the schema-level when freshness is missing.

### Expected Behavior

When table-level freshness is missing and schema-level freshness is set to `null`, table-level freshness should inherit from schema-level and be set to None instead of the default missing value of `{'warn_after': None, 'error_after': None, 'filter': None}`

### Steps To Reproduce

Using dbt == 0.21, create a .yml file using the above yml and run this as a run operation or analysis:

```
{% for source in graph.sources.values() %}

  schema: {{ source.schema }}
  name: {{ source.name }}
  freshness: {{ source.freshness }}

{% endfor %}
```

### Relevant log output

```shell
schema: my_src
  name: src_freshness_default
  freshness: {'warn_after': None, 'error_after': None, 'filter': None}

  schema: my_src
  name: src_freshness_disabled
  freshness: None

  schema: my_src2
  name: src_freshness_default
  freshness: {'warn_after': None, 'error_after': None, 'filter': None}

  schema: my_src2
  name: src_freshness_default
  freshness: None
```

### Environment

```markdown
- OS: Mac OS Big Sur
- Python: 3.8
- dbt: 0.21
```

### What database are you using dbt with?

snowflake

### Additional Context

https://getdbt.slack.com/archives/C50NEBJGG/p1634829239001900
