### ISSUE TITLE
[Feature] Author models and add ability to dbt ls --select author:<author>

### ISSUE THREAD

**Issue by TeddyCr** [dbt-labs/dbt-core#4251]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

One need that was recently brought up in our team was the ability to filter models by the person who created them. The idea would be add an `author` key (similar to the `tag` key) that can be defined either in the `project.yml` file or the model itself.

With this key available we would want to be able to use it in `--select` or the `selector.yml` file to filter only on models authored by a specific person.

This information could also be used in the dbt documentation to more accurately populate the owner information.

Example

```
dbt_project.yml 
[...]
models:
    dim:
      tags: [stuart_dimensional_layer]
      my_model:
        tags: [modeled]
        authors: [author_1, author_2]
[....]
```

```
model.sql
{{
    config(
        authors=[author_1, author_2]
    )
}}
[....]
```

```
dbt ls --resource-type model --select authors:author_1
```

```
selectors.yml

selectors:
  - name: nodes_to_joy
    definition: ...
  - name: nodes_to_a_grecian_urn
    description: Attic shape with a fair attitude
    author: author_1
    default: true
    definition: ...
```

### Describe alternatives you've considered

- Passing the author in the tag

### Who will this benefit?

- teams maintaining dbt project

### Are you interested in contributing this feature?

yes

**Comment by jtcohen6** [comment]
@TeddyCr Thanks for the issue!

I think there's a lot of merit in assigning "authors" or "owners" to different resources in a dbt project. We require an `owner` for exposures. It also seems like a great idea for tests (#3436), as a way to selectively notify just the right team or person when a test fails.

For what you're requesting, however, I think `tags` and `meta` get the job done! Both will show up in the auto-generated documentation for the model. Tags have always supported node selection; starting in v0.21, `meta` is now a config, meaning that it can qualify for [the `config:` selection method](https://docs.getdbt.com/reference/node-selection/methods#the-config-method).

Assuming you have:
```yml
# models/whatever.yml
version: 2
models:
  - name: my_model
    config:
      meta:
        author: jerco
      tags: "author=jerco"
```
(which could also be defined in the model's SQL file via `config()`, or in `dbt_project.yml` under the `models` block)

Then you can select this model using either:
```
$ dbt ls -s tag:"author=jerco"
$ dbt ls -s config.meta.author:jerco
```

This works for `meta` key-value pairs nested arbitrarily deep in the `meta` config:
```yml
      meta:
        author:
          name:
            first: jeremy
```
```
$ dbt ls -s config.meta.author.name.first:jeremy
```

I'm going to close this issue, as I believe it's already possible. That said, I do think it would be a good idea to document that `config:` can be used for `meta:` in this manner, and perhaps add an integration test case to make sure this behavior doesn't regress in the future. If you'd be interested in helping out with those, I'd welcome PRs for them.
