### ISSUE TITLE
[Bug] `metrics.filters.value` doesn't accept any type other than string

### ISSUE THREAD

**Issue by buremba** [dbt-labs/dbt-core#4309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the column is a numeric/boolean value we need to define the filters as follows:

```
metrics:
  - name: new_customers
    label: New Customers
    model: ref('customer')
    description: "The number of paid customers who are using the product"
    type: count
    sql: c_custkey
    filters:
      - field: is_paying
        operator: "="
        value: "true"
```

### Expected Behavior

It's ideal to use the appropriate types as follows:

```
metrics:
  - name: new_customers
    label: New Customers
    model: ref('customer')
    description: "The number of paid customers who are using the product"
    type: count
    sql: c_custkey
    filters:
      - field: is_paying
        operator: "="
        value: true
```

I believe that the `filters.value` should not enforce a type as we don't have strict `operator` values. The schema of value should be `any`.

### Relevant log output

```shell
If we pass boolean / numeric value to `metrics.filters.value`, dbt complains about the type.
```

### Environment

```markdown
- OS: MacOS
- Python: 3.9.7
- dbt: 1.0.0-rc1
```
