### ISSUE TITLE
`sql` and `type` fields on metrics are ambiguously named

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4325]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

In this metric definition: 
```
metrics:
  - name: new_customers
    label: New Customers
    model: ref('dim_customers')

    type: count
    sql: user_id # superflous here, but shown as an example
```

`sql` is an ambiguous term. Everything dbt does is SQL. 

Could we call it something else? 

### Describe alternatives you've considered

I'm thinking `expression` vibes. I'd like to clarify what will happen to the expression, which takes me to `agg_expression` but I don't want people to start writing `avg` in there (maybe that's an argument to rename `type` to `agg_style` or something? 

Open to other words!

### Who will this benefit?

Metrics users, so _every single dbt user_ right? 😉 

### Are you interested in contributing this feature?

No, because when I discussed it with @drewbanin he muttered under his breath "oh that'd be a real pain to implement"
