### ISSUE TITLE
[Bug] dbt deps sometimes takes >90sec to complete

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Over the last couple of weeks, I've noticed that `dbt deps` sometimes takes >90 seconds between `Running with dbt==0.21.0` and the first `Installing...` line.

It's sporadic, and when I re-run to try and capture it performance improves, which makes me suspect it's some sort of cold cache thing. 

### Expected Behavior

<img alt="Let's go faster" src="https://media.giphy.com/media/3ohuPuRnWLwIsCuHPa/giphy.gif">

### Steps To Reproduce

With this packages.yml file (from the internal-analyics project): 
```
packages:
  - local: '../dbt-utils'
  - package: dbt-labs/snowplow
    version: 0.13.0
  - package: dbt-labs/codegen
    version: 0.4.0
  - package: tailsdotcom/dbt_artifacts
    version: 0.5.0
  - package: fivetran/hubspot
    version: 0.4.0
  - package: fivetran/zendesk_source
    version: 0.4.0
  - package: dbt-labs/audit_helper
    version: 0.4.0
```

run `dbt deps`. I was on the VPN, but from memory I've experienced it off the VPN as well. 

Note that this combination will ultimately result in a duplicate package error due to codegen depending on utils as well, but I don't think that's relevant. 

### Relevant log output

```shell
https://www.loom.com/share/95a1c1f62c304673a4649d609aa98781
```

### Environment

```markdown
- OS: macOS 11.6.1
- Python: Python 3.8.10
- dbt: I've noticed this on 0.21.0 as well as various prerelease versions of 1.0
```

### What database are you using dbt with?

snowflake
