### ISSUE TITLE
[Feature] Allow individual tests to be enabled / disabled

### ISSUE THREAD

**Issue by thisiscab** [dbt-labs/dbt-core#4365]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I want to be able to disable a specific test. Currently, one can [disable a model, a seed or snapshot](https://docs.getdbt.com/reference/resource-configs/enabled).

Having the ability to do it a singular test level would be great. For example:

```
  - name: my_table
     columns:
     - name: my_column
        tests:
            - dbt_utils.not_constant:
                 enabled: {true/false}
 ```

### Describe alternatives you've considered

1) Set `error_if` to 9999999 when we want tests to be ignored based on certain variables.
2) Pull the test macros in our own package and change its content based on certain variables.

### Who will this benefit?

The use-case of this feature for us is that we have custom logic built on top of the snapshot functionality where we have columns that shouldn't be constant if multiple snapshots have run, but will be constant if it only ran once. One of these columns is `_scd_version`. 

In our CI/CD we only run the snapshot once, which makes these columns constant and makes the test fails, even though it's appropriate behavior. So we want to be able to disable these specific tests under certain situations in order to not raise "expected" failures.

I'm sure others would appreciate being able to turn off specific tests.

### Are you interested in contributing this feature?

no

### Anything else?

Nope!

**Comment by jtcohen6** [comment]
@thisiscab The ability to configure `enabled: true|false` for specific tests (specific instances of generic tests, to be precise) was introduced in v0.20. As long as you're using a version of dbt since then, the code you've included above should work just fine.

In v0.21, we introduced and documented a new syntax that leverages the `config:` property, to make clear that `enabled` is a config that can be set in multiple places, and (b) it has a subtly different rendering context from the context used for generic test keyword arguments. The old syntax still works, too.

```yml
version: 2
models:
  - name: my_model
    columns:
      - name: my_column
        tests:
          - dbt_utils.not_constant:
              config:  # new syntax
                enabled: false
```
```
$ dbt test
Running with dbt=0.21.1
Found 1 model, 0 tests, 0 snapshots, 0 analyses, 352 macros, 0 operations, 0 seed files, 0 sources, 0 exposures

WARNING: Nothing to do. Try checking your model configs and model specification args
```

### documentation

This capability is documented under "test configs" here: https://docs.getdbt.com/reference/test-configs#general-configurations

It does look like the "enabled" page, [which you linked above](https://docs.getdbt.com/reference/resource-configs/enabled), is lacking an example of this specific capability; the tab for "tests" just includes setting the `enabled` config in generic/singular test definitions (SQL files) and in `dbt_project.yml`. Would you be up to [opening an issue](https://github.com/dbt-labs/docs.getdbt.com/issues) / [proposing a change](https://github.com/dbt-labs/docs.getdbt.com/edit/current/website/docs/reference/resource-configs/enabled.md) to that page?

In the meantime, I'm going to close this issue, as it's already supported functionality in dbt-core.
