### ISSUE TITLE
log_format in UserConfig should be str, not bool

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#4391]
https://github.com/dbt-labs/dbt-core/blob/eeb490ed154a71e42564f5ec8d6b1bc03216a378/core/dbt/contracts/project.py#L234

I'd expect to be able to set this as:
```yml
# profiles.yml
config:
  log_format: json
```
Which I think just looks like replacing it with:
```python
  log_format: Optional[str] = None 
```
