### ISSUE TITLE
[Bug] generate_schema_name macro removes ability to use custom schema

### ISSUE THREAD

**Issue by KaoruDev** [dbt-labs/dbt-core#4409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was using the https://github.com/fivetran/dbt_github package with the following in `dbt_project.yml`

```yaml
models:
  github:
    github__pull_requests:
      +schema: marts
```

Test runs appear the `+schema` property was being ignored. I then realized I was overriding the `generate_schema_name` macro per: https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas#an-alternative-pattern-for-generating-schema-names

Luckily I copied and pasta the source code (cause I wanted to switch from `prod` to something else) and noticed that there's a missing condition (which is if there is a `custom_schema_name` is `None` then we should return a prefixed custom schema name.

### Expected Behavior

I expected the `github__pull_requests` model to be created in the `marts` schema.

### Steps To Reproduce

1. packages:
```yaml
packages:
  # Source Github Models
  # https://github.com/fivetran/dbt_github_source
  - package: fivetran/github_source
    version: [">=0.3.0", "<0.4.0"]
  # Transformational Github Models
  # https://github.com/fivetran/dbt_github
  - package: fivetran/github
    version: [">=0.3.0", "<0.4.0"]
```
2. `macro/get_custom-schema.sql`:
```jinja
{% macro generate_schema_name(custom_schema_name, node) -%}
    {{ generate_schema_name_for_env(custom_schema_name, node) }}
{%- endmacro %}
```
3. `dbt_project.yml`
```yaml
models:
  github:
    github__pull_requests:
      +schema: marts
```

### Environment

```markdown
- OS: Ubuntu on WSL2
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"

- Python: `3.8.12`
- dbt: `0.21.1`
```

### What database are you using dbt with?

bigquery

### Additional Context

The following fixed it for me:

```jinja
{% macro generate_schema_name(custom_schema_name, node) -%}
    {%- set default_schema = target.schema -%}

    {%- if target.name == 'live' and custom_schema_name is not none -%}

        {{ custom_schema_name | trim }}

    {%- elif custom_schema_name is not none %}

        {{ default_schema ~ "_" ~ custom_schema_name }}

    {%- else -%}

        {{ default_schema }}

    {%- endif -%}
{%- endmacro %}
```

I'd be more than happy to submit a PR if folks think the above is the right solution.
