### ISSUE TITLE
[Feature] Add flexibility to source freshness, e.g. weekdays

### ISSUE THREAD

**Issue by NoToWarAlways** [dbt-labs/dbt-core#4450]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Source freshness should have options for loading schedules that are different than every x minutes/hours/days. E.g only on working days, only on Tuesday and Friday or only on the first of each month.
This could be defined by a cron-like schedule when data is expected to be updated and a time that we can be behind this schedule. A possible implementation could look something like the code below.
```
       freshness:
          error_after:
            schedule: "0 16 * * 1-5"
            count: 12
            period: hour
```

### Describe alternatives you've considered

A behavior like this can already be achieved via some jinja, e.g. like the code block below. However, this isn't the most intuitive and easy to read way of doing it. It's also currently not picked up by partial parsing, which is the default from v1.0.0 onwards.

```
       freshness:
          error_after:
            count: "{{ 48 if run_started_at.strftime('%w') == '1' else 24 }}"
            period: hour
```

Second alternative: Having separate jobs for the different weekdays where one is not testing source freshness at all.

### Who will this benefit?

In general: all users that have loads that are recurring regularly, but not on a schedule of every x/minutes/hours/days.
Our specific use case: we load exchange rate data from the European Central Bank. They publish new rates around 16:00 CET on working days. On weekends, there are no updates. This leads to the last update being more than 48 hours old on a Monday morning. We’d like to be notified if data is older than 24 hours on Tuesday to Saturday, but it can be a lot more on Sunday and Monday.
We're exposing source freshness and data test results on our main MRR dashboard to the company via the Looker dashboard tile. This means I either have an error on Monday morning or I’m not timely notified of problems on other weekdays. Using separate dbt jobs isn’t an option as we can only reference one job for the dashboard tile.

### Are you interested in contributing this feature?

Generally yes. However, I've never coded in python before, so no idea where to start.

### Anything else?

Slack community thread: https://getdbt.slack.com/archives/C2JRTGLLS/p1638216863082300
