### ISSUE TITLE
[Feature] Allow dbt init to use profile templates with nested configurations

### ISSUE THREAD

**Issue by edgarrmondragon** [dbt-labs/dbt-core#4462]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Some adapters may have complex profiles with nested objects and arrays, and currently it's not possible to capture user input of such values with `dbt init` and [`profile_template.yml`](https://docs.getdbt.com/docs/contributing/building-a-new-adapter#profile_templateyml)

An example of such a profile is what [dbt-sqlite](https://github.com/codeforkjeff/dbt-sqlite) requires:

```yaml
default:
  outputs:

    dev:
      type: sqlite
      threads: 1
      database: <database name>
      schema: 'main'
      schemas_and_paths:
        main: '/my_project/data/etl.db'
      schema_directory: '/my_project/data'
      extensions:
        - '/path/to/sqlite-digest/digest.so'

    prod:
      type: sqlite
      threads: 1
      database: <database name>
      schema: 'main'
      schemas_and_paths:
        main: '/my_project/data/etl.db'
      schema_directory: '/my_project/data'
      extensions:
        - '/path/to/sqlite-digest/digest.so'

  target: dev
```

[Source](https://github.com/codeforkjeff/dbt-sqlite/blob/f4f0f04047fcfc4af96fd12f1fbc76e0eb4b6a89/dbt/include/sqlite/sample_profiles.yml)

- The `extensions` array will have as many entries as SQLite extensions the user needs.
- The `schemas_and_paths` object can have any number of key-value pairs.

So, my proposal is to add a new `yaml` type option to `profile_template.yml` prompts and use that to parse input as YAML that is  written as such to the profiles file.

### Describe alternatives you've considered

1. Make arrays and objects `fixed` in the `profile_template.yml` file. This makes the user edit the `~/.dbt/profiles.yml` instead of relying solely on input.

2. A different (and harder to implement) spec where object and array prompts are walked recursively based on something like a JSON schema for the profile.

### Who will this benefit?

Users of `dbt-sqlite` (or any adapter with such configuration requirements) initializing new dbt projects.

### Are you interested in contributing this feature?

Yes!

### Anything else?

If you're interested, I can start a PR soon 😄
