### ISSUE TITLE
[Bug] Seed properties file no longer works in 1.0.0

### ISSUE THREAD

**Issue by DVAlexHiggs** [dbt-labs/dbt-core#4471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to override column types via a seed properties file ( `whatever_you_want.yml`), as follows:

properties.yml:
```
version: 2
seeds:
  - name: raw_source
    config:
      CUSTOMER_PK: BINARY(16)
      BOOKING_FK: BINARY(16)
      ORDER_FK: BINARY(16)
      LOAD_DATE: DATE
  - name: raw_source_2
    config:
      CUSTOMER_PK: BINARY(16)
      BOOKING_FK: BINARY(16)
      ORDER_FK: BINARY(16)
      LOAD_DATE: DATE
```

I have also tried:

properties.yml:
```
version: 2
seeds:
  - name: raw_source
    config:
      +column_types:
        CUSTOMER_PK: BINARY(16)
        BOOKING_FK: BINARY(16)
        ORDER_FK: BINARY(16)
        LOAD_DATE: DATE
  - name: raw_source_2
    config:
      +column_types:
        CUSTOMER_PK: BINARY(16)
        BOOKING_FK: BINARY(16)
        ORDER_FK: BINARY(16)
        LOAD_DATE: DATE
```

It does work in `dbt_project.yml` still, with the following config:

```
...
seeds:
  +quote_columns: true
  dbtvault_test:
    raw_source:
      +column_types:
        CUSTOMER_PK: BINARY(16)
        BOOKING_FK: BINARY(16)
        ORDER_FK: BINARY(16)
        LOAD_DATE: DATE
    raw_source_2:
      +column_types:
        CUSTOMER_PK: BINARY(16)
        BOOKING_FK: BINARY(16)
        ORDER_FK: BINARY(16)
        LOAD_DATE: DATE
```

### Expected Behavior

As per these docs:

- https://docs.getdbt.com/reference/resource-configs/column_types#usage
- https://docs.getdbt.com/reference/seed-configs#apply-the-schema-configuration-to-one-seed-only

I expect at least one of the following to work:

properties.yml:
```
version: 2
seeds:
  - name: raw_source
    config:
      CUSTOMER_PK: BINARY(16)
      BOOKING_FK: BINARY(16)
      ORDER_FK: BINARY(16)
      LOAD_DATE: DATE
  - name: raw_source_2
    config:
      CUSTOMER_PK: BINARY(16)
      BOOKING_FK: BINARY(16)
      ORDER_FK: BINARY(16)
      LOAD_DATE: DATE
```

properties.yml:
```
version: 2
seeds:
  - name: raw_source
    config:
      +column_types:
        CUSTOMER_PK: BINARY(16)
        BOOKING_FK: BINARY(16)
        ORDER_FK: BINARY(16)
        LOAD_DATE: DATE
  - name: raw_source_2
    config:
      +column_types:
        CUSTOMER_PK: BINARY(16)
        BOOKING_FK: BINARY(16)
        ORDER_FK: BINARY(16)
        LOAD_DATE: DATE
```

i.e.

When I run `dbt seed --full-refresh`

I should get two tables:
- `raw_source`
- `raw_source_2`

And the columns should be the configured types, instead, types are inferred as if no `properties.yml` exists. 

### Steps To Reproduce

1. Snowflake and dbt 1.0.0
2. Create a file `project_root/seeds/raw_source.csv` with the following content:
https://gist.github.com/DVAlexHiggs/8f108f07d083654e663894651d90615a
3. Run `dbt seed --full-refresh`
4. Resulting table does not have the correct types

### Relevant log output

```shell
N/A - Logs are normal and don't report an errors
```

### Environment

```markdown
- OS: Ubuntu 21.01
- Python: 3.9.6
- dbt: 1.0.0
```

### What database are you using dbt with?

snowflake

**Comment by DVAlexHiggs** [comment]
Ok just after I submitted this, I got it to work with the following:

properties.yml
```
version: 2
seeds:
  - name: raw_source
    config:
      column_types:
        CUSTOMER_PK: BINARY(16)
        BOOKING_FK: BINARY(16)
        ORDER_FK: BINARY(16)
        LOAD_DATE: DATE
  - name: raw_source_2
    config:
      column_types:
        CUSTOMER_PK: BINARY(16)
        BOOKING_FK: BINARY(16)
        ORDER_FK: BINARY(16)
        LOAD_DATE: DATE
```

This is not explained/not made clear in the docs, so should perhaps be updated. Either that or this unintended?
