### ISSUE TITLE
[Bug] Deprecation warnings about dbt_project.yml config paths changes always triggered

### ISSUE THREAD

**Issue by landier** [dbt-labs/dbt-core#4535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every time I run `dbt compile`, I'm getting the following warnings although the `dbt_project.yml` file is up-to-date with new config paths (`model-paths` over `source-paths` and `seed-paths` over `data-paths`):

```
14:48:13  [WARNING]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
14:48:13  [WARNING]: Deprecated functionality
The `data-paths` config has been renamed to `seed-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
```

And here is the relevant section of `dbt_project.yml`:
```
model-paths: ["models", "src"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["resources/seed"]
macro-paths: ["macros"]
log-path: logs
```

Any idea what is going? Is there a reminiscence of the previous `dbt_project.yml` stored somewhere?
How can I debug the project configuration which is loaded?

### Expected Behavior

I would expect those warnings to not appear.

### Steps To Reproduce

Here is `dbt debug` output:
```
14:51:42  Running with dbt=1.0.0
dbt version: 1.0.0
python version: 3.8.7+
python path: /Users/nlandier/.pyenv/versions/3.8-dev/bin/python3.8
os info: macOS-11.4-x86_64-i386-64bit
Using profiles.yml file at /Users/nlandier/.dbt/profiles.yml
Using dbt_project.yml file at /Users/nlandier/Spendesk/dbt/dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [OK found]

Connection:
  account: db93014.eu-west-1
  user: nlandier
  database: SPX_DBT_NICOLAS
  schema: dev
  warehouse: WH_TRANSFORM
  role: ROLE_TRANSFORMER_DATA_DEV
  client_session_keep_alive: False
  Connection test: [OK connection ok]

All checks passed!
```

### Environment

```markdown
- OS: macOS-11.4-x86_64-i386-64bit
- Python: 3.8.7+
- dbt: 1.0.0
```

### What database are you using dbt with?

snowflake

**Comment by joellabes** [comment]
@landier what packages are installed in packages.yml? They are also dbt projects, so also need to be updated. All dbt Labs-managed packages already have 1.0 compatible releases out, as do a number of other packages served through the Package Hub.

**Comment by gshank** [comment]
Might be a good idea to update those deprecation warnings with the package name.

**Comment by landier** [comment]
Good catch @joellabes. It was indeed due to two DBT Labs packages we're using and that have been updated meanwhile to their most recent version making the warning disappear.

Thanks

**Comment by annayeomans** [comment]
getting the same thing now

**Comment by joellabes** [comment]
Hi @annayeomans, have you checked that your packages are up to date? Can you share your `packages.yml` file?

**Comment by annayeomans** [comment]
@joellabes here is the setup we currently have. For context, I started getting this error after trying to install `snowflake_spend` package.

```
name: 'project_name'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

target-path: "target" 
clean-targets:   
  - "target"
  - "dbt_packages"
 
models:
  project_name:
    materialized: table
    staging:
      +schema: STAGING
    marts:
      core_pii:
        +schema: PII
      core_details:
        +schema: DETAILS
      core_snapshots:
        +schema: SNAPSHOTS
      core_segment:
        +schema: SEGMENT

tests:
  +store_failures: true
```
