### ISSUE TITLE
[Bug] Test alias not working with dbt_utils.accepted_range

### ISSUE THREAD

**Issue by crystalro0** [dbt-labs/dbt-core#4549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Customer uses `--store-failures` on some columns in the same model, multiple instances of a test with a `where` clause. For example: two different `dbt_util.accepted_range` tests on different subsets of the same column. 

```
      - name: status
        tests:
          - dbt_utils.accepted_range:
              alias: sale_placed_accepted_range
              where: "status = 'Placed'"
          - dbt_utils.accepted_range:
              alias: sale_shipped_accepted_range
              where: "status = 'Shipped'"
```

They experienced errors in v0.21 with `--store-failures` due to duplicate test names. Aliasing the tests resolved the dupe issue, but since they upgraded to 1.0, this doesn't seem to be working anymore. 

### Expected Behavior

Both tests run with the two aliases from the test config in the yml to differentiate between the two.

### Steps To Reproduce

1. Use environment on v1.0.0 or v1.0.1
2. Add 2 tests to the same column with different where clauses.
3. Run `dbt test --store-failures`
4. Error: 
```
Compilation Error
  dbt found two resources with the name "dbt_utils_accepted_range_test__0"
Since these resources have the same name,
  dbt will be unable to find the correct resource when "dbt_utils_accepted_range_test__0" is used.
```

### Environment

```markdown
- dbt: 1.0.1
```

### What database are you using dbt with?

snowflake
