### ISSUE TITLE
[Bug] dbt deps

### ISSUE THREAD

**Issue by olivierdet** [dbt-labs/dbt-core#4554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have defined a profile like that :
```
    prod:
      type: redshift
      threads: "{{ env_var('DBT_THREADS', 1)| int }}"
      host: "{{ env_var('REDSHIFT_HOST') }}"
      port: 5439
      user: "{{ env_var('REDSHIFT_USER') }}"
      pass: "{{ env_var('REDSHIFT_PASSWORD') }}"
      dbname: "{{ env_var('REDSHIFT_DATABASE') }}"
      schema: "bi"
```
If one of the env is not defined  ( ex : REDSHIFT_DATABASE) we now have the following error message while running `dbt deps`
```
13:26:05  Encountered an error:
Parsing Error
  Env var required but not provided: 'REDSHIFT_DATABASE'
```
If it is defined with a dummy data, it works properly. ( So it does not check connection)

### Expected Behavior

`dbt deps`should not return any issue when a env variable is not defined.

### Steps To Reproduce

1. Define a profile with env variable 
2. Do not define the given env variable 
3. run `dbt deps`

### Environment

```markdown
- OS:container python:3.9.6-slim-buster
- Python: 3.9.6
- dbt:1.0.0
```

### What database are you using dbt with?

redshift
