### ISSUE TITLE
[CT-76] [Feature] Allow vars to be declared in selectors

### ISSUE THREAD

**Issue by jjuanramos** [dbt-labs/dbt-core#4599]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

As of now, selectors are a great way of allowing dbt users to version control the dbt cloud jobs we run. Nevertheless, when it comes to variables we are still limited to declare them on the dbt Cloud UI.

It would be great if we could set the variables in the selector itself.
This could look like this:
```YAML
selectors:
  - name: update_warehouse
    description: >
      Selection of models that we want to run when we
      update the whole warehouse.
    definition:
      union:
        - method: fqn
          value: "*"
        - exclude:
            - 'tag:tag_1'
            - 'base.kafka'
      vars:
        - treat_base_sources_as_relations: true
        - excluded_base_sources_from_relation_treatment: ['kafka']
```

Achieving this in the dbt Cloud UI:
`dbt build --selector update_warehouse`

### Describe alternatives you've considered

Keep declaring them on the UI:
`dbt build --selector update_warehouse --vars "{treat_base_sources_as_relations: true, excluded_base_sources_from_relation_treatment: ['kafka']}"`

### Who will this benefit?

Any dbt user that wants to maximize how much of the dbt flow is version controlled.

More specifically, dbt users that rely heavily on variables will improve the reliability and ease of their release process. Right now, any dbt user that has a staging/production environment has to make sure the variables are manually updated in all of their dbt Cloud jobs whenever necessary.

### Are you interested in contributing this feature?

Yes!
