### ISSUE TITLE
[Bug] Models are not correctly quoted when materialized as views in dbt 1.0

### ISSUE THREAD

**Issue by rossserven** [dbt-labs/dbt-core#4611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Models with quoted columns (e.g. containing spaces) fail to run when materialized as a view.

It looks like dbt 1.0.1 is explicitly referencing column names in the `create or replace  view` statement:

e.g.
 ```
 create or replace  view MODEL_DEV.dbt_XXX.finance_concepts    
(
      App
    , 
      Account Name
)
   as (
WITH finance_concepts AS (
```
where 0.21.1 did not:
```
  create or replace  view MODEL_DEV.dbt_XXXX.finance_concepts  as (
WITH finance_concepts AS (
```

materializing as table in 1.0.1 does not reference columns and works correctly
```
      create or replace transient table MODEL_DEV.dbt_XXXX.finance_concepts  as
      (
WITH finance_concepts AS (
```

### Expected Behavior

Either correctly quote columns or stop explicitly referencing columns in `create or replace  view`

### Steps To Reproduce

1. in dbt 1.0.1 
2. create model with spaces in column name
3. materialize as view
4. `dbt run` model will fail
5. materialize as table
6. `dbt run` model will succeed

### Environment

```markdown
- OS: dbt Cloud
- dbt: 1.0.1
```

### What database are you using dbt with?

snowflake

**Comment by jtcohen6** [comment]
@rossserven Thanks for opening the issue!

Have you enabled [column-level `persist_docs`](https://docs.getdbt.com/reference/resource-configs/persist_docs) for the view model in the example above? In `dbt-snowflake==1.0.0`, we introduced the capability to persist descriptions on a view model's columns as column-level comments. This requires a little bit of fancy footwork, whereby dbt infers the column schema of the model in advance, so as to include that column schema in its `create view` statement, along with each column's comments:
```sql
-- models/my_view.yml
select 1 as id
```
```yml
# models/views.yml
version: 2
models:
  - name: my_view
    config:
      persist_docs:
        columns: true
    columns:
      - name: id
        description: My primary key
```
```sql
-- target/run/.../my_view.sql
  create or replace  view analytics.dbt_jcohen.my_view 
( 
      ID
)
   as (
    select 1 as id
  );
```

If your column names are quoted, their identifiers will be case-sensitive—[not something we recommend on Snowflake](https://docs.getdbt.com/reference/resource-properties/quote#explanation), since it runs into problems like this one, though it is necessary if you need column names containing mixed casing or special characters. All the same, I believe this will work just by telling dbt that your column name needs to be quoted, via the [`quote` column property](https://docs.getdbt.com/reference/resource-properties/quote#explanation):

```sql
-- models/my_view.yml
select 1 as "My ID Column"
```
```yml
# models/views.yml
version: 2
models:
  - name: my_view
    config:
      persist_docs:
        columns: true
    columns:
      - name: "My ID Column"
        quote: true
        description: My primary key
```
```sql
-- target/run/.../my_view.sql
  create or replace  view analytics.dbt_jcohen.my_view 
( 
  "My ID Column" COMMENT $$My primary key$$
)
   as (
    select 1 as id
  );
```

Voila!

I'm going to transfer this issue to the `dbt-snowflake` repo. If there's any change we need to make, it might be to [the `get_persist_docs_column_list` macro](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/include/snowflake/macros/adapters.sql#L45) over there. But I think we might be able to close this issue as resolved.
