### ISSUE TITLE
[CT-155] [Bug] env_var does not work for setting db port in profiles.yml

### ISSUE THREAD

**Issue by zzztimbo** [dbt-labs/dbt-core#4668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i try to set my db port using an environment variable, it get an error. 

### Expected Behavior

it seems reasonable to me that i would want to also set my db port using environment variables. I'm not sure how to do this. 

### Steps To Reproduce

```
dbt_example_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_EXAMPLE_PGHOST', 'localhost') }}"
      user: "{{ env_var('DBT_EXAMPLE_PGUSER', 'dbt_example') }}"
      pass: "{{ env_var('DBT_EXAMPLE_PGPASSWORD', 'dbt_example') }}"
      port: "{{ env_var('DBT_EXAMPLE_PGPORT', 5435) }}"
      dbname: dbt_example
      schema: public
      threads: 2
```

```
export PREFECT_DBT_EXAMPLE_PGPORT=5432
```

### Relevant log output

```shell
1 check failed:
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "dbt_example_project", target "dev" invalid: '5432' is not of type 'integer'
```

### Environment

```markdown
- OS: MacOS 12.0.1
- Python: 3.9.6
- dbt: 1.0.1
```

### What database are you using dbt with?

postgres

**Comment by joellabes** [comment]
Hi @zzztimbo, to make this work you need to use the [`as_number`](https://docs.getdbt.com/reference/dbt-jinja-functions/as_number) filter: 

```
dbt_example_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_EXAMPLE_PGHOST', 'localhost') }}"
      user: "{{ env_var('DBT_EXAMPLE_PGUSER', 'dbt_example') }}"
      pass: "{{ env_var('DBT_EXAMPLE_PGPASSWORD', 'dbt_example') }}"
      port: "{{ env_var('DBT_EXAMPLE_PGPORT', 5435) | as_number }}"
      dbname: dbt_example
      schema: public
      threads: 2
```

I'm going to close this out; if it doesn't solve your problem feel free to re-open or post in the dbt Community Slack where someone will be able to help you troubleshoot 🆘
