### ISSUE TITLE
[CT-218] [Feature] dbt metrics should support versioning

### ISSUE THREAD

**Issue by k-aranke** [dbt-labs/dbt-core#4712]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

`dbt metrics` doesn't currently support metrics versions: https://docs.getdbt.com/docs/building-a-dbt-project/metrics.
This behavior means that we cannot change the metric in backward-incompatible ways post-creation.

In software engineering, REST APIs have version numbers for this reason.

Expected behavior:
1. I want to specify a version number for a metric and increment it when there is a breaking change.
1. Then, I can track down consumers on the old version and migrate them to the new version.
1. Eventually, I can deprecate the old version of the metric.

### Describe alternatives you've considered

We're currently date-versioning models and aliasing the latest one as the main one, but that's messy, so I'd prefer to avoid this route.

### Who will this benefit?

This change will benefit anyone who needs to change their dbt metrics in a backward-incompatible fashion.

### Are you interested in contributing this feature?

Yes, happy to help

### Anything else?

REST API versioning: https://restfulapi.net/versioning/

**Comment by jtcohen6** [comment]
@k-aranke Thanks for the issue, I love how you're thinking about this! The timing is also right, as we just released a package for calculating metrics: [`dbt_metrics`](https://github.com/dbt-labs/dbt_metrics)

Questions that your issue raises for me:
- What are the types of backward-incompatible changes that you're envisioning? Changes to available dimensions (might break constructed queries), or changes to the underlying business logic powering the calculation (not breaking from a technical perspective, but might cause surprise)?
- How would "migration" between v1 and v2 of a metric work for downstream queriers? Would you want both versions to be available, via your dbt project ("dbt API") in production, for some designated overlap period? If so, this might look like having _two separate metric definitions_, clearly named/versioned to indicate that one is to be deprecated. The downstream querier would specify the version (or versioned name) of the metric it wants to use. Perhaps, at query time, dbt could pass along a warning that the querier is using a metric with a deprecation date, or for which a newer version is available?

Just imagining:
```yml
metrics:
  - &new_customers
    name: new_customers_v1
    label: New Customers
    model: ref('dim_customers')
    description: "The number of paid customers using the product"

    type: count
    sql: user_id

    timestamp: signup_date
    time_grains: [day, week, month]

    dimensions:
      - plan
      - country
      
    meta:
      deprecation_date: '2022-06-01'
    
    # v2: new name + breaking change to dimensions
  - <<: *new_customers
    name: new_customers_v2
    dimensions:
      - subscription_tier
      - region
    meta: {}
```
