### ISSUE TITLE
[Feature] Support BigQuery labels for seeded models

### ISSUE THREAD

**Issue by darrylng** [dbt-labs/dbt-core#4757]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Current models support `+labels:` config as follows:
```
models:
  my_project:
    snowplow:
      +labels:
        domain: clickstream
```

However, seeded models do not currently support this, at least not that I am aware. Having the `+labels:` config under `seeds:` do not currently result in labels being set when running `dbt seed` to the database.

### Describe alternatives you've considered

I have written a macro that is always run as a post-hook for all seeded models.

```
{% macro set_labels_to_seed_models(model_ref) -%}
    {% if execute %}
        {{ log("set_labels_to_seed_models: About to add labels to model: " ~ model_ref) }}
        {% set set_label_to_model_query %}
            ALTER TABLE {{ model_ref }}
            SET OPTIONS (
                labels=[("domain", "clickstream")]
            )
        {% endset %}
        {%- set result = run_query(set_label_to_model_query) -%}
    {% endif %}

{%- endmacro %}
```

And in `dbt_project.yml`, I attach the macro as a post-hook to all models in seeds config:
```
seeds:
  my_project:
    snowplow:
        +post-hook: "{{ set_labels_to_seed_models(this) }}"
```

### Who will this benefit?

BigQuery users who need to seed data into the database but also need labels applied.

### Are you interested in contributing this feature?

Yes, if this is a feature that is wanted.
