### ISSUE TITLE
[CT-287] [Feature] Column tests should only query for that column

### ISSUE THREAD

**Issue by Jaxing** [dbt-labs/dbt-core#4787]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

To day if you do something like

```yaml
models
  - name: some_model
    columns:
      - name: some_column
        tests:
          - not_null
```

This will generate a test like this

```sql
select * 
from (sub_query)
where some_column is null
```

In BigQuery each column that is queried will add more that to process and since we are only interested in some_column here there really is no point in querying for all columns.

### Describe alternatives you've considered

Instead of `*` use the column to be tested.

### Who will this benefit?

People using columnar databases like BigQuery, as it will lower cost per test.

### Are you interested in contributing this feature?

Yes, but I don't know where this is controlled.
