### ISSUE TITLE
[CT-397] [Bug] package selector doesn't work if Full YAML or with "package:" prefix

### ISSUE THREAD

**Issue by solomonshorser** [dbt-labs/dbt-core#4819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I define a selector using "full YAML" and it includes a package reference, the models in the package reference do not get run. When I define the selector using CLI-style syntax, the models in the package _do_ get run.

### Expected Behavior

I would expect both versions of the selector to work in the same way.

### Steps To Reproduce

Use this selector in the `selectors.yml`:
```yaml
  - name: cust
    definition:
      union:
      - staging_models.staging.cust
      - models/cust/*
```
And all models in `models/cust/*` and also in `staging_models.staging.cust` will be built.

Use this selector
```yaml
  - name: cust2
    definition:
      union:
      - method: package
        value: staging_models.staging.cust
      - method: path
        value: models/cust/*
```

And _only_ the models in `models/cust/*` will be built.

Additionally, if you use the "path:" or "package:" prefix like this:
```yaml
  - name: cust
    definition:
      union:
      - package:staging_models.staging.cust
      - path:models/cust/*
```
the models in the package do not get built.

Is there something wrong with the way the package selectors work, or am _I_ doing something wrong?

### Environment

```markdown
- OS: Mac OS 11.6.4
- Python: 3.9
- dbt: 1.0.1
```

### What database are you using dbt with?

bigquery

**Comment by stu-k** [comment]
@solomonshorser Thank you for the submission, and apologies for the long response time!

In your examples `models/cust/*` resolves to a `path` selector, as you have already pointed out, however your other example `staging_models.staging.cust` resolves to a `fqn` (fully qualified name) selector, not a `package` selector.

If you change the entries in your `selectors.yml` that you have listed above to the following, I think you will find they work as expected!
```yaml
selectors:

  - name: cust2
    definition:
      union:
        - method: fqn
          value: staging_models.staging.cust
        - method: path
          value: models/cust/*

  - name: cust3
    definition:
      union:
        - fqn:staging_models.staging.cust
        - path:models/cust/*
```
From the documentation on the [package selection method](https://docs.getdbt.com/reference/node-selection/methods#the-package-method):
> The `package` method is used to select models defined within the root project or an installed dbt package. While the package: prefix is not explicitly required, it may be used to make selectors unambiguous.
>```bash
># These three selectors are equivalent
>dbt run --select package:snowplow
>dbt run --select snowplow
>dbt run --select snowplow.*
>```

If you have further questions about this behavior, please let us know!
