### ISSUE TITLE
[CT-319] [Feature] Selection method based on a selection definition

### ISSUE THREAD

**Issue by danieldiamond** [dbt-labs/dbt-core#4821]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I would like to be able to use a selection definition within another selection definition.
I believe the technical feature request here would be that `selector` is included in the list of methods that can be applied to a selector definition.

```yaml
selectors:
  - name: default_for_dev
    default: "{{ target.name == 'dev' | as_bool }}"
    definition: ...
  - name: default_for_prod
    default: "{{ target.name == 'prod' | as_bool }}"
    definition: ...
  - name: my_ci_job
    definition:
        - union:
            - method: selector
              value: "{{ "default_for_dev" if target.name == 'dev' else "default_for_prod"}}"
            - exclude ...
```

### Describe alternatives you've considered

The most immediate alternative here is to use anchors and aliases. However, the issue arrises where we want to _dynamically_ define the selector definition. Unfortunately you cannot create an alias variable, for instance `*{{ my_jinja_var }}` would not work.

Additionally tried creating variables at the start of the yaml but `Could not parse selector file data:`
```
variables:
  - foo: bar

selectors:
...
union
  - *$(foo)
```

### Who will this benefit?

- Anyone looking to create dynamic selector definitions i.e. if X use a previously defined selector, else use a different selector definition
- Anyone less familiar with anchors and aliases and wanting to implement DRY methods.

A specific example includes having two default definitions depending on the environment and wanting to run a seperate selector that leans on the default.
```yaml
selectors:
  - name: default_for_dev
    default: "{{ target.name == 'dev' | as_bool }}"
    definition: ...
  - name: default_for_prod
    default: "{{ target.name == 'prod' | as_bool }}"
    definition: ...
  - name: my_ci_job
    definition:
        - union:
            - method: selector
              value: "{{ "default_for_dev" if target.name == 'dev' else "default_for_prod"}}"
            - exclude ...
```

### Are you interested in contributing this feature?

Yes
