### ISSUE TITLE
[CT-323] [Bug] Generic test names collide when same args but different config is used

### ISSUE THREAD

**Issue by judahrand** [dbt-labs/dbt-core#4830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If for example there are two different tests which are the same a part from their configs only the first will run due to a naming collision. An example of this might be:

```
- not_null:
    where: color = 'red'
- not_null:
    where: color = 'blue'
```

### Expected Behavior

Both tests should name and have different names.

### Steps To Reproduce

Run the integration tests in #4829 without the commit which fixes the issue.

### Environment

```markdown
- OS:
- Python:
- dbt:
```
