### ISSUE TITLE
[CT-324] [Feature] `quote` setting for metric filters, like `expected_values` test

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4831]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

A sibling to https://github.com/dbt-labs/dbt-core/issues/4294, due to feedback in https://github.com/dbt-labs/dbt_metrics/issues/15

This metric definition:
```
metrics:
  - name: event_count
    label: Event Counts
    model: ref('activity_stream')
    description: "Count of events logged"

    type: count
    sql: activity

    timestamp: timestamp
    time_grains: [day, week, month]

    dimensions:
      - source

    filters:
      - field: timestamp
        operator: '>='
        value: '2021-01-01'
```

gets rendered in the SQL query as `where timestamp >= 2021-01-01`, because the first set of quotes are [for the ~pot~ parser](https://www.teachat.com/viewtopic.php?t=5009). 

The `expected_values` test handles this by [adding a `quote` parameter](https://docs.getdbt.com/reference/resource-properties/tests#accepted_values):
```
      - name: status_id
        tests:
          - accepted_values:
              values: [1, 2, 3, 4]
              quote: false
```

We should _probably_ be consistent and have quotes here on-by-default as well, but that does feel a bit weird to me. 

### Describe alternatives you've considered

Continuing to double-quote dates and strings

### Who will this benefit?

People filtering their metrics against strings or dates

### Are you interested in contributing this feature?

Maybe

**Comment by jtcohen6** [comment]
One other thing that comes quickly to mind: How to differentiate between whether the `field` should be quoted, versus the `value`? We could have sensible per-database defaults for `field`, or even be clever by looking up the associated column in the `model`. If we wanted to be cleverer with `value`, we'd need to do type introspection...

**Comment by joellabes** [comment]
Oh yeah, I was mostly thinking about the `value`. Haven’t gotten as far as thinking about `field` quoting - I'm sorta hoping that there's something I can tap into that magically gets it right 😬 

I was imagining that it'd be like this (assuming 4294 is done, otherwise add a single set of quotes back around every `value`)
```yaml
version: 2

metrics:
  - name: new_customers
    label: New Customers
    [...]    
    filters:
      - field: is_paying
        operator: 'is'
        value: true
           quote: false
      - field: lifetime_value
        operator: '>='
        value: 100
           quote: false
      - field: company_name
        operator: '!='
        value: Acme, Inc
           quote: true #true by default anyway
      - field: signup_date
        operator: '>='
        value: 2020-01-01
```
