### ISSUE TITLE
[CT-345] [Bug] dbt docs generate fail when source test present

### ISSUE THREAD

**Issue by lmmentel** [dbt-labs/dbt-core#4852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I specify a test for a source in my `schema.yml` and run `dbt docs generate` I get 

```bash
12:07:32  Encountered an error:
Runtime Error
  Compilation Error in test source_<test_name>_<source_name>_ (models/schema.yml)
    'test_<test_name>' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
```
here is my `schema.yml` (anonymized)

```yml
sources:
  - name: schema_name
    database: name
    tables:
      - name: users
        identifier: users
        tests:
          - <test_name>
        columns:
    ...
```

I have also tried to put the test at the column level but I get same result.

My test file is in `tests` folder which is added to `dbt_projects.yml` and I can run the test with `dbt test -m <test_name>`

### Expected Behavior

Documentation is generate without errors.

### Environment

```markdown
- OS:linux mint
- Python:3.9.9
- dbt:1.0.2
```

### What database are you using dbt with?

snowflake
