### ISSUE TITLE
[CT-369] [Feature] Use variables declared in dbt_project.yml file in the file

### ISSUE THREAD

**Issue by solomonshorser** [dbt-labs/dbt-core#4873]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

When I declare a variable in a dbt_project file, I sometimes need to use it _in the same_ file. For example:

```yaml
vars:
  special_schema: "my_special_schema"

models:
  my_staging_models:
    staging:
      +materialized: view
      common:
        +enabled: true
        +schema: "{{ var('my_special_schema') }}"
```

`special_schema` is declared in the project-level vars because I need it in several places. I _also_ need to specify this schema as the schema for some models. Currently when I do the above, I get an error: 

>Compilation Error
>  Could not render {{ var('my_special_schema') }}: Required var 'my_special_schema' not found in config:
>  Vars supplied to <Configuration> = {}

### Describe alternatives you've considered

Currently, I am adding a config block to _every_ model to specify the schema, and that works, but with many models, it gets very repetitive. It would be nice to specify the schema once (using a _variable_), in the project file, and not have to do it again.

I suppose I could also include `--vars "my_special_schema: some_schema"` when running DBT, but for ease of use by others, I'd prefer to use the `vars:` block in the project file. We have many variables, and there are a few more I'd like to use in this way. Passing them all from the CLI makes for messier scripts.

### Who will this benefit?

Everyone who wants to make use of variables in the project file, for variables that are declared in the project file.

### Are you interested in contributing this feature?

Yes, but I'm not sure I have the necessary skills or time.

**Comment by gshank** [comment]
It would make a lot of sense to be able to separate out the variables. I could see doing this in two different ways: moving the vars into their own file or pulling the vars out of the dbt_project file first and using them to process the rest of the file.

**Comment by solomonshorser** [comment]
Having the vars in a separate file as one option could make life easier for some devops people as they could move a project around between environments and instead of modifying the vars in the project file, they could just swap different vars files in different environments and leave everything else untouched.

**Comment by joaoheron** [comment]
Looking forward to have something like this as well. Thanks for the initiative @solomonshorser

**Comment by solomonshorser** [comment]
So will this feature be available in the future?

**Comment by Smellow19** [comment]
Upvoting this as I am also running into this issue

**Comment by msohaill** [comment]
Not sure if it's been mentioned and albeit redundant, you could look into the `default` parameter to the `var()` function. [Docs](https://docs.getdbt.com/reference/dbt-jinja-functions/var#variable-default-values). 

```yaml
vars:
  special_schema: "my_special_schema"

models:
  my_staging_models:
    staging:
      +materialized: view
      common:
        +enabled: true
        +schema: "{{ var('special_schema', 'my_special_schema') }}"
```
