### ISSUE TITLE
[Bug] Schema name appended to target schema from 'dbt seed'

### ISSUE THREAD

**Issue by richiebful** [dbt-labs/dbt-core#4880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In my dbt_project.yml file I have the following code to configure my target seed schema.

```yml
seeds:
  +schema: "dev_ref"
```

In my profile.yml file I have the schema set to dev_example.

```yml
databricks:
  outputs:
    dev:
      #skipping some config details here
      schema: dev_example
      type: databricks
      threads: 8
  target: dev
```

The seed file is called my_seed_file.csv.

The seed table created is dev_example_dev_ref.my_seed_file

### Expected Behavior

I expect schema name = dev_ref.

For snapshots, the target_schema config in dbt_project.yml overrides the schema config in profiles.yml. I expect this to be the same for seeds as well.

### Steps To Reproduce

1. Create a seed
2. Configure the seed schema to "dev_ref" in dbt_project.yml
3. Configure the schema in the dbt profile to be "dev_example"
4. Run 'dbt seed'

### Environment

```markdown
- OS: macOS Monterey 12.3
- Python: 3.10.2
- dbt: 1.0.3
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

Using dbt-databricks adapter
