### ISSUE TITLE
[CT-418] [Bug] Env var required profile which is not selected

### ISSUE THREAD

**Issue by JCZuurmond** [dbt-labs/dbt-core#4947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you have an undefined variable in a profile that you do not use, dbt complains about the environment variable not being provided. 

### Expected Behavior

Only raise an error about an undefined environment variable if the variable is used.

### Steps To Reproduce

1. Create a profiles.yml with:

``` yaml
example:
  target: dev
  outputs:
    dev:
      type: databricks
      method: http
      schema: "default"
      host: development.datatabricks.net
    prd:
      type: databricks
      method: http
      schema: "default"
      host: "{{ env_var('DATABRICKS_HOST') }}"
```

2. Do NOT define DATABRICKS_HOST environment variable
2. Run `dbt debug`

### Relevant log output

```shell
bash
Parsing Error
  Env var required but not provided: 'DATABRICKS_HOST'
```
```


### Environment

```markdown
- OS:OSx
- Python: 3.7.2
- dbt: 1.0.0
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

Work around:

``` yaml
      host: "{{ env_var('DATABRICKS_HOST', 'not-set') }}"
```
