### ISSUE TITLE
[CT-485] dbt test fails because of space in source name 

### ISSUE THREAD

**Issue by Freia3** [dbt-labs/dbt-core#5051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading dbt-core and dbt-sqlserver from 0.20.1 to 0.21.0, `dbt test` fails because of spaces (and dot) present in the source name:

source.yml:
```
version: 2
sources:
- name: 'OMOP CDM v5.4'
  schema: omop
  tables:
  - name: cdm_source
    columns:
    - name: cdm_version_concept_id
      tests:
      - not_null
```
Error message after running `dbt test`:
16 of 184 ERROR source_not_null_OMOP CDM v5.4_cdm_source_cdm_version_concept_id [ERROR in 0.84s]
Database Error in test source_not_null_OMOP CDM v5.4_cdm_source_cdm_version_concept_id (sources/source.yml)
  ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'CDM'. (102) (SQLExecDirectW)")

I get the error in all dbt versions >=0.21.0.

Is there any way to resolve this error without adjusting the source name?

### Expected Behavior

successful dbt test

### Steps To Reproduce

dbt test

### Environment

```markdown
- OS:Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
- Python:3.8.10
- dbt:0.21.0
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

using sql server
