### ISSUE TITLE
[CT-492] Support Unit Tests and Macros to be stored along with the models

### ISSUE THREAD

**Issue by SOVALINUX** [dbt-labs/dbt-core#5061]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

**Context**
In complex projects with multiple modules/folders/models it's easy to get lost what is where
That's why it's more convenient to store models + tests + model-specific macroses within 1 folder instead of 3 separate places 
Otherwise it's easy to forget to write a new test, fix existing test/macro/etc.
Modern testing frameworks do support such structure (e.g. https://jestjs.io/ )

**Suggestion**
Allow storing Models, Macros, Tests in 1 folder and distinguish them via file name patterns

How it may look like in dbt_projects.yml:
```
model-paths: ["models"]
model-filenames:
  include: [".sql"]
  exclude: [".test.sql", ".macro.sql"]
test-paths: ["tests"]
test-filenames:
  include: [".test.sql"]
macro-paths: ["macros"]
macro-filenames:
  include: [".macro.sql"]
```

### Describe alternatives you've considered

1. Existing workaround is to store it in 3 different folders
2. Specify `test-paths` like ["models/**/test/"]

### Who will this benefit?

Any projects with big and complex structure

### Are you interested in contributing this feature?

Most likely my team can implement it
