### ISSUE TITLE
[CT-527] Unexpected macro resolution order for `collect_freshness` macro 

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5123]
_Split off from https://github.com/dbt-labs/dbt-core/issues/4525_

When running `dbt source freshness`, why does the definition of `collect_freshness` in a package silently take precedence over the global/default version in `dbt-core`, without the end user / root project "opting into" the override?

These codepaths are in execution/adapter land:

https://github.com/dbt-labs/dbt-core/blob/979e1c74bf55bc6849c89accd75ce86531e7a1f9/core/dbt/task/freshness.py#L145

https://github.com/dbt-labs/dbt-core/blob/979e1c74bf55bc6849c89accd75ce86531e7a1f9/core/dbt/adapters/base/impl.py#L1005-L1006

But the real question here is around the macro resolver for `collect_freshness`, so I think Language team is best positioned to weigh in. For all other "built-in" macros (ones defined in the global project), only the root project can override them, or explicitly opt into a `dispatch` order ([docs](https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch)) that prefers macros from packages.

### Reproduction case

Create a source for a nonexistent table in your project:
```yml
version: 2

sources:
  - name: fake_source
    loaded_at_field: current_timestamp
    freshness:
      warn_after: {period: day, count: 7}
    tables:
      - name: does_not_exist
```

Run `dbt source freshness`, fails because the table doesn't exist.

Create a local package with `macros/collect_freshness.sql`:
```sql
{% macro collect_freshness(source, loaded_at_field, filter) %}
  {% call statement('collect_freshness', fetch_result=True, auto_begin=False) -%}

  -- postgres syntax
  select
    current_timestamp as max_loaded_at,
    current_timestamp as snapshotted_at

  {% endcall %}
  {{ return(load_result('collect_freshness').table) }}
{% endmacro %}

```
Add that local package in `packages.yml`:
```yml
packages:
  - local: local_package
```

Run `dbt source freshness`, it passes—even though the end user never opted into the override.

### Expected behavior

The user could override `collect_freshness` in their own project, to point to the package version instead:
```sql
{% macro collect_freshness(source, loaded_at_field, filter) %}
    {{ return(fivetran_utils.collect_freshness(source, loaded_at_field, filter) }}
{% endmacro %}
```

Or rearrange dispatch order to prefer candidate macros from the `fivetran_utils` package:
```yml
dispatch:
  - macro_namespace: collect_freshness
    search_order: ['fivetran_utils', 'dbt']
```
