### ISSUE TITLE
[CT-540] [Bug] 'target' suddenly not available at compile time in selectors.yml

### ISSUE THREAD

**Issue by ljhopkins2** [dbt-labs/dbt-core#5131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading to `dbt v1.0.5`, I get the following error when compiling my model:
```
Compilation Error
  Could not render {{ target.name == 'dev' | as_bool }}: 'target' is undefined
```

### Expected Behavior

The project should compile without error, as it did in earlier post-v1 releases.

### Steps To Reproduce

1. Add a selector like this to `selectors.yml`
```yml
selectors:
  - name: dev_defer_snapshots
    default: "{{ target.name == 'dev' | as_bool }}"
    definition:
      method: fqn
      value: '*'
      exclude:
        - method: config.materialized
          value: snapshot
```
2. Compile the project with `dbt v1.0.5`
3. Note the error
4. Comment out the line containing `default: "{{ target.name == 'dev' | as_bool }}"`
5. Compile the project
6. Note no error

### Environment

```markdown
- OS: MacOS 12.3.1
- Python: 3.9.10
- dbt: 1.0.5
```

### What database are you using dbt with?

redshift
