### ISSUE TITLE
[Bug] column description is not send to BigQuery

### ISSUE THREAD

**Issue by meretri** [dbt-labs/dbt-core#5157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

````
{{
  config(
    materialized = 'table',
    persist_docs={"relation": true, "columns": true}
 ) }}
 
SELECT
1 as ID,
2 as otherID
 
 ````
````
models:
  - name: my_model
    description: "table description"
    columns:
      - name: ID
        description: "this is an ID"
      - name: otherid
        description: "this is another ID"
````

When running the model, the description is only added for the column "ID" not "otherID"
![image](https://user-images.githubusercontent.com/94354876/165337208-29454ea6-a1f9-4dc3-bd4b-939a5eff73b6.png)

This is probably because of the inconsistent capitalisation between the model ("otherID") and the yml ("otherid").

### Expected Behavior

The description for both columns should be added even though, otherID doesn't have the same capitalisation in the model and in the schema.yml file. BigQuery is not case sensitive in column names, so capitalisation shouldn't matter in the schema.yml

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8.10
- dbt: 1.0.4
- dbt-bigquery: 1.0.0
```

### What database are you using dbt with?

bigquery
