### ISSUE TITLE
[CT-568] [Feature] model-level tests

### ISSUE THREAD

**Issue by solomonshorser** [dbt-labs/dbt-core#5175]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Allow generic tests to be specified at the model level. Not all tests require a column (it even says so in the generic test documentation), but as far as I can tell, the tests still have to be specified under _some_ column.

When new developers are on-boarded to the project, they are confused about why a generic test that applies to the whole model is specified under a specific column.

It would be nice if I could do this:
```YAML
version: 2

models:
  - name: users
    tests:
      - whole_model_test
    columns:
      - name: ID
      ...
```

instead of having to do this:

```YAML
version: 2

models:
  - name: users
    columns:
      - name: ID
        tests:
        - whole_model_test
        ...
```

### Describe alternatives you've considered

I just put the test under whatever serves as a primary key for the model, but it's a somewhat arbitrary convention, and it also can confuse since the name of the primary key is not the same across all models.

### Who will this benefit?

Users who write generic tests that apply to a whole model rather than specific columns.

### Are you interested in contributing this feature?

Yes, but I'm not sure I have the necessary skills or time.

**Comment by solomonshorser** [comment]
A coworker just told me this is possible (I haven't had a chance to try it out yet). If so, maybe this is a request for improved documentation rather than a new feature?

**Comment by jtcohen6** [comment]
@solomonshorser Yes, this is totally possible!

There are some examples in the docs here: https://docs.getdbt.com/reference/resource-properties/tests

And also more examples in the [`dbt_utils`](https://github.com/dbt-labs/dbt-utils#generic-tests) + [`dbt_expectations`](https://github.com/calogica/dbt-expectations/tree/main#documentation) packages:
```yml
models:
  - name: my_model
    tests:
    - dbt_utils.equal_rowcount:
          compare_model: ref('other_table_name')
    - dbt_expectations.expect_table_column_count_to_equal:
        value: 7
```

I think the thrust of your second comment is right on — we should present this capability much more clearly and quickly in the docs. Could I ask you to [open an issue in that repo](https://github.com/dbt-labs/docs.getdbt.com/issues/new?assignees=&labels=content%2Cimprovement&template=improve-docs.yml)? :)
