### ISSUE TITLE
[CT-575] [Bug] 1.0.0 Cannot execute an empty query

### ISSUE THREAD

**Issue by Fouad-Kichauat** [dbt-labs/dbt-core#5183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

dbt is errorring with cannot execute and empty query for a model that **does have** columns description in a schema.yml file, and having persist_docs: {columns: true} configured.

```Database Error in model my_third_dbt_model (models/example/my_third_dbt_model.sql)```

### Steps To Reproduce

1. dbt init
2. Create a third simple model with column description: e.g.: **models/example/my_third_dbt_model.sql** 
```
select *
from {{ ref('my_second_dbt_model') }}
```
3. Add the documentation of newly created model to schema.sql: i.e: **models/example/schema.sql**
```
  - name: my_third_dbt_model
    description: "An additional starter dbt model"
    columns:
      - name: Id
        description: 'The primary key for this table'
        tests:
          - unique
          - not_null
``` 
4. Enable column-level docs persistence; i.e.: **dbt_project.yml**
```
models:
  ...
  +persist_docs:
    relation: true
    columns: true
```
5. Run dbt run and observe the error

### Environment

```markdown
- OS: MacOS
- Python: Python 3.9.9
- dbt: 1.0.0
```

### What database are you using dbt with?

postgres

**Comment by muscovitebob** [comment]
Seems related to https://github.com/dbt-labs/dbt-core/issues/2439 but in reverse.

**Comment by jtcohen6** [comment]
@Fouad-Kichauat Thanks for opening, and for the clear reproduction case!

This is due to the mismatched casing for your column name: `Id` in your `.yml` file, and yet `id` in your model (flowing through from `my_first_dbt_model`):

https://github.com/dbt-labs/dbt-core/blob/f633e9936f62702a59fa661d261caaff9cefbe92/core/dbt/include/starter_project/models/example/my_first_dbt_model.sql#L14

If you change your `Id` to `id`, the issue goes away.

### Better error?

One straightforward change we could make: Check to ensure that 

https://github.com/dbt-labs/dbt-core/blob/f633e9936f62702a59fa661d261caaff9cefbe92/core/dbt/include/global_project/macros/adapters/persist_docs.sql#L31

That would still result in the column comment not being persisted, but it would at least avoid the "can't execute an empty query" error. Instead, it would fail silently. Is that actually better...?

### Case-insensitive comparison?

This just came up over on `dbt-bigquery` as well: https://github.com/dbt-labs/dbt-bigquery/issues/169

For databases that retain case-sensitive names, I think it's reasonable for dbt to expect users to match case as well. For instance, on Postgres, this is possible:

```psql
jerco=# create table dbt_jcohen.my_wonky_tbl as (select 1 as "id", 2 as "ID", 3 as "Id");
SELECT 1
jerco=# select * from dbt_jcohen.my_wonky_tbl;
 id | ID | Id
----+----+----
  1 |  2 |  3
(1 row)
```

We could add case-insensitive comparison logic [here](https://github.com/dbt-labs/dbt-core/blob/main/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L183-L184), but then how could we handle the case above?

### Update docs

My inclination is to say, our best bet is to update the docs on `persist_docs`, to really drive home that column names _must_ match across yaml + sql, with regard to their casing as well: https://docs.getdbt.com/reference/resource-configs/persist_docs

**Comment by muscovitebob** [comment]
Is it possible to warn when the `yml` contains columns which are not created by the model `sql` file I wonder?

**Comment by jtcohen6** [comment]
Good question! Some past conversations on that theme:
- https://github.com/dbt-labs/dbt-core/issues/1438
- https://github.com/dbt-labs/dbt-core/issues/1570
- https://github.com/dbt-labs/dbt-core/issues/2191

**Comment by Fouad-Kichauat** [comment]
@jtcohen6 Thank for the fast reply!

Using the prior example and matching the exact case of the source column solves the issue for the demo code.
But in our current project it does not. To better replicate the issue we are facing, following changes need to be made to the above mentioned demo:

**models/example/schema.sql**
```
models:
  - name: my_third_dbt_model
    description: "An additional starter dbt model"
    columns:
      - name: Id
        description: 'The primary key for this table'
        tests:
          - unique
          - not_null
      - name: SecondColumn
```

**models/example/my_third_dbt_model.sql**
```
select id as Id,
'test' as SecondColumn
from {{ ref('my_second_dbt_model') }}
```

**Comment by jtcohen6** [comment]
It all depends on whether you're quoting the column name or not. In Postgres, column names are lowercased by default, but they retain case-sensitivity if they're quoted.

If you change your model to quote the column names, this should now work:
```
select id as "Id",
'test' as "SecondColumn"
from {{ ref('my_second_dbt_model') }}
```
```
models:
  - name: my_third_dbt_model
    description: "An additional starter dbt model"
    columns:
      - name: Id
        quote: true
        description: 'The primary key for this table'
        tests:
          - unique
          - not_null
      - name: SecondColumn
        quote: true
        description: 'Another column'
```

To be clear, **I don't recommend this.** It's all much simpler if you lowercase (and snake case) column names across the board:
```yml
models:
  - name: my_third_dbt_model
    description: "An additional starter dbt model"
    columns:
      - name: id
        description: 'The primary key for this table'
        tests:
          - unique
          - not_null
      - name: second_column
```
```
select id,
'test' as second_column
from {{ ref('my_second_dbt_model') }}
```
