### ISSUE TITLE
[Bug] Adding tags to a test causes compile error

### ISSUE THREAD

**Issue by nathan-protempo** [dbt-labs/dbt-core#5217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

According to the documentation in https://docs.getdbt.com/reference/test-configs it is possible to add tags to tests, and it gives the following example:

```
models:
  - name: my_model
    columns:
      - name: id
        tests:
          - unique:
              tags: ['my_tag']

```
I added tags to a test in my own project as follows:

```
models:
  - name: fact_seller_inventory
    tests:
      - rowcount_gt_zero
    columns:
      - name: offer_key
        tests:
          - unique
              tags: ['my_tag']
          - not_null
```

However it generates an error at compile time:

```
$ dbt compile
20:59:55  Running with dbt=1.0.1
20:59:56  Encountered an error:
Parsing Error
  Error reading project: report\facts\seller_inventory\schema.yml - Runtime Error
    Syntax error near line 11
    ------------------------------
    8  |       - name: offer_key
    9  |         tests:
    10 |           - unique
    11 |               tags: ['my_tag']
    12 |           - not_null
    13 |

    Raw Error:
    ------------------------------
    mapping values are not allowed in this context
      in "<unicode string>", line 11, column 19
```

As far as I can tell I am using the same syntax as the documentation example. 

### Expected Behavior

Project should compile successfully.
Tags should be appear in the project docs for the test.

### Steps To Reproduce

Using dbt 1.0.1 on Snowflake:
- add ` tags: ['my_tag']` to an existing generic column test such as `unique`.
- execute `dbt compile`
- get error as described 

### Relevant log output

```shell
No relevant log output.
```

### Environment

```markdown
- OS: Windows 11
- Python: 3.8.10
- dbt: 1.0.1
```

### What database are you using dbt with?

snowflake

**Comment by jeremyyeo** [comment]
@nathan-protempo do you have a typo in the copy paste to this issue or were you actually missing a colon (`:`) after the `unique`?

```yaml
models:
  - name: fact_seller_inventory
    tests:
      - rowcount_gt_zero
    columns:
      - name: offer_key
        tests:
          - unique                        <<<<<<< Missing ":" character here.
              tags: ['my_tag']
          - not_null
```

I think you accidentally missed out the `:` character going by your error log.

**Comment by jtcohen6** [comment]
@jeremyyeo is right on!

Since v0.21, we've encouraged everyone to stick `tags` under a `config:` property, in order to group configs together and distinguish them from other test arguments (e.g. `values` for `accepted_values`).

```yml
models:
  - name: fact_seller_inventory
    tests:
      - rowcount_gt_zero
    columns:
      - name: offer_key
        tests:
          - unique:
              config:
                tags: ['my_tag']
          - not_null
```

As of v1.1, this format is also now supported:
```yml
models:
  - name: fact_seller_inventory
    tests:
      - rowcount_gt_zero
    columns:
      - name: offer_key
        tests:
          - test_name: unique
            config:
              tags: ['my_tag']
            name: my_tagged_unique_test  # optional
          - not_null
```

Docs on this:
- https://docs.getdbt.com/reference/resource-properties/tests
- https://docs.getdbt.com/reference/test-configs
