### ISSUE TITLE
Sources are not passed into catalog.json

### ISSUE THREAD

**Issue by hanna-liashchuk** [dbt-labs/dbt-core#5234]
Hi, I'm working with dat-spark and I have a dbt project with source and a model that is using this source. I'm generating docs and ingesting metadata into Datahub. My issue is that schema for Source is not transferred.

Source definition:

```
version: 2

sources:
  - name: filialinfo
    description: Info about filials
    tables:
      - name: tab_filialfiscalregisters
        description: Fiscal registers in filials table
        columns:
          - name: filID
            description: Foreign key of the filials table
          - name: frID
            description: Fiscal register ID
          - name: frNum
            description: Fiscal register number
          - name: modified
            description: modified datetime
          - name: frType
            description: Fiscal register type
          - name: frVersion
            description: Fiscal register version
          - name: FACTORYSERIALNUMBER
            description: Factory serial number

```

Model definition:

```
{{ config(
    materialized = 'table'
) }}

WITH source_data AS (

    SELECT
        filID,
        frID,
        frNum,
        date_format(
            modified,
            "yyyy-MM-dd HH:mm:ss"
        ) AS modified,
        CASE
            WHEN frType == ''
            OR frType == 'NONE' THEN NULL
            ELSE frType
        END AS frType,
        CASE
            WHEN frVersion == ''
            OR frVersion == 'NONE' THEN NULL
            ELSE frVersion
        END AS frVersion,
        CASE
            WHEN factoryserialnumber == ''
            OR factoryserialnumber == 'NONE' THEN NULL
            ELSE factoryserialnumber
        END AS factoryserialnumber
    FROM
        {{ source(
            'filialinfo',
            'tab_filialfiscalregisters'
        ) }}
)
SELECT
    *
FROM
    source_data

```

dbt_project.yml

```

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'palefat_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'palefat_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  palefat_dbt:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
    marts:
      +materialized: table
      +file_format: parquet

```

According to Datahub [documentation](https://datahubproject.io/docs/generated/ingestion/sources/dbt/#config-details), _catalog.json_ should contain schema and I can see that it's generated without sources' schema, while _manifest.json_ has this information.  I tried to add sources into _catalog.json_ manually and metadata were ingested correctly.
