### ISSUE TITLE
[CT-655] [where] Macro support for get_where_subquery

### ISSUE THREAD

**Issue by cccs-jc** [dbt-labs/dbt-core#5259]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

the get_where_subquery macro allows you to place conditions in a where configuration
```
version: 2

models:
  - name: large_table
    columns:
      - name: my_column
        tests:
          - accepted_values:
              values: ["a", "b", "c"]
              config:
                where: "date_column = current_date"
```

However it's not possible to make use of macro in the `where`. It is treated as a string a place as is in the subquery.

We have period filter macro what we would like to use inside the `where`

```
version: 2

models:
  - name: large_table
    columns:
      - name: my_column
        tests:
          - accepted_values:
              values: ["a", "b", "c"]
              config:
                where: " {{ period_filter_sql(date_column) }} "
```

### Describe alternatives you've considered

We worked around this limitation by writing our own version of the `get_where_subquery` macro.

Our version of the macro is specific to our use case of using period_filter_sql.

```
tests:
  model1:
    +meta:
      period_filter: date_column
```

This works but makes it hard to cover other uses cases since our `get_where_subquery` macro does one thing only.

### Who will this benefit?

Having the ability to use the power of dbt within the `where` configuration would enable uses to leverage macros when applying conditions to the tests.

### Are you interested in contributing this feature?

I'm interested in contributing.
