### ISSUE TITLE
[CT-695] [Feature] Disable custom tests from dbt_project.yml

### ISSUE THREAD

**Issue by LoicChesneau** [dbt-labs/dbt-core#5307]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Missing feature

In our project, we sometimes want to avoid running certain tests depending on the context (target.name) and/or the location of the test (e.g. in an installed package). To do that, we expected `dbt_project.yml` to help us conditionally disable tests (enbaled = false). 

This feature seems to be available for models, but I could not disable tests in the same fashion.

I have unsuccessfully tried the following syntax:
```
tests:
    dbt_utils:
      +enabled: |
        {%- if  target.name == "prod" -%} true {%- else -%} false {%- endif -%}
```
This triggered the following error
```
There are 1 unused configuration paths:
- tests.dbt_utils
```

Oddly enough, [the documentation seems to assert this feature is available](https://docs.getdbt.com/reference/test-configs#disable-all-tests-from-a-package), but I haven't been able to use this feature.

I documented my qui research [in the following slack thread](https://getdbt.slack.com/archives/C2JRRQDTL/p1651670516112109).

### Why do we sometimes need to disable certain tests

In our CI tests, we build and test models that have been changed along with their dependencies everytime a published pull requests receives a new commit. Since we have a lot of models in our project, this might mean we need to rebuild hundreds of models everytime. To prevent expansive builds, we have decided to add a `limit 100` to our model builds. This means we do not test our models with a full volumetry, but dbt's syntax and SQL are tested.

Yet some of the tests we want to run out of the CI (in production) require full volumetry, such as `dbt_utils.recency`. In the CI, we would like to disable tests that will fail without full volumetry.

### Describe alternatives you've considered

I tried adding tags to tests when they were assigned to models. Indeed those tags can be excluded from CI workflow commands.

Example: 
```
      tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - id
                - name
              config:
                tags: ['packages']
```
Can be excluded with the following command:
```
dbt test --exclude tag:packages
```

I also considered disabling dbt data testing from the CI workflow given that tests run tests that are mostly or totally incomplete. The result of those tests are therefore almost always irrelevant to the actual results we will get in production.

### Who will this benefit?

I think disabling any node from the dbt_project can be useful for other applications. It seems natural to me that we should be able to manage any node's config from `dbt_project.yml`.

### Are you interested in contributing this feature?

I am not familiar with dbt-core's source code at all, but I would like to review this feature's code for sure!

### Anything else?

I tested this both on my professional project and in a dummy project to make sure this feature was not disabled by our config. I hope I am not mistaken!

More generally I feel like it is difficult for dbt users to explore nodes and figure out which resource is linked to which resources-path. Maybe there is a command that could let us output the resource-path of a node in the console?

**Comment by jtcohen6** [comment]
Hey @LoicChesneau! Thanks for the clear write-up. I think the confusion here might be around the difference between disabling _specific test resources_, which are often instances of generic tests, versus the _generic test definitions_ (macros) that are (re)used to define each of those resource. This is a subtle distinction, and I'll do my best to explain it below.

Specific instances of generic tests — actual test _resources_ — are defined in specific yaml files. Those files are included in the test resources' fully qualified names, allowing them to be configured from `dbt_project.yml`. So if I have a `dbt_utils.equality` test defined in a file named `models/subfolder/some_tests.yml`:
```yml
# models/subfolder/some_tests.yml
version: 2
models:
  - name: some_model
    tests:
      - expression_is_true:
          expression: "1=1"
```


I can conditionally the tests _defined in that file_ via:
```yml
tests:
  my_project:
    subfolder:
      +enabled: "{{ target.name == 'prod' | as_bool }}"
```

Generic test _definitions_ are templates/functions, which can be reused to define specific tests. They can define default configuration for all tests within their functional definition. For example, I could redefine the `equality` test from `dbt_utils` to change its default configuration, while cleverly avoiding the need to copy-paste all its logic (very similar to the discussion in https://github.com/dbt-labs/dbt-core/issues/3841):
```sql
{% test expression_is_true(model, expression, column_name=None, condition='1=1') %}
    {{ config(enabled = (target.name == "prod")) }}
    {{ dbt_utils.default__test_expression_is_true(model, expression, column_name=None, condition='1=1') }}
{% endtest %}
```
Then, all specific instances of `expression_is_true` tests in my project will be disabled _by default_. This configuration will take precedence over configuration in `dbt_project.yml`, but it will be superseded by configuration on each specific test in its `.yml` file (https://docs.getdbt.com/reference/test-configs):
```yml
# models/subfolder/some_tests.yml
version: 2
models:
  - name: some_model
    tests:
      - expression_is_true:
          expression: "1=1"
          config:
            enabled: true
```

Does that help answer your question? I think the thing you want already exists—it may just be trickier to disentangle than it should be, and we could come up with clearer ways to expose or document the functionality.

**Comment by LoicChesneau** [comment]
Hi Jeremy,

Got it, that's exactly what I was looking for!

I redefined `recency` as a project test with the following syntax:

```
{% test recency(model, datepart, field, interval) %}
    {{ config(enabled = (target.name == "prod")) }}
    {{ dbt_utils.default__test_recency(model, field, datepart, interval) }}
{% endtest %}
```

And used the function in my tests just like this:

```
  - name: my_tested_model
    description: some description
    tests:
      - recency:
          datepart: day
          field: created_at
          interval: 2
          severity: warn
```

Under target `prod`, the test was run, under target `dev`, it was not.

Thank you! 👏
