### ISSUE TITLE
[CT-732] [Bug] Placing custom generic test in tests/generic folder causing compilation error

### ISSUE THREAD

**Issue by ashleemtib** [dbt-labs/dbt-core#5341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are experiencing an issue where our custom generic tests defined as {%test%} blocks are causing compilation errors when placed in the tests/generic folder, as is noted as a location for these definitions in [dbt documentation](https://docs.getdbt.com/guides/legacy/writing-custom-generic-tests).

We used to (and still currently do) define our tests as either {%test%} blocks or {%macro%} blocks and place them in our macros/tests/ folder. Tests that are defined here compile with no issue, including the test in question here.

This compilation error occurs in our containerized staging/prod environments but does not occur when the test is run locally. There is no difference between the local dbt_project.yml and the staging/production yml.

Error: 
```
Compilation Error
  'test_stable_source_count' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
```
  
Test definition location: tests/generic 

Test path defined in dbt_project.yml: `test-paths: ["tests"]`

Test definition (shell): 

```
{%- test stable_source_count(model, line_of_business_field, member_field, allowed_deviation=0.1) -%}

{{- config(severity='warn') -}}

  with member_counts as (),

  comparison as (),

  deviation_calc as (),

  errors as ( )

  select * from errors

{%- endtest -%}
```

Test application/call (in source.yml): 

```
sources:
  - name: revenue
    description: Revenue data
    database: [database]
    schema: [schema]

    tables:
      - name: [table name]
        tests:
          - stable_source_count:
              line_of_business_field: data.Plan
              member_field: patient.externalId
```

### Expected Behavior

Expectation is for the test to compile and run on the source it is applied to, as it does locally and for the tests we have defined in macros/tests folder.

### Environment

```markdown
- OS: 
- Python: 3.9.10
- dbt: 1.0.3
```

### What database are you using dbt with?

bigquery
