### ISSUE TITLE
[CT-788] Support disabling `metrics` + `exposures`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5422]
Pretty simple:
```yml
# models/specific_file.yml

metrics:
  - name: disabled_metric
    config:
      enabled: false
  
exposures:
  - name: disabled_exposure
    config:
      enabled: false
```
```yml
# dbt_project.yml

metrics:
  +enabled: false

exposures:
  +enabled: false
```

Expectations:
- Moved to `disabled` section of `manifest.json`
- Needs to work with partial parsing
- If a disabled metric is referenced via `metric()`, it should raise an error at the end of parsing (just as `ref()` or `source()` do)

Grouping these together because I believe it would require touching the same code paths!
