### ISSUE TITLE
[CT-823] [Feature] support table prefix for tables

### ISSUE THREAD

**Issue by leo-schick** [dbt-labs/dbt-core#5454]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

The [sources](https://docs.getdbt.com/reference/source-properties) can be specified for a specific database or schema. I would like to have an option to define a table prefix in the source configuration which then applies to all tables.

For example:
``` yml
source:
    - name: my_source
      database: db1
      schema: public
      table_prefix: "p1_"
      tables:
          - name: users
```

When using the table 'users' with `{{ source('my_source','users') }}` it will be translated to `db1.public.p1_users`.

### Describe alternatives you've considered

Would be fine as well to define the source table name by using a named synonym in dbt, e.g.

``` yml
source:
    - name: my_source
      database: db1
      schema: public
      tables:
          - name: users
            source_table: p1_users
```

### Who will this benefit?

People who have to deal with systems which use a prefix for database tables to define the instance of the system.

Sample systems:
* MODX - a CMS system using "modx_" as default table prefix
* Microsoft Dynamics NAV - an enterprise ERP system using the company name as prefix, e.g. "MyCompany$tablename"
