### ISSUE TITLE
[CT-860] Auto generated test names not unique.

### ISSUE THREAD

**Issue by poshjoshi** [dbt-labs/dbt-core#5491]
I'm trying to store the tests results from our dbt production run using the following command:

```
tests:
  +store_failures: true  # all tests
  ```
  
  Being able to track the failing tests over time will be very useful for us and I am a fan of how they will be stored.
  
  There is a problem though where after adding this hint I am getting the following error:
  
  ```
  dbt found two tests with the name "blah".
  
  Since these resources have the same name, dbt will be unable to find the correct resource
  when running tests.
  
  To fix this, change the name of one of these resources:
```

The reason for this is nested columns and the way it generates the test name. For example:

```
name: column.a.value
test:
  - not_null
name: column_a.value
test:
  - not_null
 ```
It generates them to have the same name because I guess it is replacing "." with "_". I'd normally change the column name but because this is source data I have no choice. The error generated looks like this:
```
To fix this, change the name of one of these resources:
 - test.blah.source_not_null_sources_table_account_column_a_value.dad63b2d73
 - test.blah.source_not_null_sources_table_account_column_a_value.cfa1271ebd
```

Hope this makes sense thanks!

**Comment by jtcohen6** [comment]
Hey @poshjoshi, your instinct here about the `.` &rarr; `_` conversion seems right.

In v1.1, we made it possible to define custom names for specific instances of generic tests: https://docs.getdbt.com/reference/resource-properties/tests#define-a-custom-name-for-one-test

That capability allows you to give each of these tests a unique name of your own design, even though dbt's auto-generated names are colliding. I think that's definitely the way to go here!
```yml
columns:
  - name: column.a.value
    tests:
      - not_null:
          config:
            name: column_a_value_is_not_null
  # alt syntax, same idea
  - name: column_a.value
    tests:
      - name: column_a_value_this_one_different_also_not_null
        test_name: not_null
```
