### ISSUE TITLE
[CT-908] Allow generic tests to accept arbitrary configs

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5532]
Motivation: https://github.com/dbt-labs/dbt-snowflake/pull/210#discussion_r929104933

This is supported:
```yml
version: 2
models:
  - name: my_model
    config:
      any_key: any_value
```

But this isn't:
```yml
version: 2
models:
  - name: my_model
    columns:
      - name: id
        tests:
          - unique:
              config:
                any_key: any_value
```

I think it's because dbt only loads up the test's `config` property with values from `CONFIG_ARGS`:

https://github.com/dbt-labs/dbt-core/blob/3f54f303492b411a377f6724a9cfb685950b5de0/core/dbt/parser/generic_test_builders.py#L250-L262

**Exit criteria:** Tests' `config` property should be able to accept any arbitrary key-value pairs, just like other resource types. Those configs can then be used to set runtime behavior, e.g. in a custom `'test'` materialization.
