### ISSUE TITLE
[CT-1068] [Bug] Hardcoded connect_timeout value for PostgreSQL

### ISSUE THREAD

**Issue by danielkh** [dbt-labs/dbt-core#5698]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

There is an issue with PostgreSQL connection timeout with unstable network connection. After some investigation I've found that it's hardcoded to set connection timeout to 10s and the connect_timeout parameter of profile is not applied. 

### Expected Behavior

There should be an option to specify a connection timeout value as a profile parameter.

### Steps To Reproduce

1. Any environment with unstable network connection 
2. profiles.yml sample:
```
outputs:
  dev:
    type: postgres
    threads: 1
    host: <DB_HOST>
    port: <DB_PORT>
    user: <DB_USER>
    pass: <DB_PASS>
    dbname: <DB_NAME>
    schema: <DB_SCHEMA
    connect_timeout: 120
```
3. Run `dbt run ...`
4. Error: `ERROR: Database Error
  timeout expired`

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8.10
- dbt: 0.18.1
```

### Which database adapter are you using with dbt?

postgres
