### ISSUE TITLE
[CT-1076] [Bug] indirect-selection does not work in selector definitions

### ISSUE THREAD

**Issue by danieldiamond** [dbt-labs/dbt-core#5709]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

One selector definition is defined e.g. `my_selector`, which unions a few tables. When testing (given that indirect-selection is by default "greedy") other tables will be read e.g. relationship tests etc.

Another selector inherits this predefined selector and adds the `indirect_selection: cautious` flag. However, this seems to include those periphery tables as well. The `indirect` selection does not seem to work.

```yaml
  - name: my_selector
    definition:
      union:
        - table_a
        - table_b

  - name: my_secondary_selector
    definition:
      union:
        - method: selector
          value: my_selector
          indirect_selection: cautious
```

### Expected Behavior

`indirect_selection: cautious` should exclude indirect tables.

### Steps To Reproduce

1. create a selector definition which includes a table with a relationship test to another table that is not included in the list.
2. create another selector that selects the previously defined selector and add the `indirect_selection: cautious` attribute
3. run the second selector and observe the indirect models included in the selection.

### Environment

```markdown
- OS: macOS Monterey 12.5
- Python: 3.9.12
- dbt: 1.2.1-rc1
```

### Which database adapter are you using with dbt?

redshift, snowflake

### Additional Context

* PR where selector inheritance was introduced: https://github.com/dbt-labs/dbt-core/pull/4827
* Documentation on adding the `indirect` flag in selectors: https://docs.getdbt.com/reference/node-selection/yaml-selectors

Separate question: Can we add the `indirect_selection: cautious` simply to a list of unioned tables in a selector definition? 
e.g.
```yaml
  - name: my_selector
    definition:
      union:
        - indirect_selection: cautious ???? somewhere associated with this union
        - table_a
        - table_b
```

**Comment by danieldiamond** [comment]
@lostmygithubaccount do you need any additional information for this?

**Comment by danieldiamond** [comment]
@lostmygithubaccount any updates on this?

**Comment by lostmygithubaccount** [comment]
hi @danieldiamond, apologies for the delay here. thanks for opening this issue! for this last suggestion:  

> Separate question: Can we add the `indirect_selection: cautious` simply to a list of unioned tables in a selector definition? e.g.
> 
> ```yaml
>   - name: my_selector
>     definition:
>       union:
>         - indirect_selection: cautious ???? somewhere associated with this union
>         - table_a
>         - table_b
> ```

I recommend opening a new feature request. it's likely not something the Core team will prioritize, but could be a `good_first_issue` for someone to pickup if they're interested. 

onto the main issue: I am able to reproduce this behavior. TLDR: I'm not entirely convinced this is a bug. it is undocumented, and perhaps surprising, behavior. shown below, the inherentence of the `indirect_selection: cautious` field does work as expected. what doesn't seemed define is the same field after inherentence of another selector. since you're defining it on the selector, does that apply to all models in the inhereted selector? paging @jtcohen6 for thoughts 

repro examples built off jaffle_shop:

```yaml
# schema.yml
version: 2

models:

  - name: customer_orders

    columns:
      - name: customer_id
        tests:
          - relationships:
              to: ref('customers')
              field: customer_id

  - name: customers

    columns:
      - name: customer_id
        tests:
          - relationships:
              to: ref('customer_orders')
              field: customer_id


  - name: orders

    columns:
      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - relationships:
              to: ref('customers')
              field: customer_id

```


```yaml
# selectors.yml
selectors:
  - name: s1
    definition:
      union:
        - method: fqn
          value: orders
        - method: fqn
          value: customers
          #indirect_selection: cautious

  - name: s2
    definition:
      union:
        - method: selector
          value: s1
          indirect_selection: cautious

  - name: s3
    definition:
      union:
        - method: fqn
          value: orders
          indirect_selection: cautious
        - method: fqn
          value: customers
          indirect_selection: cautious
```

```bash
@lostmygithubaccount ➜ /workspaces/codyspace/jaffle_shop (main ✗) $ dbt ls --selector s1 
jaffle_shop.customers
jaffle_shop.orders
jaffle_shop.relationships_customer_orders_customer_id__customer_id__ref_customers_
jaffle_shop.relationships_customers_customer_id__customer_id__ref_customer_orders_
jaffle_shop.relationships_orders_customer_id__customer_id__ref_customers_

@lostmygithubaccount ➜ /workspaces/codyspace/jaffle_shop (main ✗) $ dbt ls --selector s2
jaffle_shop.customers
jaffle_shop.orders
jaffle_shop.relationships_customer_orders_customer_id__customer_id__ref_customers_
jaffle_shop.relationships_customers_customer_id__customer_id__ref_customer_orders_
jaffle_shop.relationships_orders_customer_id__customer_id__ref_customers_

@lostmygithubaccount ➜ /workspaces/codyspace/jaffle_shop (main ✗) $ dbt ls --selector s3
jaffle_shop.customers
jaffle_shop.orders
jaffle_shop.relationships_orders_customer_id__customer_id__ref_customers_
@lostmygithubaccount ➜ /workspaces/codyspace/jaffle_shop (main ✗) $ 
```
so `s1` and `s2` behave the same, even though you're expecting `s2` to behave like `s3`. 

switching the `indirect_selection: cautious` to `s1` results in the expected behavior in `s2`:

```yaml
selectors:
  - name: s1
    definition:
      union:
        - method: fqn
          value: orders
        - method: fqn
          value: customers
          indirect_selection: cautious

  - name: s2
    definition:
      union:
        - method: selector
          value: s1
          #indirect_selection: cautious

  - name: s3
    definition:
      union:
        - method: fqn
          value: orders
          indirect_selection: cautious
        - method: fqn
          value: customers
          indirect_selection: cautious
```

to:

```bash
@lostmygithubaccount ➜ /workspaces/codyspace/jaffle_shop (main ✗) $ dbt ls --selector s1 
jaffle_shop.customers
jaffle_shop.orders
jaffle_shop.relationships_orders_customer_id__customer_id__ref_customers_
@lostmygithubaccount ➜ /workspaces/codyspace/jaffle_shop (main ✗) $ dbt ls --selector s2
jaffle_shop.customers
jaffle_shop.orders
jaffle_shop.relationships_orders_customer_id__customer_id__ref_customers_
@lostmygithubaccount ➜ /workspaces/codyspace/jaffle_shop (main ✗) $ dbt ls --selector s3
jaffle_shop.customers
jaffle_shop.orders
jaffle_shop.relationships_orders_customer_id__customer_id__ref_customers_
@lostmygithubaccount ➜ /workspaces/codyspace/jaffle_shop (main ✗) $ 
```

is this an acceptable workaround? otherwise defining each selector more than once?

back to the first case, printing some things out:

```bash
@lostmygithubaccount ➜ /workspaces/codyspace/jaffle_shop (main ✗) $ dbt ls 

s1 definition: {'components': [SelectionCriteria(raw={'method': 'fqn', 'value': 'orders'}, method=<MethodName.FQN: 'fqn'>, method_arguments=[], value='orders', childrens_parents=False, parents=False, parents_depth=None, children=False, children_depth=None, indirect_selection=<IndirectSelection.Eager: 'eager'>), SelectionCriteria(raw={'method': 'fqn', 'value': 'customers'}, method=<MethodName.FQN: 'fqn'>, method_arguments=[], value='customers', childrens_parents=False, parents=False, parents_depth=None, children=False, children_depth=None, indirect_selection=<IndirectSelection.Eager: 'eager'>)], 'expect_exists': False, 'raw': {'union': [{'method': 'fqn', 'value': 'orders'}, {'method': 'fqn', 'value': 'customers'}]}}

s2 definition: {'components': [<dbt.graph.selector_spec.SelectionUnion object at 0x7f24ed6df220>], 'expect_exists': False, 'raw': {'union': [{'method': 'selector', 'value': 's1', 'indirect_selection': 'cautious'}]}}

s3 definition: {'components': [SelectionCriteria(raw={'method': 'fqn', 'value': 'orders', 'indirect_selection': 'cautious'}, method=<MethodName.FQN: 'fqn'>, method_arguments=[], value='orders', childrens_parents=False, parents=False, parents_depth=None, children=False, children_depth=None, indirect_selection=<IndirectSelection.Cautious: 'cautious'>), SelectionCriteria(raw={'method': 'fqn', 'value': 'customers', 'indirect_selection': 'cautious'}, method=<MethodName.FQN: 'fqn'>, method_arguments=[], value='customers', childrens_parents=False, parents=False, parents_depth=None, children=False, children_depth=None, indirect_selection=<IndirectSelection.Cautious: 'cautious'>)], 'expect_exists': False, 'raw': {'union': [{'method': 'fqn', 'value': 'orders', 'indirect_selection': 'cautious'}, {'method': 'fqn', 'value': 'customers', 'indirect_selection': 'cautious'}]}}
```

everything looks correct. my personal assumption at this point is that `'indirect_selection': 'cautious'` has no effect after inheritance

**Comment by jtcohen6** [comment]
@lostmygithubaccount Thanks for including the full reproduction case!

I agree, this is undocumented behavior at the extension / intersection of the selector inheritance functionality recently added (by @danieldiamond!) in https://github.com/dbt-labs/dbt-core/pull/4827. It is consistent, and not limited to `indirect_selection`: I also see this behavior with, for example:

```
# selects any model that is a downstream child of 'orders' &/or 'customers'
selectors:
  - name: s1
    definition:
      union:
        - method: fqn
          value: orders
          children: true
        - method: fqn
          value: customers
          children: true

  - name: s2
    definition:
      union:
        - union:
          - method: selector
            value: s1
            # children: true
```
```
# does not select any downstream children
selectors:
  - name: s1
    definition:
      union:
        - method: fqn
          value: orders
          children: true
        - method: fqn
          value: customers
          children: true

  - name: s2
    definition:
      union:
        - union:
          - method: selector
            value: s1
            # children: true
