### ISSUE TITLE
[CT-1091] [Feature] Add Lookback Attribute for Metrics

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-core#5721]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The metrics package is looking to expand the types of metrics that it can operate on and one consistent piece of feedback we've received is that people want to be able to define metrics that have a concept of time included in their definition. IE 14 Day Average, etc.

This functionality has an [open PR here](https://github.com/dbt-labs/dbt_metrics/pull/92) for the metrics package. We've proven that it works but want to move the definition of this metric aspect into the metric itself instead of meta.

Example:

```yml
metrics:
  - name: base_lookback_metric
    model: ref('fact_orders')
    label: Total Discount ($)
    timestamp: order_date
    time_grains: [day, week, month]
    type: sum
    sql: discount_total
    dimensions:
      - had_discount
      - order_country
      
    window: 14 days
   
```

### Describe alternatives you've considered

Not including it.

### Who will this benefit?

Anyone who wants to use metrics that are cumulative or lookback.

### Are you interested in contributing this feature?

Yep!

### Anything else?

I am not married or even really attached to the name of lookback. It is a placeholder while we work on the functionality.
