### ISSUE TITLE
[CT-1120] [Bug] BigQuery profile does not work when passing individual keyfile parameters using keyfile_json

### ISSUE THREAD

**Issue by smithcb88** [dbt-labs/dbt-core#5761]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have the below `profiles.yml` file in my environment (sensitive information replaced with root vegetables):

```
myprofile:
  target: dev
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: my-project
      location: europe-west2
      dataset: core
      threads: 1
      keyfile_json:
        type: potato
        project_id: potato
        private_key_id: potato
        private_key: potato
        client_email: potato
        client_id: potato
        auth_uri: potato
        token_uri: potato
        auth_provider_x509_cert_url: potato
        client_x509_cert_url: potato
```

When I execute `dbt run` in my project, I get the below error:

```
Database Error
  expected str, bytes or os.PathLike object, not NoneType
```

### Expected Behavior

The command would run my models, as it would (and does) do if I comment out everything under keyfile_json and replace with `keyfile` & a path to my JSON key file.

### Steps To Reproduce

Run `dbt_run` using the above `profiles.yml`

### Environment

```markdown
- OS: Mac OS Monterey (12.3.1)
- Python: 3.10.4
- dbt: 1.2.0
- dbt-bigquery = 1.2.0
```

### Which database adapter are you using with dbt?

bigquery
