### ISSUE TITLE
[Feature] Update Metric Spec With Clearer Names

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-core#5774]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

_Technically a duplicate of this issue https://github.com/dbt-labs/dbt-core/issues/4325_

Right now, we have two fields within the metric spec whose names don't perfectly match what they are trying to convey.
- `sql` : this attribute represents the sql expression that will be aggregated. It can be a simple field (user_id) or more complicated (case when x > y then x else y end)
- `type` : this attribute represents the calculation / aggregation method that we are performing on the expression. 

### Proposed Change

As such, I propose the following changes:
- Renaming `type` to `calculation_method`. 
  - **_Why calculation method and not aggregation method?_** This is because we do have some metrics that aren't aggregations. Specifically expression/derived metrics. Calculation method keeps the door open to other metric types in the future that also aren't technically aggregations
- Renaming `sql` to `expression`
  - Alternatively we could call this `measure` - this would build off the prior art of a lot of BI tools.
- Renaming `expression` type metrics to `derived` metrics
  - This was the top suggestion for name by the community. I have no strong opinions on this one so I will bow to the will of the community
 
<details>
<summary> Old format </summary>

```yml
version: 2 
metrics:
  - name: base_average_metric
    type: average
    sql: discount_total

    model: ref('fact_orders')
    label: Total Discount ($)
    timestamp: order_date
    time_grains: [day, week, month, all_time]
    dimensions:
      - had_discount
      - order_country
```

</details>

<details>
<summary> New format </summary>

```yml
version: 2 
metrics:
  - name: base_average_metric
    calculation_method: average
    expression: discount_total

    model: ref('fact_orders')
    label: Total Discount ($)
    timestamp: order_date
    time_grains: [day, week, month, all_time]
    dimensions:
      - had_discount
      - order_country

```

</details>

Let me know what y'all think!

### Describe alternatives you've considered

Not changing this.

### Who will this benefit?

Anyone who uses metrics!

### Are you interested in contributing this feature?

Yep! Already scoping it out in a PR
