### ISSUE TITLE
[Bug] Not all jinja target attributes are available from profiles.yml

### ISSUE THREAD

**Issue by rjh336** [dbt-labs/dbt-core#5776]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am currently trying to access `target.query_tag` based on the currently set value in my `profiles.yml` but it does not appear in the target object when I log it out during parsing.

profiles.yml
```yaml
config:
    send_anonymous_usage_stats: False
    use_colors: True

integration_tests:
  outputs:

    bigquery:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('BIGQUERY_SERVICE_KEY_PATH') }}"
      project: "{{ env_var('BIGQUERY_TEST_DATABASE') }}"
      schema: "{{ env_var('TEST_SCHEMA') }}"
      location: us
      threads: 4

    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT_ID') }}"
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_TEST_DATABASE') }}"
      schema: "{{ env_var('TEST_SCHEMA') }}"
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_integration_tests
      connect_retries: 0
      connect_timeout: 10
      retry_on_database_errors: False
      retry_all: False
```

log output of `target` object from dbt parse -t snowflake
```
{
    'account': 'XXXXXX',
    'user': 'XXXXXX',
    'database': 'XXXXXX',
    'schema': 'XXXXXX',
    'warehouse': 'XXXXXX',
    'role': 'ACCOUNTADMIN',
    'client_session_keep_alive': False,
    'type': 'snowflake',
    'threads': 4,
    'name': 'snowflake',
    'target_name': 'snowflake',
    'profile_name': 'integration_tests',
    'config': {
        'send_anonymous_usage_stats': False,
        'use_colors': True
    }
}
```

### Expected Behavior

I would expect the target object to contain all properties defined in profiles.yml

### Steps To Reproduce

Using snowflake target and profiles.yml with query_tag defined, try to access `target.query_tag`

### Environment

```markdown
- OS:macOS 12.3
- Python: 3.8.11
- dbt: 1.2.1
- dbt-snowflake: 1.2.0
```

### Which database adapter are you using with dbt?

snowflake
