### ISSUE TITLE
[CT-1155] Blueprint `dbt_contracts.yml` config

### ISSUE THREAD

**Issue by sungchun12** [dbt-labs/dbt-core#5819]
**Success Criteria:**

- [x] Links to existing files in dbt-core that need to be updated
- [x] Net new files in dbt-core and why it needs new files
- [x] Potential "gotcha" implementations based on the above(think: if we update this file here, we have to update 100 files downstream)
- [x] pseudo-code snippets on initial approach for the above to make this functionality work
- [x] Working Code to verify general flow is in the right direction
- [x] Loom demo video

- This will be included in the draft pull request

**Comment by sungchun12** [comment]
Comments from an internal slack thread:
- Feeling like for this to work we need the concept of “organization” or “project group”
- So if we’re in project C and referencing a contracts.json that presumably contains pointers to models from upstream projects A and B, how do we know that those projects are related in order to create the contract?
Maybe in project A you specify what downstream projects can consume your stuff. Then how to organize / reconcile that plus what project B says can go downstream of it, other projects. Seems like a central hub would be the way to do it.
I can’t see how this would work in dbt Core except Core just learning about a new contracts.json object that it gets a priori.
- Sung's initial blueprint for this would define the upstream or downstream contracts at the individual project level.  So, presumably, in project C you would define the upstream contracts for project A and B that you need to properly ref those models.  Part of that contract is defining a location and version where you can get that contract.
- yeah I’ve read that, but may not be fulling internalizing it yet :grin: .
Feels like we are heading towards a two-way connection that needs to be specified in each of the upstream and downstream things. I was thinking more pub / sub to start with. Will put a pin in this and may come back to it!

**Comment by sungchun12** [comment]
So if we’re in project C and referencing a contracts.json that presumably contains pointers to models from upstream projects A and B, how do we know that those projects are related in order to create the contract?
- There should NOT be groupings as API keys and `ref()` statements will map relationships across projects

**Comment by sungchun12** [comment]
Quick Hit Guardrails:

- enforce all project names, paths, artifacts location are unique to prevent people creating circular lineage

**Comment by sungchun12** [comment]
Core vs. Cloud
- Core makes this hard but doable because users are expected to own artifact management by themselves
- Cloud could provide a managed database to store these artifacts ergonomically over time

**Comment by sungchun12** [comment]
https://www.hashicorp.com/campaign/drift-detection-for-terraform-cloud?li_fat_id=c6b383f0-88a4-414f-a889-740847fc6711&utm_medium=video&utm_campaign=tfc-drift-detection&utm_offer=signup&utm_content=6s&utm_source=linkedin&utm_channel_bucket=paid

Huge reason why having UI, stateful experiences will make this contracts mechanism making a hard thing feel easy.

**Comment by lostmygithubaccount** [comment]
> * Feeling like for this to work we need the concept of “organization” or “project group”

drive-by comment checking GH notifications -- I feel like this is a well-solved problem in some other products. I'd recommend looking at other tools with "project" or "workspace" concepts and how they solve these similar problems

**Comment by sungchun12** [comment]
Worth reading deeper: https://www.terraform.io/language/state/workspaces

**Comment by sungchun12** [comment]
There needs to be a data versioning mechanism to make it smooth and elegant to fallback to previously correct data without manually re-running or building overhead mechanisms to ensure this. Similar to this open source tool: https://github.com/dolthub/dolt

**Comment by lostmygithubaccount** [comment]
I always thought this one was git for data :) https://github.com/iterative/dvc they also have this: https://github.com/iterative/gto. very interesting to see similar tools coming from a data/SQL/DB-spin versus a ML-spin.

> Solves the problem of multiple versions of the the same contract to experiment with. Probably helpful to promote a contract to dev, QA, prod too.

this is something MLflow/Databricks/Azure ML have or are doing -- at Azure ML we had the concept of a label, basically special system-defined tags. `@latest` means the last pushed version, otherwise labels are applied through some process to versions. 

so you might have a (ML) model with versions 1-10, where version 10 is the `@latest` tag, version 8 is `@production`, and version 9 is `@staging`. it gets difficult to manage but allows the system I think you're talking about (again doing a bit of drive-by commenting, happy to put more thought into this!). then you should define a CI/CD process for moving staging -> production or rolling back. the underlying model versions and their data don't change, just the labels

**Comment by sungchun12** [comment]
@lostmygithubaccount thank you for the drive by comments :) Helps track all the thinking about this!

**Comment by sungchun12** [comment]
Quick thought:

What if I have a backup config within the contract similar to a post-hook to point to a previous, correct, version of the production contract data?

However, a user has to define a macro or create their own backup process. More overhead code to maintain: they'd have to use a combination of `dbt_artifacts` and their own macro code to lookup the previous `run_results.json` and copy over the failed tables/views in the latest run that worked successfully in a previous run. 

```yml
# dbt_contracts.yml
# upstream-only config for illustration
contracts-upstream:
  backup: production_backup_database # OR dbt run-operation backup_prod_data --args '{from: production_backup_database.production_schema}'
  core-only: # give the project a plain name to ref
    path: git repo OR local subfolder # example: "https://{{env_var('DBT_ENV_SECRET_GIT_CREDENTIAL')}}@github.com/dbt-labs/awesome_repo.git" OR ./models/core/
    version: 0.2.0 # Versioning is at the project level, NOT the model level
    models:
      - ref('fct_orders')
      - ref('dim_customers')
    requirements: # these can be LESS strict compared to the upstream contract, but NEVER more
      - tests
      - '>5 run history' # I don't trust data until it's been run a few times, this is tracked statefully within the artifacts_location with run_results.json file counts
    api_private_key: 'jioq2hfj28338' # replace with env_var for security TODO: how to store this securely? Do we read this in memory and match public and private api keys?
    artifacts_location: 's3://my-bucket/dbt-contracts' # replace with env_var for security, this can be a local path too
```
