### ISSUE TITLE
[CT-1217] [Bug] ConfigSelectorMethod should check for bools

### ISSUE THREAD

**Issue by danielcmessias** [dbt-labs/dbt-core#5890]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The `ConfigSelectorMethod` only checks for string equality. If you have a config property that is boolean, there is no way to match it.

Consider the example:

```yaml
# schema.yml
models:
  - name: some_model
    config:
      meta:
        pii: true
```

Then running `dbt  run --select config.meta.pii:true` would not match.

### Expected Behavior

Running `dbt  run --select config.meta.pii:true` would include the node

### Steps To Reproduce

Create a model with some metadata, e.g.
```yaml
# schema.yml
models:
  - name: some_model
    config:
      meta:
        pii: true
```

Then run `dbt  run --select config.meta.pii:true`

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")
