### ISSUE TITLE
[CT-1230] [Feature] Derived metrics' expressions should be able to be a string or a numerator + denominator dict for division

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#5918]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

- Derived metrics can be one metric divided by another. 
- Sometimes, the second metric might be a zero. 
- Computers dislike dividing by zero. 

https://github.com/dbt-labs/dbt_metrics/pull/96 is protecting against this, but has to parse the `expression` property and look for `/` signs, then wrap the denominator in `nullif(x, 0)`. 

The current approach feels fragile: 
- I hate string matching in general 
- Edge case of edge case, but Exasol and MySQL have a `DIV()` function which this won't capture
- Less edge case-y: Snowflake and BQ have `DIV0()` and `safe_divide()`, which this also won't capture. Admittedly _we_ are safely dividing on their behalf so it's redundant.

[I would prefer](https://github.com/dbt-labs/dbt_metrics/pull/96#discussion_r978172213) that we explicitly define the numerator and denominator: 
```yaml
# models/marts/product/schema.yml
version: 2

models:
 - name: dim_customers
   ...

metrics:
  - name: average_revenue_per_customer
    label: Average Revenue Per Customer
    description: "The average revenue received per customer"

    type: derived
    expression:
       numerator: {{metric('total_revenue')}}
       denominator: {{metric('count_of_customers')}}
    ...
```

while also still allowing `expression` to be a string in most other cases. 

### Describe alternatives you've considered

Leaving it as is 

### Who will this benefit?

People generating ratio metrics

### Anything else?

```
# models/marts/product/schema.yml
version: 2

models:
 - name: dim_customers
   ...

metrics:
  - name: inflated_revenue_for_pitch_deck
    ...
    type: expression
    sql: "{{metric('total_revenue')}} /* some people want to see the world burn */ * 2"

```

**Comment by callum-mcdata** [comment]
I think in this case we'd want to remove this from `derived` metrics and create a new metric calculation method called `ratio` that could be used in conjunction with this? There are a lot of valid use cases for ratio metrics that I think can be extended beyond derived metrics.

```
metrics:
  - name: average_revenue_per_customer
    label: Average Revenue Per Customer
    description: "The average revenue received per customer"

    type: ratio
    expression:
       numerator_expression: field_a
       numerator_calculation_method: count
       denominator: field_b
       denominator_calculation_method: average
```

The `calculation_method` field would only accept values if no metric jinja is found.
