### ISSUE TITLE
[CT-1277] coloring analyses nodes from dbt_project.yml isn't working

### ISSUE THREAD

**Issue by lostmygithubaccount** [dbt-labs/dbt-core#5974]
### Describe the bug

Can't figure how to (is it possible?) color nodes in the DAG for analyses. I've tried a few things and Sung seemed to confirm it's a bug. Opening this to track/further commentary.

### Steps To Reproduce

Create `analyses/explore.sql` or whatever in your dbt project.

I tried some of the following in `dbt_project.yml`:

```yaml
analyses:
  +docs:
    node_color: "black"

```

```yaml
analyses:
  docs:
    node_color: "black"

```

```yaml
models:
  analyses:
    docs:
      node_color: "black"
```

a few others. Could be missing something obvious. also tried "analysis"

node is then the default color, not black

### Expected behavior

node is the intended color

### Additional context

workaround in `schema.yml` in analyses is fine for now:

```yaml
version: 2

analyses:
  - name: explore
    docs:
      node_color: "black"
```
