### ISSUE TITLE
[CT-1282] [Bug] Cannot reference a Source containing a dot (.) in node selection

### ISSUE THREAD

**Issue by rossserven** [dbt-labs/dbt-core#5980]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Trying to reference a Source through node selection and I’m running into an issue because our sources contain periods.  e.g.:
```
sources:
  - name: raw.test
    database: 'RAW'
    schema: 'TESTING'
    tables:
      - name: TEST_TABLE

```
so this doesn’t work: `source:raw.test.TEST_TABLE`
however if it’s defined as:
```
sources:
  - name: test
    database: 'FIVETRAN_RAW'
    schema: 'TESTING'
    tables:
      - name: TEST_TABLE

```
this works: `source:test.TEST_TABLE`

### Expected Behavior

```
sources:
  - name: raw.test
    database: 'RAW'
    schema: 'TESTING'
    tables:
      - name: TEST_TABLE

```
this should work (or optionally enclosed with quotes): `source:raw.test.TEST_TABLE`

### Steps To Reproduce

1. define a Source with a dot/period
2. Attempt to reference that source in node selection

### Relevant log output

```shell
[0m15:38:00 No nodes selected!
[0m15:38:00 'source:raw.test.TEST_TABLE' does not match any nodes
```

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

snowflake
