### ISSUE TITLE
[CT-1305] Defining Target specific grants via models/schema.yml file

### ISSUE THREAD

**Issue by minhajpasha** [dbt-labs/dbt-core#6017]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Hello ,
Dbt version :1.2
We have 3 git branches
develop - pointing to bigquery GCP dev project
uat - pointing to bigquery GCP uat project
prod - pointing to bigquery GCP prod project.
If we use the Grant in models/schema.yml file as below , when the models gets executed in dev(by developers), uat(by QA) and prod(LIVE box) the required access will granted in all the 3 environments.

name: student
description: “student table”
config:
grants:
roles/bigquery.dataViewer: [‘user:someone@yourcompany.com’]
I want this role to be granted in specific target . For eg: i want above grant to be applied in uat environment only.

### Describe alternatives you've considered

I have used below alternative 
{% if target.name == 'dev' %}
    {{ config(grants = {'roles/bigquery.dataViewer': ['user:someone@yourcompany.com']}) }}

{% elif target.name == 'uat' %}
    {{ config(grants = {'roles/bigquery.dataViewer': ['user:sometwo@yourcompany.com']}) }}

{% elif target.name == 'prod' %}
    {{ config(grants = {'roles/bigquery.dataViewer': ['user:somethree@yourcompany.com']}) }}
{% endif %} 

### Who will this benefit?

The Grants which are defined in yml file will be applied to specific target environment.

### Anything else?

https://discourse.getdbt.com/t/using-grants-in-a-target-specific-way/4981/6

**Comment by jtcohen6** [comment]
@minhajpasha Thanks for opening!

Thanks also for opening up a discourse thread about this: https://discourse.getdbt.com/t/using-grants-in-a-target-specific-way/4981

I believe you could accomplish this with a conditional Jinja expression inside a yaml file:
```yml
version: 2
models:
  - name: students
    description: "student table"
    config:
      grants:
        "roles/bigquery.dataViewer":
          - "{%- if target.name == 'dev' -%}user:someone@yourcompany.com
             {%- elif target.name == 'uat' -%}user:someonetwo@yourcompany.com
             {%- elif target.name == 'prod' -%}user:someonethree@yourcompany.com
             {%- endif -%}"
```
If you find yourself typing that over and over, I imagine you'll want to DRY that up, such as by wrapping that logic in a macro that returns the appropriate user given the `target.name`. Unfortunately, custom macros aren't supported for configuration in `.yml` files today. At that point, it would make more sense to call it from within your model `.sql` files:
```sql
{% macro grantee_based_on_target() %}
    {%- if target.name == 'dev' -%}
        {{ return({"roles/bigquery.dataViewer": "user:someone@yourcompany.com"}) }}
    {%- elif target.name == 'uat' -%}
        {{ return({"roles/bigquery.dataViewer": "user:someonetwo@yourcompany.com"}) }}
    {%- elif target.name == 'prod' -%}
        {{ return({"roles/bigquery.dataViewer": "user:someonethree@yourcompany.com"}) }}
    {%- endif -%}
{% endmacro %}
```
```sql
{{ config(grants = grantee_based_on_target() }}
```
You could also accomplish the per-environment configuration with an environment variable:
```yml
version: 2
models:
  - name: students
    description: "student table"
    config:
      grants:
        "roles/bigquery.dataViewer": ["{{ env_var( 'DBT_GRANTEE_ON_STUDENTS') }}"]
```
I'm going to close this issue, as I think we have the right constructs already in place to support this pattern — though I appreciate that the most-ergonomic future answer here will look like a way to support defining custom functions and passing them into `.yml` configuration.

**Comment by minhajpasha** [comment]
Thanks for your reply @jtcohen6 ,
When i tried "Jinja expression inside a yaml file::"
 it throws me back below error:
  File "/opt/homebrew/Cellar/dbt-bigquery/1.2.0/libexec/lib/python3.9/site-packages/dbt/parser/schemas.py", line 523, in parse_file
    parser.parse()
  File "/opt/homebrew/Cellar/dbt-bigquery/1.2.0/libexec/lib/python3.9/site-packages/dbt/parser/schemas.py", line 703, in parse
    source = self._target_from_dict(UnparsedSourceDefinition, data)
  File "/opt/homebrew/Cellar/dbt-bigquery/1.2.0/libexec/lib/python3.9/site-packages/dbt/parser/schemas.py", line 678, in _target_from_dict
    raise ParsingException(msg) from exc
dbt.exceptions.ParsingException: Parsing Error

- at path []: Additional properties are not allowed ('grants' was unexpected)
15:11:10  Encountered an error:
Parsing Error

Above macro works if we have generic grants for database, but the use case here is that the grants should be specific to table level . Also we can't write specific marco for each sql model. The best place to define grants is in schema.yml(if it works to handle different grants based on target.name or to define in sql model.

**Comment by jtcohen6** [comment]
> `at path []: Additional properties are not allowed ('grants' was unexpected)`

@minhajpasha Are you nesting the `grants` config within a `config` block? That's important to avoid this error:
```yml
# models/anything.yml
version: 2
models:
  - name: students
    description: "student table"
    config: # <-- need this
      grants:
```
I just edited the comment above to also make it clear that the yaml I'm showing is for `models/*.yml`, not `dbt_project.yml`.
