### ISSUE TITLE
[CT-1317] Validate source config enabled flag

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#6030]
There is no validation of the "enabled" config flag for sources, whether in dbt_project.yml or in a schema file. This means that people can set the flag to strange things such as "False and False" and it will be saved with no error message.

**Comment by emmyoop** [comment]
There doesn't seem to be validation for the enabled config for metrics and exposures either.  Exposures seem to behave like sources.  Metrics will fail, but with a misleading error message.

This `schema.yml`

```yaml
version: 2

metrics:

  - name: number_of_people
    label: "Number of people"
    description: Total count of people
    model: "ref('people')"
    calculation_method: count
    expression: "*"
    timestamp: created_at
    time_grains: [day, week, month]
    dimensions:
      - favorite_color
      - loves_dbt
    meta:
        my_meta: 'testing'

  - name: collective_tenure
    label: "Collective tenure"
    description: Total number of years of team experience
    model: "metric('number_of_people')"
    calculation_method: sum
    expression: tenure
    config:
      enabled: False and False
    timestamp: created_at
    time_grains: [day]
    filters:
      - field: loves_dbt
        operator: 'is'
        value: 'true'
```

results in 

```bash
Compilation Error in metric collective_tenure (models/metric_y.yml)
  Metric 'metric.basic_dbt.collective_tenure' (models/metric_y.yml) depends on a metric named 'number_of_people' which is disabled
```

When in fact `collective_tenure` has an invalid config and `number_of_people` is enabled.
