### ISSUE TITLE
[CT-1338] [Bug] generate_schema_name not available for sources

### ISSUE THREAD

**Issue by jayhale** [dbt-labs/dbt-core#6056]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using a source configuration like this:
```yml
version: 2
source:
  - name: source_a
    schema: "{{ generate_schema_name("BRONZE") }}"
    # ...
```

compiling the project fails:
```
dbt.exceptions.CompilationException: Compilation Error
  Could not render {{ generate_schema_name('BRONZE') }}: 'generate_schema_name' is undefined
```

and requires a workaround like:
```yml
version: 2
source:
  - name: source_a
    schema: "{{ 'bronze' if target.name.startswith('prod') else target.schema }}"
    # ...
```

### Expected Behavior

`generate_schema_name` should be available for source configuration similar to the way it can be used for model configuration.

### Steps To Reproduce

See above

### Environment

```markdown
- OS: OSX
- Python: 3.10
- dbt: 1.2.2
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

Related: https://github.com/dbt-labs/dbt-core/issues/4753
