### ISSUE TITLE
[Bug] Source not evaluated properly when used in a `set` block which is then assigned to a hook in a model file

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#6058]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

It looks like source doesn't work properly when it's being used in a `set` jinja block + used in a hook.

### Expected Behavior

`source()` should evaluate properly.

### Steps To Reproduce

1. Setup profile.

```yaml
# ~/.dbt/profiles.yml

snowflake:
  target: dev
  outputs:
    dev:
      database: development   # Just to show the default (I think is not relevant here).
      ...
```

2. `dbt_project.yml` - nothing special.

```yaml
# dbt_project.yml

name: "my_dbt_project"
version: "1.0.0"
config-version: 2
profile: "snowflake"

models:
  my_dbt_project:
    +materialized: table
```

3. Sources.

```yaml
version: 2
sources:
  - name: my_sources
    database: analytics  # Override default of 'development'
    tables:
      - name: my_source
```

3. Setup model.

```sql
-- models/foo.sql

{% set my_var -%}
    update {{ source('my_sources', 'my_source') }} set foo = 'bar'
{%- endset %}

{{ config(post_hook = 'select 2 -- ' ~ my_var) }}

select 1 as id -- {{ source('my_sources', 'my_source') }}
```

4. Run our models:

```
$ dbt --debug run | grep -E 'select 1|select 2'

select 1 as id -- analytics.my_sources.my_source
select 2 -- update development.dbt_jyeo.foo set foo = 'bar'
```

Clearly `{{ source('my_sources', 'my_source') }}` evaluated correctly when it's in the body of the model but when we declare it in a `set` and then assign that to a hook, it becomes weird (evaluates to the `{{ this }}` for some reason).

### Environment

```markdown
- OS: macOS
- Python: 3.8.7
- dbt: 1.2.1
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

I know this is not best practice but more so for understanding why this is happening. 

For readers, to make this work properly, we could do something like:

1. Add a macro:

```sql
-- macros/update.sql
{% macro update_something(arg) %}
    select 2 -- update {{ arg }} set foo = 'bar'
{% endmacro %}
```

2. Tweak our model:

```sql
-- models/foo.sql

{{ config(post_hook = "{{ update_something(source('my_sources', 'my_source')) }}") }}

select 1 as id -- {{ source('my_sources', 'my_source') }}
```

3. Run:

```
$ dbt --debug run | grep -E 'select 1|select 2'

select 1 as id -- analytics.my_sources.my_source
select 2 -- update analytics.my_sources.my_source set foo = 'bar'
```
