### ISSUE TITLE
[CT-1346] [Feature] Extend grants config to include usage grants

### ISSUE THREAD

**Issue by AlexFrid** [dbt-labs/dbt-core#6063]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

[#5189 ](https://github.com/dbt-labs/dbt-core/issues/5189) and [#5263](https://github.com/dbt-labs/dbt-core/issues/5263) introduced grants as node configs.

This feature request seeks to extend the grants config to include usage grants as well.

Currently, we can do this:
```
models:
  +grants:
    select: ['reporter', 'bi']
```
    
 The extended version could look very similar:
```
models:
  +grants:
    select: ['reporter', 'bi']
    warehouse: ['transform']
    database: ['prod']
    schema: ['analytics']
```
or 
```
models:
  +grants:
    select: ['reporter', 'bi']
    usage:
      - warehouse: ['transform']
      - database: ['prod']
      - schema: ['analytics']
```

### Describe alternatives you've considered

The current recommended way of doing usage grants is by using [on-run-end ](https://docs.getdbt.com/reference/project-configs/on-run-start-on-run-end#grant-privileges-on-all-schemas-that-dbt-uses-at-the-end-of-a-run)
Example:
```
on-run-end:
  - "{% for schema in schemas %}grant usage on schema {{ schema }} to group reporter; {% endfor %}"
```

A similar approach is also in the dbt labs partner engineering team [demos](https://github.com/dbt-labs/snowflake_dbt_partner_demo/blob/main/dbt_project.yml)) 

### Who will this benefit?

This will benefit the same people who appreciate [grants as node configs ](https://github.com/dbt-labs/dbt-core/issues/5189) and push the envelope further in terms of how dbt can enable people to configure grants.

As select grants are often used in conjunction with usage grants, this will allow people to consolidate their workflow to fully use the grants config for standard things, instead of having it fragmented between the grants config for select grants and on-run-end for usage grants.

The dbt labs partner engineering team noticed that this would be useful as we updated our demos and enablement recommendations to use the grants config, but couldn't fully replace our current macro since we are using usage grants.

@ernestoongaro has also noticed people asking about this.

### Are you interested in contributing this feature?

Yes
