### ISSUE TITLE
[Feature] Add column type constraints as dbt native configs

### ISSUE THREAD

**Issue by sungchun12** [dbt-labs/dbt-core#6079]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

**Problem**:
- Data types are created after the fact(assumed by the database) and/or a dbt user has to explicitly cast data types in their SQL. Because of this, there isn't much incentive to assure dbt models have expected data types for consumers to depend on(it's tedious work :/). This may not be a problem for 50 dbt models, but becomes a big problem when you have 2000+ dbt models. There should be an easier way to configure data type constraints for any dbt models and provide options to enable/disable data type enforcement(think: what [mypy](http://mypy-lang.org/) does for the python static typing experience).

**Solution**:
- Bring data types as native to the dbt experience
- Example BigQuery Constraints Macro:https://gist.github.com/sungchun12/f7ea081773ae824a83294649530d6e41
- Related discussion: https://github.com/dbt-labs/dbt-core/discussions/5244#discussioncomment-3880254

### Describe alternatives you've considered

Custom Materialization Macro in BigQuery: https://www.loom.com/share/1f1f190e66254d12984962c613e8082d

This is a general design pattern, but uses meta configs to enable this functionality. 

### Who will this benefit?

dbt users with large projects that need extra robustness in their developer experience and downstream users get the data they expect: data types and all. 

### Are you interested in contributing this feature?

yes, and I'll be working with someone in the community @jonathanneo

### Anything else?

**Research:** 
- Postgres Constraints: https://www.postgresql.org/docs/current/ddl-constraints.html#id-1.5.4.6.6
- Snowflake ONLY enforces `not null` constraints, the rest are nice to have metadata: https://docs.snowflake.com/en/sql-reference/constraints-overview.html#supported-constraint-types
- BigQuery Macro Demo: https://www.loom.com/share/1f1f190e66254d12984962c613e8082d

**Considerations:**
- have the configs embedded in dbt-core and then each adapter can take stable configs to adjust table materialization macros
- Enforce column positions based on schema config
- dbt-core contains the hub of native configs while adapters own specific implementations as each database has nuances to which enforceable constraints are valid.
-  think about not null and default values for a table
- Work with Jon Neo from Canva
- Include a `check` constraint as pgsql enables it? 
- What if constraints could be defined once within a subfolder path in dbt_project.yml and then in automatically creates not null constraints in the DDL?
- Leverage how seed configs enable data types

**Comment by sungchun12** [comment]
What this could look and feel like in snowflake: https://www.loom.com/share/14020499f5f646b6bc80c909716850fd

**Comment by sungchun12** [comment]
What if we add `enum` data types to prevent dbt users from having to run accepted values tests?

```yml
version: 2
models:
  - name: constraints_example
    config:
      constraints_enabled: true
    columns:
      - name: color
        column_type: varchar
        constraint: value in ('red', 'green', 'yellow', 'blue')
      - name: shape
        column_type: enum('square', 'circle', 'triangle')
```

**Comment by jonathanneo** [comment]
Good spike! Just in time too, more and more data warehouse providers are adding constraints into their table definitions. For example, databricks have just added table constraints in October 2022: https://docs.databricks.com/tables/constraints.html

**Comment by sungchun12** [comment]
A couple notes on design and scoping

**dbt-core design:**
- Ensure the below is allowed and contains defensive code for when `constraints_enabled: true` that it requires other schema config values are filled in and are not blank
- `constraints_enabled` should have overrides similar to `node_color` configs: `<example-sql-file.sql> `overrides `schema.yml` overrides `dbt_project.yml`

```sql
--example sql file config

{{
  config(
    materialized = "table",
    constraints_enabled = true
  )
}}

select 
  1 as id, 
  'blue' as color, 
  cast('2019-01-01' as date) as date_day
```

```yml
# schema.yml
version: 2

models:
  - name: constraints_example
    config:
      constraints_enabled: true
    columns:
      - name: id
        column_type: integer
        description: I want to describe this one, but I don't want to list all the columns
        constraint: not null
      - name: color
        column_type: string
      - name: date_day
        column_type: date
        default_value: CURRENT_DATE()
```

```yml
# dbt_project.yml
models:
  +constraints_enabled: true # enforce all models have constraints typed
  dbt_artifacts:
    +docs:
      show: false
    +schema: dbt_artifacts_sung
    staging:
      +schema: dbt_artifacts_sung
  tpch:
    staging:
      database: '{{ env_var("DBT_DYNAMIC_DATABASE","analytics") }}'
      +materialized: view
      +docs:
        node_color: "#FB6962"

    marts:
      intermediate:
        +constraints_enabled: false # overrides the root level enforcement
        +docs:
          node_color: "#3AAAE0"
      core:
        +tags: "owner:sung"
        materialized: table
        +docs:
          node_color: "#F6AE3E"
```


**adapter design:**
- Works with guaranteed configs from `dbt-core` and dynamically injects those config values into the table materialization
- Each adapter will have their own flavor of table materialization jinja code adjustments
- Specific adapters(Databricks, Postgres) allow `check` constraints while BigQuery and Snowflake do not, there will need to be defensive terminal logs to state to the user when their `check` config is not allowed based on the database
- Each adapter needs to provide guardrails for data types allowed. For example, snowflake interprets `string` as `VARCHAR(38)`, `integer` as `NUMBER(1,0)`. How much should an adapter enforce strict typing according to database syntax?
- Example places in snowflake adapter to make jinja changes: https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/include/snowflake/macros/adapters.sql#L1, https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/include/snowflake/macros/materializations/table.sql#L1
