### ISSUE TITLE
[Bug] Duplicated source when seed and model paths overlap

### ISSUE THREAD

**Issue by jmg-duarte** [dbt-labs/dbt-core#6102]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If I have the following structure:
```
proj_name/
- data_provider
  - seeds
  - models
    - sources.yml
- < consider the previous structure repeated for N providers >
```

And the following configuration:
```yml
model-paths: 
  - proj_name/data_provider/
seed-paths: 
  - proj_name/data_provider
```

I will get an error like:
```
10:32:20  Running with dbt=1.3.0
10:32:21  Encountered an error:
Compilation Error
  dbt found two sources with the name "some_source".
  
  Since these resources have the same name, dbt will be unable to find the correct resource
  when looking for source("data_provider", "some_source").
  
  To fix this, change the name of one of these resources:
  - source.proj_name.data_provider.some_source (proj_name/data_provider/models/sources.yml)
  - source.proj_name.data_provider.some_source (proj_name/data_provider/models/sources.yml)
```

I am aware that I can do:
```yml
model-paths: 
  - proj_name/data_provider/models
seed-paths: 
  - proj_name/data_provider/seeds
```
But this is not practical for several data providers, furthermore, as the data in question is usually not mixed with other providers, we would like to keep the structure as close as it is.

### Expected Behavior

No name clash.

My intuition says that sources shouldn't be analysed when searching for seeds, but there may be a reason behind this.

### Steps To Reproduce

Described in current behavior.

### Relevant log output

```shell
Described in current behavior.
```

### Environment

```markdown
- OS: MacOS
- Python: 3.8.10
- dbt: 1.3.0
```

### Which database adapter are you using with dbt?

snowflake
