### ISSUE TITLE
[CT-1394] [Feature] metrics should infer semantic information from models

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-core#6131]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Right now, metrics are tightly scoped to a single unit of analysis within the bounds of a single model. the semantic layer should allow analytics engineers to more flexibly declare these metric attributes for improved and simplified metric definition, as well as future looking features, like joining models within metric definitions. 

Here's a samply yml file with additional semantic attributes declared:

```yml
version: 2

models: 
  - name: fct_orders
    is_public: true
    relationships:
      - to: dim_customers
        join_key: customer_id
        relationship_type: many_to_one

    columns:
      - name: order_id
        is_primary_key: true
        data_type: integer
        tests:
          - unique
          - not_null

      - name: customer_id
        is_dimension: false
        data_type: integer
      
      - name: state
        is_dimension: true
        data_type: string


  - name: dim_customers
    is_public: true
    columns:
      - name: customer_id
        is_primary_key: true
        data_type: integer
      
      - name: is_nice
          
      - name: species
        is_dimension: true
        data_type: string
```

Here, we're declaring:
 - which subset of the columns of each of these models are the primary keys, and which are available to be selected as metric dimensions
 - how models join together, and the nature of their relationship
 - that models are "public" -- which allows users to more easily declare which models should be accessible by others (i.e. give a mechanism to allow metrics to inherit this semantic info, but also keep the existing functionality the same -- you can still declare a single metric on a single model without issue)

Then, if I had these two metrics, I would have access to all dimensions in `fct_orders` and `dim_customers` due to the declared relationship:

```yml
version: 2

metrics:
  - name: total_customers
    label: Total Customers
    model: ref('dim_customers')
    calculation_method: count
    expression: order_id

    timestamp: report_date
    time_grains: [day, week, month, all_time]


  - name: total_orders
    label: Total Orders
    model: ref("fct_orders")
    calculation_method: count
    allow_joins: False
    expression: order_id

    timestamp: report_date
    time_grains: [day, week, month, all_time]
```

There's some additional mechanisms here that will need to be ironed out, but the goal is to explore the ergonomics of using the model yml to house semantic info that can be leveraged by metrics!

### Describe alternatives you've considered

- Creating new node types to house this semantic info -- i.e. an Entity
- Extending exposures to contain semantic info

### Who will this benefit?

Semantic Layer users new and old!

### Are you interested in contributing this feature?

I am!
