### ISSUE TITLE
[Feature] Support lineages between sources

### ISSUE THREAD

**Issue by andrewcstewart** [dbt-labs/dbt-core#6143]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Sources are a great way to bootstrap a dbt project by documenting 'references' to existing tables, but source tables often have lineages relationships which cannot currently be represented in dbt.  The source layer is essentially 'flat'.  It would be valuable from a primarily documentation perspective if any known lineage between sources could be encoded in their configuration so as to be rendered in the DAG.

The syntax could probably borrow the `depends_on` property from `exposures`, as follows:

```
version: 2

sources:
  - name: my_sources
    tables:
      - name: first_upstream_source
      - name: second_upstream_source
      - name: downstream_source
        depends_on:
          - first_upstream_source
          - second_upstream_source
```

Instead of rendering the DAG like this: 

```mermaid
flowchart LR
   a[first_upstream_source]
   c[downstream_source]
   b[second_uptream_source]
   c --> s1[stg_downstream]
   s1 --> m1[my_model]
   
   style a fill:lightgreen
   style b fill:lightgreen
   style c fill:lightgreen
   style s1 fill:cyan
   style m1 fill:cyan
```

...it could be rendered instead like this:

```mermaid
flowchart LR
   a[first_upstream_source] --> c[downstream_source]
   b[second_uptream_source] --> c
   c --> s1[stg_downstream]
   s1 --> m1[my_model]
   
   style a fill:lightgreen
   style b fill:lightgreen
   style c fill:lightgreen
   style s1 fill:cyan
   style m1 fill:cyan
```

### Describe alternatives you've considered

One could potentially use the `meta` property to at least document the relationships between sources:

```
version: 2

sources:
  - name: my_sources
    tables:
      - name: first_upstream_source
      - name: second_upstream_source
      - name: downstream_source
        meta:
          depends_on:
            - first_upstream_source
            - second_upstream_source
```

Of course this wouldn't have any functional value.

### Who will this benefit?

dbt users who need to document upstream data lineages that are beyond their jurisdiction to reimplement with dbt but still wish to document.

### Are you interested in contributing this feature?

Maybe?
