### ISSUE TITLE
[CT-1436] Treat warnings as errors for specific events, based on user configuration

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6165]
Today, `--warn-error` is a simple on/off switch that turns _all_ warnings into errors. We've gotten multiple requests (https://github.com/dbt-labs/dbt-core/issues/4383, https://github.com/dbt-labs/dbt-core/issues/6080) from users who want finer-grained control for raising errors on specific types of warnings.

We should allow users to configure exactly which event classes they want to raise as exceptions instead of warnings. This will be enabled by https://github.com/dbt-labs/dbt-core/pull/6064, which will turn all `warn_or_error` call sites into structured events.

**Where should this configuration live?** It feels like "runtime" config, rather than something that goes in project code. But it might be awkward to pass as a CLI flag or env var. The best places feels like the "user config" which currently lives in `profiles.yml`.
```yml
config:
  warn_error: true     # all of them

config:
  warn_error_events:  # scoped down to specific events
    - NoNodesForSelectionCriteria
    - UnusedResourceConfigPath
```

```python
def warn_or_error(event, node):
    # pseudo code!
    if flags.WARN_ERROR or type(event) in flags.WARN_ERROR_EVENTS:
        from dbt.exceptions import raise_compiler_error
        raise_compiler_error(scrub_secrets(event.info.msg, env_secrets()), node)
    else:
        fire_event(event)
```

**Comment by emmyoop** [comment]
We need to define how we want this to behave a bit more concretely by allowing include or exclude of specific warn events.

Error for all events _except_ the ones listed
```yaml
config:
  warn_error: true     # all of them

config:
  warn_error_override:
    - NoNodesForSelectionCriteria
    - UnusedResourceConfigPath
```

Warn for all events _except_ the one listed
```yaml
config:
  warn_error: false     # none of them (default)

config:
  warn_error_override:
    - NoNodesForSelectionCriteria
    - UnusedResourceConfigPath
```

Question: Should there be separate configs for what to include/exclude from the list based on if `warn_error` is true/false or a single config that just swaps including or excluding specific events.

**Comment by jtcohen6** [comment]
I like the framing of this as `_override`!

**Comment by emmyoop** [comment]
As part of this work, we should remove `warn_or_error` entirely to make the `warn_error` config work for _all_ warnings, not just a subset.

**Comment by github-christophe-oudar** [comment]
It would be great to be able to scope the related configuration so that in a large project you could keep warnings on a project/directory/package while raising errors on others.

It would look like:
```
models:
 my_project:
    team1:
      warn_error_override:
        include:
          - NoNodesForSelectionCriteria
          - UnusedResourceConfigPath
```

`include` / `exclude` would allow simple declaration for those site specific configurations.

**Comment by github-christophe-oudar** [comment]
I agree that supporting a global level should cover most use cases.

I agree that playing prefix decorator would be pretty confusing inside a YAML file.
`default` doesn't feel very explicit though.
Yet it's hard to find a better wording, maybe `any_warning: true`?

**Comment by leahwicz** [comment]
@nathaniel-may comment- Choose what to be warned on and then raise warnings to errors

What is the scenario when there is a mix of warnings and errors? Warning for config missing or isn't there.

**Comment by jtcohen6** [comment]
My understanding of Nate's proposal:
- Flag specific warnings to be ignored
- `warn_error` is still a simple on/off, for all non-ignored warnings
- We'd want to disambiguate between warnings in the sense of "bad configuration," and warnings in the sense of tests + source freshness checks with a certain status result

The appeal of that approach is it's more in keeping with the standard practice of other compilers. The downside is losing some of the flexibility that the more-complex configuration (proposed in this issue) would enable.

**Comment by emmyoop** [comment]
Looking into the code I would say we actually have three types of warnings: deprecations, bad configs and tests + source freshness checks.  Both deprecations and configs are already implemented differently since they are both utilizing [warn_or_error](https://github.com/dbt-labs/dbt-core/blob/987764858b81b95d8b93dcce67a4a9aace532ba3/core/dbt/events/functions.py#L215-L221) where tests and source configs are setting the result status based on if the `warn-error` flag is set but do not use `warn_or_error`.

1. _Deprecations_ - it seems safe to never allow these to be treated as errors.
2. _Bad Configs_ - We have had community members asking to be able to turn specific warnings of this class into errors in the past(linked in original issue body).  The big question is if this is something we want to support (I think yes) and to what extent/customizability?
3. _tests + source freshness checks_ - To allow this to be triggered to fail, it would just require using a separate flag since it's really one type of warning, just a different type.  The `warn-error` flag could just get deprecated at some point.  The problem here would be clearly defining what wins (or throwing an error when old and new flags are used within the same project)

Looking at other compilers:
[C#](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings) covers its bases with
```
TreatWarningsAsErrors / -warnaserror: Treat all warnings as errors
WarningsAsErrors / -warnaserror: Treat one or more warnings as errors
WarningsNotAsErrors / -warnnotaserror: Treat one or more warnings not as errors
NoWarn / -nowarn: Set a list of disabled warnings.
```

[GCC](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html) actually does something similar where you can
1. Make all warnings errors
2. Make a specified warning an error
3. Specify a warning to _not_ become an error even when you've already indicated _all_ warnings should be errors

Making a note to not lose it: `mypy` does something similar with error codes ([disable_error_codes](https://mypy.readthedocs.io/en/stable/config_file.html#confval-disable_error_code) and [enable_error_codes](https://mypy.readthedocs.io/en/stable/config_file.html#confval-enable_error_code)) but is not exactly the same as what we're trying to do.  The interesting thing is that it's two separate configs and they also make the executive decision that `(enable_error_codes)... will override disabled error codes from the disable_error_code option`.  So if both are filled it's well documented what wins while also having explicit fields.

**Comment by MichelleArk** [comment]
A functionally similar configuration syntax was recently proposed in the [dbt should know more about semantic information issue](https://github.com/dbt-labs/dbt-core/issues/6379). It turns out that entity definitions also need to provide an overall true/false option, plus some additional include/exclude modifications.

Implementing the same configuration syntax for `warn_error` would need some custom validation (expecting valid exception class names, not column names), but would have the benefit of a consistent experience with what's being proposed for entities. Below are a few examples of the syntax applied to the `warn_error` config:

```yaml
# all warnings are treated as exceptions, same as warn_error: true
warn_error: 
  include: *  

# all warnings are treated as exceptions except NoNodesForSelectionCriteria, UnusedResourceConfigPath
warn_error: 
  include * 
  exclude: 
    - NoNodesForSelectionCriteria
    - UnusedResourceConfigPath 

# only NoNodesForSelectionCriteria, UnusedResourceConfigPath are treated as errors
warn_error: 
  include: 
    - NoNodesForSelectionCriteria
    - UnusedResourceConfigPath 

# invalid - exclude only supported when include is '*'
warn_or_error: 
  include:
    - ThisEvent
    - ThatEvent 
  exclude: 
    - NoNodesForSelectionCriteria
    - UnusedResourceConfigPath 

# invalid
warn_error: 
  exclude: * 
```
