### ISSUE TITLE
[CT-1464] What should config UX feel like(think: setting and updating configs, terminal logs, defensive behaviors to prevent users causing unintended effects)?

### ISSUE THREAD

**Issue by sungchun12** [dbt-labs/dbt-core#6195]
**Success Criteria**
- [x] Potential "gotcha" implementations based on the above(think: if we update this file here, we have to update 100 files downstream)
- [x] pseudo-code snippets on initial approach for the above to make this functionality work

**Comment by sungchun12** [comment]
How does dbt do error handling when multiple files have bad configs?

**Comment by sungchun12** [comment]
```sql
--example sql file config

{{
  config(
    materialized = "table",
    constraints_enabled = true
  )
}}

select 
  1 as id, 
  'blue' as color, 
  cast('2019-01-01' as date) as date_day
```

```yml
# schema.yml
version: 2

models:
  - name: constraints_example
    config:
      constraints_enabled: true
    columns:
      - name: id
        data_type: integer # required and errors if NOT all columns have defined data types
        description: I want to describe this one, but I don't want to list all the columns
        constraint: not null # optional for all adapters
        check: price > 0 # optional for all adapters, we keep this separate because constraints(built-in) are different from checks(custom)
      - name: color
        data_type: string
      - name: date_day
        data_type: date
        default_value: CURRENT_DATE()
```

```yml
# dbt_project.yml
models:
  +constraints_enabled: true # enforce all models have constraints typed
  dbt_artifacts:
    +docs:
      show: false
    +schema: dbt_artifacts_sung
    staging:
      +schema: dbt_artifacts_sung
  tpch:
    staging:
      database: '{{ env_var("DBT_DYNAMIC_DATABASE","analytics") }}'
      +materialized: view
      +docs:
        node_color: "#FB6962"

    marts:
      intermediate:
        +constraints_enabled: false # overrides the root level enforcement
        +docs:
          node_color: "#3AAAE0"
      core:
        +tags: "owner:sung"
        materialized: table
        +docs:
          node_color: "#F6AE3E"
```
