### ISSUE TITLE
[CT-1471] [Bug] YAML Selectors: `children: true` does not work with `method: selector`

### ISSUE THREAD

**Issue by seub** [dbt-labs/dbt-core#6212]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

As far as I can tell, `children: true` is ignored when used with `method: selector`. 

```
selectors:
  - name: my_selector
    definition: ...
  - name: my_selector_children
    definition:
      method: selector
      value: my_selector
      children: true
```

The code above only selects the nodes of `my_selector`, not its children. (With other methods such as `tag`, it does select the children as expected).

### Expected Behavior

Should select all the nodes of `my_selector` **and** all the children nodes.

### Steps To Reproduce

Try the code in "Current Behavior"

### Environment

```markdown
- OS:
- Python:
- dbt:
```
