### ISSUE TITLE
[CT-1478] [Bug] No `target/{compiled|run}/model_doc.yml/testname.slq` file if test has `name:` property

### ISSUE THREAD

**Issue by Gregory108** [dbt-labs/dbt-core#6223]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

All tests, if their names are derived from test technical names (e.g. `accepted_values` or `dbt_utils.expression_is_true`), have a compiled SQL version in `/compiled/` and `/run/` folders.
However, if I define `name:` property of the test, no such compiled version is created.

PS: not sure this problem can be spotted with `unique` or `not_null` tests, because they do not allow `:` with `name:` property after

### Expected Behavior

There is a compiled sql file for the test with the `name:` as defined in the property or, at least, derived from the test technical name.

### Steps To Reproduce

1. For any model, create documentation with a test like this and property `name:`
``` yaml
version: 2

models: 
  - name: test_model
    description: "A model with UID filed name `id`"
    columns:
      - name: id
        tests:
           - accepted_values:
               name: "Test test name"
```
2. Build the model
3. go to `target/{compiled|run}/test_model_path/test_model.yml/*` and you would not find `.sql` corresponding to this test

### Environment

```markdown
- OS: Windows 11
- Python: 3.10.8
- dbt: core=1.1.1 + bigquery=1.1.1
```
