### ISSUE TITLE
[CT-1571] [Feature] Allow parameterised selectors

### ISSUE THREAD

**Issue by jelstongreen** [dbt-labs/dbt-core#6343]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Allowing the use of parameterised macros to improve the usability of selector inheritance. As an example, if I have 3 selectors that run on schedules like:
```
selectors:
  - name: foo_and_bar_hourly
    definition:
      intersection:
        - tag: foo
        - tag: bar
        - tag: hourly
  - name: foo_and_bar_daily
    definition:
      intersection:
        - tag: foo
        - tag: bar
        - tag: daily
  - name: foo_and_bar_weekly
    definition:
      intersection:
        - tag: foo
        - tag: bar
        - tag: weekly
```

If I then want to use selector inheritance to add a version of the selectors where buzz is excluded I would need to add 3 new selectors:
```
selectors:
  - name: foo_bar_less_buzz_hourly
    definition:
      intersection:
        - method: selector
          value: foo_and_bar_hourly
        - exclude:
            - method: tag
              value: buzz
  - name: foo_bar_less_buzz_daily
    definition:
      intersection:
        - method: selector
          value: foo_and_bar_daily
        - exclude:
            - method: tag
              value: buzz
  - name: foo_bar_less_buzz_weekly
    definition:
      intersection:
        - method: selector
          value: foo_and_bar_weekly
        - exclude:
            - method: tag
              value: buzz
```

This feature would enable more consolidated selectors where selector args are used which are then passed to any inherited selectors:
```
selectors:
  - name: foo_and_bar
    args:
      - schedule
    definition:
      intersection:
        - tag: foo
        - tag: bar
        - tag: {schedule}
  - name: foo_bar_less_buzz
    args:
      - schedule
    definition:
      intersection:
        - method: selector
          value: foo_and_bar
        - exclude:
            - method: tag
              value: buzz
```

Which is then executed using 

`dbt build --selector foo_and_bar --selector_args {"schedule":"hourly"}`

or

`dbt build --selector foo_bar_less_buzz --selector_args {"schedule":"hourly"}`

Could even have more advanced uses like:
```
  - name: include_tags_schedule
    args:
      - include_tags
      - schedule
    definition:
      intersection:
        - method: tag
          value: [tag for tag in include_tags]
        - tag: {schedule}
  - name: include_exclude_tags_schedule
    args:
      - include_tags
      - exclude_tags
      - schedule  
    definition:
      intersection:
        - method: selector
          value:  include_tags_schedule
        - exclude:
          - method: tag
            value: [tag for tag in exclude_tags]
```

### Describe alternatives you've considered

Alternative solution is writing every selector for each use case and maintaining the list. 

### Who will this benefit?

Anyone with complex selectors using yamls

### Are you interested in contributing this feature?

Potentially although software engineering is not my area

**Comment by jtcohen6** [comment]
@jelstongreen Something like this, even?

```yml
selectors:
  - name: foo_and_bar
    args:
      - schedule
    definition:
      intersection:
        - tag: foo
        - tag: bar
        - tag: "{{ var('schedule') }}"
  - name: foo_bar_less_buzz
    args:
      - schedule
    definition:
      intersection:
        - method: selector
          value: foo_and_bar
        - exclude:
            - method: tag
              value: buzz
```
```
$ dbt build --selector foo_and_bar --vars '{"schedule":"hourly"}'
$ dbt build --selector foo_bar_less_buzz --vars '{"schedule":"hourly"}'
```

You can pass a second arg to `{{ var('var_name', 'default_value') }}` so you don't have to pass `--vars` from the CLI every time. You can use `{{ env_var(...) }}` here as well.

Going to close this one as resolved, I think. If you're up for it, you could [open a PR against the docs site](https://github.com/dbt-labs/docs.getdbt.com/edit/current/website/docs/reference/node-selection/yaml-selectors.md) to document this behavior, for the next person who wants the same thing :)
