### ISSUE TITLE
[CT-1741] [Bug] git deps "calls home" to hub even if installing from github

### ISSUE THREAD

**Issue by MazrimT** [dbt-labs/dbt-core#6502]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Due to security issues we can not install packages from dbt hub but have to use git repos isntead.
packages.yml file:

```yml
packages:
  - git: "https://github.com/dbt-labs/dbt-utils.git"
    revision: 0.8.0
  - git: "https://github.com/dbt-labs/dbt-event-logging"
    revision: 0.6.0
  - git: "https://github.com/calogica/dbt-date"
    revision: 0.5.0
```

git is correctly installed on the server and can be used to pull things from github through proxy

however it will not work through dbt deps and we get these debug messages:
```
Making package index registry request: GET https://hub.getdbt.com/api/v1/index.json
External call exception: HTTPSConnectionPool(host='hub.getdbt.com', port=443): Max retries exceeded with url: /api/v1/index.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f25dbc049d0>, 'Connection to hub.getdbt.com timed out. (connect timeout=30)'))
```

### Expected Behavior

if we're only installing through git there is no reason at all to be contacting hub.getdbt.com

### Steps To Reproduce

set up an environment where you can connect to github but not to hub.getdbt.com

### Relevant log output

```shell
Making package index registry request: GET https://hub.getdbt.com/api/v1/index.json
External call exception: HTTPSConnectionPool(host='hub.getdbt.com', port=443): Max retries exceeded with url: /api/v1/index.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f25dbc049d0>, 'Connection to hub.getdbt.com timed out. (connect timeout=30)'))
```

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)  (image running in kubernetes)
- Python: 3.9.15
- dbt: 1.3.1
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
Thanks for reaching out about this @MazrimT !

You are seeing this because of transitive dependencies. If you look at the dependencies of `dbt-event-logging` and `dbt-date`, you will see that they are specifying _their_ dependencies using the [`package` syntax](https://docs.getdbt.com/docs/build/packages#how-do-i-add-a-package-to-my-project) (which uses the dbt package hub rather than GitHub):
- https://github.com/dbt-labs/dbt-event-logging/blob/0.6.0/packages.yml
- https://github.com/calogica/dbt-date/blob/0.5.0/packages.yml

You have a few different options moving forward:
1. Fork the dbt packages you want to use and update their `packages.yml` files to use the [`git` syntax](https://docs.getdbt.com/docs/build/packages#how-do-i-add-a-package-to-my-project) instead of the `package` syntax (if applicable)
1. Host the dbt package hub yourself using [these](https://github.com/dbt-labs/hub.getdbt.com/blob/4584909205ba7102bbf0981d44e97f1c20475c4b/CONTRIBUTING.md) instructions and set the `DBT_PACKAGE_HUB_URL` environment variable for each of your dbt projects so that `dbt deps` knows where to look
1. Work with your security team to add https://hub.getdbt.com/ to the list of allowed hosts

**Comment by jtcohen6** [comment]
I think the new tarball-based approach (coming in v1.4, currently in beta) could also be an option here! Docs forthcoming: https://github.com/dbt-labs/docs.getdbt.com/issues/2474

You'd need to specify every package, plus all their dependencies, and do the version resolution yourself... which isn't fun, but, it works!
```yml
# packages.yml
packages:
  - tarball: https://codeload.github.com/dbt-labs/dbt-utils/tar.gz/0.8.0
    name: 'dbt_utils'
  - tarball: https://codeload.github.com/dbt-labs/dbt-event-logging/tar.gz/0.6.0
    name: 'logging'
  - tarball: https://codeload.github.com/calogica/dbt-date/tar.gz/0.5.0
    name: 'dbt_date'
```
```bash
$ dbt deps
14:49:49  Running with dbt=1.4.0-b1
14:49:49  Installing dbt_utils
14:49:50    Installed from tarball (url: https://codeload.github.com/dbt-labs/dbt-utils/tar.gz/0.8.0)
14:49:50  Installing logging
14:49:50    Installed from tarball (url: https://codeload.github.com/dbt-labs/dbt-event-logging/tar.gz/0.6.0)
14:49:50  Installing dbt_date
14:49:51    Installed from tarball (url: https://codeload.github.com/calogica/dbt-date/tar.gz/0.5.0)
```

This feels like "full control" mode. Zero requests to the Hub. It doesn't even need to shell out to `git` commands. This feels very much within the intended audience of dbt users at security-conscious orgs.
