### ISSUE TITLE
[CT-1762] [Bug] generate_schema_name_for_env() breaks generic tests in prod job.

### ISSUE THREAD

**Issue by cjcdoomed** [dbt-labs/dbt-core#6542]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using target set to `prod` and using `generate_schema_name_for_env(),` generic tests fail for the models that have schema set because tests are referencing the target schema, not the custom schema.

If you add the custom schema to the generic test, the test picks up the custom schema but the compiled sql is broken.

### Expected Behavior

* Tests should use the same schema as the models under test 
* Setting schema on test should not break the compiled sql

### Steps To Reproduce

1. Set your job target to be `prod` and command to be `dbt test`
2. Add the following macro as mentioned in https://docs.getdbt.com/docs/build/custom-schemas#an-alternative-pattern-for-generating-schema-names
``` 
{% macro generate_schema_name(custom_schema_name, node) -%}
    {{ generate_schema_name_for_env(custom_schema_name, node) }}
{%- endmacro %}
```
3. Define schema in the dbt_project.yml
```
models:
  my_dbt:
    # Config indicated by + and applies to all files under models/example/
    staging:
      database: MYDB
      +materialized: view
      model_folder_1:
        schema: custom
```

4. Create tests in `models/staging/model_folder_1/schema.yml`

```
version: 2

models:
  
  - name: stg_groups
    description: "Groups"
    columns:
      - name: group_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
```

5. Run the job which has `dbt test` command
6. Inspect the failed test artifact sql and notice that the schema is not the custom schema
```
select
      count(*) as failures,
      count(*) != 0 as should_warn,
      count(*) != 0 as should_error
    from (
      
    
    

select
    group_id as unique_field,
    count(*) as n_records

from MYDB.target.stg_groups
where group_id is not null
group by group_id
having count(*) > 1


      
    ) dbt_internal_test
```    

8. Try setting schema in `models/staging/model_folder_1/schema.yml`

```
version: 2

models:
  
  - name: stg_groups
    description: "Groups"
    schema: custom
    columns:
      - name: group_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
```

8. Run the job which has `dbt test` command again
6. Inspect the failed test artifact sql and notice that the schema is the custom schema but the sql template was broken
```

    
    

select
    group_id as unique_field,
    count(*) as n_records

from MYDB.custom.stg_groups
where group_id is not null
group by group_id
having count(*) > 1





```    

### Environment

```markdown
- OS: dbtCloud
- Python:
- dbt: 1.3.2
```
