### ISSUE TITLE
[CT-1772] [Feature] Unexpected DuplicateProjectDependencyError in `git` packages with common transitive dependency

### ISSUE THREAD

**Issue by GiorgioBaldelli** [dbt-labs/dbt-core#6552]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Let's say we have two projects, project A & project B. 

Both projects A and B import the same, custom dbt package from a git repository, let's call it example_package.

If we now modify project A's packages.yml to import project B, the package configurations would look like this:

Project A:

```
packages:
  - git: "https://gitlab.com/example/example_package.git"
    revision: main
  - git: "https://gitlab.com/example/project_b.git"
    revision: main
```

Project B:

```
packages:
  - git: "https://gitlab.com/example/example_package.git"
    revision: main
```

If we now attempt to run any dbt command on project A, for example `dbt deps`, we get the following error:

```Found duplicate project "example_package". This occurs when a dependency has the same project name as some other dependency.```

Is there a way to handle duplicate packages when using the git sytax to import custom, non-standard packages?

It looks like dbt may be able to handle duplicates only if we attempt to [import standard packages](https://docs.getdbt.com/docs/build/packages#how-do-i-specify-a-package) from dbt hub? The recommended solution in [this issue](https://github.com/dbt-labs/dbt-core/issues/2956) does not address situations in which the package is custom and does not therefore exist on dbt's package hub.

### Expected Behavior

dbt knows how to handle duplicate package import using the git syntax.

### Steps To Reproduce

Use the example package definition & attempt to run `dbt deps`.

**Comment by jtcohen6** [comment]
@GiorgioBaldelli Thanks for opening!

There have been a handful of issues similar to this one, although none that's _exactly_ the scenario you're outlining here:

- https://github.com/dbt-labs/dbt-core/issues/4946
- https://github.com/dbt-labs/dbt-core/issues/4975
- https://github.com/dbt-labs/dbt-core/issues/5374
- https://github.com/dbt-labs/dbt-core/issues/5410

> It looks like dbt may be able to handle duplicates only if we attempt to [import standard packages](https://docs.getdbt.com/docs/build/packages#how-do-i-specify-a-package) from dbt hub?

That's more or less correct. The simple fact is, there are more user-friendly things we can do when you specify a Hub `package`, versus a `git`, `local`, or `tarball` (new in v1.4!) package. The Hub API includes metadata about each package's dependencies on other packages, which we can use to resolve versions and deduplicate common transitive dependencies.

As @dbeatty10 mentioned in https://github.com/dbt-labs/dbt-core/issues/6502#issuecomment-1370428388, you _can_ optionally host the dbt package hub yourself, using [these](https://github.com/dbt-labs/hub.getdbt.com/blob/4584909205ba7102bbf0981d44e97f1c20475c4b/CONTRIBUTING.md) instructions, and set the `DBT_PACKAGE_HUB_URL` environment variable for each of your dbt projects so that `dbt deps` knows where to look (instead of hub.getdbt.com). That's a pretty significant amount of work on your end, though.

In the meantime, since you know that Project A depends on Project B which depends on `example_package`, could you just take the following approach?
```yml
# project_a/packages.yml
packages:
# this will be installed via project_b
#  - git: "https://gitlab.com/example/example_package.git"
#    revision: main
  - git: "https://gitlab.com/example/project_b.git"
    revision: main

# project_b/packages.yml
packages:
  - git: "https://gitlab.com/example/example_package.git"
    revision: main
```

I'm going to reclassify this from a `bug` to an `enhancement`. Unless I'm missing something, I think it would require a fairly significant lift to get this working, and it's not something we're likely to prioritize.
