### ISSUE TITLE
[CT-1871] [Feature] Spike research on deeper tie between derived metrics & entities

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-core#6683]
Part of #6626
--------

### What this issue entails?

This issue dovetails slightly with #6662 in that it stems from conversations with integration partners. Our friends in the Reverse ETL space understood the value of entities but mentioned that our current proposed solution would fail to address a key need of theirs: **metrics aggregated in specified ways.**

For example, let us say that we have two entities. `customers` and `orders`. In orders we have a metric called `revenue` which is a sum aggregation of the column `order_value`. Great! 

In a future where we support joins & relationships between `entities` this gets a bit more confusing. Let's say that our Reverse ETL friends want a metric for `customer_ltv`. They define it as the lifetime aggregation `revenue` for that customer. 

In a world where metrics are their own nodes and only contain relationships to their base entity, this gets ... tricky. There are three paths forward:
- They could aggregate `customer_ltv` as a field inside their model using generalized sql. 
- They could aggregate `revenue` using the metrics macros inside the model and alias it as a `customer_ltv` field.
- They could create a new metric called `customer_ltv` with the same definition as revenue but require that `customer_id` be used in any query (we would need to add this functionality).

All of these have their own weaknesses. In the first two, `customer_ltv` isn't actually represented as a metric because it exists in the underlying model. In the latter, it doesn't maintain the relationship between `revenue` and `customer_ltv` which means that any changes to the `revenue` metric wouldn't carry forward to `customer_ltv`.

### So what can we do 

Assuming a world where the example above is the case, how would we implement this in an ideal world? One solution is to allow `metrics` to be more tightly defined on top of one another beyond what is supported in `derived` metrics today. There are a few open questions about this implementation, perhaps most seriously how closely we tie the associated metrics with the querying of the entity. Do they always appear? Or are they conditional add ons depending on the query syntax?

<details>
<summary>Option One:</summary>

```yml
entities:
  - name: orders
    model: ref('fact_orders')
    dimensions:
      - include: all
      - exclude: 
          - order_id
          - order_value
          - order_timestamp

      - name: order_id
        column_name: order_id
        primary_key: true

      - name: order_timestamp
        column_name: order_timestamp
        default_timestamp: true
        time_grains: [day, week, month]

  - name: customers
    model: ref('dim_customers')
    dimensions:
      - include: all
      - exclude: 
          - user_id

      - name: user_id
        primary_key: true

metrics:
  - name: revenue
    entity: entity('orders')
    calculation_method: sum
    expression: order_value

  - name: customer_ltv
    entity: entity('customer')
    metric: metric('revenue') ##maybe??
    calculation_method: sum
    expression: metric('revenue') ##by primary key??
    time_grains: 
      - all
    group_by: somehow make it only group by primary key
```
</details>

**Alternative**:  This is an alternative path where we support defining metrics inside the entity. I am generally less supportive of this one because of the potential complication it adds to how we calculate lineage but we'll present it in the interest of completeness.

<details>
<summary>Option Two:</summary>

```yml
entities:
  - name: orders
    model: ref('fact_orders')
    dimensions:
      - include: all
      - exclude: 
          - order_id
          - order_value
          - order_timestamp

      - name: order_id
        column_name: order_id
        primary_key: true

      - name: order_timestamp
        column_name: order_timestamp
        default_timestamp: true
        time_grains: [day, week, month]

    metrics:
      - name: revenue
        calculation_method: sum
        expression: order_value

  - name: customers
    model: ref('dim_customers')
    dimensions:
      - include: all
      - exclude: 
          - user_id

      - name: user_id
        primary_key: true

    metrics:
      - name: customer_ltv
        metric: metric('revenue') ##maybe??
        calculation_method: sum
        expression: metric('revenue') ##by primary key??
        time_grains: 
          - all
        group_by: somehow make it only group by primary key
```

</details>
