### ISSUE TITLE
[Bug] Jinja expression is not parsed under tests meta

### ISSUE THREAD

**Issue by IDoneShaveIt** [dbt-labs/dbt-core#6693]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When defining a test's meta field with jinja expression, the jinja expression is not being parsed and returned as string `"{{ jinja_expression }}"`.

For example:
```yaml
  - name: customers
    meta:
      channel: "{{ 'one' if 1 == 2 else 'two' }}"
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique:
              meta:
                channel: "{{ 'one' if 1 == 2 else 'two' }}"
```

When looking at the customers model node, the meta's channel field is set to `two`.
When looking at the unique test node, the meta's channel field is set to `"{{ 'one' if 1 == 2 else 'two' }}"`. 

<img width="837" alt="image" src="https://user-images.githubusercontent.com/48473443/213923577-9f14d321-016b-4d82-ae38-3004bf53adff.png">

### Expected Behavior

Both meta's channel field should be set to `two`
(The jinja should be parsed on both cases)

### Steps To Reproduce

1. Define a field under test's meta with jinja expression (at the `schema.yml`)
2. Run dbt command and check the graph

### Environment

```markdown
- OS: macOS
- Python: Python 3.9.13
- dbt: 1.3.2
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment]
Thanks for opening @IDoneShaveIt! I was able to reproduce this, using the newer location of `meta` as well (nested under `config`, since v0.21):
```yml
version: 2
models:
  - name: customers
    description: "This table has basic information about a customer, as well as some derived facts based on a customer's orders"
    config:
      meta:
        channel: "{{ 'one' if 1 == 2 else 'two' }}"
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique:
              config:
                meta:
                  channel: "{{ 'one' if 1 == 2 else 'two' }}"
```
```
$ dbt ls --output json --output-keys name,meta
{"name": "customers", "meta": {"channel": "two"}}
{"name": "unique_customers_customer_id", "meta": {"channel": "{{ 'one' if 1 == 2 else 'two' }}"}}
```

I think what's going on here is that `meta` is a dictionary, and the logic here only renders config values if they're strings:
https://github.com/dbt-labs/dbt-core/blob/93619a9a3761d3606d257c1274828ac4eef4f627/core/dbt/parser/generic_test_builders.py#L265-L268

We need to loop through the `meta` keys and render each value one by one. We could treat `meta` as a special case, or try to apply logic similar to what we do in [`deep_map_render`](https://github.com/dbt-labs/dbt-core/blob/93619a9a3761d3606d257c1274828ac4eef4f627/core/dbt/utils.py#L207) / [`render_data`](https://github.com/dbt-labs/dbt-core/blob/93619a9a3761d3606d257c1274828ac4eef4f627/core/dbt/config/renderer.py#L47).
