### ISSUE TITLE
[CT-1913] Snapshot target_schema & target_database used from dbt_project.yml

### ISSUE THREAD

**Issue by minhajpasha** [dbt-labs/dbt-core#6745]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Profiles.yml
```
    dev:
      type: bigquery
      method: oauth
      project: gcp-project-test
      **dataset: holding**
      location: EU
```

snapshot config in dbt_project.yml 

```
snapshots:
    test_dbt_project
        +persist_docs:
            relation: true
            columns: true
        primary:
            snapshot_models:
                **+target_schema: snapshot_dataset**
```

schema.yml to add the descriptions to snapshots tables

```
snapshots:
    - name: customers
      config:
        enabled: true
      columns:
        - name: customer_id
           description: 'customer unique id'
```

snapshot folder structure:
```
-snapshots
  -primary
      -snapshot_models
         -customers.sql
         -orders.sql
         - schema.yml
```

When we add the schema.yml file under snapshots/primary/snapshots_models and run the below command

`dbt snapshot --select customers` then the model is getting created under holding dataset(profile.yml) instead of snapshot_dataset(dbt_project.yml)

-

### Expected Behavior

The snapshots should be created in the dataset defined in dbt_project.yml file. For now have removed the schema.yml file so that it can create the model's under dataset provided in dbt_project.yml file. This is stopping to add the descriptions to table columns

### Steps To Reproduce

details provide in descriptions

### Environment

```markdown
- OS: Airflow 2.2 composer 2.2
- Python:3.8
- dbt: dbt bigquery 1.2.0
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thank you for reaching out about this @minhajpasha !

p.s. I added some ` ``` ` to your description to help format each or your YAML examples -- hope you don't mind.

I was able to reproduce what you described, and I agree this is a bug. It _might_ be related to https://github.com/dbt-labs/dbt-core/issues/4000

### Workaround

Removing your `snapshots/primary/snapshot_models/schema.yml` file altogether is an option!

But if you want to keep that file (for its column descriptions, etc), then you can use the following workaround.

Remove each `config` section from your `schema.yaml`:
```yaml
version: 2

snapshots:
  - name: customers
    columns:
      - name: customer_id
        description: 'customer unique id'
```

And add your specific `config` assignments within each snapshot instead:
```
{% snapshot customers %}

{{
    config(
      enabled=true,
      ...
    )
}}

...
{% endsnapshot %}
``` 

### How to reproduce
Here's the simplified setup that I used to reproduce the error using dbt-snowflake:

`dbt_project.yml`
```yaml
snapshots:
  +target_schema: dbeatty_snapshot_dataset
```

`snapshots/customers.sql`
```sql
{% snapshot customers %}

{{
    config(
      enabled=false,
      unique_key='id',
      strategy='check',
      check_cols='all',
    )
}}

select 0 as id 

{% endsnapshot %}
```

This will not work as intended (since it won't use configured the snapshot `target_schema` and will use the schema from profiles.yml instead):
`snapshots/schema.yml`
```yaml
version: 2

snapshots:
  - name: customers
    # Adding a config section here will break the snapshot `target_schema`!
    config:
      enabled: true
```

#### Run it
Run it and observe the (unintended!) schema it uses for snapshots:
```shell
dbt snapshot --select customers
```

But removing the `config` key will use the intended target schema for snapshots:
`snapshots/schema.yml`
```yaml
version: 2

snapshots:
  - name: customers
```

#### Run it again
Run it again and observe the intended schema it uses for snapshots:
```shell
dbt snapshot --select customers
```
