### ISSUE TITLE
Support 'constraints' as a model-level config

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6754]
In addition to `constraints` as a column-level property, support constraints as a model-level config for row-level boolean expressions that require multiple columns, or combined primary keys (unenforced & informational-only).

Will depend on what we land on in terms of a spec for the column-level `constraints` property in https://github.com/dbt-labs/dbt-core/issues/6750#issue-1558234542

**Comment by MichelleArk** [comment]
From: https://github.com/dbt-labs/dbt-core/issues/6750#issuecomment-1436064688

```yaml
models:
  constraints: Optional[List[ModelLevelConstraint]]
  columns:
    - name: str
      data_type: Optional[str]
      not_null: Optional[bool]
      constraints: Optional[List[ColumnLevelConstraint]]
```

**Comment by MichelleArk** [comment]
From https://github.com/dbt-labs/dbt-core/issues/7066: 

```python
class ConstraintOption(StrEnum):
    check = "check"
    not_null = "not_null"
    unique = "unique"
    primary_key = "primary_key"
    foreign_key = "foreign_key"
    custom = "custom"  # I have no idea -- but let's leave it open for the wacky & wild data platforms out there

ColumnLevelConstraint:
    type: ConstraintOption
    name: Optional[str]
    warn_unenforced: bool = True  # raise a warning if this constraint is not enforced by this data platform (but will still be included in templated DDL)
    warn_unsupported: bool = True  # raise a warning if this constraint is not supported by this data platform (and will be excluded from templated DDL)
    expression: Optional[str] # free for all. required if constraint is 'check' or 'foreign_key' -- can we validate via post-init ?
    # additional properties allowed: yes! there are going to be lots of constraint-specific and platform-specific shenanigans

# the same, with an added 'columns' attribute (which isn't needed when the constraint is defined for one column)
ModelLevelConstraint(ColumnLevelConstraint):
    columns: List[str]
```

```yml
models:
  constraints: Optional[List[ModelLevelConstraint]]
```
If `constraints` is set a the model level, it should be a model-level attribute, _not_ a "config." This means it isn't settable in `{{ config() }}` or in `dbt_project.yml`, and that's okay.

**Comment by jtcohen6** [comment]
### Example

(Borrowing heavily from Postgres docs: https://www.postgresql.org/docs/current/ddl-constraints.html)

```yml
models:
  - name: my_model
    columns:
      - name: first_id
        data_type: int
      # ... rest of columns ...
    constraints:
      - type: primary_key
        columns: [first_id, second_id]
      - type: unique
        columns: [product_id, order_no]
        name: must_be_different
      - type: foreign_key
        columns: [column_a, column_b]
        expression: references other_table (another_x, another_y)  # hmmm do we need to be able to support 'ref' here?
      - type: check
        columns: [discounted_price]  # not technically needed, but I sort of like it as metadata?
        expression: discounted_price > 0
      - type: check
        columns: [price, discounted_price]  # as above
        name: valid_discount
        expression: discounted_price > 0
```

This should template out DDL like:
```sql
create table dbt_jcohen.my_model (
    # all of the columns first
    first_id int,
    ...
    
    # then the model-level constraints
    primary key (first_id, second_id),
    constraint must_be_different unique (product_id, order_no),
    foreign key (column_a, column_b) references other_table (another_x, another_y),
    check (discounted_price > 0),
    constraint valid_discount check (price > discounted_price)
);
```

Try this yourself in `psql`:
```
jerco=# create schema if not exists dbt_jerco;
jerco=# create table dbt_jerco.other_table (another_x int, another_y int, unique (another_x, another_y));
CREATE TABLE
jerco=# create table dbt_jerco.my_model (
    first_id int,
    second_id int,
    product_id int,
    order_no int,
    column_a int,
    column_b int,
    price float,
    discounted_price float,
    primary key (first_id, second_id),
    constraint must_be_different unique (product_id, order_no),
    foreign key (column_a, column_b) references dbt_jerco.other_table (another_x, another_y),
    check (discounted_price > 0),
    constraint valid_discount check (price > discounted_price)
);
CREATE TABLE
```

How should users actually choose to define these, as column-level versus model-level constraints? To quote from the Postgres docs:

> It's a matter of taste.

### Notes
- `name` is always optional. On some data platforms, you can provide a custom name or not. On other data platforms (e.g. Databricks), we'll need to auto-generate hashed names if the user doesn't provide one — this is already how the current implementation works.
- `check`-type constraint doesn't actually require the `columns` field, if defined at the model level — but I'm sort of inclined to keep it there, and encourage people to use it anyway
- We've defined `constraints` as a top-level property, not a `config`. Meaning that it can't be set via either in-file `{{config()}}` or in `dbt_project.yml`. Let's keep having the larger conversation around configs vs. properties; out of scope for this specific issue.
- Ugh!! If we're serious about supporting `foreign_key` constraints, I think we need a way to let users define `ref` in the `expression` field, like we do for the `to` field in [`relationships`](https://docs.getdbt.com/reference/resource-properties/tests#relationships) tests. Otherwise it can _only_ be defined on a model in the same/default database/schema. (Maybe that's a reasonable limitation...?)
