### ISSUE TITLE
[CT-1989] Parse group resource

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6822]
Parse a group resource as defined in schema yml files. Groups have a required (at least for now!) owner that should be unified with the existing [`ExposureOwner`](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/contracts/graph/unparsed.py#L427) dataclass internally.

Example spec: 
```yaml
# models/marts/github/github.yml

groups:
  - name: github
    owner: 
      name: Jeremy
      email: data@jer.co
      slack: talk-jerco-memes
      github: jtcohen6
      whatever: you want
```

Eventually ([issue](https://github.com/dbt-labs/dbt-core/issues/6823)), group names will be used as values for the optional `group` model config:
```yaml
# models/marts/github/github.yml

models:
  - name: int__github_issue_label_history
    config: 
      group: github  # explicit opt-in
  - name: fct_github_issues
    config: 
      group: github  # explicit opt-in
```

### Considerations
* `ExposureOwner` currently has a required email, and an optional name. What should the unified unparsed `Owner` schema be? Proposal for a unified schema/dataclass in https://github.com/dbt-labs/dbt-core/issues/6833
