### ISSUE TITLE
[CT-1990] Parse access property on model node

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6824]
### Requirements
- `access` is a new property on model nodes. For phase 1, cannot be provided for any other ['groupable' nodes](https://github.com/dbt-labs/dbt-core/issues/6823)
- `access` property should be defined as an enum, for potential extension in the future. Currently must be one of `private` or `public`, or `protected`:
* private - ref works within the same group
* protected - ref works within the same project/package
* public - ref works across projects/packages
- `access` defaults to `protected`, irrespective of the group config value

### Reference spec
```yaml
# models/marts/github/github.yml

groups:
  - name: github
    owner: 
      name: Jeremy
      email: data@jer.co

models:
  - name: int__github_issue_label_history
    access: private
    config: 
      group: github  # explicit opt-in
  - name: fct_github_issues
    access: protected
    config: 
      group: github  # explicit opt-in
  - name: fct_github_issues
    access: public
```
