### ISSUE TITLE
Compilation Error in model dup_check (models\dup_check.sql)   macro 'dbt_macro__check_duplicates' was invoked with two values for the special caller argument. This is most likely a  bug.

### ISSUE THREAD

**Issue by jiyauppal** [dbt-labs/dbt-core#6884]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

check_duplicates.sql (macro):
```
{% macro check_duplicates(table) %}
  {% set columns = run_query("select * from {{ table }} limit 1") %}

  {% for column in columns.columns %}
    {% set total_count = run_query("select count(*) from {{ table }}").rows[0][0] %}
    {% set distinct_count = run_query("select count(distinct " + column + ") from {{ table }}").rows[0][0] %}

    {% if total_count > distinct_count %}
      {{ log("Duplicates found in column: " + column) }}
    {% else %}
      {{ log("No duplicates found in column: " + column) }}
    {% endif %}
  {% endfor %}
{% endmacro %}
```

dup_check.sql (model):

```
{% call check_duplicates("data.adp_ingested") %}

{% endcall %}
```
and I am getting this error.

### Expected Behavior

It should run for the csv file.

### Steps To Reproduce

In DBT Trino enviorment.

### Environment

```markdown
- OS: Windows
- Python: 3.10.9
- dbt-Core:
  - installed: 1.4.1
  - latest:    1.4.1 - Up to date!

Plugins:
  - snowflake: 1.4.0 - Up to date!
  - trino:     1.4.0 - Up to date!
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

DBT Trino

**Comment by dbeatty10** [comment]
Hi @jiyauppal 👋

It looks like your end goal might be to test if all columns in a table contain unique values?

In general, there's a multiple ways to go about testing data, and we'd recommend assessing them in this order:
1. use a [built-in test](https://docs.getdbt.com/reference/resource-properties/tests#out-of-the-box-tests)
1. use an existing test from a [dbt package on the Hub](https://hub.getdbt.com/)
1. create a [custom generic test](https://docs.getdbt.com/guides/best-practices/writing-custom-generic-tests)
1. create a [custom singular test](https://docs.getdbt.com/docs/build/tests#singular-tests)

### Examples

See below for an all-in-one set of examples that you can run in your project to see how each of those different types of test work.

#### Project setup

Here's what your project will look like once you've created all the files listed below (I've excluded `dbt_project.yml` and connection details in `profiles.yml` but everything else should be covered:
```
├── models
│   └── schema.yml
├── packages.yml
├── seeds
│   ├── all_unique.csv
│   └── unique_combos.csv
└── tests
    ├── generic
    │   └── my_unique.sql
    └── singular
        └── check_duplicate_column.sql
```

`models/schema.yml`
```
version: 2

seeds:
  - name: all_unique
    columns:
      - name: id
        tests:
          # built-in test
          - unique
          # custom generic test
          - my_unique
      - name: color
        tests:
          # built-in test
          - unique
          # custom generic test
          - my_unique

  - name: unique_combos
    tests:
      # existing test from a dbt package
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - alternating
            - sub_ordering
      # existing test from a different dbt package
      - dbt_expectations.expect_compound_columns_to_be_unique:
          column_list: ["alternating", "sub_ordering"]
```

`packages.yml`
```yaml
packages:
  - package: calogica/dbt_expectations
    version: [">=0.8.0", "<0.9.0"]
  - package: dbt-labs/dbt_utils
    version: [">=0.8.0", "<2.0.0"]
```

`seeds/all_unique.csv`
```
id,color
0,blue
1,green
2,pink
3,yellow
```

`seeds/unique_combos.csv`
```
id,alternating,sub_ordering
0,yes,1
1,no,1
2,yes,2
3,no,2
```

`tests/generic/my_unique.sql`
```sql
{% test my_unique(model, column_name) %}

-- custom generic test
with validation_errors as (

    select {{ column_name }}
    from {{ model }}
    group by {{ column_name }}
    having count(*) > 1

)

select *
from validation_errors

{% endtest %}
```

`tests/singular/check_duplicate_column.sql`
```sql
-- custom singular test
select id
from {{ ref("unique_combos") }}
group by id
having count(*) > 1
```

#### Run it
```shell
dbt deps
dbt build --full-refresh
```
#### Notes on the package tests in the example above

There are two entries in the `packages.yml` file and referenced within `models/schema.yml`:
- [dbt_utils](https://github.com/dbt-labs/dbt-utils)
- [dbt_expectations](https://github.com/calogica/dbt-expectations)

The two tests used are:
- [`dbt_utils.unique_combination_of_columns`](https://github.com/dbt-labs/dbt-utils#unique_combination_of_columns-source) ([source](https://github.com/dbt-labs/dbt-utils/blob/eaa0e41b033bdf252eff0ae014ec11888f37ebff/macros/generic_tests/unique_combination_of_columns.sql))
- [`dbt_expectations.expect_compound_columns_to_be_unique`](https://github.com/calogica/dbt-expectations#expect_compound_columns_to_be_unique) ([source](https://github.com/calogica/dbt-expectations#expect_compound_columns_to_be_unique))

### Next steps

Could you try out the examples above and see if it points you in the right direction?
