### ISSUE TITLE
[CT-2075] [Feature] Add column aliasing (identifiers) for source tables

### ISSUE THREAD

**Issue by Fleid** [dbt-labs/dbt-core#6929]
Follow up of the conversation in https://github.com/dbt-labs/dbt-bigquery/issues/365

How about dbt starts supporting column level alias / identifier in sources?
So that if a field is called `my_original_column_name` in the actual source, it will always be replaced by `my_new_column_name` in every dbt contexts.

```YAML
sources:
  - name: my_source_A
    tables:
    - name: a_table_in_A
      columns:
        - name: my_new_column_name
           identifier: my_original_column_name
          ...
```

From there, `my_new_column_name` is replaced by `my_original_column_name` in every DDL/DML/DQL statements issued to the database where the source table is ref'd (used in FROM or JOIN).

In dbt land, the name of that column is always `my_new_column_name`. This includes when dbt generates database objects based of the original schema (see original issue, persisting test results in `dbt__test_audit`). As far as dbt knows, this column was always named `my_new_column_name`. 

### Describe alternatives you've considered

Alternatives are described in the original issue.

### Who will this benefit?

Defining tests on sources that surface system columns, trigger the creation of database objects using reserved keywords. This would allow dbt to bypass that.
