### ISSUE TITLE
[CT-2111] [Feature] Allow `exposures` to depend on other `exposures`

### ISSUE THREAD

**Issue by david-beallor** [dbt-labs/dbt-core#6963]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Allow exposures to list other exposures in their list of dependencies. At Compass Digital, we have exposures representing Looker explores, and exposures representing Looker dashboards. It would be great if we could have the Looker dashboard exposures list the Looker explore exposures as it's dependencies.

### Describe alternatives you've considered

Currently, we manually collate the list of dependencies from each explore exposure and list those as the dashboard dependencies.

### Who will this benefit?

Anyone that has exposures that depend on other exposures :)

### Are you interested in contributing this feature?

Yes, would love to contribute, but would require some guidance on the moving pieces here to get started.

**Comment by jtcohen6** [comment]
@david-beallor Thanks for opening!

This was discussed way back when:
- #5106 

> Exposures representing Looker explores, and exposures representing Looker dashboards. It would be great if we could have the Looker dashboard exposures list the Looker explore exposures as it's dependencies.

This is indeed the use case:
- Looker explores &rarr; Looker dashboards
- Mode queries &rarr; Mode dashboards
- Census/Hightouch sync &rarr; Salesforce report &rarr; CEO's email &rarr; my DMs &rarr; ...

I've been open to this idea in the past. Nowadays, I'm hesitant to make `exposures` anything other than a terminal/leaf node (always a child, never a parent) — in the same way that `sources` should only ever be a root node (always a parent, never a child).

Is there another way to go here, that looks like "grouping" exposures, similar to how we enable grouping common sources?
```yml
exposures:
  - name: looker_explore
    owner: ...
    maturity: high
    depends_on:
      - ref('my_model')
    nested_exposures: # this is a bad name, but you get the idea
      - name: specific_looker_dashboard
        # inherits properties from above, but could also override some
        maturity: low
```
It wouldn't be possible to have a "child" exposure referencing two "parent" exposures. Rather, it's really just a way to logically group related exposures together.

What do you think?

**Comment by david-beallor** [comment]
Thanks for the thorough response @jtcohen6!

I like the logic of keeping `exposures` as terminal nodes, but it would be great if there is a way to respect this, while also enabling "child" exposures to have multiple "parent" exposures. We often have Looker dashboards that have visuals from multiple explores, so the multiple "parent" functionality would be very useful.

What if the "child" to "parent" relationship was one of inheritance rather than nesting?

I'm thinking something like the following...
```yaml
exposures:
  - name: looker_explore_orders
    owner: ...
    maturity: high
    depends_on:
      - ref('orders')
  - name: looker_explore_customers
    owner: ...
    maturity: high
    depends_on:
      - ref('customers')
  - name: looker_customer_orders_dashboard
    # Inherits unioned dependencies from the extended exposures
    extends:
      - looker_explore_orders
      - looker_explore_customers
    # Other props can be overridden
    owner: ...
    maturity: low
```
