### ISSUE TITLE
[CT-2174] [Regression] Package max version range throwing error

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [dbt-labs/dbt-core#7039]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

On the latest 1.4.2 version of dbt-core when installing a dbt package with the range including a range with a max of `0.10.0` you will receive an erroneous failure. For example:
```yml
packages:
   - package: fivetran/google_ads_source
     version: [">=0.9.0", "<0.10.0"]
```
Will result in 
```zsh
Version error for package fivetran/google_ads_source: Could not find a satisfactory version from options: ['>=0.9.0', '<0.10.0']
```
However, the [latest version of fivetran/google_ads](https://hub.getdbt.com/fivetran/google_ads_source/latest/) is 0.9.0 and should be fine with that version range.

If I then adjust the range to just not include 0.10.0 it will succeed:
```yml
packages:
   - package: fivetran/google_ads_source
     version: [">=0.9.0", "<0.9.9"]
```
Result
```zsh
22:28:23  Installing fivetran/google_ads_source
22:28:24    Installed from version 0.9.0
22:28:24    Up to date!
```

### Expected/Previous Behavior

The range would succeed with 0.10.0.

### Steps To Reproduce

1. Install the google_ads_source package with the following range

```yml
packages:
   - package: fivetran/google_ads_source
     version: [">=0.9.0", "<0.10.0"]
```
2. Run `dbt deps`
3. See the following error:
```zsh
Version error for package fivetran/google_ads_source: Could not find a satisfactory version from options: ['>=0.9.0', '<0.10.0']
```

### Relevant log output

```shell
Version error for package fivetran/google_ads_source: Could not find a satisfactory version from options: ['>=0.9.0', '<0.10.0']
```

### Environment

```markdown
- OS: Mac OS
- Python: 3.9.6
- dbt (working version): 1.4.1
- dbt (regression version): 1.4.2
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

[Here](https://getdbt.slack.com/archives/C01D1R2JLLA/p1677183954010909) is a slack thread where a user experienced a similar issue when trying to install the fivetran/ad_reporting package.
