### ISSUE TITLE
[CT-2188] [Feature] Add `jsonschema` to `BaseContext`

### ISSUE THREAD

**Issue by adavoudi** [dbt-labs/dbt-core#7053]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Select the [`validate`](https://python-jsonschema.readthedocs.io/en/latest/validate/#the-basics) function from the `jsonschema` library as accessible from the [modules](https://docs.getdbt.com/reference/dbt-jinja-functions/modules) variable.

Imagine we want to construct a model based on its metadata or the input variables specified during compilation, or even enforce some standards in namings. As the data becomes more complex, we must write more lines to verify the validity of those data. For example, we might want one parameter to exist and another to be integer with a minimum value of 1. The jsonschema library allows you to validate an instance against a schema.

In the following example, we want the `items` variable to be a list of maximum two items:

```sql

{% set items = var('items') %}

{% set jschema %}
{"maxItems": 2}
{% endset %}

{% set check_result = modules.jsonschema.validate(items, fromjson(jschema)) %}

```

The output of `modules.jsonschema.validate` function should be changed to have the following structure:

```
is_valid: boolean
errors: list of strings
```  

### Describe alternatives you've considered

If we don't have access to this module, we should write a series of tests to validate the structure and type of complex input variables or model metadata.

### Who will this benefit?

Anyone who want to construct a model based on its metadata or the input variables specified during compilation, or even enforce some standards in namings.

### Are you interested in contributing this feature?

yes, I can create a PR.

**Comment by dbeatty10** [comment]
Thanks for opening @adavoudi !

We have held a pretty high bar before adding new Python libraries to [modules](https://docs.getdbt.com/reference/dbt-jinja-functions/modules), and only four have made it in so far.

Using jsonschema sounds interesting, but I'll need some more help seeing the vision. Could you provide some more fleshed out examples? It would be great to see as much detail as possible in your examples. It would also be nice to see coverage of all the different use cases that you are thinking.

**Comment by adavoudi** [comment]
Thanks @dbeatty10 for your reply!
In my case, I'm looking to insert a graph into a database table. To that end, I define the graph in the model yaml file's meta field:

```yml
version: 2

models:
  - name: config_tree
    description: my graph
    config:
      materialized: table

    meta:
      graph:
        nodes: 
           - id: node_a
             display_name: Node A
             color: red
           - id: node_b
             display_name: Node B
        edges: 
            - src: node_a
              dst: node_b
              weight: 12.4
```

I can now access the graph definition via the `model['meta']` variable and generate the SQL that insert this graph into the database based on my table definition. However, before generating the SQL code, I want to ensure that the graph definition is correct. That is why I propose including the jsonschema library in the list of available modules.
