### ISSUE TITLE
[CT-2195] [Feature] Validation: disallow access:private on ungrouped model

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#7063]
Models without a group, and with `access` set to `private` should raise an error at parse-time. 

```yaml
models: 
- name: model
  access: private
```

[ParsedNode.patch](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/contracts/graph/nodes.py#L373-L380) could be the right spot for this validation, since group information should be available at this point.
