### ISSUE TITLE
[CT-2197] [Feature] Detect breaking changes to constraints in state:modified check

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#7065]
If a model with `contract: True` has its constraints modified in a way that represents a breaking change, dbt should raise an error as part of the `state:modified` check. 

What constitutes a breaking change?
- Removing a (column or model-level) constraint that is _enforced_ by the data warehouse
- Changing the materialization from `table` to `view` or `ephemeral` on a model that has at least one enforced constraint.

---

_Blocked by:_
- #7066
- #7067
- #6754

**Comment by MichelleArk** [comment]
> array

**Comment by jtcohen6** [comment]
Good point! We really shouldn't allow `ephemeral` models to be `contract: true` or `access: public` in the first place

**Comment by emmyoop** [comment]
We are unclear on exactly what we would be checking has changed and how often.  There's concern this would cause a slowdown in detecting changes if we have to check every single column for every model with a contract.

**Comment by sadahry** [comment]
We think this feature will be useful for us, so I'd like to ask you about this spec.

We've tried to using `dbt-core==1.5.0-b5` ,
and found disallowing adding new columns to yml in this version.

e.g., 

before
```yml
version: 2

models:
  - name: sometable
    config:
      contract:
        enforced: true
    columns:
      - name: order_id
        data_type: number

      - name: order_name
        data_type: varchar
```

after -> then failed with `dbt.exceptions.ModelContractError`
```yml
version: 2

models:
  - name: sometable
    config:
      contract:
        enforced: true
    columns:
      - name: order_id
        data_type: number

      - name: order_name
        data_type: varchar
```

That is what you excepted?

I read it and found this description.
> Additive changes are not considered breaking:
>* adding a new column to a contracted model
>https://docs.getdbt.com/reference/resource-configs/contract#detecting-breaking-changes

My understand is that it means allow adding columns in yaml, but current behavior does not.
Allowing adding columns is useful for us because our model's are updated in a fast cycle.

I'd like to know if this specification is as expected
or if there is a mistake in me or dbt-core.
