### ISSUE TITLE
[CT-2339] [Feature] combine profiles.yml from multiple places

### ISSUE THREAD

**Issue by ying-w** [dbt-labs/dbt-core#7241]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently only one profiles.yml is read when `dbt run` is triggered

To be consistent with how yml files are combined when using dbt, I think it would be useful to combine profiles.yml in the following order

- specified by `--profiles-dir`
- `./`
- `~/.dbt`

### Describe alternatives you've considered

Putting profiles.yml in a different directory

### Who will this benefit?

If you have profiles.yml for prod in `./` (for ease of packaging for deployment) and credentials for dev in `~/.dbt` when you run `dbt run` in `./` then dbt will only read in profiles.yml in `./`

By having dbt combine multiple profiles it becomes less redundant as you won't need to have both prod and dev credentials in ~/.dbt

**Comment by dbeatty10** [comment]
Thanks for submitting this idea @ying-w !

If you have profiles.yml for prod in `./` (for ease of packaging for deployment) why wouldn't you also have credentials for dev in the same file?

Is it because you have prod configured to use environment variables but dev has hard-coded values instead? So the prod version can be checked into version control, but the dev credentials are plain text so can't be checked into version control?

### Example profiles

e.g., do your profiles look something like the following?

#### prod

`./profiles.yml`
```yaml
profile:
  target: prod
  outputs:
    prod:
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      ....
```

#### dev

`~/.dbt`
```yaml
profile:
  target: dev
  outputs:
    dev:
      user: dbeatty10
      password: my_pa$$w0rd
      ....
```
