### ISSUE TITLE
[CT-2410] [Bug] Contracted Model Breaking Change Not Detected with `state:modified` When Model SQL and YAML Updated Together

### ISSUE THREAD

**Issue by anaghshineh** [dbt-labs/dbt-core#7349]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I was recently testing out some of the newer features slotted for `v1.5` - [model contracts and the detection of breaking schema changes](https://docs.getdbt.com/reference/resource-configs/contract).

Using `dbt-bigquery==1.5.0b4`, I tested out the running of a single contracted model using `state:modified` to catch breaking changes. Things looked great overall... apart from a bug I encountered:

When I ran dbt using `state:modified` after updating the `data_type` of a column (in both the model SQL AND the YAML contract - so the schemas did align), dbt failed to catch this as a breaking change. The model built successfully. However, when I ran just `state:modified.contract` first, dbt was able to detect this scenario as a breaking change.

### Expected Behavior

I expect that running dbt with `state:modified` after updating the data type of a column (in both the model SQL and the associated YAML) will give a breaking change error.

### Steps To Reproduce

1. Installed `dbt-bigquery==1.5.0b4` via `pip`
2. Used the following simple model and associated YAML:

```sql
# test.sql
SELECT
    'test' AS a,
    'hi' AS b
```
```yaml
version: 2

models:
  - name: test
    config:
      contract:
        enforced: true
    columns:
      - name: a
        data_type: string
      - name: b
        data_type: string
```

3. Updated the model SQL to be (change `a` to be type `int`):
```sql
# test.sql
SELECT
    3 AS a,
    'hi' AS b
```

4. Update the associated YAML to be (change `a` to be type `int`):
```yaml
version: 2

models:
  - name: test
    config:
      contract:
        enforced: true
    columns:
      - name: a
        data_type: int
      - name: b
        data_type: string
```

5. Ran `dbt run --select state:modified --state path/to/manifest/with/original/data_types` and observed that the run succeeded - which it shouldn't!
5. Ran `dbt run --select state:modified.contract --state path/to/manifest/with/original/data_types` and observed that the run failed with the appropriate breaking change message!

### Environment

```markdown
- OS:
- Python:
- dbt:
```
