### ISSUE TITLE
[CT-2436] [Bug] Version 0 makes itself the `latest_version`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#7408]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

https://docs.getdbt.com/docs/collaborate/govern/model-versions#how-to-create-a-new-version-of-a-model

I was expecting that I could do something like this:
```yaml
models:
  - name: dim_customers
    versions:
      - v: 1
      - v: 0
        defined_in: dim_customers  # keep original file name
```

And then have a model that generically always selects from the `latest_version` (without actually needing to specify the version):

`models/dim_customers_latest`
```
select * from {{ ref('dim_customers') }}
```

But the `ref`erence doesn't work correctly when starting the versioning at 0. It does work when starting the versioning at 1.

### Expected Behavior

See above.

### Not working when starting with `v: 0`

`models/_models.yml`
```yaml
models:
  - name: dim_customers
    versions:
      - v: 1
      - v: 0
        defined_in: dim_customers  # keep original file name
```

`models/dim_customers.sql`
```sql
{{ config(alias="dim_customers") }}

select 7 as id, 'Argentina' as country_name
```

`models/dim_customers_v1.sql`
```sql
select 12 as id, 'Bahamas' as country_name
```

`models/dim_customers_latest.sql`
```sql
select * from {{ ref('dim_customers') }}
```

Run the models and inspect the latest version:
```shell
dbt run
dbt show -s dim_customers_latest
```

| id | country_name |
| -- | ------------ |
|  7 | Argentina    |

### This also doesn't work

Explicitly setting the `latest_version` doesn't work either:
```yaml
models:
  - name: dim_customers
    latest_version: 1
    versions:
      - v: 1
      - v: 0
        defined_in: dim_customers  # keep original file name
```

### Working when starting with `v: 1`

Same project as above, but with the following modifications:

Re-index the version numbers:

`models/_models.yml`
```yaml
models:
  - name: dim_customers
    versions:
      - v: 2
      - v: 1
        defined_in: dim_customers  # keep original file name
```

Rename v1 to v2:
```shell
mv models/dim_customers_v1.sql models/dim_customers_v2.sql 
```

Try it again, and it shows the expected data:
```shell
dbt run
dbt show -s dim_customers_latest
```

| id | country_name |
| -- | ------------ |
| 12 | Bahamas      |

### Environment

```markdown
- OS:
- Python:
- dbt: 1.5.0rc1

dbt-postgres
```

### Additional Context

When inspecting the manifest, its `latest_version` values all looked correct. So the underlying difference is probably in the implementation of `ref()` somehow.
