### ISSUE TITLE
[CT-2519] [CT-2442] [Bug] Foreign key constraint templating

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#7417]
The most common syntax I see is:
- column level ("inline"): `references {expression}`
- model level ("out-of-line"): `foreign key {column_list} references {expression}`

Right now we're templating this out as `foreign_key`, instead of `references`.

Docs:
- https://www.postgresql.org/docs/current/ddl-constraints.html
- https://docs.snowflake.com/en/sql-reference/sql/create-table-constraint
- https://duckdb.org/docs/sql/statements/create_table.html
- etc

FWIW on BigQuery it does seem to be `foreign_key` and NOT `references`: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#syntax_2

---

If we were to take FK constraints more seriously, we're missing a pretty important ingredient, which is the ability to include & template `ref` inside the `expression` field — or providing more structure, i.e.
```yml
constraints:
  - type: foreign_key
    ref_table_name: ref('other_table_name')
    ref_column_names: ['id'] # could be multiple
```

Per https://github.com/dbt-labs/dbt-core/issues/6754#issuecomment-1449200569, we kicked that out of scope for v1.5, and we're unlikely to prioritize it while this remains a metadata-only (nonfunctional & unenforceable) feature on the majority of data platforms.
