### ISSUE TITLE
[Feature] For versioned models, automatically create view/clone of latest version in unsuffixed database location

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#7442]
_Thanks @dbeatty10 @joellabes for working through this with me!_

As the producer of a versioned model, I want the unsuffixed database relation (`<db>.<schema>.<model_name>`) to always point to the latest version of that model. It should do this using a "pointer" view (`select * from <latest>`) or table clone, depending on the relation type and data platform support.

### Implementation options

I'm not in love with any of these options:
1. Create a new node in the manifest with this logic
2. Update the view, table, and incremental materializations to produce an additional relation, if the model is versioned
3. Provide users with a macro that they can "set and forget" as a model `post-hook`

Of those, (3) is the least magical, and it's what we'll propose to users in the short term (v1.5). We still don't like:
- Hooks in general, and especially hooks that run DDL to create database objects
- Lacking the robustness of an actual materialization
- Requiring users to copy-paste a macro and update their project, when this is the Right Behavior that should just happen out of the box
- Making the proposed logic for [schema management](https://github.com/dbt-labs/dbt-core/pull/5392) more complicated

**Comment by jtcohen6** [comment]
We have three implementation options. Each has trade-offs around user limitations and complexity of implementation.

Next step: Let's spike each of the options, and make a call.

**Comment by nicohein** [comment]
Hi All, 

I would like to propose a fourth option, that is a little bit more verbose but adds flexibility:

## Option 4 

The main model itself remains unchanged. It is expected to be implemented in `dim_customers.sql`. The materialization with the version number of the main model becomes optional. If you want to have this materialization, then you create an item in the versions.

```
- models:
  - name: dim_customers
     # it essentially becomes obsolete to specify the main/latest version
    config:
      materialized: table
      meta:
        key: value
    columns:
      - name: customer_id
        description: This is the primary key
        data_type: int
      - name: ...
    versions:
      - version: 1
        implemented_in: dim_customers_OLD
        deprecation_date: '2022-01-01'
        config:
          meta: {} #remove the meta from v2
        columns:
          include: ...
          exclude: ...
      - version: 2
        implemented_in: dim_customers
      - version: 3
        description: A dramatic reimagining of our customers model with no column overlap? What are they thinking?!
        implemented_in: dim_customers_NEW_BUT_NOT_READY
        # deprecation_date is optional and not included for this version
        columns:
          - name: totally_new_column_1
          - name: totally_new_column_2
          - name: totally_new_column_3
          ...
```

This would result in a second table being created called  `dim_customers_v2`. If the developer instead choses to materialize `_v2` as a view thats possible by instead writing:

```
      - version: 2
        # implemented_in: dim_customers_v2   # expected default 
```

And adding the corresponding `.sql` file: 

```
{{ config(materialized="view") }}

select * from {{ ref('dim_customers') }}
``` 

If a team decides to have `_v2` materialized as a table and define `dim_customers` as a view, that is now equally possible.

One remaining challenge I can think of is that a developer could introduce a drift between the main model and `v2` because there is simply no guarantee of those models being equal. I regard this risk as low because whoever will make use of models, will put some thought behind the versioning model.

**Comment by Spince** [comment]
this is concerning to me.. the whole purpose of versioning an api is to NOT introduce breaking changes. unless every model is postfixed with `_v1` from the beginning the proposed solutions would cause breaking changes. ie- dim_customers was created but is now being modified, the above solution places a view where dim_customers "v1" originally existed

i need to give it more thought but it seems like the pointer object that routes a query to the latest version should instead be postfixed with `_latest`. i think this needs to be considered in terms of implemention on an existing project that's been around for years rather than a clean slate project that's perfectly configured according to dbt features and standards that weren't even discussed or codified until years after the original dim_customers table was created.

**Comment by nicohein** [comment]
I think I still would expect dim_customers to behave just like like dim_customers_latest. Nevertheless would the proposal for option 4 handle different ways of implementation:

### dim_customers unchanged & latest materialized as table

```
- models:
  - name: dim_customers
    config:
      materialized: table
      meta:
        key: value
    columns:
       ...
    versions:
      - version: latest  # just like a tag in docker 
        implemented_in: dim_customers_v2
        alias: dim_customers_latest  # just in case default behavior results in dim_customers_vlatest
      ...
      - version: 2
        # implemented_in: dim_customers_v2  
      ...
```

### dim_customers unchanged & latest as view

```
- models:
  - name: dim_customers
    config:
      materialized: table
      meta:
        key: value
    columns:
       ...
    versions:
      - version: latest
        alias: dim_customers_latest
      ...
      - version: 2
        # implemented_in: dim_customers_v2
      ...
```

and `dim_customers_latest.sql`:

```
{{ config(materialized="view") }}

select * from {{ ref('dim_customers', version="2") }}
```

### dim_customers like latest & v2 + latest as view


```
- models:
  - name: dim_customers
    config:
      materialized: table
      meta:
        key: value
    columns:
       ...
    versions:
      - version: latest
        alias: dim_customers_latest
      - version: 2
        implemented_in: dim_customers_latest
     ...
```

and `dim_customers_latest.sql`:

```
{{ config(materialized="view") }}

select * from {{ ref('dim_customers') }}
```

Happy to clarify any questions around this idea and receive some more feedback.

**Comment by Spince** [comment]
@nicohein I guess I should have been more specific. I don't agree with `I want the unsuffixed database relation (<db>.<schema>.<model_name>) to always point to the latest version of that model` from the original comment here.. if I was implementing such a feature I would not do it that way.

**Comment by jtcohen6** [comment]
From discussion yesterday:
- We're unlikely to move forward with option 1. Adding this as a new node to the manifest doesn't feel quite, even if it would in a similar case for [`metricflow_time_spine`](https://github.com/dbt-labs/dbt-core/issues/7938)
- While this makes sense as a default/common pattern, we think enough users will want a way to opt out of or modify this pattern, that the explicitness of option 3 is appealing. For example, there might not be a need for this behavior if you're defining a versioned model with a single version, as for the use case described in https://github.com/dbt-labs/dbt-core/issues/8028#issuecomment-1622649555
- Whether we move forward with option 2 (implicit) or option 3 (explicit), the thing to figure out is what code we'd be calling (whether in our materialization/task or in the users' hook). Now that there's a `clone` materialization, which abstracts over DWH support for table clones and the object relation type to produce a clone or "pointer view" accordingly — can we call that as a macro in a hook, in a way that's cleaner than [the code we currently have documented](https://docs.getdbt.com/docs/collaborate/govern/model-versions#configuring-database-location-with-alias)?

Next step:
- Spike on writing hook code that would leverage the clone macro / materialization. If we can get to clean code that's supported across DWHs, it's then just a UX question of whether this is enabled/disabled via yaml config or `post-hook`

**Comment by joellabes** [comment]
My preference is Option 2.5, where it happens automatically but the logic is implemented in an overridable macro in the vein of `generate_alias_name` so that you can modify it if you want to. You could even do something like 

```yml
models:
  - name: some_model
     versions: 
       - v: 1
         ...
       - v: 2
         config: 
           generate_pointer_view: false
```

if you wanted model-by-model control, right?

**Comment by alison985** [comment]
Link to a Slack message with the way I think about this. https://getdbt.slack.com/archives/C2JRRQDTL/p1692185439979629?thread_ts=1692185332.030239&cid=C2JRRQDTL Specifically:

> Rename foobar to foobar_v1
Create foobar as view (it should know that foobar in after is not the same as foobar in before)
Create foobar_v2

I also have to make sure foobar(view/MV), foobar_v1(table/MV), and foobar(table/MV) are _all_ getting refreshed data. Assume there are some objects that I could be maintaining 3 versions of at the same time for months.

@Spince **is :100: correct - you can't have an object name change version.** 1 object name == 1 version == 1 model.  If I'm reading correctly, I think that means that Option 4 from @nicohein with @Spince's requirements is the closest thinking. I'm not sure I understand @joellabes's latest comment.

Right now, I'm handling this in naming convention as opposed to anything in dbt syntax because I need explicit control and dbt doesn't support `ALTER`s and changing materialization type of an object. (I haven't thought through incremental models for this yet, but I'm sure there's interesting cases there.) If you have the benefit of starting a code base from scratch everything has a `_v1` suffix, `_v2` suffix, and so on. Sometimes I put the version on the schema, sometimes on the individual model. When you don't have that luxury, the non-suffixed version is `_v1` implicitly.

Think of this like API version control. I have to give downstream(e.g. BI) a chance to update. The downstream customer is pinned to a version, it's just a matter if they know that explicitly(`vX` suffix) or not(no `_vX` suffix). The version append suffixes are _important for organizational expectations and communications_.

If I want to have `dim_customers_latest`, that can be an optional object creation so people can choose to be on the bleeding edge that might break at anytime(e.g. a developer release).

**Comment by jtcohen6** [comment]
@Spince @nicohein @alison985 Thank you for the feedback on this! We've been working on the technical spiking that might make this mechanism possible. I'm coming back around to the questions about the desirable product / end user experience.

After reading through the comments above, this is what I'd propose:
- This "latest" pointer view/clone should have a suffix `_latest`, creating a database object named `<modelname>_latest`.
- This will be a pointer view / clone of whichever version the dbt model's maintainer has specified via `latest_version`, or the default if not specified.
- This is _instead of_ having an unsuffixed representation (`<modelname>`) by default.
- dbt _should_ automatically create this view/clone for all versioned models.
- It should be possible to **disable** dbt's automatic creation of the "latest" view/clone.
- If disabled, you could then recreate the "latest" view/clone, using all your own custom configs, as @nicohein was showing above:
```yaml
versions:
  - v: latest  # this is an actual version of the model called 'latest'
    defined_in: dim_customers_latest  # it needs a custom definition
    config:
      alias: dim_customers_latest  # instead of default, which would be '_vlatest'
```
In this case, we are defining another real version of the model — not just a pointer to an existing (latest) version. It has all the same flexibility as any other model version.

---

How should users **disable** dbt's automatic creation of the "latest" view/clone? Ideas:
- By passing an additional config, as @joellabes suggested (`generate_pointer_view: false`), to the top-level model definition
- By creating a `v: latest` and explicitly disabling it — though this doesn't feel quite right to me:
```yaml
models:
  - name: dim_customers
    versions:
      - v: latest
        config: {enabled: false}
```

I will give that last piece a bit more thought - but I'm curious to hear how this lands overall!

**Comment by alison985** [comment]
Sounds right to me. I would vote for disabling via configuration as @joellabes suggested, but I don't think it can be specified at the version level(see below).

New item: you're repeatedly saying "view/clone" instead of just view. But I don't see a proposed spec on where to define which it is in YML. I learned about `dbt clone` today and I don't want to use it, but presumably others will. Also, since it's a choice, I removed "view" from the keyword being proposed. I propose the following, Option A:

```yaml
models:
  - name: some_model
    config:
      materialized: table

      ########
      generate_pointer: false
      # OR                                      # both can not be specified at the same time
      materialized_pointer: [view | clone]      # default to view if not specified
      ########
    versions: 
       - v: 1
         ...
       - v: 2
         # How would we know what period of time an automatic alias of a version should be disabled?
         #config:   
         #  generate_pointer_view: false
       - v: 3
         #config:
         #  generate_pointer_view: true
```
I thought about doing (Option B)`generate_pointer: [false | view | clone]` because they are mutually exclusive, but it didn't feel right to mix a boolean and a string. I guess you could do (Option C)`generate_pointer: [no | view | clone]` but it would introduce new boolean keywords(yes/no) to dbt YML which also feels wrong.

**Comment by jtcohen6** [comment]
@alison985 Thanks for taking another look!

Re: "view/clone," I had been thinking that:
1. If the "latest version" of this model corresponds to a table in the database (because it's materialized as `table` or `incremental`), and this DWH supports table clones, we would create a table clone. This shares all metadata attributes of the cloned table.
2. If the "latest version" of this model is materialized as a view (or materialized view, or something else), or if this DWH does not support table clones, we would create a pointer view (`create view ... as select * from ...`).

The benefit of this approach is that metadata queries expecting this object to be a table would still work, if the conditions for (1) are met. But it is more complex as an approach. I get that it would be simpler to just say: _This is always a pointer view._

So to answer all the outstanding questions here:
1. Let's keep things simple, by always creating a view.
2. The view should be named `_latest`.
3. We check the config `generate_latest_pointer: true|false`. It is `true` by default, the user can set to `false` in any of three places: `dbt_project.yml` for many/all models; in the top-level model config for this versioned model; or in the config for the "latest" version of a versioned model.
4. For more custom behavior, users could add a `v: latest` with their own alias config, contents, etc.

**Comment by SBurwash** [comment]
Hey everyone 👋 very much in love with this feature.
 
Question - with the pointer, would we be able to pass documentation? The goal here would be to have the pointer have the same documentation as the latest table (through the `persist_docs` feature)

**Comment by smitsrr** [comment]
Just had a production bug this morning because the new `_v1` model didn't have a database object (unsuffixed) which triggered a full-refresh 😬 .
I am emphatically upvoting this issue for development!

**Comment by AnotherGuitar** [comment]
*upvote

**Comment by shahinsaleh** [comment]
*upvote

**Comment by geoHeil** [comment]
upvote

**Comment by rapha-pereira** [comment]
upvote!

**Comment by frannydelaney** [comment]
upvote (is there a better way to do this?)

**Comment by elyobo** [comment]
> upvote (is there a better way to do this?)

Yes, use 👍 on the issue

**Comment by sigveks** [comment]
Regarding the implementation of post-hooks for triggering the view generation of latest model. I think that on-run end hook is better than project-wide post-hook as any model specific post-hooks will run after the generation of a view. This means that if you have a post-hook that is manipulating the data of the model, the view on top will not be reflected by these changes. Consider changing the documentation here https://docs.getdbt.com/docs/collaborate/govern/model-versions#configuring-database-location-with-alias

**Comment by ChristianP89** [comment]
Upvoting this as well 👍

**Comment by lord-skinner** [comment]
Up doot 👍🏼

**Comment by dassowmd** [comment]
*upvote

**Comment by atalnarayan** [comment]
*upvote

**Comment by tamora-dawn** [comment]
*upvote

**Comment by mouscaillot** [comment]
*upvote

**Comment by jim256** [comment]
*upvote !

Been planning to implement something like this manually in my dbt-core project. Would be much better to have it part of dbt.

**Comment by james-johnston-thumbtack** [comment]
The `create_latest_version_view.sql` macro that is in the documentation ignores the alias of the original versioned model.  That might be undesirable, e.g. if you have a custom `generate_alias_name` macro.

Here is an alternative variation that uses a regex to find and strip the specific `_v123` version substring from the alias, without changing anything else in the alias.  This substring must occur at the end of the model name, or must be followed by a delimiter, e.g. it will change `my_model_v123` --> `my_model`, or `my_model_v123_deploy` --> `my_model_deploy`, but not `my_model_v123deploy` which would remain unchanged.

(Just sharing in case it is of interest to anyone else!)

Also, the macro uses `adapter` and an option for unconditionally dropping the view is provided, in case you want to use it with a database engine that does not support `CREATE OR REPLACE VIEW`.

<details>
  <summary>
    Click here for the code
  </summary>

```sql
{% macro create_latest_version_view() %}
    {{ return(adapter.dispatch('create_latest_version_view', 'tt_utils')()) }}
{% endmacro %}

{% macro default__create_latest_version_view() %}
    {{ tt_utils._do_create_latest_version_view(can_replace_view=true) }}
{% endmacro %}

-- Implementation copied and adapted from dbt 1.9 documentation:
-- https://docs.getdbt.com/docs/collaborate/govern/model-versions#configuring-database-location-with-alias
--
-- Improvements:
--  * Preserve any other aliasing done with the alias config or generate_alias_name macro by using a regex to strip the
--    version number part.  For example, a model "stg_mydb__customers_v2" that was aliased to "stg_customers_v2_deploy"
--    will result in a view being created as "stg_customers_deploy", rather than "stg_mydb__customers".
--  * Have a way to unconditionally drop the view first for databases that don't support `CREATE OR REPLACE VIEW`.
{% macro _do_create_latest_version_view(can_replace_view) %}

    -- this hook will run only if the model is versioned, and only if it's the latest version
    -- otherwise, it's a no-op
    {% if model.get('version') and model.get('version') == model.get('latest_version') %}

        -- this is version substring is copied from what the default generate_alias_name macro generates
        {% set version_search_substring = modules.re.escape("_v" ~ (model.get('version') | replace(".", "_"))) %}
        -- we will look for this version only at the end of the string, or if followed by an underscore, and then
        -- remove only this version substring.
        {% set version_strip_pattern = '(.*)' ~ version_search_substring ~ '((?:_.*)?)' %}
        {% set match = modules.re.fullmatch(version_strip_pattern, this.identifier) %}
        {% if not match %}
            -- We couldn't find the version substring in the identifier.  This is probably due to one of these reasons:
            --  * A generate_alias_name macro was used that did not properly include the version string.
            --  * The user manually aliased the model to a name that does not include the version string.
            --
            -- If this becomes a problem, we may consider whether we want to create this view at all.  A common
            -- scenario might be if the user followed dbt documentation to manually alias latest version of
            -- model 'my_model_v2' to just 'my_model', which would conflict with the view created by this macro.
            -- In this case, we may revisit the decision of throwing an exception, and consider whether we want to
            -- just silently skip creating the view entirely (perhaps logging a message).
            {{ exceptions.raise_compiler_error(
                "Could not find version substring '" ~ version_search_substring ~
                "' in identifier '" ~ this.identifier ~ "'."
            ) }}
        {% endif %}
        {% set new_name = match.group(1, 2) | join %}

        {% set new_relation = this.incorporate(path={"identifier": new_name}) %}

        {% set existing_relation = load_relation(new_relation) %}

        {% if existing_relation and (not existing_relation.is_view or not can_replace_view) %}
            {{ drop_relation_if_exists(existing_relation) }}
        {% endif %}

        {% set create_view_sql -%}
            -- this syntax may vary by data platform
            create {% if can_replace_view -%} or replace {%- endif %} view {{ new_relation }}
                as select * from {{ this }}
        {%- endset %}

        {% do log("Creating view " ~ new_relation ~ " pointing to " ~ this, info = true) if execute %}

        {{ return(create_view_sql) }}

    {% else %}

        -- no-op
        select 1 as id

    {% endif %}

{% endmacro %}
``` 
</details>

[Here is a link to the diff](https://www.diffchecker.com/ZWrXRoW9/) showing what changed from the macro in the dbt documentation.

**Comment by emanuel-luis** [comment]
*upvote

**Comment by Kverm** [comment]
*upvote

**Comment by ttusing** [comment]
I'm pretty surprised this isn't a core feature yet - there are a few things that don't behave as expected with this macro workaround.

For instance - grant configs are not applied to the view. I also think `dbt clone` will not clone the view.

Upvote

**Comment by ttusing** [comment]
I had a bit of a headache where the views being created did not receive grants from the grants feature of DBT, since these views aren't associated with the relation directory.

I threw the problem at Gemini to apply the grants and it works great. Would really like more of this behavior in core.

<details>
<summary>Click to expand: Updated create_latest_version_view Macro</summary>

```
{% macro create_latest_version_view() %}

    -- This hook will run only if the model is versioned and it's the latest version.
    -- Otherwise, it's a no-op.
    {% if model.get('version') and model.get('version') == model.get('latest_version') %}

        {# Define the new relation (the view) using the model's base name #}
        {% set new_relation = this.incorporate(path={"identifier": model['name']}) %}

        {# Check if a relation with the same name already exists and if it's not a view.
           If it's a table, drop it to ensure the view can be created without conflicts. #}
        {% set existing_relation = load_relation(new_relation) %}

        {% if existing_relation and not existing_relation.is_view %}
            {% do log("Dropping existing relation " ~ new_relation ~ " which is a table, to create view.", info=true) %}
            {{ drop_relation_if_exists(existing_relation) }}
        {% endif %}
        
        {# Construct the SQL to create or replace the view, pointing to the latest version of the model #}
        {% set create_view_sql -%}
            create or replace view {{ new_relation }}
              as select * from {{ this }}
        {%- endset %}
        
        {% do log("Creating view " ~ new_relation ~ " pointing to " ~ this, info = true) if execute %}
        
        {# Initialize the final SQL string with the view creation statement #}
        {% set final_sql = create_view_sql %}

        {#
            Now, retrieve and apply the grants configured for the model.
            This block accesses `model.config.grants`, which holds grant definitions
            from your `dbt_project.yml` or the model's `config` block.
            The `execute` check ensures this logic runs during compilation.
        #}
        {% if model.config.grants and execute %}
            {% do log("Applying grants for view " ~ new_relation, info=true) %}
            {% for grant_type, grantees in model.config.grants.items() %}
                {% if grantees is iterable and grantees is not string %} {# Ensure grantees is a list of roles/users #}
                    {% for grantee in grantees %}
                        {# Construct the grant SQL statement for each privilege type and grantee #}
                        {# This generic `grant ... on ... to ...` syntax is broadly compatible across SQL dialects. #}
                        {% set grant_sql = "grant " ~ grant_type ~ " on " ~ new_relation ~ " to " ~ grantee ~ ";" %}
                        {% do log("    " ~ grant_sql, info = true) %}
                        {# Append each grant SQL statement to the final SQL, separated by a newline for readability #}
                        {% set final_sql = final_sql ~ "\n" ~ grant_sql %}
                    {% endfor %}
                {% else %}
                    {% do log("Warning: Grants for type '" ~ grant_type ~ "' are not a list and will be skipped for " ~ new_relation ~ ".", info=true) %}
                {% endif %}
            {% endfor %}
        {% else %}
            {% do log("No grants configured or 'execute' is false for view " ~ new_relation, info=true) %}
        {% endif %}
        
        {# Return the complete SQL string, which dbt will execute #}
        {{ return(final_sql) }}
        
    {% else %}
    
        -- If the model is not versioned or not the latest version, perform a no-op.
        select 1 as id
    
    {% endif %}

{% endmacro %}
```
</details>

Let me know what you think!

**Comment by htitz** [comment]
Upvote

**Comment by alexander-williamson** [comment]
Upvote 👍

**Comment by jtcohen6** [comment]
_Coming back to this issue after a few years! Thanks to @aahel & @dbeatty10 for driving this one forward with me :)_

Here's what I think we could do: After the "latest" version of a versioned model materializes successfully, dbt automatically creates a **view** at the unsuffixed model name (e.g. `dim_customers`) that selects from the latest version (e.g. `dim_customers_v2`). That's the happy path.

This behavior can be controlled by a new model-level config, `latest_version_view`, that has two sub-fields:

```yaml
models:
  - name: dim_customers
    latest_version: 2    # optional - dbt picks max version by collation
    versions:
      - v: 1
      - v: 2
    config:
      latest_version_view:
        enabled: true                 # true by default
        alias: dim_customers_current  # optional; overrides the view name
```

The config can be set project-wide:

```yaml
# dbt_project.yml
models:
  +latest_version_view:
    enabled: false  # opt out globally, re-enable per model
```

Users who want a different naming convention (e.g. `_latest` suffix instead of unsuffixed) can override a new dispatched macro:

```sql
{% macro generate_latest_version_view_alias(node=none) %}
    {{ node.name }}_latest
{% endmacro %}
```

The default macro returns just `node.name` (e.g. `dim_customers`) - unsuffixed - which we keep as the simplest, opinionated default. This is the happiest path - but, crucially, other paths are possible! We heard that feedback loud & clear.

### Happy path

This can be as simple as:

```yaml
models:
  - name: dim_customers
    config:
      materialized: table
    versions:
      - v: 1
      - v: 2
```

What this means:
- the latest version is `v2` (because `latest_version` is not specified)
- when dbt runs `dim_customers_v2`, after materializing the table, it will create a view named `dim_customers` (no suffix) pointing to `dim_customers_v2` (the latest version)
- so dbt produces **three objects** from **two files**:
    - `dim_customers_v1.sql` → `<db>.<schema>.dim_customers_v1` (tbl)
    - `dim_customers_v2.sql` OR `dim_customers.sql` (unsuffixed file because it’s the latest version) → `<db>.<schema>.dim_customers_v2` (tbl) AND `<db>.<schema>.dim_customers` (view with unsuffixed name)

### How users can achieve other (desirable!) behaviors

For **ONE specific** versioned model, OR for **ALL** the versioned models in my project, a user may want to:

- (a) disable the latest-versioned view(s)
- (b) create the latest-versioned view with a different name/suffix
- (c) create the latest version as the unsuffixed model name, without an additional view / DWH object
- (d) point to an **older** version (= the thing downstream consumers were using before versions were introduced), instead of the latest version, to avoid breaking those consumers

While I do not believe we should not make any of ^these the **default** behavior, it should be possible to achieve them with these knobs:

1. Model-level `latest_version` configuration
2. `generate_latest_version_view_alias` macro
3. `generate_alias_name` macro
4. Version-level `alias` config

With those knobs in mind, working through each of those scenarios:

- (a) I can disable latest-version views by setting `latest_version_view.enabled: false`, on one model or many/all models
- (b) I can create the latest-versioned view with a different name/suffix
    - for **one** model by setting `latest_version_view.alias` on that model
    - for **all** models by overriding `generate_alias_name`
- (c) I can disable the `latest_version_view`, and configure my older version with the `alias` of the unsuffixed model name
    
    ```yaml
    models:
      - name: dim_customers
        latest_version: 2
        versions:
          - v: 1
            alias: dim_customers
          - v: 2
        config:
          latest_version_view:
            enabled: false
    ```
    
    dbt would only produce two objects — `dim_customers` (v1) + `dim_customers_v2` — rather than three.
    
    This scenario feels a little wonky, tbh:
    
    - I have a newer version I am calling “latest” (`v2`)
    - but I want `dim_customers` to continue pointing to the previous implementation (`v1`)
    - meaning that a BI tool referencing `<db>.<schema>.dim_customers` (no suffix) will get a **different** version/implementation from a downstream dbt model referencing `ref('dim_customers')` (no `version=` pin) - *and this is what I want*
    
    I’m not going to go so far as to call this an explicit anti-pattern — but it doesn’t feel like a pattern we want to encourage, either. A much happier path would be:
    
    ```yaml
    models:
      - name: dim_customers
        latest_version: 1
        versions:
          - v: 1
          - v: 2
    ```
    
    - dbt will automatically create the unsuffixed view `dim_customers` pointing to `v1` because it’s the latest
    - Downstream consumers selecting from `dim_customers` AND downstream dbt models selecting from `ref('dim_customers')` get the same result - `v1`
    - Downstream consumers AND downstream dbt models can opt into selecting from `v2` explicitly - by selecting from  `ref('dim_customers', v=2)` (within dbt) or `<db>.<schema>.dim_customers_v2` (outside of dbt)
    - The maintainer of `dim_customers` should not bump to `latest_version: 2` until they have communicated / coordinated with all downstream consumers
    
    Importantly - the wonkier scenario is less happy (harder to implement), but it is still *possible* with the knobs that we’ve provided.


If we pursue this approach, a couple of questions:
1. Config name for `latest_version_view` - like, love, hate?
    - I do like `_view` because we're not going to make it any other way!
    - @dbeatty10 would prefer a two-word config over a three-worder if possible
2. Can we safely turn this on by default, in v1.12, for existing versioned models? Or require users to opt in, to avoid unexpected breaking changes during the upgrade?
    - I can think of one failure mode so far - if you have aliased a model version to `model_name` (unsuffixed), without disabling `latest_version_view`, the two will "collide" (same `db.schema.identifier`) and raise an error

**Comment by jtcohen6** [comment]
## Alternative (much simpler) idea

_credit to @graciegoheen_

Premises:
- I want the latest version to materialize as the unsuffixed model name
- I don't want to remember to update the `alias` config every time I add a new model version or update `latest_version` config

Solution:
- I can reimplement `generate_alias_name` to check  `node.is_latest_version` and return the unsuffixed model name - or even suffixed with `_latest`. Rather than creating a separate pointer view, this simply aliases the latest version of the model.


Example:
```sql
{% macro generate_alias_name(custom_alias_name=none, node=none) -%}

    {%- if custom_alias_name -%}

        {{ custom_alias_name | trim }}

    {%- elif node.version and not node.is_latest_version -%}

        {{ return(node.name ~ "_v" ~ (node.version | replace(".", "_"))) }}

    {%- else -%}

        {{ node.name }}

    {%- endif -%}

{%- endmacro %}
```

Meaning:
- If my model is versioned and _not_ the latest version, append `_v#`
- If this model is the latest version, just the unsuffixed model name, please

I remember thinking of this a few years ago, and suggesting it to some folks - so there must be some reason why this isn't desirable / sufficient ... ? @Spince @nicohein @alison985 do you remember, or have thoughts one way or the other?

If a custom `generate_alias_name` macro solves for the use case, without any additional complexity (or implementation work) - this could be our recommended pattern, instead of the `create_latest_version_view` post-hook. At minimum I think [we should document it](https://docs.getdbt.com/docs/mesh/govern/model-versions) as a viable path!

**Comment by joellabes** [comment]
> so there must be some reason why this isn't desirable / sufficient

This approach removes the ability to proactively pin to a specific version. 

```
models:
  - name: dim_customers
    latest_version: 2
    versions:
      - v: 1
      - v: 2
      - v: 3
```

creates the db objects
```
analytics.prod.dim_customers_v1
analytics.prod.dim_customers
analytics.prod.dim_customers_v3
```

I have a load-bearing dashboard which is incompatible with v3. If it's Monday, and v3 is going to be turned into the latest version on Friday at midday, what can I do between now and then to pre-pin to v2? 

At 12.01 pm my database will start looking like this: 

```
analytics.prod.dim_customers_v1
analytics.prod.dim_customers_v2
analytics.prod.dim_customers
analytics.prod.dim_customers_v3
```

So I'd better be sitting at my laptop ready to find-and-replace `dim_customers(\b)` with `dim_customers_v2$1` before anyone notices the queries are failing. 

Bonus footgun: analytics.prod.dim_customers_v3 [still exists](https://discourse.getdbt.com/t/faq-cleaning-up-removed-models-from-your-production-schema/113) but will never be refreshed again (until v4 is marked as the latest_version). So anyone who built a model on top of the prerelease table – or stumbles across it in their data catalog – will also have a bad experience.
