### ISSUE TITLE
Generic tests for schemas (datasets)

### ISSUE THREAD

**Issue by lauralehoczkiCE** [dbt-labs/dbt-core#7516]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Native generic dbt tests that operate on a schema (dataset) instead of a model. Ideally one would be able to add them to a dataset just like a generic test on models, in the schema.yml or dbt_project.yml.

**Comment by Harmuth94** [comment]
You can specify tests for non-models using `sources`. For example in this example source specification tests would be run against existing the table `my_schema.mytable` with `dbt test`.

```yaml
version: 2
sources:
  - name: my_schema
    tables:
      - name: my_table
        columns:
          - name: col_a
            tests:
              - nut_null:
          - name: col_b
            tests:
              - unique
```
