### ISSUE TITLE
[CT-2536] [Feature] Enable `indirect_selection` as a global config

### ISSUE THREAD

**Issue by otttt** [dbt-labs/dbt-core#7518]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

By default indirect-selection is eager. Aim is to define in on project level as cautious or buildable to reduce code in selectors.

### Describe alternatives you've considered

Right now my solution is to define it separately in every selector as cautious.

**Comment by dbeatty10** [comment]
Thanks for reaching out @otttt !

Did you already try setting the `DBT_INDIRECT_SELECTION` environment variable?

**Comment by dbeatty10** [comment]
If you are using [YAML selectors](https://docs.getdbt.com/reference/node-selection/yaml-selectors#full-yaml), you can also do something like this:

```yaml
selectors:
  - name: nodes_to_joy
    definition:
      method: tag
      value: nightly
      parents: true
      indirect_selection: cautious
```
