### ISSUE TITLE
[CT-2578] [Feature] Hierarchical access config in dbt_project.yml

### ISSUE THREAD

**Issue by sp-tkerlavage** [dbt-labs/dbt-core#7619]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The new groups and access features have been defined as properties
https://docs.getdbt.com/reference/resource-properties/access

Is it possible to instead define them as configs so that they can be specified in the dbt_project.yml hierarchically?
dbt_project.yml:
```
models:
  <resource-path>:
    +group: path1
    +access: private
  <resource-path>:
    +group: path2
    +access: public
```

Then certain model configurations can override these hierarchical definitions?
path1.yml
```
groups:
  - name: path1
    owner:
      name: Customer Success Team
      email: cx@jaffle.shop

# Then, add 'group' + 'access' modifier to specific models
models:
  # This is a public model -- it's a stable & mature interface for other teams/projects
  - name: dim_customers
    group: path1
    access: public
```

### Describe alternatives you've considered

Obviously we can define the access individually for each model as shown in the documentation

### Who will this benefit?

Anyone that wants to hierarchically apply groups/access to large swaths of models

### Are you interested in contributing this feature?

Most likely not familiar enough with the inner workings of dbt-core to contribute

**Comment by dbeatty10** [comment]
Thanks for reaching out @sp-tkerlavage !

The [`group` config](https://docs.getdbt.com/reference/resource-configs/group) can be defined in `dbt_project.yml`, and it can already be defined hierarchically as you describe (see example below).

Are you requesting that the [`access` property](https://docs.getdbt.com/reference/resource-properties/access) be a converted from a property to a config as well?

<details>
<summary>

### Example
</summary>

Suppose you have the following directory tree:
```
models/
├── _models.yml
├── resource_path_1
│   └── stg_customers.sql
└── resource_path_2
    └── dim_customers.sql
```

And this `models/_models.yml`:
```yaml
groups:
  - name: path1
    owner:
      name: Customer Success Team
      email: cx@jaffle.shop
  - name: path2
    owner:
      name: Developer Experience Team
      email: dx@jaffle.shop
```

And this `dbt_project.yml`:
```yaml
name: "my_project"
version: "1.0.0"
config-version: 2
profile: "sandcastle"


models:
  my_project:
    resource_path_1:
      +group: path1
    resource_path_2:
      +group: path2
```

Then we can see that the `group` config is taken into account (and you can override it in a `_properties.yml` or the `.sql` or `.py` model file):
```shell
dbt \
    --quiet \
    ls \
    --output json \
    --output-keys name original_file_path version access group contract latest_version \
    -s '*.dim_customers*' \
| python -m json.tool
```

Output:
```json
{
    "name": "dim_customers",
    "original_file_path": "models/resource_path_2/dim_customers.sql",
    "group": "path2",
    "contract": {
        "enforced": false,
        "checksum": null
    },
    "access": "protected",
    "version": null,
    "latest_version": null
}
```

</details>

**Comment by sp-tkerlavage** [comment]
Yes thats what I meant, sorry for the confusion. I meant it would be nice to have the access property as a config so that it can be assigned hierarchically.

**Comment by sp-tkerlavage** [comment]
Actually one last bit of input, if the goal is to make sure that model access is set to `public` consciously, could access be a hierarchical configuration that is only configurable to either `protected` _or the more restrictive_ `private`?

Or another suggestion is for access a property of the group, where again it can either be left as the default `protected`, or made more restrictive by explicitly setting it to private

```
groups:
  - name: path1
    access: private
    owner:
      name: Customer Success Team
      email: cx@jaffle.shop
  - name: path2
    # this will just use the default of access: protected
    owner:
      name: Developer Experience Team
      email: dx@jaffle.shop
```

In my use case I want everything to be `private`.With the current implementation, there's a risk of someone creating a model and forgetting to assign it an access level. If someone does forget to make the access policy more restrictive, models from outside the group can reference it later on in the pipeline it becomes difficult to find.
