### ISSUE TITLE
[Bug] directories containing only source .yml files are reported as lacking configuration paths and config directives not applied

### ISSUE THREAD

**Issue by codigo-ergo-sum** [dbt-labs/dbt-core#7660]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We are using the helpful dbt-meta-testing package (https://github.com/tnightengale/dbt-meta-testing) to validate that certain kinds of tests exist for all sources and models in our dbt project.

One of the directories in our project is used only for source definitions. E.g. we have a structure like this:

- models
- - source_yml
- - - source_1
- - - source_2

We want to use dbt_meta_testing to enforce that sources also have certain kinds of tests. We define a separate .yml file for each incoming table, so, if `source_1` has two tables, we will have two .yml files, e.g. `table_1.yml` and `table_2.yml`. Then the contents of `table_1.yml` would look like this:

```
version: 2

sources:
  - name: source_1
    database: fivetran-dev
    tables:
    - name: bench_cost_report

      freshness:
        error_after: {count: 2, period: hour}

      loaded_at_field: _fivetran_synced

      columns:
        - name: created
          tests:
            - not_null

        - name: report_date
          tests:
            - not_null

        - name: last_updated
          tests:
            - not_null

        - name: created_by
          tests:
            - not_null

        - name: bench_cost_report_id
          tests:
            - not_null
            - unique
            - dbt_utils.at_least_one

```

Then we want to use `dbt_project.yml` with dbt_meta_testing to validate that every source in each of these directories has a `unique` test, a `not_null` test, and an `at_least_one` test. So we do this in our `dbt_project.yml`:

```
    source_yml:
      source_1:
        +required_tests:
          "^unique$": 1
          "^not_null$": 1
          "at_least_one$": 1
      source_2:
        +required_tests:
          "^unique$": 1
          "^not_null$": 1
          "at_least_one$": 1
```

However, what happens right now when we do this is dbt gives us this warning:

```
15:33:06  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.project.source_yml.source_1
- models.project.source_yml.source_2
```

But that's not true - there are resources defined there - it's just that they are not models, they are sources. Can dbt be made more robust in validating cases like this where other objects like sources exist in a directory even if models don't? Also, it looks like dbt_meta_testing isn't able to validate missing tests in these directories - I tried "testing for failure" to see if it would catch a missing test, and it doesn't. That may be a bug with dbt_meta_testing but I wonder if it's actually an underlying issue with dbt core because core isn't somehow detecting or parsing the sources in these directories in the same way as it is for other models.

### Expected Behavior

I would expect dbt core to detect a case where a directory has only sources, or any other type of non-model resources defined in a directory, appropriately apply configuration directives defined in dbt_project.yml, and then also not give a warning that paths are defined in dbt_project.yml which do not apply to any resources.

### Steps To Reproduce

1. Create a directory in the dbt project and then add only one file in it with a source definition
2. Create a configuration directive in dbt_project.yml which applies to this directory.
3. Run a dbt command and see output warning and also how config directive is ignored.

### Relevant log output

```shell
15:33:06  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.project.source_yml.source_1
- models.project.source_yml.source_2
```

### Environment

```markdown
- OS:MacOS Ventura 13.3.1
- Python:3.9.6
- dbt: 1.5.0
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thanks for reaching out @codigo-ergo-sum !

Does your `dbt_project.yml` look like this, by any chance?

```yaml
models:
  my_project:
    source_yml:
      source_1:
        +required_tests:
          "^unique$": 1
```

If so, could you try replacing `models:` with `sources:` instead?
```yaml
sources:
  my_project:
    source_yml:
      source_1:
        +required_tests:
          "^unique$": 1
```

When I do the former and execute `dbt ls`, I get the same warning as you. When I do the latter, the warning goes away.

**Comment by codigo-ergo-sum** [comment]
Thanks @dbeatty10. So you are right, I should have thought of that, that "works" in the sense that dbt is no longer complaining about unused configuration paths.

Unfortunately, it looks like dbt_meta_testing doesn't support validating required tests for sources nor for seeds, only for models. I filed a ticket asking about that: https://github.com/tnightengale/dbt-meta-testing/issues/26

As a larger question though, why have separate hierarchies like this for models versus sources in the `dbt_project.yml` file? Sources and models both occupy the same directory hierarchy under `models` in the directory structure and it can result in code duplication and confusion having to look in two different places. I can sort of see it for seeds as they have a separate directory hierarchy structure.

**Comment by dbeatty10** [comment]
Glad that this "works" for you now in the sense that dbt is no longer complaining about unused configuration paths. 

I trust and hope that the issue you've opened in `dbt_meta_testing` will be able to get you the rest of the way there. 😎

### Question
> why have separate hierarchies like this for models versus sources in the `dbt_project.yml` file?

Good question! Those hierarchies within `dbt_project.yml` are separated by resource type since they have different expected key structures:
- [source](https://docs.getdbt.com/reference/source-configs#available-configurations) 
- [model](https://docs.getdbt.com/reference/model-configs#model-specific-configurations)
- [seed](https://docs.getdbt.com/reference/seed-configs#seed-specific-configurations)
- [snapshot](https://docs.getdbt.com/reference/snapshot-configs#snapshot-specific-configurations)
- [test](https://docs.getdbt.com/reference/test-configs#test-specific-configurations)

e.g., `sources` has this hierarchy:
- project name > source name > table name

whereas `models` has this hierarchy:
- project name > directory

Also each resource type has different configurations that are available to it and you may want configure each differently.

### Next steps

It seems like dbt-core is working as intended here, and I'd like to close this unless we have something outstanding left to cover. What do you think @codigo-ergo-sum ?

**Comment by codigo-ergo-sum** [comment]
Hi @dbeatty10. Is it not possible to specify a setting that applies across all tables for a given source? I'm running into issues referring to this by the actual source names, from our `dbt_project.yml` file:

```
sources:

  oba_postgres_public:
    +required_tests:
      "^unique$": 1
      "^not_null$": 1
      "at_least_one$": 1
  oba_postgres_secure_db:
    +required_tests:
      "^unique$": 1
      "^not_null$": 1
      "at_least_one$": 1
```

Which gives me this message:

```
23:00:22  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- sources.oba_postgres_secure_db
- sources.oba_postgres_public
```

Also including our project name doesn't work either:

```
sources:

  op_analytics:

    oba_postgres_public:
      +required_tests:
        "^unique$": 1
        "^not_null$": 1
        "at_least_one$": 1
    oba_postgres_secure_db:
      +required_tests:
        "^unique$": 1
        "^not_null$": 1
        "at_least_one$": 1
```

Output:

```
23:03:02  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- sources.op_analytics.oba_postgres_secure_db
- sources.op_analytics.oba_postgres_public
```

**Comment by dbeatty10** [comment]
> Is it not possible to specify a setting that applies across all tables for a given source?

It is possible to specify a setting that applies across all tables for a given source within `dbt_project.yml`, but you'll need to get the folder structure _just_ right.

@codigo-ergo-sum could you give the following a try and let me know if it works for you or not?

### Example

Folder structure:
```
models
└── some
    └── very
        └── deeply
            └── nested
                └── folder
                    └── _sources.yml
```

`models/some/very/deeply/nested/folder/_sources.yml`
```yaml
version: 2

sources:
  - name: oba_postgres_public
    tables:
    - name: some_table_1
  - name: oba_postgres_secure_db
    tables:
    - name: some_table_2
```

`dbt_project.yml`
```yaml
name: "my_project_name"
version: "1.0.0"
config-version: 2
profile: "sandcastle"

sources:
    some:
      very:
        deeply:
          nested:
            folder:
              oba_postgres_public:
                +required_tests:
                  "^unique$": 1
                  "^not_null$": 1
                  "at_least_one$": 1
              oba_postgres_secure_db:
                +required_tests:
                  "^unique$": 1
                  "^not_null$": 1
                  "at_least_one$": 1
```

Finding the full path for all your sources:
```shell
dbt -q ls --output json -s 'source:*' | python -m json.tool --json-lines
dbt -q ls --output json --resource-type source | python -m json.tool --json-lines
```

Or for one particular source:
```
dbt -q ls --output json -s source:my_project_name.oba_postgres_public.some_table_1 | python -m json.tool --json-lines
```

```json
{
    "name": "some_table_1",
    "resource_type": "source",
    "package_name": "my_project_name",
    "original_file_path": "models/some/very/deeply/nested/folder/_sources.yml",
    "unique_id": "source.my_project_name.oba_postgres_public.some_table_1",
    "source_name": "oba_postgres_public",
    "tags": [],
    "config": {
        "enabled": true
    }
}
```
