### ISSUE TITLE
[Bug] Selectors in `selectors.yml` do not default to `--indirect-selection` or `DBT_INDIRECT_SELECTION`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#7673]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When a [YAML selector](https://docs.getdbt.com/reference/node-selection/yaml-selectors#indirect-selection) definition does not include `indirect_selection`, then neither the `--indirect-selection` CLI argument nor the `DBT_INDIRECT_SELECTION` environment variable have any effect.

Instead, these YAML selectors always default to `eager`, no matter what.

### Expected Behavior

[This](https://github.com/dbt-labs/docs.getdbt.com/blob/89f838049f13829312edf833f6cbdec5e604fa5e/website/docs/reference/node-selection/yaml-selectors.md?plain=1#L167) says:
> If provided, a YAML selector's `indirect_selection` value will take precedence over the CLI flag `--indirect-selection`. 

And [this](https://github.com/dbt-labs/dbt-core/blob/87ea28fe84edd65d589fd3cf658d8dd1f65c000a/core/dbt/graph/selector_spec.py#L120) says:
> If defined field in selector, override CLI flag

Both of those imply that the intent was that selectors would use `get_flags().INDIRECT_SELECTION` or `flags.INDIRECT_SELECTION` when `indirect_selection` is not defined within a selector in `selectors.yml`.

## Reprex

<details>
<summary>

### Project contents
</summary>

`models/_models.yml`
```yaml
version: 2

models:
  - name: model_b
    columns:
      - name: id
        tests:
          - relationships:
              to: ref('model_a')
              field: id
  - name: model_c
    columns:
      - name: id
        tests:
          - relationships:
              to: ref('model_b')
              field: id
```

`models/model_a.sql`
```sql
select 1 as id
```

`models/model_b.sql`
```sql
select * from {{ ref("model_a") }}
```

`models/model_c.sql`
```sql
select * from {{ ref("model_b") }}
```

`selectors.yml`
```yaml
selectors:
  - name: my_selector
    definition:
      method: fqn
      value: model_b
```

</details>

### Try it
Compare the output of these commands:
```shell
dbt ls -s model_b --indirect-selection eager
dbt ls -s model_b --indirect-selection cautious
dbt ls -s model_b --indirect-selection buildable
```
with the output of these:
```shell
dbt ls --selector my_selector --indirect-selection eager
dbt ls --selector my_selector --indirect-selection cautious
dbt ls --selector my_selector --indirect-selection buildable
```

### Expectations

Eager:
```
my_project.model_b
my_project.relationships_model_b_id__id__ref_model_a_
my_project.relationships_model_c_id__id__ref_model_b_
```

Buildable:
```
my_project.model_b
my_project.relationships_model_b_id__id__ref_model_a_
```

Cautious:
```
my_project.model_b
```

### Diagram
<img width="450" alt="image" src="https://user-images.githubusercontent.com/44704949/206818219-24bc93ea-8e54-43bf-814f-d8f6b4fc4899.png">

### Environment

```markdown
- OS:
- Python:
- dbt: 1.5.0
```

### Additional Context

I tried a sampling of versions between dbt v1.0 and v1.5 and none of them took the `--indirect-selection` CLI argument into account for selectors.

I didn't include the `empty` mode for indirect selection in the reprex because I already had a diagram without it, and it doesn't affect explaining the bug report one way or the other. `buildable` isn't a relevant option prior to v1.4 and could have been left out as well, but it was already in the diagram so it gets to come along for the ride 😃
