### ISSUE TITLE
[CT-2598] [Bug] Get a error when load a csv file with cyrrilic symbols

### ISSUE THREAD

**Issue by shpunt** [dbt-labs/dbt-core#7701]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Error loading for files with cyrrilic symbols
[example.csv](https://github.com/dbt-labs/dbt-core/files/11561950/example.csv)

### Expected Behavior

Load all files

### Steps To Reproduce

OS: macOS Ventura 13.3.1 
Python: 3.11.3
dbt-core: 1.5.0

part of config for seeds:
```
name: dict_product_ean
    config:
      quote_columns: false
      column_types: {product_id: varchar, product_name: varchar}
      distribute_by_replication: true
```
run command: dbt seed

### Relevant log output

```shell
06:56:22  Finished running 4 seeds in 0 hours 0 minutes and 2.54 seconds (2.54s).
06:56:22
06:56:22  Completed with 1 error and 0 warnings:
06:56:22
06:56:22  Runtime Error in seed dict_product_ean (seeds/dict_product_ean.csv)
06:56:22    'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
06:56:22
06:56:22  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
```

### Environment

```markdown
- OS: macOS Ventura 13.3.1 
- Python: 3.11.3
- dbt: 1.5.0
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
Thanks for reaching out @shpunt!

I wasn't able to reproduce that error message with the project setup below. Could you try out the example below and see if it works for you or not?

If it works fine, could you try tweaking it to get the same error as you reported? 

### Reprex

`seeds/example.csv`
```csv
product_id,product_name
xxx-001,Smart Plug
xxx-002,Тест
```

`models/_seeds.yml`
```yaml
version: 2

seeds:
  - name: example
    config:
      column_types:
        product_id: varchar
        product_name: varchar
```

```shell
dbt seed --full-refresh
```
