### ISSUE TITLE
Compilation error when rendering filter in metrics

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/dbt-core#7864]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have a metric with a filter defined: 
```
metrics:
  - name: "east_coast_order_amount"
    description: "Sum of orders from the east coast."
    type: simple
    label: "test"
    type_params:
      measures:
        - orders
    filter: |
      {{dimension('location_name')}} in ('Philadelphia')"
```

When I execute `dbt run` I get the following error:
```
Compilation Error
  Could not render {{dimension('location_name')}} in ('Philadelphia')
  : 'dimension' is undefined
```

This is likely due to the parser trying to render jinja when it encounters the double curlies, which it shouldn't be doing. If i escape the curlies dbt run succeeds. i.e 
```
metrics:
  - name: "east_coast_order_amount"
    description: "Sum of orders from the east coast."
    type: simple
    label: "test"
    type_params:
      measures:
        - orders
    filter: |
      \{\{dimension('location_name')\}\} in ('Philadelphia')"
```

### Expected Behavior

dbt should parse the filter correctly.

### Steps To Reproduce

Define a filter in a semantic model and run `dbt run`.

### Environment

```markdown
- OS:
- Python:
- dbt:
```
