### ISSUE TITLE
[CT-2698]  `use_approximate_percentile` and `use_discrete_percentile` keys defualt to None but are defined as bool in the protocol

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/dbt-core#7866]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The default None for `use_approximate_percentile` and `use_discrete_percentile` causes an error. I need to define the bool value for these parameters in the measure. However, I should only assign true or false to these parameters if I need to use them, and they should default to false. 

Current implementation:
```
- name: discrete_order_value_p99
        expr: order_total
        agg: percentile
        agg_params:
          percentile: 0.99
          use_discrete_percentile: True
          use_approximate_percentile: False
        create_metric: true
```

Expected implementation:
```
- name: discrete_order_value_p99
        expr: order_total
        agg: percentile
        agg_params:
          percentile: 0.99
          use_discrete_percentile: True
        create_metric: true
```

### Expected Behavior

I should not need to define true or false explicitly for use_discrete_percentile and use_approximate_percentile. They should default to false. 

### Steps To Reproduce

Define a measure like below and run dbt run.

```
- name: discrete_order_value_p99
        expr: order_total
        agg: percentile
        agg_params:
          percentile: 0.99
          use_discrete_percentile: True
        create_metric: true
```

### Environment

```markdown
- OS:
- Python:
- dbt:
```
