### ISSUE TITLE
[CT-2705] dbt deps behaves different between windows and linux  when adding a package 

### ISSUE THREAD

**Issue by heshamh96** [dbt-labs/dbt-core#7874]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

i currently have a project that has the expermntal features [materialized views] added to the packages.yml

and i get 2 different responses when running  dbt deps on windows machine and linux machine
the windows reponse ends up adding the packages successfully as per the following

while the linux response is the following 

`16:02:09  Running with dbt=1.5.1
16:02:13  Encountered an error:
Internal Error
  Error checking out spec='HEAD' for repo https://github.com/dbt-labs/dbt-labs-experimental-features
  error: No such remote 'origin'`
        

### Expected Behavior

the windows output is the following

'
14:45:41  WARNING: The git package "https://github.com/dbt-labs/dbt-labs-experimental-features" 
        is None.
        This can introduce breaking changes into your project without warning!

See https://docs.getdbt.com/docs/package-management#section-specifying-package-versions
14:45:41  Installing dbt-labs/codegen
14:45:41  Installed from version 0.9.0
14:45:41  Up to date!
14:45:41  Installing https://github.com/dbt-labs/dbt-labs-experimental-features
14:45:42  Installed from HEAD (default revision)
14:45:42  and subdirectory materialized-views
14:45:42  Installing calogica/dbt_date
14:45:42  Installed from version 0.7.2
14:45:42  Up to date!
14:45:42  Installing dbt-labs/dbt_utils
14:45:43  Installed from version 1.1.1
14:45:43  Up to date!
'

### Steps To Reproduce

on both machines i did the following

1- created a conda environment and performed pip install dbt-redshift

2- cloned the project 

3- switched to a branch that is in a working state

4- ran dbt clean

5- ran dbt deps

### Environment

```markdown
- OS: POP_OS 22.04
- Python:3.10.11
- dbt:1.5.1
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

![image](https://github.com/dbt-labs/dbt-core/assets/24191100/0e64023e-04dd-42fd-b999-c8316e30ec16)

**Comment by dbeatty10** [comment]
Thanks for reaching out @heshamh96 !

Could you share a copy of your `packages.yml` file?

Also, could you try each of the following options and see if they work for you or not?

The most recent revision of [this](https://github.com/dbt-labs/dbt-labs-experimental-features) repo:
```yaml
packages:
  - git: "https://github.com/dbt-labs/dbt-labs-experimental-features"
    subdirectory: "materialized-views"
    revision: 7200ac20a070ac7ba0eb13707453df1a1fa87380
```

`main` branch of that same repo:
```yaml
packages:
  - git: "https://github.com/dbt-labs/dbt-labs-experimental-features"
    subdirectory: "materialized-views"
    revision: main
```

Side note: if you are interested in materialized views, they are going to be included in dbt v1.6 🚀  Read more here: https://github.com/dbt-labs/dbt-core/issues/6911

**Comment by heshamh96** [comment]
yeah sure ...

```
packages:
  - package: dbt-labs/codegen
    version: 0.9.0
  
  #- package: dbt-labs/dbt_utils
  # version: 1.1.0

  - git: https://github.com/dbt-labs/dbt-labs-experimental-features
    subdirectory: materialized-views
  
  - package: calogica/dbt_date
    version: 0.7.2
```


i just would like to let you know that after troubleshooting... it's resolved for me 

apparently  dbt deps when trying to clone the subdirectory from this second package which is  a package on github  

it can't generate because there was a git configuration called 
`clone.defaultremotename=all `
this value was unset on windows configuration 

so when i tried to unset it in Linux using the following command

`git config --global --unset clone.defaultremotename`

 it got resolved .... so i think dbt deps is senstive to such configuration ... not sure why honestly ... but as i said it's now fixed
