### ISSUE TITLE
[CT-2714] [Bug] [Snowflake] Model contracts: `null as [column_name]` is created as a varchar column despite contract specifying number 

### ISSUE THREAD

**Issue by mogensni** [dbt-labs/dbt-core#7901]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Creating a model where some columns are defined as `null as [column name]`. These columns seem to be created as varchar columns, despite the contract datatype specifies that the column should be number.

### Expected Behavior

When the contract datatype is `number` the column should be created as a column of datatype number and not varchar.

### Steps To Reproduce

1. Environment (running as virtualenvironment
```
Core:
  - installed: 1.5.1
  - latest:    1.5.1 - Up to date!

Plugins:
  - snowflake: 1.5.1 - Up to date!
```
2. I *think* config i irrelevant
3. Create `new_model.sql`

```
select null as foo
```

Add yaml definition

```
models:
  - name: new_model
    description: ""
    config:
      contract:
        enforced: true
    columns:
      - name: foo
        data_type: number(38, 0)
```
Run `dbt run -s new_model`
4. I get this result

```
07:10:45    | column_name | definition_type | contract_type | mismatch_reason    |
07:10:45    | ----------- | --------------- | ------------- | ------------------ |
07:10:45    | FOO         | TEXT            | FIXED         | data type mismatch |
```

### Environment

```markdown
- OS: Windows 10
- Python: 3.10.6
- dbt-core: 1.5.1
- dbt-snowflake: 1.5.1
```

### Which database adapter are you using with dbt?

snowflake
