### ISSUE TITLE
[CT-2731] Semantic Models should be able to reference sources

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/dbt-core#7934]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently, semantic models can only be built from another model: 
```
semantic_models:
 - name: customers
    model: ref('customers')
```

We should allow semantic models to be defined from sources. This is useful to users who do not use dbt for transformations, but want to use the semantic layer. I'm envisioning these users setting up a shallow DAG that only contains sources, semantic models, and metrics where the sources are tables they build outside of dbt. This is an easy entry point to the dbt ecosystem that doesn't require moving your transformation pipeline to dbt. A user could define a semantic model like this:
```
semantic_models:
 - name: customers
    model: source('seeds', 'customers')
```

### Describe alternatives you've considered

Without this feature, you could write a dbt model like the one below for each table:

```
select
*
from seeds.customers
```
It would be much easier to define one source config, instead of 3 separate models:

```
sources:
  - name: tutorial
    schema: seeds
    description: Data sets for running mf tutorial
    tables:
      - name: $transactions_table
      - name: $customers_table
      - name: $countries_table
```

### Who will this benefit?

Users who don't use dbt and want to use the semantic layer. Users who want to create semantic models from sources!
