### ISSUE TITLE
[CT-2751] Support Configuration and Enabling/Disabling Semantic Models

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#7968]
**Acceptance Criteria**

- A `semantic_model` can be enabled and disabled by YAML configuration, both individually and at the project level.
- A `semantic_model` can be configured to belong to a `group`, both individually and at the project level, so that it can `ref` a private model within the same group.

```
# models/semantic.yml
```yml
semantic_models:
  - name: orders
    config:
      enabled: true | false
      group: some_group
```
```yml
# dbt_project.yml
semantic_models:
  my_project_name:
    +enabled: true | false
    +group: some_group
```
