### ISSUE TITLE
[CT-2760] Add additional parameter the column in the model.yml

### ISSUE THREAD

**Issue by RalfKow** [dbt-labs/dbt-core#7982]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I have the sql
```sql
create table if not exists meta.product_information (
    product_name varchar(255) comment 'Name des Datenproduktes',
    product_description	text comment 'Kurze Beschreibung des Datenproduktes',
    schema variant comment 	'JSON welches Datentypen und Beschreibungen zu Feldern des Produkts liefert',
    schema_change_ts timestamp comment 'Letzte Änderung am Datenmodel',
    created timestamp default current_timestamp() comment 'Erstellungsdatum des Produkts'
    _hash bigint default {{ _hash() }}
);
```

Is it possible to configer it in a .yaml file

f.E
```yaml
version: 2

models:
  - name: lod_dim_measure_1_load
    config:
      schema: ramsi_loading
      materialized: incremental
    description: "Dimension table of measure"
    columns:
      - name: _hash
        description: "Hash over all primary key's"
        meta:
          datatype: varchar(200)
          default: {{ _hash() }}
```

### Describe alternatives you've considered

Writing it in sql

### Who will this benefit?

Everyone how uses the model

**Comment by dbeatty10** [comment]
Thank you for reaching out @RalfKow !

Could you take a look at the following example and see if there's something missing that you are hoping for and want to propose?

In particular, you can use the following:
- [`columns` properties](https://docs.getdbt.com/reference/resource-properties/columns) for `description`s and `data_type`s
- [`persist_docs` configuration](https://docs.getdbt.com/reference/resource-configs/persist_docs) to write the descriptions out as table / column comments
- `coalesce()` to fill in default values (note in the example below that this approach **won't** show up in the DDL but should achieve a similar effect)

To reproduce the DDL you showed, I think you'd want something like the following (which I didn't fully test out):

`models/product_information.sql`
```sql
with stg__product_information as (
    ....
)

select
    cast(product_name as varchar(255)) as product_name,
    cast(product_description as text) as product_description,
    cast(schema as variant) as schema,
    cast(schema_change_ts as timestamp) as schema_change_ts,
    cast(coalesce(created, current_timestamp()) as timestamp) as created,
    cast(coalesce(_hash, {{ _hash() }}) as bigint) as _hash
from stg__product_information
```

`models/_models.yml`
```yaml
models:
  - name: product_information
    config:
      materialized: table
      schema: meta
      +persist_docs:
        relation: true
        columns: true
    columns:
      - name: product_name
        description: Name des Datenproduktes
        data_type: varchar
      - name: product_description
        description: Kurze Beschreibung des Datenproduktes
        data_type: text
      - name: schema
        description: JSON welches Datentypen und Beschreibungen zu Feldern des Produkts liefert
        data_type: variant
      - name: schema_change_ts
        description: Letzte Änderung am Datenmodel
        data_type: timestamp
      - name: created
        description: Erstellungsdatum des Produkts
        data_type: timestamp
      - name: _hash
        data_type: bigint
```
