### ISSUE TITLE
[CT-2774] Optional type aliasing for model contract `data_type`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#8007]
Give users a way to opt into dbt adapters' built-in type translation, for the `data_type` defined in their contract.

```yml
config:
  contract:
    enforced: true
    alias_types: true
```

E.g. on Postgres/Redshift, I could write `string` instead of `text` and it would "just work". It would continue to "just work" if I take the same model with the same contract and run it on Snowflake/BigQuery/etc — _if_ the type aliasing for those adapters is correctly implemented._ That's a big "if", which is why this functionality should be optional and off by default.
```yml
models:
  - name: my_model
    config:
      contract:
        enforced: true
        alias_types: true
    columns:
      - name: my_string_col
        data_type: string  # will be aliased to 'text' or kept as 'string' depending on data platform
      - name: my_int_col
        data_type: integer  # 'int' or 'int64'
```

The implementation should be fairly simple: Wherever we access the `data_type` for contract enforcement / DDL templating, we should wrap it in `{{ return(api.Column.translate_type("string")) }}`.

https://github.com/dbt-labs/dbt-core/blob/5d937802f1d5b34baeb8412cca68bfb33112a763/core/dbt/adapters/base/column.py#L23C1-L25

This would have the same effect as letting users write `{{ dbt.type_timestamp() }}` instead of just the string `"timestamp"`, given [those macros actually call `translate_type` behind the scenes](https://github.com/dbt-labs/dbt-core/blob/5d937802f1d5b34baeb8412cca68bfb33112a763/core/dbt/include/global_project/macros/utils/data_types.sql#L8).
