### ISSUE TITLE
[Bug] Error - `cannot reference permanent table from temporary table constraint` when running incremental model with a foreign key

### ISSUE THREAD

**Issue by amardatar** [dbt-labs/dbt-core#8022]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running an incremental model with contract enforced and a foreign key, the model will fail on subsequent updates.

### Expected Behavior

The update should succeed without an error.

### Steps To Reproduce

First run a statement like:
```sql
create table if not exists numbers (n int not null primary key)
```

Then, given a `schema.yml` file:

```yml
version: 2

models:
  - name: test
    config:
      contract:
        enforced: true
      materialized: incremental
      on_schema_change: append_new_columns
      unique_key: n
    columns:
      - name: n
        data_type: integer
        constraints:
          - type: foreign_key
            expression: "numbers (n)"
```

And a SQL file:

```sql
select 1 as n
```

dbt will succeed on the first run, and subsequently fail with the error:
```
cannot reference permanent table from temporary table constraint
```

As per the error returned, the issue appears to be that while rendering a temporary table as part of the update, dbt will also render the foreign key constraint (which is not valid in the context of a temporary table). This leads to the above failure.

### Environment

```markdown
- OS: macOS Ventura 13.4.1
- Python: 3.11.4
- dbt: 1.5.2
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

While I've run into this issue using Redshift (and using the `dbt-redshift` adapter) I've put this bug in `dbt-core` as I believe from a bit of research that the same issue would occur if this were run in PostgreSQL (and possibly in other data warehouses, although it was harder to research the issue broadly).

**Comment by LeviAndrewDixon** [comment]
I have the same issue on Postgres 15.x, dbt: 1.52, dbt-postgres:1.5.2 with an incremental model: i.e. `materialized="incremental"`.  It works on full-refresh and fails on subsequent builds when `is_incremental()` is `true`.

```
18:54:56  Database Error in model fact_session (models/public/fact_session.sql)
18:54:56    constraints on temporary tables may reference only temporary tables
```

dim_partner:
```
models:
  - name: dim_partner
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: varchar(32)
        constraints:
          - type: primary_key
          - type: not_null
...
```

fact_session:
```
  - name: fact_session
    config:
      contract:
        enforced: true
    columns:
      - name: partner_id
        data_type: varchar(32)
        constraints:
          - type: not_null
          - type: foreign_key
            expression: "dim_partner (id) ON DELETE CASCADE"
...
```
