### ISSUE TITLE
[CT-2789] [Bug] Contract checksum not appropriately built for versioned models

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#8030]
Versioned models do not appropriately generate their contract checksums during parsing, if the `contract` enforcement config is defined in yaml (as opposed to in-file `{{ config }}`). Meaning that `same_contract` checks always return `True` for this type of versioned model.

### Repro case

Start with:
```sql
-- models/my_model.sql
select 1 as id
```
```yml
models:
  - name: my_model
    config:
      contract: {enforced: true}
    columns:
      - name: id
        data_type: integer

    versions:
      - v: 1
```

Generate a manifest and move it to a local folder:
```
$ mkdir state/
$ dbt parse
$ mv target/manifest.json state/
```

Change to:
```sql
-- models/my_model.sql
select 1 as id
```
```yml
models:
  - name: my_model
    config:
      contract: {enforced: true}
    columns:
      - name: id
        data_type: text

    versions:
      - v: 1
```

Then select modified models. I expected to see a Breaking Change to Contract Error:
```
$ dbt -q ls -s state:modified --state state/
09:37:41  Encountered an error:
Breaking Change to Contract Error in model my_model (models/my_model.sql)
  While comparing to previous project state, dbt detected a breaking change to an enforced contract.

  Columns with data_type changes:
   - id (integer -> text)

  Consider making an additive (non-breaking) change instead, if possible.
  Otherwise, create a new model version: https://docs.getdbt.com/docs/collaborate/govern/model-versions
```

Instead, it succeeds:
```
$ dbt -q ls -s state:modified --state state/
my_dbt_project.my_model.v1
```

This should raise a "Breaking Change" error that can be resolved by bumping the model version.

### Potential resolutions

The problem is that a versioned model doesn't have its contract checksum appropriately generated, so this check succeeds (both are `None`):
https://github.com/dbt-labs/dbt-core/blob/7fbfd53c3e68d05577c4d73eb562e0c96ac83778/core/dbt/contracts/graph/nodes.py#L652-L656

Two potential fixes:
1. Within `same_contract`, `if not contract.checksum`, generate it: https://github.com/dbt-labs/dbt-core/commit/879957a65e1d5be865be22bb0240ea02c0d1cd2e
2. During parsing, call `build_contract_checksum()` for versioned models specifically, after configs are resolved: https://github.com/dbt-labs/dbt-core/commit/434d491b0d731289c5e4b41907d9b119ebef5cd5
