### ISSUE TITLE
[CT-2791] [Bug] dbt-core where documentation on custom macros incorrect or misleading?

### ISSUE THREAD

**Issue by WillAyd** [dbt-labs/dbt-core#8033]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Following along the documentation for custom macros in where clauses:

https://docs.getdbt.com/reference/resource-configs/where#custom-logic

The provided code only works for tests that use the `where` key. However, if you change the documentation example to something like:

```yml
version: 2
models:
  - name: my_model
    columns:
      - name: id
        tests:
          - not_null
          - unique:
              config:
                where: "date_column > __last_three_days__"  # placeholder string for static config
```

(note the not_null test without any where clause) you get a compilation error such as `argument type of 'NoneType' is not iterable`

This can be worked around if you change the provided macro to use a clause like `{% if where and "__three_days_ago__" in where %}`, though I'm not clear that is the idiomatic approach. It seems like the line prior of `{% set where = config.get('where', '') %}` should already be handling that yet it doesn't seem to be the case

### Expected Behavior

Compilation of a test should work whether or not a `where` object is attached to the test

### Steps To Reproduce

See setup in `current behavior` then simply `dbt test`

### Environment

```markdown
- OS:ubuntu 22.04
- Python:3.10.2
- dbt:dbt-core 1.3.0
```

### Which database adapter are you using with dbt?

redshift

**Comment by dbeatty10** [comment]
Thank you for reporting this @WillAyd !

It looks like we need to update the examples in the documentation here. It looks like there are two different things going on:
- one place has `__last_three_days__ ` when it should be `__three_days_ago__` everywhere
- example throws an error when `where` is `None` (which should be allowed)

Something more like this should work instead -- could you give it a shot and see if it works?

`macros/my_macros.sql`
```sql
{% macro get_where_subquery(relation) -%}
    {% set where = config.get('where', '') %}
    {% if where %}
        {% if "__three_days_ago__" in where %}
            {# replace placeholder string with result of custom macro #}
            {% set three_days_ago = dbt.dateadd('day', -3, current_timestamp()) %}
            {% set where = where | replace("__three_days_ago__", three_days_ago) %}
        {% endif %}
        {%- set filtered -%}
            (select * from {{ relation }} where {{ where }}) dbt_subquery
        {%- endset -%}
        {% do return(filtered) %}
    {%- else -%}
        {% do return(relation) %}
    {%- endif -%}
{%- endmacro %}
```

`models/_models.yml`
```yaml
version: 2

models:
  - name: my_model
    columns:
      - name: id
        tests:
          - not_null
          - unique:
              config:
                where: "date_column > __three_days_ago__"  # placeholder string for static config
```
