### ISSUE TITLE
[Feature] Coerce data types in dbt Model Contracts

### ISSUE THREAD

**Issue by sungchun12** [dbt-labs/dbt-core#8035]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Problem: I want to coerce data types when defining model contracts to avoid writing out cast statements tediously.

However, I don't have an elegant mechanism to do that without writing cast statements. 

Proposed Solution: Add a config to enable/disable strict mode (current behavior) similar to this example: https://docs.pydantic.dev/latest/blog/pydantic-v2/#strict-mode

```yaml
version: 2

models:
  - name: demo
    description: demo
    config:
      contract:
        enforced: true
        strict: false # additional config

    columns:
      - name: id
        description: This is a unique identifier for a customer
        data_type: text
        constraints:
          - type: unique
          - type: not_null
```

```sql
--original SQL
select 2 as id
union all
select 1 as id
```

```sql
--compiled SQL
  create  table "neondb"."dbt_sung_dev"."demo__dbt_tmp"
  
  
    
    
  (
    id text unique not null
    
    )
 ;
    insert into "neondb"."dbt_sung_dev"."demo__dbt_tmp" (
      id
    )
  
  (
    
    select id
    from (
        select cast(2 as varchar) as id
union all
select cast(1 as varchar) as id
    ) as model_subq
  );
  
 ```

### Describe alternatives you've considered

Writing cast statements explicitly in my SQL. 

### Who will this benefit?

Model Contract users who want to be lazy like me when defining data types. 

### Are you interested in contributing this feature?

Not for now! That may change when I start my new job.
