### ISSUE TITLE
[CT-2807] [Feature] Support YAML anchor reuse

### ISSUE THREAD

**Issue by joebeeson** [dbt-labs/dbt-core#8059]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We use a lot of YAML anchors for repeated columns (_foreign keys are the big one_), repeated configurations (partitions, tests) which exist across multiple model areas (_staging, marts, intermediate_) meaning we have to duplicate these anchors to the top of each area's file, e.g.: models/marts/_models.yml, models/staging/_models.yml, etc:

```yaml
x-columns-account_id: &x-columns-account_id
  name: account_id
  data_type: INT64
  description: "{{ doc('account_id') }}"
  meta:
    feature_type: nominal
```

It would be useful if there was a place for these repetitive YAML anchors to be defined that would be appended to all other reads so we could DRY.

### Who will this benefit?

Users looking to DRY and more easily manage their configurations.

### Are you interested in contributing this feature?

Yes
