### ISSUE TITLE
[Feature] Support hiding all resources from a package (not just models)

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#8061]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

This is an extension of https://github.com/dbt-labs/dbt-core/issues/1671

Currently, we can hide docs of models in packages by doing:

```yaml
# dbt_project.yml
name: my_dbt_project

models:
  local_package:
    +docs:
      show: false
  my_dbt_project:
....
```

However, this causes package macros to still show up in the docs site. Since `macros` is not a top level key in the `dbt_project.yml` file (https://docs.getdbt.com/reference/dbt_project.yml), you can't hide docs of a packages macros easily. And of course, most dbt packages include macros :)

We can try this out quite simply:

```yaml
# dbt_project.yml
name: my_dbt_project
profile: snowflake
config-version: 2
version: 1.0

models:
  my_dbt_project:
    +materialized: table

# packages.yml
packages:
  - local: ../some_package
  - package: brooklyn-data/dbt_artifacts
    version: 2.3.0
```

```yaml
# ../some_package/dbt_project.yml
name: "some_package"
version: "0.1.0"
config-version: 2
```

```sql
-- ../some_package/models/bar.sql
select 1 id
```

![image](https://github.com/dbt-labs/dbt-core/assets/8496748/4b42f43f-8760-452b-9d3b-18e47d3c892b)

Now let's hide those docs!

```yaml
# dbt_project.yml
name: my_dbt_project
profile: snowflake
config-version: 2
version: 1.0

models:
  some_package:
    +docs:
      show: false
  dbt_artifacts:
    +docs:
      show: false
  my_dbt_project:
    +materialized: table
```

![image](https://github.com/dbt-labs/dbt-core/assets/8496748/0f8e7142-ed65-423c-92cf-6e925d23f9e3)

^ There is no longer a folder for `some_package` since it only contains models but still one for `dbt_artifacts` - cause of the macros.

### Describe alternatives you've considered

Not too sure how one go about hiding entire package macros from docs today.

### Who will this benefit?

Anyone who wants to remove some clutter from their dbt docs site.

**Comment by dbeatty10** [comment]
Thanks for such a nice write-up @jeremyyeo 🤩

It seems reasonable to enable configs for macros within `dbt_project.yml` as you described:

```yaml
# dbt_project.yml

...

macros:
  dbt_artifacts:
    +docs:
      show: false
```

This could include the [`docs` config](https://docs.getdbt.com/reference/resource-configs/docs) shown in the screenshot below as well as any other current or future configs for macros (like [`meta`](https://docs.getdbt.com/reference/resource-configs/meta)).

<img width="650" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/23b03e49-cc86-42b5-b573-83bee56b0a5f">

---

@jtcohen6 Is there any reason why we wouldn't want to add `macros` as a top level key in `dbt_project.yml`?
