### ISSUE TITLE
Support `ref` in foreign key constraint expressions

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#8062]
_originally left as comment in https://github.com/dbt-labs/dbt-core/issues/7417_

I'm opening this issue to track upvotes/comments that could inform eventual prioritization. Is this something people want/need in their production workflows? Are happy to solve by other means in the meantime (e.g. [`dbt_constraints`](https://github.com/Snowflake-Labs/dbt_constraints))?

---

If we were to take FK constraints more seriously, we're missing a pretty important ingredient, which is the ability to include & template ref inside the expression field — or providing more structure, i.e.
```
constraints:
  - type: foreign_key
    ref_table_name: ref('other_table_name')
    ref_column_names: ['id'] # could be multiple
```

Per https://github.com/dbt-labs/dbt-core/issues/6754#issuecomment-1449200569, we kicked that out of scope for v1.5, and we're unlikely to prioritize it while this remains a metadata-only (nonfunctional & unenforceable) feature on the majority of data platforms.
