### ISSUE TITLE
[CT-2822] [Bug] `Measure`s on `SemanticModel`s break on `NonAdditiveDimension` specification

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#8088]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

On `Measure`s, one should be able to specify `NonAdditiveDimension` properties like so
```yaml
semantic_models:
  ...
  measures:
    ...
    - name: total_account_balance_first_day
      agg: sum
      expr: order_cost
      non_additive_dimension:
        name: ds
        window_choice: min
        window_groupings:
          - user
```

However when you do so, an error gets raised
```
at path ['measures'][7]['non_additive_dimension']: {'name': 'ds', 'window_choice': 'min', 'window_groupings': ['user']} is not valid under any of the given schemas
```

### Expected Behavior

An error should not be raised, the example YAML specification should not cause an error

### Steps To Reproduce

1. Define a `Measure` in your YAML with `NonAdditiveDimension` information
```yaml
semantic_models:
  name: test_semantic_model
  model: ref('any_model_you_have')
  dimensions:
    - name: test_dimension
       type: categorical
       expr: true
  entities:
    - name: user
       type: primary
       expr: 1
  measures:
    - name: test_measure_with_not_additive_dimension
      agg: sum
      expr: 1
      non_additive_dimension:
        name: ds
        window_choice: min
        window_groupings:
          - user
```
2. Run `dbt parse`

### Relevant log output

```shell
at path ['measures'][7]['non_additive_dimension']: {'name': 'ds', 'window_choice': 'min', 'window_groupings': ['user']} is not valid under any of the given schemas
```

### Environment

```markdown
- OS: MacOS Ventura 13.4.1
- Python: 3.8.10
- dbt: HEAD
```

### Which database adapter are you using with dbt?

snowflake
