### ISSUE TITLE
[Bug] `.dbtignore` doesn't ignore files in dbt_packages

### ISSUE THREAD

**Issue by rlh1994** [dbt-labs/dbt-core#8169]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Adding reference to any files in the `dbt_packages` folder to the `.dbtignore` file does not lead to these being ignored. This may be needed as you wish to ignore certain files from the package (e.g. a sources or other yaml file that clashes, or docs. Models/seeds could be disabled via the project yaml).

### Expected Behavior

These files would be ignored on a compile or a run.

### Steps To Reproduce

1. Initialise a new project
2. Install a package that contains some models or seeds, e.g. :
    ```
    packages:
      - package: snowplow/snowplow_web
        version: [">=0.15.0"]
    ```
3. Create and ddd the whole package file to the `.dbtignore` file:
    ```
    dbt_packages/snowplow_web/*
    ```
4. Run `dbt run` and notice that all models from the package is still included in the run.

### Environment

```markdown
- OS: Mac OS
- Python: 3.9.13
- dbt:
Core:
  - installed: 1.5.1
  - latest:    1.5.3 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - databricks: 1.5.4 - Update available!
  - bigquery:   1.5.1 - Update available!
  - snowflake:  1.5.1 - Update available!
  - redshift:   1.5.4 - Update available!
  - postgres:   1.5.1 - Update available!
  - spark:      1.5.0 - Up to date!
```

### Additional Context

This PR introduced the feature, but I am not sure where in here these would be being not included in the ignore...
https://github.com/dbt-labs/dbt-core/pull/5897/

**Comment by dbeatty10** [comment]
Thanks for reporting this @rlh1994 !

Putting some debugging breakpoints around [here](https://github.com/dbt-labs/dbt-core/blob/ff5cb7ba51b4133f836d8d45ee8bb52f01ff4b4e/core/dbt/parser/read_files.py#L166-L173), it looks to me like each package can include its _own_ `.dbtignore` file, but it's not currently possible to refer to installed packages within the root `.dbtignore` file.

I'm assuming that you already tried [disabling via `dbt_projects.yml`](https://docs.getdbt.com/reference/resource-configs/enabled) like the following, but it wasn't applicable (or didn't work)?

`dbt_projects.yml`
```yaml
...

models:
  snowplow_web:
    +enabled: false

seeds:
  snowplow_web:
    +enabled: false

snapshots:
  snowplow_web:
    +enabled: false

tests:
  snowplow_web:
    +enabled: false

sources:
  snowplow_web:
    +enabled: false

metrics:
  snowplow_web:
    +enabled: false

exposures:
  snowplow_web:
    +enabled: false
```

Could you share an example of a sources or other yaml file that clashes (and the net affect it has on you)?

**Comment by rlh1994** [comment]
@dbeatty10 yeah I was able to disable the seeds (in my case) themselves in the package via the `dbt_project.yml`, which works exactly as expected.

However the "issue" comes when I then build a model in the root project with the same name as the seed from the package (basically I need to overwrite a seed with a model but use the same name so it gets used in `ref`s), it leads to a warning on compile that the model is under the seeds heading in the yaml file. It still compiles and runs, but it would be nice to be able to avoid the warnings by somehow disabling the associated yaml for the seeds, and the `.dbtignore` was the only way I thought I might be able to.

I'll throw together a more thorough reprex over the weekend if needed.

**Comment by rlh1994** [comment]
Reprex of the warning issue:

```yml
# dbt_project.yml
...

models:
  snowplow_web:
    +enabled: false

seeds:
  snowplow_web:
    +enabled: false

snapshots:
  snowplow_web:
    +enabled: false

tests:
  snowplow_web:
    +enabled: false

sources:
  snowplow_web:
    +enabled: false

metrics:
  snowplow_web:
    +enabled: false
```

```yml
# packages.yml
packages:
  - package: snowplow/snowplow_web
    version: 0.15.0
```

```jinja2
{# models/dim_ga4_source_categories.sql #}
select 1 as a
```

(not relevant as we have confirmed it does not work, but ideally this would ignore these files thus removing the issue)
```
# .dbtignore
dbt_packages/
```

Commands:
```term
dbt clean
dbt deps
dbt compile
```

Output:
```log
09:09:05  Running with dbt=1.5.1
09:09:05  Unable to do partial parsing because saved manifest not found. Starting full parse.
09:09:07  [WARNING]: 'dim_ga4_source_categories' is a model node, but it is specified in the seeds
section of seeds/seeds.yml. To fix this error, place the
`dim_ga4_source_categories` specification under the models key instead.
09:09:07  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 611 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
09:09:07  
09:09:08  Concurrency: 1 threads (target='postgres')
09:09:08  
```
