### ISSUE TITLE
[CT-2863] [Bug] Incorrect curly braces handling in `password` field in `profiles.yml`

### ISSUE THREAD

**Issue by Trymzet** [dbt-labs/dbt-core#8192]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`dbt debug` fails when the password contains curly braces inside, eg. `my{curly}pw123`. I validated this by running with the same password but one of the braces removed.

### Expected Behavior

I would expect special characters to be escaped within dbt so it sends the correct password to my database.

### Steps To Reproduce

Tested on `sqlserver` extension.

### Relevant log output

```shell
Database Error
  ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'my_user'. (18456) (SQLDriverConnect)")
```

### Environment

```markdown
- OS: Ubuntu 22.04
- Python: 3.10.6
- dbt:
Core:
  - installed: 1.3.2
Plugins:
  - sqlserver: 1.3.1
(1.3.2 are incompatible with each other (sic!) so I had to downgrade dbt-sqlserver)
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

adatper used: `sqlserver`

**Comment by dbeatty10** [comment]
The following worked for me using dbt-postgres, so I'm thinking this might be dbt-sqlserver (or just SQL Server?) instead of of dbt-core.

<details>
<summary>

### Reprex</summary>


```shell
git clone https://github.com/dbt-labs/dbt-core.git
cd dbt-core
```

Update the password here to include your password with opening and closing curly braces (`my{curly}pw123`):
```shell
code docker-compose.yml 
```

Launch the Docker container:
```sh
docker-compose up -d database
PGHOST=localhost PGUSER=root PGPASSWORD='my{curly}pw123' PGDATABASE=postgres bash test/setup_db.sh
```

Add it to your `profiles.yml`:
```yaml

sandcastle:
  target: postgres
  outputs:
    postgres:
      type: postgres
      dbname: 'postgres'
      host: 'localhost'
      port: 5432
      schema: dbt_dbeatty
      threads: 5
      user: 'root'
      password: 'my{curly}pw123'
```

</details>

@dataders what do you want to do for next steps?
