### ISSUE TITLE
[CT-2878] [Bug] Adding `meta` tag to metrics throws an error.

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/dbt-core#8227]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Adding the `meta` tag to a metric causes the following error: 
![Screenshot 2023-07-27 at 10 26 42 AM](https://github.com/dbt-labs/dbt-core/assets/26796796/90c88482-8481-42e2-a184-e677a81e1328)

### Expected Behavior

I should be able to add a meta tag to a metric. The meta tag is part of the metric node, so it should be expected.  However, we're using the pydantic node definition for metrics from DSI which does not have the meta tag, and doesn't allow extra properties. 

### Steps To Reproduce

1. In an env running dbt 1.6 create a metric with a meta tag i.e
```yaml
metrics:
  - name: orders
    description: Count of orders.
    label: Orders
    type: simple
    type_params:
      measure: order_count
    meta:
      metric_level: 'Company'
      owner(s): 'Jane Doe't
```
2. Run dbt parse

### Environment

```markdown
- OS:
- Python:
- dbt:
```
