### ISSUE TITLE
[Bug] Versioned models are appear with the same name in docs

### ISSUE THREAD

**Issue by Jaxing** [dbt-labs/dbt-core#8242]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When creating versions of a model I have one model called abc_v1 and one model called abc_v2 however when generating the docs they both appear as abc in the model overview (see first image below).
If you look in the side menu the model version is included (see second image).
In my production environment I have also managed to make the version disappear from the side menu (see third image), but I can't reproduce that so it might be something specific to our prod environment.

### Expected Behavior

I would expect the name to be abc_v1 or abc.v1 instead of abc. Preferable I would like to have one view for the both of them and be able to select version from a dropdown, but as a starting point I think that just printing the full name of the model would be good. 

It feels like it might be because the node name for the models in the manifest is ...<model_name>.v<version> and maybe it's hard coded somewhere that the name in the docs should be split(node, '.')[2] or something like that?

### Steps To Reproduce

Running dbt-core 1.5.2 dbt-bigquery 1.5.1.

create two models:
abc_v1
abc_v2

generate and serve docs

example files:

abc_v1.sql
```sql
{{
    config(
        materialized='view'
    )
}}
select 1 as a, 2 as b, 3 as c
```

abc_v2.sql
```sql
{{
    config(
        materialized='view'
    )
}}
select * from {{ ref('abc', v='1') }}
```

abc.yaml
```yaml
version: 2

models:
  - name: abc
    latest_version: 1
    config:
      contract: {enforced: true}
    columns:
      - name: a
        data_type: integer
      - name: b
        data_type: integer
      - name: c
        data_type: integer
    versions:
      - v: 1
      - v: 2
```

### Environment

```markdown
- OS: ubuntu 22.04
- Python: 3.8
- dbt-core: 1.5.2
- dbt-bigquery: 1.5.1
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

![image1](https://github.com/dbt-labs/dbt-core/assets/8545525/73862a81-d359-43f9-911f-786e6c06d407)
![image2](https://github.com/dbt-labs/dbt-core/assets/8545525/58c33a68-1637-4146-8554-fba81c5cbb1a)
![image3](https://github.com/dbt-labs/dbt-core/assets/8545525/3e106faf-ff5b-49a4-a817-1248f5c982d0)
