### ISSUE TITLE
Add ability to specify the format for fixtures and use csv files for inputs/expected in addition to yaml

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#8290]

**Comment by MichelleArk** [comment]
This capability should probably also be available for `expect` fixtures in addition to `given` input fixtures. We'll need to generalize the type of `expect` to support this (and unify it with the parsing of `InuptFixture`s, as it is [currently simply a List[Dict[str, Any]]](https://github.com/dbt-labs/dbt-core/pull/8411/files#diff-42f07118add483c2e34f2e1b77388819659667339ab74066353882b4adfed07eR755)

Here's a first stab at what this spec could look like:
```
unit:
  - model: my_model
    tests:
      - name: test_my_model
        given:
          - input: ref('my_model_a')
            format: csv_file # optional
            rows: path/to/model_a_fixture.csv
          - input: ref('my_model_b')
            rows: #default 
              - {id: 1, b: 2}
              - {id: 2, b: 2}
        expect:
          format: csv #format can also be applied to expected
          rows: """
          c
          3
          """
```

But its worth considering whether the `format` config would be applied at the fixture (input or expected) level, as above -- 
or at the test (suite?) level, for example:

```
unit:
  - model: my_model
     config:
       format: csv_file #applies to all fixtures in tests for my_model
    tests:
      - name: test_my_model
        config:
          format: csv_file #applies to all fixtures in test_my_model
        given:
          - input: ref('my_model_a')
            rows: path/to/fixture.csv
          - input: ref('my_model_b')
            rows: path/to/fixture_b.csv
        expect:
          rows: path/to/expected_model.csv
```

either way, should a single test case be able to use multiple different input formats? for example, `input: ref('my_model_a')` uses `format: dicts` and `input: ref('my_model_b')` uses `csv_file`? i think that variability within a test case could reduce readability but there may be valid use cases to support it.

**Comment by graciegoheen** [comment]
A few thoughts here, in somewhat of a random order:

The default for `format` is an "inline list of dictionaries" - what is the appropriate explicit name for this? I see @MichelleArk mentioned `format: dicts` as an option - I feel good about this, unless anyone has strong opinions otherwise.

I'm curious about the implications for using something other than `rows` for formats other than `dicts` - what if `format: dicts` used `rows`, and `format: csv_file` used `path`?

How do you feel about specifying the path to the csv file (ex: `path: path/to/model_a_fixture.csv`) vs. just specifying the name of the fixture file (ex: `filename: model_a_fixture.csv`) or even something akin to a docs block (ex: `rows: {{ fixture('model_a_fixture')`). Do we imagine a future format where we allow people to specify multiple fixtures in a single csv file?

I think there could be some confusion with specifying the file path - is it the relative path? the path from the root directory? 

Should we havea unit-paths config in the `dbt_project.yml` similar to [test-paths](https://docs.getdbt.com/reference/project-configs/test-paths) - by default maybe this is a new subfolder `unit/`, but folks could override it if they wanted to specify a different location for fixtures like `tests/unit` or `fixtures/`. 

I think we should definitely support `format: csv_file` - `format: csv` for inline csvs seems less important to me, though curious other folks' opinions on this.

> But its worth considering whether the format config would be applied at the fixture (input or expected) level, as above --
or at the test (suite?) level

In the same vein, is the `format` config something people would want to override at the `dbt_project.yml` file level?

```yml
#dbt_project.yml
unit:
    format: csv_file
```

I do think we should support variability of `format`s within a single unit test.

**Comment by graciegoheen** [comment]
```
    format: csv
    fixture: my_model_fixture
```

```
    format: csv
    rows: """
          c
          3
          """
```

**Comment by MichelleArk** [comment]
Split out the `format: csv` piece in https://github.com/dbt-labs/dbt-core/issues/8626. Let's continue refining the `fixture` spec here.

**Comment by graciegoheen** [comment]
From refinement:

If I have a csv file - `tests/fixtures/my_model_a_fixture.csv` - this is the definition of my fixture named `my_model_a_fixture` (similar to how if I have a sql file `models/my_model_a.sql` that is the definition of my model named `my_model_a`), and I can reference that fixture in my yml with the file name:

```
unit-tests:
  - name: test_my_model
    model: my_model
    given:
      - input: ref('my_model_a')
        format: csv
        fixture: my_model_a_fixture
...
```

This feels similar to how [defined_in](https://docs.getdbt.com/reference/resource-properties/versions#defined_in) for model versions work:
![Screenshot 2023-09-14 at 3 31 15 PM](https://github.com/dbt-labs/dbt-core/assets/53586774/5907e5db-ccfd-4fd2-947e-c79946554d8d)
