### ISSUE TITLE
[CT-2933] [Bug] The leading plus is required when using `+grants` in `dbt_project.yml`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#8315]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm not _certain_ if this is a bug or not, but reporting it due to insightful feedback from @b-per [here](https://github.com/dbt-labs/docs.getdbt.com/pull/3814#issuecomment-1655223799):

> My expectation is that `+` is optional in `dbt_project.yml` and only required if there is a folder called `<config_object>`. 
> 
> The following error message mentions that dbt is looking for `grants` as a folder but this folder doesn't exist. If the `grants` folder doesn't exist I would expect dbt to consider `grants` as the config point even though there is no `+`.
> ```
> Compilation Error
>   [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
>   There are 1 unused configuration paths:
>   - models.PROJECT_NAME.FOLDER_A.SUB_FOLDER_B.grants
> ```

### Expected Behavior

The expected behavior is described above, but this documentation may be helpful (or may need slight tweaking):
https://docs.getdbt.com/reference/resource-configs/plus-prefix

### `+grants`
> Note: This use of the `+` prefix, in `dbt_project.yml`, is distinct from the use of `+` to control config merge behavior (clobber vs. add) in other config settings (specific resource `.yml` and `.sql` files). Currently, the only config which supports `+` for controlling config merge behavior is [grants](https://docs.getdbt.com/reference/resource-configs/grants#grant-config-inheritance).

### Caveats: dictionary inputs or collisions with a path

> the leading `+` is in fact _only required_ when you need to disambiguate between resource paths and configs, for example when:
> 
> - A config accepts a dictionary as its inputs, for example, the [persist_docs config](https://docs.getdbt.com/reference/resource-configs/persist_docs).
> - Or, a config shares a key with part of a resource path, for example, if you had a directory of models named `tags`.

### ❌ Does not work for `grants`

Using the Docker image for Postgres described in `CONTRIBUTING.md`, either of the following does not actually apply grants and emits this warning message instead:
```
[WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
```

`dbt_project.yml`
```yaml
models:
  grants:
      select: ['dbt_test_user_1', 'dbt_test_user_2']
```

`dbt_project.yml`
```yaml
name: "my_project"

models:
  my_project:
    grants:
      select: ['dbt_test_user_1', 'dbt_test_user_2']
```

### ✅  Does work for `grants`

Either of the following with the plus sign included (`+grants`) does work though.

`dbt_project.yml`
```yaml
models:
  +grants:
      select: ['dbt_test_user_1', 'dbt_test_user_2']
```

`dbt_project.yml`
```yaml
name: "my_project"

models:
  my_project:
    +grants:
      select: ['dbt_test_user_1', 'dbt_test_user_2']
```

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Additional Context

This came up within https://github.com/dbt-labs/docs.getdbt.com/pull/3814
