### ISSUE TITLE
[CT-2998] [SPIKE] Handle unit testing of JSON and ARRAY data types

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#8423]
### Description

We should enable adding unit test mock inputs and outputs that contain fields of type JSON or type ARRAY.

Example using in-line yaml `dict` format:
```
unit-tests:
  - name: test_json_unpack # this is the unique name of the test
    model: my_model # name of the model I'm unit testing
    given: # optional: list of inputs to provide as fixtures
      - input: ref('employees')
        rows:
         - {id: 1, empl_info: {"employee":{"name":"John", "age":30, "city":"New York"}}}
         - {id: 2, empl_info: {"employee":{"name":"Doug", "age":97, "city":"Flagstaff"}}}
      - input: ref('office_locations')
        rows:
         - {id: 1, offices: [1,3]}
         - {id: 2: offices: [2,4]}
    expect: # required: the expected output given the inputs above
      rows:
      - {employee_id: 1, name: John, age: 30, city: New York, offices: [1,3]}
      - {employee_id: 2, name: Doug, age: 97, city: Flagstaff, offices: [2,4]}
    ...
```

Example using `csv` format:
```
unit-tests:
  - name: test_json_unpack # this is the unique name of the test
    model: my_model # name of the model I'm unit testing
    given: # optional: list of inputs to provide as fixtures
      - input: ref('employees')
        format: csv
        rows:  |
        id, empl_info
        1,{"employee":{"name":"John", "age":30, "city":"New York"}}
        2,{"employee":{"name":"Doug", "age":97, "city":"Flagstaff"}}
      - input: ref('office_locations')
        format: csv 
        rows: |
        id,offices
        1,[1,3]
        2,[2,4]
    expect: # required: the expected output given the inputs above
      format: csv
      rows: |
      employee_id,name,age,city,offices
      1,John,30,New York,[1,3]
      2,Doug,97,Flagstaff,[2,4]
    ...
```

Note: we can assume we already know the data types and columns of the inputs.

### Acceptance criteria

FOR SPIKE:

- Understand the technical complexities, edge cases, and how we would go about testing this
- Draft implementation 

FOR IMPLEMENTATION:

- You can specify inputs or expected outputs for unit tests with columns of JSON data type (in at least one of the available `format`s, ideally all)
- You can specify inputs or expected outputs for unit tests with columns of ARRAY data type (in at least one of the available `format`s, ideally all)
- The error message for when a unit test fails should still be readable when using JSON data types.
- The error message for when a unit test fails should still be readable when using ARRAY data types.
- Bonus if it works for STRUCT to (lol, if not it's chill we'll open another issue) 

### Impact to other teams

Impact adapter teams

### Will backports be required?

No

### Context
