### ISSUE TITLE
[CT-3024] [Bug] should_store_failures() is undefined (when compiling custom macros/tests) before first successful compile

### ISSUE THREAD

**Issue by adamcunnington-mlg** [dbt-labs/dbt-core#8483]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have a custom test that references `should_store_failures()`. Before my first ever successful compilation, running `dbt test` (which causes this macro to get invoked) fails to successfully compile because `should_store_failures() is undefined`. If I comment it out (or do something like `{% if execute and should_store_failures() %}` to skip during compilation time, then the first compile succeeds and I can then restore the code and it works fine.

If i do `dbt run` or `dbt build` first, it's all fine because this macro is compiled in time. I guess it must be down to the order of when dbt's builtin macros are defined. It looks like I can get dbt to compile my custom macros first which leads to the issue (albeit not common because you wouldn't normally run dbt test first on a brand new project).

This non-determinism is confusing though? 

### Expected Behavior

Deterministic behaviour with this macro guaranteed always defined in time.

### Steps To Reproduce

As above.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thanks for reaching out @adamcunnington-mlg !

I wasn't able to reproduce this on my first pass. Could you provide a little more detail about your set up that triggered the error? See below for a set of simple files you could modify as-needed.

The following worked for me:

`dbt_project.yml`
```yaml
name: "my_project"
profile: "sandcastle"

clean-targets:
  - target
  - dbt_packages
  - logs

tests:
  +store_failures: true  # all tests
```

`models/my_model.sql`
```sql
select 1 as id
```



`tests/generic/my_unique.sql`
```sql
{% test my_unique(model, column_name) %}

{% set store_failures = should_store_failures() %}
{{ log("store_failures: " ~ store_failures, True) }}

-- custom generic test
with validation_errors as (

    select {{ column_name }}
    from {{ model }}
    group by {{ column_name }}
    having count(*) > 1

)

select *
from validation_errors

{% endtest %}
```

`tests/my_test.sql`
```sql
{% set store_failures = should_store_failures() %}
{{ log("store_failures: " ~ store_failures, True) }}

select 1 as id
where 1=0
```

`models/_models.yml`
```yaml

models:
  - name: my_model
    columns:
      - name: id
        tests:

          # built-in test
          - unique

          # custom generic test
          - my_unique
```

Running these commands will clean out any pre-compiled artifacts and run the tests with a clean slate:
```shell
dbt clean
dbt test
```
