### ISSUE TITLE
[CT-3028] default database name coming while running dbt test (dbt-databricks)

### ISSUE THREAD

**Issue by abhishek-7781** [dbt-labs/dbt-core#8490]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running **dbt test** (either from local Python environment or Databricks) to run tests on tables in ADLS/ Databricks, the SQL command generated has table name in this format **".schema_name.table_name"** instead of **"schema_name.table_name"** causing the following error:
**[PARSE_SYNTAX_ERROR] Syntax error at or near '.': extra input '.'**

The same issue came with **dbt run** but got resolved by overriding the **ref** macro as below:
```
{% macro ref_dbx(model_name) %}
    {% do return(builtins.ref(model_name).include(database=false)) %}
{% endmacro %}
```
However, this didn't work for **dbt test** since the tests are run from the backend and there is no code for test.
Tried using the **generate_database_name** but it didn't work either.

### Expected Behavior

Running the **dbt test** command to run default tests (e.g. not null, unique) on tables in ADLS/ Databricks, the SQL command generated should not include the database_name (**"schema_name.table_name"**).

### Steps To Reproduce

1. Setup a dbt project for Databricks
2. profiles.yml
```
project_name:
    output:
        databricks_job:
              type: databricks
              method: http
              threads: 4
              schema: "{{ env_var('target_schema') }}"
              host: "{{ env_var('hostname') }}"
              http_path: "{{ env_var('http_path') }}"
              token: "{{ env_var('token') }}"
```
3. schema.yml
```
models:
  - name: "model_name"
    description: ""
    config:
      enabled: true
      materialized: table
      alias: <alias_name>
      index: CLUSTERED COLUMNSTORE INDEX
      dist: HASH (<column_name>)
      file_format: delta
    columns:
      - name: <column_name>
        #description: 
        tests:
          - not_null
          - unique
```
4. Run command - **dbt test --select model_name**

### Relevant log output
![image](https://github.com/dbt-labs/dbt-core/assets/141800574/cf667f64-51e9-421e-89c3-a993e1591874)

### Environment

```markdown
- OS:Windows
- Python:3.10.9
- dbt-core:1.3.4
- dbt-databricks:1.3.2
- databricks-sql-connector:2.1.0/2.7.0
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

dbt adapter being used is dbt-databricks

**Comment by dbeatty10** [comment]
Thanks for reaching out about this @abhishek-7781 !

I haven't looked at this in great detail yet. My initial thought is that this looks like an issue in [dbt-databricks](https://github.com/databricks/dbt-databricks) rather than within dbt-core.

Is there a particular reason you thought this issue should be solved within the dbt-core repo rather than the [dbt-databricks](https://github.com/databricks/dbt-databricks) repo?

**Comment by abhishek-7781** [comment]
Thank you for your comment @dbeatty10.
This can be looked at in 2 ways:

1. It's a bug in dbt-databricks where it shouldn't add the default database name and instead expects just the schema and identifier/table.
2. There should be a functionality/feature in dbt-core to remove database name from the SQL commands run for **tests** similar to how it can be done in the **models** by overriding the ref macro.

**Comment by abhishek-7781** [comment]
Closed by mistake.

**Comment by abhishek-7781** [comment]
Closed by mistake.

**Comment by abhishek-7781** [comment]
@dbeatty10 I looked everywhere possible but didn't find any working solution or workaround for this.
However, I found a way to make this work but I'm sure it can be modified to be more efficient, effective and robust.

I created the following macro **remove_database_name.sql**
```
{% macro remove_database_name(model) %}

  {% set model = model[1:] if model[0] == "." else model %}
  {% set model = model.split('.')[-2] + "." + model.split('.')[-1] if '.' in model else model %}
  {# -- % set model = model.split('.')[1] + "." + model.split('.')[2] if model.count('.') == 2 else model % #}
  
  {% do return(model) %}
{% endmacro %}
```
Now, for any custom test, this macro can be called passing the model_name.
And, for the four generic tests (**not_null**, **unique**, **accepted_values** and **relationships**), these tests can be overridden by creating a macro of the same name and adding an additional line calling the **remove_database_name** macro.
Sample for **not_null** test:
```
{% macro default__test_not_null(model, column_name) %}

  {% set model = remove_database_name(model) %}
  {% set column_list = '*' if should_store_failures() else column_name %}

  select {{ column_list }}
  from {{ model }}
  where {{ column_name }} is null

{% endmacro %}
```

I would appreciate if there's :
1. any better way to write this macro, or
2. any other more effective working solution/workaround to handle this

**Comment by dbeatty10** [comment]
I'd hope that overriding the [four generic tests](https://docs.getdbt.com/reference/resource-properties/tests#out-of-the-box-tests) that are available out-of-the-box **wouldn't** be necessary 🙏. See below for an idea for an alternative workaround.

### Did you know you can override the `ref` macro?

> This can be looked at in 2 ways:
> 
> 1. It's a bug in dbt-databricks (or dbt-core) where it shouldn't add the default database name and instead expects just the schema and identifier/table.
> 2. There should be a provision (like creating or overriding a macro, maybe generate_database_name) to remove database name from the SQL commands run for **dbt test** for tests, similar to how it can be done in **dbt run** for models by overriding the ref macro.

It doesn't look like case 2 mainly because:
- As described [here](https://docs.getdbt.com/reference/dbt-jinja-functions/builtins#usage), you can already override the `ref` macro within your project to strip out the database name from the models / [Relations](https://docs.getdbt.com/reference/dbt-classes#using-relations) used within `dbt test`, `dbt run`, etc.

So this looks like case 1 to me: bug within dbt-databricks (specifically for Delta tables?)

### Thing to try

Could you try adding this macro (from [here](https://docs.getdbt.com/reference/dbt-jinja-functions/builtins#usage)) to your project and see how it works with `dbt test`, etc?

`macros/overrides/ref.sql`

```sql
{% macro ref(model_name) %}

  {% do return(builtins.ref(model_name).include(database=false)) %}

{% endmacro %}
```

### Other info

This probably isn't needed/desired in this case, but there _does_ exist a customizable [`generate_database_name`](https://docs.getdbt.com/docs/build/custom-databases#generate_database_name) for database name just like [`generate_schema_name`](https://docs.getdbt.com/docs/build/custom-schemas#how-does-dbt-generate-a-models-schema-name) for schemas and [`generate_alias_name`](https://docs.getdbt.com/docs/build/custom-aliases#generate_alias_name) for table/view/etc names.

**Comment by abhishek-7781** [comment]
@dbeatty10 Ahh! Ok, let me explain it in a simpler way.
So, overriding the **ref** macro works when you can use the overridden ref macro explicitly (e.g. while using the reference of a model in another model's definition). Meaning, overriding the ref macro would only work for running the models (dbt run).

**ref.sql**
```
{% macro ref(model_name) %}
  {% do return(builtins.ref(model_name).include(database=false)) %}
{% endmacro %}
```
**model_1.sql**
```
SELECT * FROM {{ ref('model_2') }}
```

Now, the problems starts when you run the tests on a model (especially the [four generic tests](https://docs.getdbt.com/reference/resource-properties/tests#out-of-the-box-tests)) and there is no way to use the ref override approach here since the model definition is not available and you can't use the overridden ref macro explicitly.

So, either
1. dbt shouldn't add that extra dot (**'.'**) without any database name, if not explicitly provided in target profile, or
2. dbt should have a provision (macro or some config) to not expect the database name at all, instead of overriding it

Current Behaviour:  `.schema_name.table_name`
Expected Behaviour: `schema_name.table_name`

Now, the problem with customizable [generate_database_name](https://docs.getdbt.com/docs/build/custom-databases#generate_database_name) is that it can be used to generate a custom database name but it won't be useful if you don't want dbt to expect the database name at all. Please let me know if my understanding here is not correct.

**Comment by dbeatty10** [comment]
@abhishek-7781 okay, everything you said above makes sense.

But the thing that is surprising to me is that you're running into this error in the first place.

I tried reproducing your bug report using dbt-core==1.3.4 and dbt-databricks==1.3.2, but it worked when I ran it. See below for the exact files and commands I used.

Could you give these a shot within a fresh dbt project and see if they work for you or not?

`profiles.yml`
```yaml
sandcastle-databricks:
  target: databricks
  outputs:
    databricks:
      type: databricks
      schema: "{{ env_var('DATABRICKS_USER_SCHEMA') }}"
      threads: 10
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
```

`models/schema.yml `
```yaml
version: 2

models:
  - name: "model_name"
    description: ""
    config:
      enabled: true
      materialized: table
      alias: my_alias
      index: CLUSTERED COLUMNSTORE INDEX
      dist: HASH (id)
      file_format: delta
    columns:
      - name: id
        tests:
          - not_null
          - unique
```


`models/model_name.sql`
```sql
select 1 as id
```

This works for me:
```shell
dbt run --select model_name
dbt test --select model_name
```

And so does this:
```shell
dbt build -s model_name
```
