### ISSUE TITLE
[CT-3070] [Bug] accepted_values test passes despite NULL values

### ISSUE THREAD

**Issue by LePeti** [dbt-labs/dbt-core#8543]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using the `accepted_values` test, the test does not return an error when `NULL` values are found. E.g. if my test only accepts `'foo'` and `'bar'` as values, the test will actually pass given `'foo'`, `'bar'` _and_ `NULL` values in the column.

You could argue that `NULL` is not a value (and there's also the `not_null` test) but in my opinion this behaviour is counterintuitive.

This is especially tricky when you use the `where` config in combination with the test. For example when you know your column could contain `NULL`s, but given specific conditions, they should be only `'foo'` and `'bar'`. Then, even if you make a mistake when specifying the `where` config, you will not notice b/c your test will pass.

### Expected Behavior

The `accepted_values` test would return an error when `NULL` values are found in a column

### Steps To Reproduce

_my_model.sql:_

```sql
select NULL as col1
```

_my_model.yml:_

```
version: 2

models:
  - name: my_model
    columns:
      - name: col1
        tests:
          - accepted_values:
              values: ['foo', 'bar']
```

In you terminal, run: `dbt build -s my_model`

### Environment

```markdown
- OS: `Debian GNU/Linux 12 (bookworm)`
- Python: `Python 3.10.12`
- dbt:


Core:
  - installed: 1.4.4
  - latest:    1.6.1 - Update available!

Plugins:
  - postgres: 1.4.4 - Update available!
  - bigquery: 1.4.3 - Update available!
  - redshift: 1.4.0 - Update available!
```
```


### Which database adapter are you using with dbt?

redshift

### Additional Context

_No response_

**Comment by LePeti** [comment]
> Hi!
> 
> The built in [accepted_values](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/generic_test_sql/accepted_values.sql) test uses [not in](https://docs.aws.amazon.com/redshift/latest/dg/r_in_condition.html) SQL syntax.
> 
> How about adding a `not_null` test

Yes, I think technically it should do it but still would think this is counterintuitive and not what people would expect from this test exactly. This is what happened to me and why I raised this (I promise it was a bit more complicated than the below example 😸 ):

_my_table.sql output:_

|col1|col2|
|---|---|
|A|foo|
|A|bar|
|B|NULL|
|B|NULL|

_my_table.yml_:

```
models:
  - name: my_model
    columns:
      - name: col1
        tests:
          - not_null:
              where: col1 = 'A'
          - accepted_values:
              values: ['foo', 'bar']
                where: col1 = 'C'   ---> I made a mistake here (should have been `col1 = 'A'`) that I didn't notice b/c the test passed
```
