### ISSUE TITLE
[Bug] <External connection exception occurred: HTTPSConnectionPool(host='hub.getdbt.com', port=443): Max retries exceeded with url: /api/v1/index.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))>

### ISSUE THREAD

**Issue by mstfkmlbsbdk2023** [dbt-labs/dbt-core#8554]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

```
packages:
  - git: "https://github.com/dbt-labs/dbt-utils.git"
    revision: 0.9.2

  - git: "https://github.com/dbt-labs/dbt-codegen.git"
    revision: 0.10.0
```

I have tried this yml file. The first one worked very well which is git: "https://github.com/dbt-labs/dbt-utils.git".  but when I tried the second one I got SSLError(SSLCertVerificationError.

### Expected Behavior

my expectation is able to install codegen dbt package.

### Steps To Reproduce

dbt deps

### Relevant log output

```shell
14:33:36  Encountered an error:
External connection exception occurred: HTTPSConnectionPool(host='hub.getdbt.com', port=443): Max retries exceeded with url: /api/v1/index.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1002)')))
(dbt_venv)
```

### Environment

```markdown
- OS: Windows 11 Enterprise
- Python: 3.11.4
- dbt: 1.6.1
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

I am using databrick as a database adapter

**Comment by dbeatty10** [comment]
Thanks for reaching out @mstfkmlbsbdk2023 !

Could you try the following within `packages.yml` and then re-run `dbt deps`?

```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.9.2
  - package: dbt-labs/codegen
    version: 0.10.0
```

**Comment by mstfkmlbsbdk2023** [comment]
hello,
Thanks a lot for your quick response. I have tried it but did not work again. I got the same error. Please find it below

` (test/dbt-test)
$ dbt deps
20:52:38  Running with dbt=1.6.1
20:52:44  Encountered an error:
External connection exception occurred: HTTPSConnectionPool(host='hub.getdbt.com', port=443): Max retries exceeded with url: /api/v1/index.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))`

**Comment by dbeatty10** [comment]
https://github.com/dbt-labs/dbt-core/issues/7153 has the same error that you reported. Another Windows user [reported](https://github.com/dbt-labs/dbt-core/issues/7153#issuecomment-1464881266) that the following worked for them. Could you give it a try and see if it works for you also?

```shell
python -m pip install python-certifi-win32
```

Then:
```shell
dbt deps
```

**Comment by andrea-montes-yello** [comment]
I'm getting the same issue when running sqlfluff in lint stage in a gitlab pipeline

`sqlfluff lint --dialect ansi --rules L013,CP02,JJ01`

**Comment by mstfkmlbsbdk2023** [comment]
> #7153 has the same error that you reported. Another Windows user [reported](https://github.com/dbt-labs/dbt-core/issues/7153#issuecomment-1464881266) that the following worked for them. Could you give it a try and see if it works for you also?
> 
> ```shell
> python -m pip install python-certifi-win32
> ```
> 
> Then:
> 
> ```shell
> dbt deps
> ```

It works on my computer. Thanks a lot @dbeatty10

**Comment by dbeatty10** [comment]
@ludbertier I've only seen this happen to a Mac user [one other time](https://github.com/dbt-labs/dbt-core/issues/7153#issuecomment-1641401256), and they were using a docker container on an M1 Mac with corporate VPN.

Do any of those apply to you as well, by any chance?

### Corporate VPN

[At least one](https://github.com/dbt-labs/dbt-core/issues/7427#issuecomment-1520194576) corporate VPN user was able to resolve this by setting the [`REQUESTS_CA_BUNDLE`](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification) environment variable.

**Comment by dbeatty10** [comment]
@ludbertier [here's](https://github.com/dbt-labs/dbt-core/issues/7772#issuecomment-1575616186) another macos that reported this same error. They reported resolving it like this:
```shell
python -m pip install certify 
/Applications/Python\ 3.11/Install\ Certificates.command
```

You'd want to replace `3.11` above with whichever minor version of Python you are running in your environment:
```shell
python --version
```

**Comment by dbeatty10** [comment]
> I'm getting the same issue when running sqlfluff in lint stage in a gitlab pipeline
> 
> `sqlfluff lint --dialect ansi --rules L013,CP02,JJ01`

@andrea-montes-yello could you share more context of your setup? i.e., could you share the following?

1. contents of your `packages.yml`
2. whether or not you can successfully run that command locally (or in an environment other than your gitlab pipeline)
3. whether or not you can run non-sqlfluff dbt commands like `dbt deps` within your gitlab pipeline

**Comment by andrea-montes-yello** [comment]
> > I'm getting the same issue when running sqlfluff in lint stage in a gitlab pipeline
> > `sqlfluff lint --dialect ansi --rules L013,CP02,JJ01`
> 
> @andrea-montes-yello could you share more context of your setup? i.e., could you share the following?
> 
> 1. contents of your `packages.yml`
> 2. whether or not you can successfully run that command locally (or in an environment other than your gitlab pipeline)
> 3. whether or not you can run non-sqlfluff dbt commands like `dbt deps` within your gitlab pipeline

@dbeatty10 
1. Content of packages.yml 
```
packages:
  - package: dbt-labs/audit_helper
    version: 0.9.0
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: calogica/dbt_expectations
    version: 0.8.5
  - package: calogica/dbt_date
    version: 0.7.2
  - package: dbt-labs/codegen
    version: 0.9.0
  - package: starburstdata/trino_utils
    version: 0.4.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.6.2
```
2. Yes, I can run sqlfluff locally from my CLI and as part of a commit hook locally
3. dbt deps  and dbt parse are working in the pipeline
