### ISSUE TITLE
[CT-3100] [Bug?] What does accepted_values count?

### ISSUE THREAD

**Issue by RoyalTS** [dbt-labs/dbt-core#8607]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm not sure if this is a bug or expected behavior. At the very least it's probably documentation that could be clearer:

I had specified an `accepted_values` test, like so:

```yaml
  - name: my_table
    columns:
      - name: does_match
        tests:
          - accepted_values:
              values: [TRUE]
              quote: false
              config:
                severity: error
                error_if: ">1428"
```

intending it to throw if the number of rows that fail the test exceed 1428. Only now do I realize that the test interprets this not as the number of rows that violate the test but the number of distinct values that aren't accepted that occur in the table.

### Expected Behavior

I can see use cases for both behaviors. Would it be possible to allow for both; or at the very least, to more explicitly mention in the documentation what the behavior is?

### Steps To Reproduce

See above

### Environment

```markdown
- OS: osx
- Python: 3.10.9
- dbt: 1.6.0
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment]
@RoyalTS Thanks for opening! Your read is right. By default, the `accepted_values` test returns one row per unexpected value, accompanied by the count of records with that unexpected value:

https://github.com/dbt-labs/dbt-core/blob/b39eeb328c9a245f21b54fb48f2761ad03d4d6ad/core/dbt/include/global_project/macros/generic_test_sql/accepted_values.sql#L5-L7

So given a model like the one below, and the sample config you included above, you would get **1** failure (= 1 unexpected value `false`):
```sql
-- models/my_model.sql
select true as does_match
union all
select false as does_match
union all
select false as does_match
```

I agree that the documentation could be clearer - however! - you can also configure a [custom `fail_calc`](https://docs.getdbt.com/reference/resource-configs/fail_calc), to return a number of failures based on `sum(n_records)` instead of `count(*)`:

```yml
models:
  - name: my_model
    columns:
      - name: does_match
        tests:
          - accepted_values:
              values: [TRUE]
              config:
                error_if: ">1428"
                fail_calc: "sum(n_records)"
```
```
$ dbt test
...
09:21:19  1 of 1 START test accepted_values_my_model_does_match__False__True ............. [RUN]
09:21:19  1 of 1 WARN 2 accepted_values_my_model_does_match__False__True ................. [WARN 2 in 0.05s]
...
09:21:19  Warning in test accepted_values_my_model_does_match__False__True (models/schema.yml)
09:21:19  Got 2 results, configured to warn if != 0
...
```

The same basic premise holds for the other built-in tests. The `unique` test returns, by default, the number of distinct duplicate values (rather than the number of rows with a duplicate value). This is called out explicitly in [the docs on `fail_calc`](https://docs.getdbt.com/reference/resource-configs/fail_calc):

> For instance, you can configure a unique test to return `sum(n_records)` instead of `count(*)` as the failure calculation: that is, the number of rows in the model containing a duplicated column value, rather than the number of distinct column values that are duplicated.

I'm going to close this, as I don't believe it to be a bug. I'd welcome you to open an issue / suggest an edit in [the docs.getdbt.com repo](https://github.com/dbt-labs/docs.getdbt.com) if you think this could be clearer in the documentation.
