### ISSUE TITLE
[CT-3101] dbt logs not getting generated for dbt commands in Databricks

### ISSUE THREAD

**Issue by abhishek-7781** [dbt-labs/dbt-core#8608]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm running a dbt project (which reads data from ADLS and writes back to ADLS) using a Databricks Workflow. When I configure **log-path** in dbt-project.yml or provide the **--log-path** CLI flag to generate dbt logs in a custom DBFS location (e.g. /dbfs/dbt-databricks/logs), dbt is generating logs only for the 1st command in the Databricks workflow (which usually is **dbt deps**) and not for any subsequent command (i.e. **dbt debug**, **dbt run** or **dbt test**).
Although, this works fine while running it from local Python virtual environment (through VSCode).

### Expected Behavior

dbt should be able to generate logs for all the above mentioned commands in a single **dbt.log** file at the specified DBFS location.

### Steps To Reproduce

1. Setup a dbt project for Databricks
2. profiles.yml
```
project_name:
    output:
        databricks_job:
              type: databricks
              method: http
              threads: 4
              schema: "{{ env_var('target_schema') }}"
              host: "{{ env_var('hostname') }}"
              http_path: "{{ env_var('http_path') }}"
              client_id: "{{ env_var('token') }}"
```
3. Run the following commands
```
dbt --log-path '/dbfs/dbt-databricks/logs/' deps
dbt --log-path '/dbfs/dbt-databricks/logs/' debug
dbt --log-path '/dbfs/dbt-databricks/logs/' run --select mode_name
dbt --log-path '/dbfs/dbt-databricks/logs/' test --select model_name
```

### Environment

```markdown
- Environment/Platform: Databricks
- Python: 3.9.5
- dbt-core: 1.3.5/1.6.1
- dbt-databricks: 1.3.2/1.6.1
- databricks-sql-connector: 2.7.0/2.9.3
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

**Error Screenshots:**

![image](https://github.com/databricks/dbt-databricks/assets/141800574/f7594ace-095d-481b-bfa2-fc0fd9e93c8b)
![image](https://github.com/databricks/dbt-databricks/assets/141800574/06415134-7f65-401b-9803-fb5aaac9f086)
![image](https://github.com/databricks/dbt-databricks/assets/141800574/c913dcf3-a6a6-4dfb-8656-88bc8b6b1376)

![image](https://github.com/databricks/dbt-databricks/assets/141800574/e17da79d-8967-42f5-865f-7227f13dc89b)
