### ISSUE TITLE
Handle input seeds in unit tests

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#8652]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Our proposed [unit testing spec](https://github.com/dbt-labs/dbt-core/discussions/8275), doesn't yet take into account if one of the inputs to the model you want to add a unit test to is a `seed`. 

Let's say `model_a` depends on `my_seed`. If you want to add a unit test to `model_a` - do you need to define an input for `my_seed`? That feels redundant since seeds don't often change and are already small data inputs.

How should we handle inputs for seeds?

**Comment by dbeatty10** [comment]
### Maybe it "just works"?

Let's suppose `my_upstream_model_a` is a model (rather than a seed) and [this](https://github.com/dbt-labs/dbt-core/issues/8606#issuecomment-1724286883) is how we configure a fixture for it:

```yaml
unit-tests:
  - name: test_my_model
    model: my_model
    given:
      - input: ref('my_upstream_model_a')
        format: csv
        fixture: my_upstream_model_a_fixture
```

Then we can imagine that the above should "just work" even if `my_upstream_model_a` were a [seed](https://docs.getdbt.com/docs/build/seeds) instead -- the seed's CSV rows would just be replaced by the CSV rows within `my_upstream_model_a_fixture`, right?

Can we think of reasons why it wouldn't "just work"?

### An additional thought

For the special case of `my_upstream_model_a_fixture` being a seed, what about the idea of being able to make `format` and `fixture` optional:

```yaml
unit-tests:
  - name: test_my_model
    model: my_model
    given:
      - input: ref('my_upstream_model_a')
```

Or maybe even going the whole way and making the `input:` optional for upstream seeds:
```yaml
unit-tests:
  - name: test_my_model
    model: my_model
    given:
      # presumably other `input`s are explicitly defined here, but at least `my_upstream_model_a` is implicitly defined -- since it's a seed, we already have all the data we need to mock it
```

**Comment by graciegoheen** [comment]
Let's say you're unit testing `my_favorite_model` that depends on:
- `my_favorite_source` (a source)
- `my_second_favorite_model` (a model)
- and `my_special_seed` (a seed)

You _must_ supply mock input data for all of the direct parent **models and sources**. 
```
unit-tests:
  - name: test_my_model
    model: my_model
    given:
      - input: ref('my_favorite_source')
        format: csv
        fixture: my_favorite_source_fixture
      - input: ref('my_second_favorite_model')
        format: csv
        fixture: my_second_favorite_model_fixture
```

You _may_ supply mock input data for direct parent **seeds**, if desired.
```
unit-tests:
  - name: test_my_model
    model: my_model
    given:
      - input: ref('my_favorite_source')
        format: csv
        fixture: my_favorite_source_fixture
      - input: ref('my_second_favorite_model')
        format: csv
        fixture: my_second_favorite_model_fixture
      - input: ref('my_special_seed')
        format: csv
        fixture: my_special_seed_fixture
```

---

Additional thought...

What would happen if you didn't care to supply mock data for one of the direct parent models (because it's not relevant for the logic that you're trying to test), where you want to instead use an "empty" mock data set or a one-row, all NULL data set?
- would you not have to supply the input at all?
```
unit-tests:
  - name: test_my_model
    model: my_model
    given:
```
- or would we require that you explicitly specify that behavior?
```
unit-tests:
  - name: test_my_model
    model: my_model
    given:
      - input: ref('my_upstream_model_a')
        rows: {}
```

The second feels less magically, but I like that it's an intentional decision rather than the risk of "oops, I forgot to add mock data for `my_upstream_model_a` but didn't get any error!

Food for thought... probably for a separate issue. cc: @MichelleArk
