### ISSUE TITLE
[CT-3144] [Regression] build never starts on 1.6.2 and 1.6.3

### ISSUE THREAD

**Issue by renanleme** [dbt-labs/dbt-core#8692]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Afterm upgrading to `1.6.2` from `1.5.1` our build is taking way longer to start the first model
From around 7 to 8 minutes to complete to more than 1 hour without starting.

**I'm running `dbt build --selector X`**
```
python: 3.11.5
dbt_core: 1.5.1 -> 1.6.2
dbt-snowflake: 1.5.1-> 1.6.2
```

**Models:**
```
Found 2840 models, 31 snapshots, 10 analyses, 2277 tests, 78 seeds, 1 operation, 499 sources, 0 exposures, 0 metrics, 960 macros, 0 groups, 0 semantic models
```

**Selector example**
```
  - name: XYZ
    definition:
      union:
        - '*'
        - exclude:
            - method: selector
              value: P1
            - method: selector
              value: P2
            - method: selector
              value: P3
            - method: selector
              value: P4
            - method: selector
              value: P5
```

### Expected/Previous Behavior

That the build would take around 8 minutes to start after compiling all the models

### Steps To Reproduce

```
root@b78d02b2ea5d:/usr/app/dbt# dbt build  --selector XYZ
15:10:34  Running with dbt=1.5.1
15:11:43  Found 2840 models, 2277 tests, 31 snapshots, 10 analyses, 909 macros, 1 operation, 78 seed files, 499 sources, 0 exposures, 0 metrics, 0 groups
15:18:21  
15:18:52  Concurrency: 8 threads (target='dev-ssh-password')
15:18:52  
15:18:52  1 of 1260 START sql view model raw.dbt_meta.Z ................. [RUN]
```
Takes around 6 to 7 minutes

Same command, different version
```
dbt build --selector XYZ
14:42:04  Running with dbt=1.6.2
14:42:05  Registered adapter: snowflake=1.6.2
14:42:06  Unable to do partial parsing because of a version mismatch
14:42:35  Found 2840 models, 31 snapshots, 10 analyses, 2277 tests, 78 seeds, 1 operation, 499 sources, 0 exposures, 0 metrics, 960 macros, 0 groups, 0 semantic models
```
And it goes for more than 50 minutes without starting with **CPU at 100%**

### Relevant log output

```shell
Checking the log file there's nothing being logged after `Found 2840 models...` line besides the CPU usage at 100%
```

### Environment

```markdown
- OS: Running inside container - `python:3.11.5-slim-bookworm`
`Linux 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64 GNU/Linux`
- Python: `3.11.5`
- dbt (working version): `1.5.1`
- dbt (regression version):  `1.6.2` and `1.6.3`
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

- I thought that this could be related to this issue: https://github.com/dbt-labs/dbt-core/issues/8360
But I upgraded to 1.6.3 before posting here and the issue continues

- **I ran `dbt compile --selector XYZ` on both and both ran successfully**
