### ISSUE TITLE
[CT-3145] [Bug] partial parsing issue when adding private models to a new group

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-core#8697]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

[loom explanation](https://www.loom.com/share/9c61cf7d28ff41348ca7a4bba98ac6f1)

adding multiple nodes that have a relationships to the same group with private access results in a parsing error:

```
Parsing Error
  Node model.mega_corp_big_co_inc.int_returns__unioned attempted to reference node model.mega_corp_big_co_inc.stg_tpcds_core__catalog_returns, which is not allowed because the referenced node is private to the 'sales_analytics' group.
```

in this case, `int_returns__unioned` is a child of `stg_tpcds_core__catalog_returns`, both were added to a newly-created group called `sales_analytics` and had access set to `private`, all of which happened between invocations of dbt. 

### Expected Behavior

everything should parse just fine! these are both private members of the same group and we love that

### Steps To Reproduce

see loom!

### Environment

```markdown
- OS: mac
- Python: Python 3.9.16
- dbt: 1.6.0 and 1.6.3 (see loom)
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

i love dbt

**Comment by dbeatty10** [comment]
### Reprex (using the Loom as inspiration)

`models/my_model_a`
```sql
select 1 as id
```

`models/my_model_b`
```sql
select 2 as id
```

`models/my_model_c`
```sql
select * from {{ ref("my_model_a") }} union all
select * from {{ ref("my_model_b") }}
```

`models/_models.yml`
```yaml
models:
  - name: my_model_a
  - name: my_model_b
  - name: my_model_c
```

Clean out any previous artifacts and compile in that fresh environment (everything should work fine):
```shell
dbt clean
dbt compile
```

Now update your `models/_models.yml` file like this:
```yaml
groups:
  - name: sales_analytics
    owner:
      name: Sales Analytics
      email: sales@jaffleshop.com

models:
  - name: my_model_a
    access: private
    group: sales_analytics
  - name: my_model_b
    access: private
    group: sales_analytics
  - name: my_model_c
    access: private
    group: sales_analytics
```

Doing this will yield an error:
```shell
dbt compile
```

But doing this instead would have not yielded an error:
```
dbt --no-partial-parse compile
```

Either way, re-running this command a 2nd time worked for me:
```
dbt compile
```
