### ISSUE TITLE
[CT-3165] [Bug] Model configurations from the model YML file are not respected

### ISSUE THREAD

**Issue by siljamardla** [dbt-labs/dbt-core#8726]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

There is #8520 which refers to problems with Python model configurations specifically, but I believe the root cause might be different in this case, so raising a separate issue. 

I have the following model configuration set up in the models.yml file:
```YML
models:
  - name: smth_smth
    description: smth_smth
    config:
      materialized: incremental
      incremental_strategy: merge
      unique_key: ["smth_key"]
      partition_by: "created_date"
      on_schema_change: append_new_columns
      schema: smth_schema
      tags: [smth_tag]
    meta:
      owner: '@silja.mardla'
      state: testing
```
However, when I run the model, dbt will create a VIEW model (our default materialisation from project YML).
```
Finished running 1 view model
```
The actual code compiled confirms that a view gets created:
```SQL
create or replace view `smth_schema`.`smth_smth`
  
  
  as
```

Also, there are other configurations not being respected, for example tags. 
```
dbt list --select tag:smth_tag
```
will not return anything
```
The selection criterion 'tag:smth_tag' does not match any nodes
```

And it seems like even the meta that comes after the configurations blocks, get lost
<img width="663" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/11821921/c4bc1fe9-bab4-4a53-9807-2675adbddcfb">

### Expected Behavior

Model configurations respected.

### Steps To Reproduce

See above

### Environment

```markdown
- OS: Mac
- Python: 3.11
- dbt: 1.6.3
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Databricks
