### ISSUE TITLE
[CT-3187] Add GHA to dependabot checks

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#8776]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

Let's leverage dependabot to check our github actions.

### Acceptance criteria

This exists in dependabot.yml

```yaml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
```

### Impact to Other Teams

None

### Will backports be required?

No

### Context

We should also validate we do this in our other repos.

At a minimum:
- `actions`
- `dbt-release`
- ?
