### ISSUE TITLE
[CT-3195] [spike+] unit testing versioned models

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#8799]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

1. If a unit test is added to a model, with no supplied version, the unit test will run on all versions of said model
```
unit-tests:
  - name: test_is_valid_email_address # this is the unique name of the test
    model: my_model # name of the model I'm unit testing
    given: # optional: list of inputs to provide as fixtures
      - input: ref('users')
        rows:
         - {user_id: 1, email: cool@example.com,     email_top_level_domain: example.com}
         - {user_id: 2, email: cool@unknown.com,     email_top_level_domain: unknown.com}
         - {user_id: 3, email: badgmail.com,         email_top_level_domain: gmail.com}
         - {user_id: 4, email: missingdot@gmailcom,  email_top_level_domain: gmail.com}
      - input: ref('top_level_domains')
        rows:
         - {tld: example.com}
         - {tld: gmail.com}
    expect: # required: the expected output given the inputs above
      - {user_id: 1, is_valid_email_address: true}
      - {user_id: 2, is_valid_email_address: false}
      - {user_id: 3, is_valid_email_address: false}
      - {user_id: 4, is_valid_email_address: false}
```
So if I have version 1, 2, and 3 of `my_model`, my `test_is_valid_email_address` unit test will run on all 3 versions.

2. To to only unit test a specific version (or versions) of a model, you can include the desired version(s) in the model config
```
unit-tests:
  - name: test_is_valid_email_address # this is the unique name of the test
    model: my_model # name of the model I'm unit testing
      versions:
        include: 
          - 2
    given: # optional: list of inputs to provide as fixtures
      - input: ref('users')
        rows:
         - {user_id: 1, email: cool@example.com,     email_top_level_domain: example.com}
         - {user_id: 2, email: cool@unknown.com,     email_top_level_domain: unknown.com}
         - {user_id: 3, email: badgmail.com,         email_top_level_domain: gmail.com}
         - {user_id: 4, email: missingdot@gmailcom,  email_top_level_domain: gmail.com}
      - input: ref('top_level_domains')
        rows:
         - {tld: example.com}
         - {tld: gmail.com}
    expect: # required: the expected output given the inputs above
      - {user_id: 1, is_valid_email_address: true}
      - {user_id: 2, is_valid_email_address: false}
      - {user_id: 3, is_valid_email_address: false}
      - {user_id: 4, is_valid_email_address: false}
```   
So if I have version 1, 2, and 3 of my_model, my test_is_valid_email_address unit test will run on ONLY version 2.

3. To to unit test all versions except a specific version (or versions) of a model, you can exclude the relevant version(s) in the model config
```
unit-tests:
  - name: test_is_valid_email_address # this is the unique name of the test
    model: my_model # name of the model I'm unit testing
      versions:
        exclude: 
          - 1
    given: # optional: list of inputs to provide as fixtures
      - input: ref('users')
        rows:
         - {user_id: 1, email: cool@example.com,     email_top_level_domain: example.com}
         - {user_id: 2, email: cool@unknown.com,     email_top_level_domain: unknown.com}
         - {user_id: 3, email: badgmail.com,         email_top_level_domain: gmail.com}
         - {user_id: 4, email: missingdot@gmailcom,  email_top_level_domain: gmail.com}
      - input: ref('top_level_domains')
        rows:
         - {tld: example.com}
         - {tld: gmail.com}
    expect: # required: the expected output given the inputs above
      - {user_id: 1, is_valid_email_address: true}
      - {user_id: 2, is_valid_email_address: false}
      - {user_id: 3, is_valid_email_address: false}
      - {user_id: 4, is_valid_email_address: false}
```   
So if I have version 1, 2, and 3 of my_model, my test_is_valid_email_address unit test will run on ONLY version 2 and 3.

(similar to include & exclude for [warn_error_options](https://docs.getdbt.com/reference/global-configs/warnings)) 

4. If you want to unit test a model that references a pinned version of model, you should specify that in the ref of your `input:`
```
unit-tests:
  - name: test_is_valid_email_address # this is the unique name of the test
    model: my_model # name of the model I'm unit testing
    given: # optional: list of inputs to provide as fixtures
      - input: ref('users', v=1)
        rows:
         - {user_id: 1, email: cool@example.com,     email_top_level_domain: example.com}
         - {user_id: 2, email: cool@unknown.com,     email_top_level_domain: unknown.com}
         - {user_id: 3, email: badgmail.com,         email_top_level_domain: gmail.com}
         - {user_id: 4, email: missingdot@gmailcom,  email_top_level_domain: gmail.com}
      - input: ref('top_level_domains')
        rows:
         - {tld: example.com}
         - {tld: gmail.com}
    expect: # required: the expected output given the inputs above
      - {user_id: 1, is_valid_email_address: true}
      - {user_id: 2, is_valid_email_address: false}
      - {user_id: 3, is_valid_email_address: false}
      - {user_id: 4, is_valid_email_address: false}
```

**Comment by graciegoheen** [comment]
@dbeatty10 What are your thoughts here if you want to only run the unit test on the "latest" version on the model?

**Comment by graciegoheen** [comment]
@MichelleArk looking at some previous notes, it sounds like we may actually already support unit testing a specific version of a model, by setting `model: model_name.v<version>` 

@dbeatty10 What are y'all's thoughts on that naming convention vs. setting the version in the unit test yml block

**Comment by graciegoheen** [comment]
I think 3 (f you want to unit test a model that references a pinned version of model, you should specify that in the ref of your `input:`) is already supported (?) but we should ensure we have a test for that

**Comment by graciegoheen** [comment]
For the future, we may want to consider enabling folks to only unit test a specific _version_ (or versions) of a model, by supplying the version(s) in my model config
```
unit-tests:
  - name: test_is_valid_email_address # this is the unique name of the test
    model: my_model # name of the model I'm unit testing
      versions:
        - v2
    given: # optional: list of inputs to provide as fixtures
      - input: ref('users')
        rows:
         - {user_id: 1, email: cool@example.com,     email_top_level_domain: example.com}
         - {user_id: 2, email: cool@unknown.com,     email_top_level_domain: unknown.com}
         - {user_id: 3, email: badgmail.com,         email_top_level_domain: gmail.com}
         - {user_id: 4, email: missingdot@gmailcom,  email_top_level_domain: gmail.com}
      - input: ref('top_level_domains')
        rows:
         - {tld: example.com}
         - {tld: gmail.com}
    expect: # required: the expected output given the inputs above
      - {user_id: 1, is_valid_email_address: true}
      - {user_id: 2, is_valid_email_address: false}
      - {user_id: 3, is_valid_email_address: false}
      - {user_id: 4, is_valid_email_address: false}
```
So if I have version 1, 2, and 3 of `my_model`, my `test_is_valid_email_address` unit test will run on ONLY version 2.

But this it out of scope for the time being

**Comment by graciegoheen** [comment]
Notes from refinement:
- creating multiple unit test definitions for each model that's versioned
- could have partial parsing implications
- how do we know all of the versions for a given model

**Comment by emmyoop** [comment]
@grace-arends How do we want to handle fixture files?  If we have versioned models and want to test them all but need to use different versions of the fixture file, will we allow it by naming them `my_fixture_v1.csv` or similar?  Or does each unit test need to be defined separately, as in the last option outlined above?

**Comment by graciegoheen** [comment]
>  If we have versioned models and want to test them all but need to use different versions of the fixture file

@emmyoop I don't think we want to allow folks to use different fixtures depending on the version in a _single_ unit test - a unit test should be defined on a _static_ set of inputs. 

If you want to create a unit test on version 1 of your model, and a _different_ unit test (with _different_ fixtures) on versions 2 and 3 of your model, I would expect you to need to use 2 different unit test definitions (regardless of the format you're supplying the mock input/expected output data in):
```
unit-tests:
  - name: test_is_valid_email_address # this is the unique name of the test
    model: my_model # name of the model I'm unit testing
      versions:
        include: 
          - 1
    given: # optional: list of inputs to provide as fixtures
      - input: ref('users')
        format: csv
        fixture: users_emails_fixture
      - input: ref('top_level_domains')
        rows:
         - {tld: example.com}
         - {tld: gmail.com}
    expect: # required: the expected output given the inputs above
      - {user_id: 1, is_valid_email_address: true}
      - {user_id: 2, is_valid_email_address: false}
      - {user_id: 3, is_valid_email_address: false}
      - {user_id: 4, is_valid_email_address: false}
  - name: test_is_valid_email_address_2 # this is the unique name of the test
    model: my_model # name of the model I'm unit testing
      versions:
        exclude: 
          - 1
    given: # optional: list of inputs to provide as fixtures
      - input: ref('users')
        rows:
        format: csv
        fixture: users_emails_fixture_2
      - input: ref('top_level_domains')
        rows:
         - {tld: example.com}
         - {tld: gmail.com}
         - {tld: hotmail.com}
    expect: # required: the expected output given the inputs above
      - {user_id: 1, is_valid_email_address: true}
      - {user_id: 2, is_valid_email_address: false}
      - {user_id: 3, is_valid_email_address: false}
      - {user_id: 4, is_valid_email_address: false}
```

If we get feedback to the contrary, we can always come back to this!
