### ISSUE TITLE
[CT-3201] [Feature] Choose a specific target for a model

### ISSUE THREAD

**Issue by RalfKow** [dbt-labs/dbt-core#8822]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

My elt pipeline depends of different databases. (postgres and snowflake). I would love to keep the whole pipeline in the same dbt project. I am aware of the option to change the target per stage. f.E having dev on a postgres and prod on snowflake.

In my case I would love to pass the option "target" to the corresponding database.

The resulting dbt_project would look like:

```yaml
models:
  #target
  postgres:
  +target: target defined in profile
    #schema
    input:
      reconciliation_landing_schema: ramsi_landing
      reconciliation_base_schema: ramsi_loading
      reconciliation_out_schema: "{{ env_var('RECONCILIATION_OUT_SCHEMA') }}"
      +on_schema_change: append_new_columns
      +incremental_strategy: update+insert
      +contract:
        enforced: false
    internal:
```

### Describe alternatives you've considered

I basically have a monorepo with multiple subfolders and the dbt_project.yaml not in root which leads to multiple pains.

- I am having trouble with the pre commit hooks 
- I am having problems with my docker image if I execute poetry run dbt deps --project-dir= path/to/project1 and poetry run dbt deps --project-dir= path/to/project2
- My sonarqube Is looking in root per default

### Who will this benefit?

Everyone that has monorepos 

### Are you interested in contributing this feature?

yes
