### ISSUE TITLE
[CT-3242] [Bug] adding a where clause to all tests of a single model doesn't work as documentation states

### ISSUE THREAD

**Issue by fathom-parth** [dbt-labs/dbt-core#8876]
### Is this a new bug in dbt-core?

- [ ] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Adding a where clause to all tests for a specific model doesn't seem to work as [documentation states](https://docs.getdbt.com/reference/test-configs#test-specific-configurations)

The docs mention you can add the following to dbt_project.yml:
```
tests:
  <resource-path>:
    ...
    +where: <string>
```

[The docs](https://docs.getdbt.com/reference/resource-configs/resource-path) for resource-path state:
> It represents the nested dictionary keys that provide the path to either a directory of models, or a single model.

This suggests that adding a resource path to a single model within the `tests` key in `dbt_project.yml` should be able to add a where clause to all tests for that single model.

However, in practice, you get a warning:
```
There are 3 unused configuration paths:
- tests.foo.staging.customer.bar
- ...
```
and no filter is applied.

### Expected Behavior

I would expect the where filter to be applied to that single model's tests.

### Steps To Reproduce

Create a model directory structure like:
```
.
├── dbt_project.yml
└── models
    └── marts
        └── live
            └── 1.sql
            └── 2.sql
            └── _live_models.yml
    └── staging
        └── customer
            └── bar.sql
            └── _customer_models.yml
```

Set the project name to `foo`.

Set the following config in `dbt_project.yml`:
```
tests:
  foo:
    marts:
      live:
        +where: "download_ts = cast('2023-01-01' as timestamp)"

    staging:
      customer:
        bar:
          +where: "download_ts = cast('2023-01-01' as timestamp)"
```

Now try running any dbt command, e.g.
```
dbt docs generate
```

You should get the error:
```
16:42:39  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 3 unused configuration paths:
- tests.foo.staging.customer.bar
- ...
```

Seemingly the marts/live where filter works fine.

### Environment

```markdown
- OS: Debian GNU/Linux 10 (buster)
- Python: 3.7
- dbt-core: 1.5.0
```

### Which database adapter are you using with dbt?

bigquery

**Comment by fathom-parth** [comment]
X-ref to dbt slack:
https://getdbt.slack.com/archives/CBSQTAPLG/p1697821046633539

**Comment by fathom-parth** [comment]
Current workaround that I'm using:
put the affected models into a folder and then apply the filter to the folder rather than the singular model resource path

However, I'm not sure if this works for tests on source models. Would you put the source yml in a folder?

**Comment by dbeatty10** [comment]
@fathom-parth Thanks for an amazing write-up, complete with a detailed example and cross-references to the documentation and a discussion in Slack! 🤩

## Explanation of the warning message

We can explain the warning you are getting with your example:
- your configuration within `dbt_project.yml` is looking for a **test** node named `bar` rather than **model** node named `bar`.

i.e., you can use one of the approaches mentioned below to add that configuration to the applicable **test** node.

First, you can do a listing of all the test node names associated with the `bar` model like this:
```shell
dbt list --select bar --resource-type test
```

For me, the output includes the `not_null` and `unique` tests that I added to the `description` column:
```
foo.marts.not_null_bar_description
foo.marts.unique_bar_description
```

### Approach 1

You are able to add a `where` config for each of those two tests within `dbt_project.yml`:

```yaml
tests:
  foo:
    marts:
      live:
        +where: "download_ts = cast('2023-01-01' as timestamp)"

    staging:
      customer:
        not_null_bar_description:
          +where: "download_ts = cast('2023-01-01' as timestamp)"
        unique_bar_description:
          +where: "download_ts = cast('2023-01-01' as timestamp)"
```

### Approach 2

Alternatively, you can add the `where` config within [singular](https://docs.getdbt.com/docs/build/tests#singular-tests) (SQL) or [generic tests](https://docs.getdbt.com/docs/build/tests#generic-tests) (YAML) tests instead. i.e., within `_customer_models.yml`:
```yaml
models:
  - name: bar
    columns:
      - name: description
        tests:
          - not_null:
              config:
                where: "download_ts = cast('2023-01-01' as timestamp)"
          - unique:
              config:
                where: "download_ts = cast('2023-01-01' as timestamp)"
```

## Workaround
### Adding a `where` clause to all tests of a single model

You've got a couple options for workarounds:
1. Create a stand-alone folder dedicated to the tests of a particular model (like you described)
2. Add the `where` config individually to each test to which you want it to apply (via either approaches 1 or 2 mentioned above)

I'd generally recommend the latter rather than the former due to it being easier to understand and implement. The cost is that there is more repetition.

But you could choose the first option instead too. If so, it should work for sources in the same manner as for models.

### Summary

I'm going to close this as "not planned" since dbt is behaving the way we expect _and_ we don't plan to add a new feature that is dedicated to enabling hierarchical test config at the model level.
