### ISSUE TITLE
[CT-3255] [implementation] interface changes to dbt-core saved_query spec to add export

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#8892]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

Add exports to saved_query

```
saved_queries:
  - name: my_query
    description:
    query:
      metrics:
        - 
      group_bys:
        - TimeDimension()
        - ...
      where:
        - 
    exports:
      - name: my_query 
        config:
          export_as: table # options: table, view - FUTURE: incremental_table, window_table, file
          schema: my_schema  # [optional - DEFAULT to deployment schema]
          alias: some_table_name # [optional - DEFAULT to export name]
```

### Acceptance criteria

- add exports to saved_query

### Impact to Other Teams

SL

### Will backports be required?

1.7 latest
