### ISSUE TITLE
[CT-3301] [Bug] sources are not disabled in dbt_project.yml

### ISSUE THREAD

**Issue by epapineau** [dbt-labs/dbt-core#8960]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Disabling an entire source in `dbt_project.yml` does not work for in-project sources although it does work in the `sources.yml` or for package sources. For example, the following in `dbt_project.yml` will not disable the source:
```
sources:
  project_name:
    source_name:
      +enabled: false
```

But in `sources.yml` this will disable the source:
```
sources:
  - name: source_name
    config:
      enabled: false
```

### Expected Behavior

The ability to toggle the `enabled` configuration across all configuration levels.

### Steps To Reproduce

1. Define a source and add the `enabled` config to `dbt_project.yml

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

snowflake

**Comment by graciegoheen** [comment]
Hey Elize - after doing some troubleshooting, it looks like our docs might actually be wrong / misleading.

If your source is nested in a yml file in a subfolder, you will need to supply the path to that yml file _plus_ the source name in the `dbt_project.yml` file. 

```
sources:
  project_name:
    staging:
      my_source_folder:
        source_name:
          +enabled: false
```

Can you give something like that a try (depending on the path to your source yml file)?

In part this is confusing, because the output of `dbt list` is _not_ the fqn of the source (it's the selector). We have an open issue for this - https://github.com/dbt-labs/dbt-core/issues/8599.

I think these are the docs we need to update:
- https://docs.getdbt.com/reference/resource-configs/resource-path
- https://docs.getdbt.com/reference/source-configs

Looks like we had a similar issue / confusion come up for disabling tests https://github.com/dbt-labs/dbt-core/issues/8876

**Comment by mirnawong1** [comment]
hey @graciegoheen ! ok thank you for clarifying this and had a few reads to understand the change.

I've created a [PR here ](https://github.com/dbt-labs/docs.getdbt.com/pull/4394/files#diff-4caaf3187919c98f42856c140e32964b0829fc19165f3c989a6cd4ea088a7164) which addresses the above and also adds the resource paths doc to the sidebar. for some reason, it wasn't on there and i think it should be on the sidebar? 

can i ask you to take a look to ensure it's technically right?

**Comment by epapineau** [comment]
@graciegoheen Yes when I provide the project name and path I get the expected behavior. Thank you for your help here everyone~

**Comment by dbeatty10** [comment]
### How to disable a single table within a source

Suppose you have a super tiny dbt project that looks like this:
```
.
├── dbt_project.yml
└── models
    └── subdirectory_name
        └── _sources.yml
```

And you have two source tables defined within `models/subdirectory_name/_sources.yml`:
```yaml
# models/subdirectory_name/_sources.yml

version: 2

sources:
  - name: my_source_name
    tables:
      - name: my_source_table_1
      - name: my_source_table_2
```

You can list them like this:
```shell
$ dbt list
...
00:00:28  Found 2 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
source:your_project_name.my_source_name.my_source_table_1
source:your_project_name.my_source_name.my_source_table_2
```

Then to disable just the first table, you'd do the following within `dbt_project.yml`:
```yaml
# dbt_project.yml

name: "your_project_name"
version: "1.0.0"
config-version: 2
profile: "sandcastle"

sources:
  your_project_name:
    subdirectory_name:
      my_source_name:
        my_source_table_1:
          +enabled: false
```

And when you do another listing, you'll see it's been disabled:
```shell
$ dbt list
...
00:01:10  Found 1 source, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
source:your_project_name.my_source_name.my_source_table_2
```

### Potential mistake

But if you don't get the hierarchy within `dbt_project.yml` _juuuuust_ right, then the `enabled` config won't have the effect you desire, and it will give an warning like this:
```
00:10:35  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- sources.your_project_name.subdirectory_name.my_source_name__misnamed.my_source_table_1
```
