### ISSUE TITLE
[Bug] Unclear error messaging returned on Snowflake quoting related syntax error

### ISSUE THREAD

**Issue by sophiad96** [dbt-labs/dbt-core#8968]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Sean at Flowcode reached out as they were seeing the following error message in their jobs: 

```
14:26:26  on-run-end failed, error:
14:26:26   100069 (22P02): Error parsing JSON: missing comma, pos 124
```

The issue, however, was actually around some quoting they used in a .yml file. They’re using the Snowflake adapter (which is finicky about quoting). Please note that this user has quoting enabled for identifiers.

### Expected Behavior

I would expect an error message around quoting on the specific line in the .yml file to be returned, rather than an error message referencing an entirely different part of the project (the `on-run-end`).

### Steps To Reproduce

I haven't had time to reproduce this yet, but my assumption is that you would need to create a dbt project that uses the Snowflake adapter, has quoting enabled for identifiers, and has a sources.yml file with a freshness config that includes a config that uses double quotes. The customer had this in their project:

```
- name: flow_directory
        freshness:
          warn_after: 
            count: 6 
            period: hour
          error_after: 
            count: 24
            period: hour
          filter: datediff('day', "DMS_S3_SYNCED_AT"::timestamp, current_timestamp) < 2
        loaded_at_field: "DMS_S3_SYNCED_AT"
```

The issue was caused by the double quotes around `DMS_S3_SYNCED_AT`.

### Relevant log output

```shell
https://dbtlabsmt.datadoghq.com/logs?query=%40extra.run_id%3A211284387%2A%20&cols=host%2Cservice&event=AgAAAYuGIO6Ti1esowAAAAAAAAAYAAAAAEFZdUdJUF80QUFBUkxVVzRiMG5LdWdBSgAAACQAAAAAMDE4Yjg2MmQtMGE4Yi00MjliLTg1YWUtOTI4MjMxZmJhNzc1&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1698591902623&to_ts=1698851102623&live=true
```

### Environment

```markdown
- OS: This was surfaced by a dbt Cloud user.
- Python: NA
- dbt: 1.5
```

### Which database adapter are you using with dbt?

snowflake
