### ISSUE TITLE
[CT-3323] Allow singular tests to be documented

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#9005]
### Description

Currently, you can document pretty much everything but a [data test](https://docs.getdbt.com/docs/build/data-tests#overview) - if you try, it fails on a parsing error. This ticket is for [singular data tests](https://docs.getdbt.com/docs/build/data-tests#singular-data-tests). A separate ticket (#2578) addresses [generic data tests](https://docs.getdbt.com/docs/build/data-tests#generic-data-tests).

Currently we don't have a "tests" section in schema files. In order to allow setting descriptions in yaml files we should add one. (As a side issue, the SingularTestNodes use the TestConfig, which is not particularly valid for SingularTestNodes. Maybe we need a separate SingularTestConfig.)

https://docs.getdbt.com/docs/build/tests#singular-tests

### Acceptance Criteria

* You can add a description to a singular test in a yaml file
* You can use a docs block to capture your test description
* That description shows up in the docs site

### Considerations

* Do we need to exclude this from state modified? 
* New section in schema files and new schema parser
* Don't have a test schema parser 
* Need yml to be able to have a description

**Comment by MichelleArk** [comment]
Since singular tests aren't explicitly linked to models in schema.yml files already, would we imagine a spec looking something like: 
```
models:
  - name: orders
    columns:
      - name: order_id
        tests:
          - my_super_cool_singular_test
            description: The order_id is unique for every row in the orders model
          - my_super_cool_singular_test2
            description: '{{ doc("not_null_test") }}'
```

cc @graciegoheen @jtcohen6
