### ISSUE TITLE
[CT-3366] [Bug] Overwridding TYPE_LABELS inside Column  doesn't work 

### ISSUE THREAD

**Issue by nicor88** [dbt-labs/dbt-core#9047]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm trying to overwrite **Column** in  dbt-athena adapter, in order to return VARCHAR, instead of TEXT to make proper type aliasing.

See this snippet: 

```
class AthenaColumn(Column):
    table_type: TableType = TableType.TABLE

    TYPE_LABELS: ClassVar[Dict[str, str]] = {
        "STRING": "VARCHAR",
        "TEXT": "VARCHAR",
    }
```
But anyhow doesn't matter that I use a new version of TYPE_LABELS, the values from Column inside dbt-core are used.

### Expected Behavior
I expect that I can overwrite the Column implementation in any adapter and use it in data-contracts as type aliasing.
Specifically I expect that any adapter can use an own version of TYPE_LABELS, as platform can slightly differer.

### Steps To Reproduce
1. Create model and this definition in dbt-athena (main branch 1.7.0 of dbt-core):

```
{{ config(
    materialized='table',
    format='parquet',
    ha=true,
    s3_data_naming='table_unique',
) }}

SELECT
  cast(t.ts AS timestamp(3)) AS ts
  , CAST('2023-04-04' AS DATE) AS test_date
  , 'abc' AS test_string_varchar
FROM
    unnest(
        sequence(
            current_date - INTERVAL '1' DAY,
            cast(REPLACE(cast(current_timestamp as varchar), ' UTC', '') as timestamp(3)),
            INTERVAL '1' MINUTE
        )
    ) AS t(ts)

```

use this schema: 
```
  - name: test_contract
    config:
      contract:
        enforced: true
        # alias_types: False
    columns:
      - name: ts
        data_type: TIMESTAMP
        constraints:
        - type: not_null
      - name: test_date
        data_type: DATE
        constraints:
          - type: not_null
      - name: test_string_varchar
        data_type: string
        constraints:
          - type: not_null
```

3. Run the model, and then the error:
TYPE_MISMATCH: line 7:9: Unknown type: TEXT

Refer to the above and this https://github.com/dbt-athena/dbt-athena/pull/498/files

NOTE: modifying the value of TYPE_MISMATCH from TEXT to VARCHAR in dbt-core makes that working...but we should be able to overwrite it in the adapter.

### Relevant log output

```shell
> 21:27:23    Runtime Error in model test_contract (models/example/test_contract.sql)
  TYPE_MISMATCH: line 7:9: Unknown type: TEXT
```

### Environment

```markdown
- OS: MacOs
- Python: 3.11
- dbt: 1.7.0
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

issue related to an adapter overwrite.
