### ISSUE TITLE
[CT-3383][Bug] Metadata freshness checks that include a filter cause dbt to hang

### ISSUE THREAD

**Issue by sp-tkerlavage** [dbt-labs/dbt-core#9078]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I found this when I was testing the new information_schema/metadata driven freshness feature released in v1.7.

I removed the loaded_at field from my freshness test configs and ran them, not realizing I still had a `filter` on my freshness check definition. The output in the terminal showed the freshness checks being executed, but they never completed. Viewing my warehouse query history, I confirmed that dbt didn't actually issue any freshness queries at all. dbt output just sat there for several minutes before I manually cancelled it.

Removing the `filter` from the freshness check definition resolved the issue.

### Expected Behavior

Metadata driven freshness checks should either support `filter` if theres a use case for that behavior, or `filter` should be ignored and there should be a warning message indicating that `filter` was ignored.

Either way the current behavior where `filter` causes metadata driven freshness checks to just hang does seem to be a bug.

### Steps To Reproduce

This should cause the freshness check to "run" but no query against the warehouse will be issued:
```
version: 2
sources:
  - name: src
    database: db
    schema: test

    tables:
      - name: test_table
        freshness:
          warn_after:
            count: 4
            period: hour
          error_after:
            count: 8
            period: hour
          filter: 1=1
```

This should resolve the error (filter config is removed--freshness check query is actually issued and runs to completion)
```
version: 2
sources:
  - name: src
    database: db
    schema: test

    tables:
      - name: test_table
        freshness:
          warn_after:
            count: 4
            period: hour
          error_after:
            count: 8
            period: hour
```

### Environment

```markdown
- OS: macOS-13.5.2-x86_64-i386-64bit
- Python: 3.11.6
- dbt-core: 1.7.1
- dbt-snowflake: 1.7.0
```
