### ISSUE TITLE
[Feature] Improve error message when metadata freshness last modified relation is not found

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#9079]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Suppose you have the following `models/_sources.yml` file to describe a source table that doesn't actually exist:

```yaml
sources:
  - name: src
    database: "{{ target.database }}"
    schema: "{{ target.schema }}"
    tables:
      - name: dont_exist
        freshness:
          warn_after:
            count: 4
            period: hour
          error_after:
            count: 8
            period: hour
```

Here's an example command and output in dbt-snowflake:
``` 
(snowflake_1.7) $ dbt source freshness

05:31:22  Running with dbt=1.7.0
05:31:23  Registered adapter: snowflake=1.7.0
05:31:23  Found 1 seed, 1 source, 0 exposures, 0 metrics, 430 macros, 0 groups, 0 semantic models
05:31:23  
05:31:24  Concurrency: 10 threads (target='snowflake')
05:31:24  
05:31:24  1 of 1 START freshness of src.dont_exist ....................................... [RUN]
05:31:29  1 of 1 ERROR freshness of src.dont_exist ....................................... [ERROR in 4.64s]
05:31:29  
05:31:29    Compilation Error in source dont_exist (models/_sources.yml)
  Got an invalid result from "get_relation_last_modified" macro: []
```

This would be a more helpful error message:
```
  Source relation `analytics_dev.dbt_dbeatty.dont_exist` was not found by the "get_relation_last_modified" macro
```

### Who will this benefit?

This will benefit anyone that runs `dbt source freshness` on a table that doesn't exist or otherwise isn't found in the metadata by giving them an informative error message.

### Anything else?

Discovered while troubleshooting https://github.com/dbt-labs/dbt-core/issues/9078.

The relevant source code is here:
https://github.com/dbt-labs/dbt-core/blob/017faf4bd18eefe030d87f61d6dd9e4a56cec020/core/dbt/adapters/base/impl.py#L1314-L1319

The logic might be updated to check if there are any results or not and raise a custom exception:

```python
        if len(table) == 0:
            raise RelationLastModifiedNotFound(...)

        try:
            row = table[0]
            last_modified_val = get_column_value_uncased("last_modified", row)
            snapshotted_at_val = get_column_value_uncased("snapshotted_at", row)
        except Exception:
            raise MacroResultError(GET_RELATION_LAST_MODIFIED_MACRO_NAME, table)
```
