### ISSUE TITLE
[CT-3387] [Bug] downstream model's tests are triggered together when it uses source() or ref() in tests referring upstream models.

### ISSUE THREAD

**Issue by rightx2** [dbt-labs/dbt-core#9083]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Describe the bug
1. sources.yaml

```
version: 2

sources:
  - name: my_source
    tables:
      - name: raw_customers
        columns:
          - name: id
            tests:
              - not_null               
      - name: raw_payments
```      

2. models/schema.yaml
```
version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - relationships:
              to: source('my_source', 'raw_customers')
              field: id
```             

When I run  `dbt test --select source:my_source.raw_customers`, it trigger TWO TESTS, not one test:
- `relationships_stg_customers_customer_id__id__source_my_source_raw_customers_`
- `source_not_null_my_source_raw_customers_id`

### Expected Behavior

Only `source_not_null_my_source_raw_customers_id` run.

### Steps To Reproduce

Explained above

### Relevant log output

```shell
INFO - [0m05:12:44  1 of 2 START test relationships_stg_customers_customer_id__id__source_my_source_raw_customers_  [RUN]
INFO - [0m05:12:44  1 of 2 ERROR relationships_stg_customers_customer_id__id__source_my_source_raw_customers_  [[31mERROR[0m in 0.01s]
INFO - [0m05:12:44  2 of 2 START test source_not_null_my_source_raw_customers_id ................... [RUN]
INFO - [0m05:12:44  2 of 2 PASS source_not_null_my_source_raw_customers_id ......................... [[32mPASS[0m in 0.02s]
INFO - [0m05:12:44
```

### Environment

**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: impala)

**The output of `dbt --version`:**

```markdown
- dbt=1.6.6
- dbt-postgres==1.6.6
```

### Additional Context

The reason might be that `source('my_source', 'raw_customers')` is used in `stg_customers` model's test..right?
But I don't understand why... I targeted just source, not downstream models.

Is there any way to make it test run only `source_not_null_my_source_raw_customers_id` when running `dbt test --select source:my_source.raw_customers`?
