### ISSUE TITLE
unit tests should support enabled config

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9109]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

Folks may want to turn unit tests on/off 

### Acceptance criteria

https://docs.getdbt.com/reference/resource-configs/enabled

Unit tests should support the `enabled` config:

By resource path in `dbt_project.yml`:
```
unit-tests:
  <resource-path>:
    +enabled: true | false
```

Or in unit test definition yml:
```
unit-tests:
  - name: test_my_model
    model: my_model
    config:
      enabled: false
    given:
      - input: ref('my_model_a')
        format: csv
	rows:
          - {id: 1, name: gerda}
          - {id: 2, b: michelle} 
```

### Impact to Other Teams

none

### Will backports be required?

no

**Comment by graciegoheen** [comment]
Notes from estimation:
- tags already works when set in the unit test definition (but ? when set in the `dbt_project.yml`, which requires a config object)
- https://github.com/dbt-labs/dbt-core/pull/8565 (already has meta and tags)

**Comment by graciegoheen** [comment]
Alternative ways to provide folks the ability the exclude all unit tests in a given environment:
- flag
- ...

**Comment by dbeatty10** [comment]
[`enabled`](https://docs.getdbt.com/reference/resource-configs/enabled) can be configured for all the other resource types that I tried out:
- models
- seeds
- snapshots
- sources
- exposures
- semantic models
- generic data tests
- singular data tests
- analyses

| **resource type**   | **`dbt_project.yml`** | **properties YAML** | **`config()` macro** |
|---------------------|-----------------------|---------------------|----------------------|
| models              |           ✅           |          ✅          |           ✅          |
| snapshots           |           ✅           |          ✅          |           ✅          |
| seeds               |           ✅           |          ✅          |           ❌          |
| sources             |           ✅           |          ✅          |           ❌          |
| exposures           |           ✅           |          ✅          |           ❌          |
| semantic models     |           ✅           |          ✅          |           ❌          |
| analyses            |           ❌           |          ✅          |           ✅          |
| singular data tests |           ✅           |          ❌          |           ✅          |
| generic data tests  |           ✅           |          ✅          |           ❌          |
| unit tests          |           ❌           |          ❌         |           ❌          |

<details>
<summary>

### Example files
</summary>

`models/metricflow_time_spine.sql`

```sql
{{ config(materialized='table') }}

select cast({{ dbt.string_literal("2000-01-01") }} as date) as date_day
```

Note: singular data tests can't be disabled within a YAML file (like `models/_properties.yml`,  but either `dbt_project.yml` or `config()` within SQL file are options.

`tests/singular_data_test.sql`

```sql
-- { { config(enabled=false) }}

select *
from {{ ref('metricflow_time_spine' )}}
where 0=1
```

`snapshots/my_snapshot.sql`

```sql
{% snapshot my_snapshot %}

{{
    config(
      target_database=target.database,
      target_schema=target.schema,
      unique_key='id',
      strategy='check',
      check_cols='all',
    )
}}

select 1 as id

{% endsnapshot %}
```

`seeds/my_seed.csv`

```csv
id
1
```

Note: analyses can't be selectively disabled within `dbt_project.yml` -- they inherit the config from `models` within `dbt_project.yml`.

`analyses/my_analysis.sql`

```sql
-- { { config(enabled=false) }}

select 1 as id
```

`models/_properties.yml`

```yaml
models:
  - name: metricflow_time_spine
    config:
      enabled: true
    columns:
      - name: date_day
        data_tests:
          - not_null:
              name: generic_data_test
              config:
                enabled: true

sources:
  - name: my_source
    tables:
      - name: my_source_table
    config:
      enabled: true

seeds:
  - name: my_seed
    config:
      enabled: true

snapshots:
  - name: my_snapshot
    config:
      enabled: true

analyses:
  - name: my_analysis
    config:
      enabled: true

exposures:
  - name: my_exposure
    type: dashboard
    owner:
      email: exposure_owner@my_company.com
    config:
      enabled: true

metrics:
  - name: my_metric
    label: my_metric
    type: derived
    type_params:
      expr: revenue - cost
    config:
      enabled: true

semantic_models:
  - name: my_semantic_model
    model: ref('metricflow_time_spine')
    config:
      enabled: true

saved_queries:
  - name: my_saved_query
    query_params:
      metrics:
        - my_metric
    config:
      enabled: true

unit_tests:
  - name: my_unit_test
    given: []
    model: metricflow_time_spine
    expect:
      rows:
        - {date_day: 2000-01-01}
    # Note: this does NOT have any effect
    # So need to comment out or delete this unit test if its associated model(s) are disabled
    config:
      enabled: true
```

`dbt_project.yml`

```yaml
name: "my_project"

# Note: also disables analyses!
models:
  my_project:
    +enabled: true

seeds:
  my_project:
    +enabled: true

snapshots:
  my_project:
    +enabled: true

sources:
  my_project:
    +enabled: true

exposures:
  my_project:
    +enabled: true

metrics:
  my_project:
    +enabled: true

# Note: inconsistent to have "semantic-models" with a dash, but "data_tests" and "unit_tests" with underscores
semantic-models:
  my_project:
    +enabled: true

# Note: this has no effect -- must configure within properties.yml or config() within the analysis file
analyses:
  my_project:
    +enabled: true

data_tests:
  my_project:
    +enabled: true

# This has no effect -- there is no way to disable a unit test outside of commenting it out or excluding it from the selection.
# It will give the following warning:
#   [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
#   There are 1 unused configuration paths:
#   - unit_tests.my_project
unit_tests:
  my_project:
    +enabled: true
```

Run this command to see which resources are enabled:
```shell
dbt list --resource-type all
```

Then change the `enabled` config for one or more resources and re-run the `dbt list` command above to see if it disappears or not.

</details>

**Comment by dbeatty10** [comment]
### Workarounds

Currently, there's a handful of ways to prevent a unit testing from running:

1. [**Comment** it out](https://stackoverflow.com/questions/2276572/how-do-you-do-block-comments-in-yaml) within the YAML. i.e. add a leading `# ` to the beginning of each line
1. **Delete** the unit test definition entirely
1. **Move** the unit test YAML. i.e. move it to a folder that is outside of the `model-paths: [directorypath]` configured in [`dbt_project.yml`](https://docs.getdbt.com/reference/dbt_project.yml) (e.g. disabled_unit_tests)
1. Add a [`tag`](https://docs.getdbt.com/reference/resource-configs/tags) and then [`--exclude`](https://docs.getdbt.com/reference/node-selection/exclude) that tag (using the ["tag" method](https://docs.getdbt.com/reference/node-selection/methods#the-tag-method))

**Comment by joellabes** [comment]
I need to conditionally enable/disable unit tests in the audit helper repo, because (for example) some use SQL fixtures which have different syntax on different platforms. 

I've gone with this, but I do not like it: 

```
unit_tests:
  [...]
    config:
      tags: "{{ 'works_on_my_machine' if (target.type in ['snowflake', 'bigquery']) else 'skip' }}"
```

And the CircleCI job will have this defined:
dbt build --exclude tag:skip

**Comment by graciegoheen** [comment]
@joellabes sounds like what you're actual after is something like conditional fixtures?
```
unit_tests:
  - name: test_my_model
    model: my_model
    given:
      - input: ref('my_model_a')
        format: csv
        fixture: "{{ 'my_model_a_fixture_snow_bq' if (target.type in ['snowflake', 'bigquery']) else 'my_model_a_fixture_other' }}"
    ...
```
