### ISSUE TITLE
[CT-3403] use of ref() in sources yml as we can use var()

### ISSUE THREAD

**Issue by obar1** [dbt-labs/dbt-core#9114]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

is there a way to use {{ ref('model') }} inside a source yml - I have a case where it makes sense to have that option
I want to have
```
tables:
- name: B_TABLE
  indentifier: b_table
- name C_TABLE
  identifier: c_table"{{ var('some_var') }}"
- name: A_TABLE
  identifier: " {{ ref('a_model_a')}} ""
```

note 

```
tables:
- name: B_TABLE
  indentifier: b_table
- name C_TABLE
  identifier: c_table"{{ var('some_var') }}"
```

works
so logically I see usage of ref() as well

### Describe alternatives you've considered

use sets to hold them in the model
but so I have duplicated code to support the fact I cannot inject ref() in sources yml

### Who will this benefit?

more flexible as I can use ref into source yml
especially for dev

**Comment by jtcohen6** [comment]
@obar1 Thanks for opening!

I feel quite strongly that we shouldn't do this — it means that your source table depends on your model, rather than the other way around! There are few things in dbt more precious than the integrity of the DAG.

If what you want is a naming convention where a source table and a model share (most of) a name, using a variable to set both feels like a much more reasonable way to go.

Is there anything you think I'm missing?

**Comment by obar1** [comment]
hi @jtcohen6 
I have tables (I cannot rename) and I dont want to start creating views on top of it 
in dev/uat/prod all are different 
I wanted a source.yml 
```
- name: some_data_dev
  schema: schema_{{var('env')}}
  tables:
  - name table_usr
    identifier: ref('table_usr')

- name: some_data_uat
  schema: schema_{{var('env')}}
  tables:
  - name table_usr
    identifier: table_usr_uat_20231122

```

dbt run ... env='dev' or 'uat'
