### ISSUE TITLE
[CT-3419] Macro/test takes no keyword argument ‘name’ 

### ISSUE THREAD

**Issue by akhildevvr** [dbt-labs/dbt-core#9143]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The problem I’m having
I am running a dbt built in test named accepted_values for a column and i am giving the name for the test.
However when running dbt compile, i am getting below error : macro ‘dbt_macro__test_accepted_values’ takes no keyword argument ‘name’.

The name argument is the name of the test in the schema.yml file.
```
- name: <column_name>
        description: <desc>
        tests: #Defining the accepted values
          - accepted_values:
              name: <test_name>
              values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
```
Some example code or error messages
```
macro 'dbt_macro__test_accepted_values' takes no keyword argument 'name'
  > in macro test_accepted_values (tests/generic/builtin.sql)
```

### Expected Behavior

DBT compile should run as expected without the above error.

### Steps To Reproduce

Dockerfile contents:

FROM python:3.9.7

RUN echo 'Setting /usr/local/dbt/access the WORKDIR'
WORKDIR /usr/local/dbt/access

RUN echo 'Running apt-get update.'
RUN apt-get update

RUN echo 'Pip install dbt-snowflake.'
RUN pip install dbt-snowflake==1.0.1

### Environment

```markdown
- OS:Docker, Ubuntu
- Python:3.9.7
- dbt-core:1.0.9
```

### Which database adapter are you using with dbt?

snowflake
