### ISSUE TITLE
[CT-3437] add test coverage for unit testing a model that depends on a snapshot

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9179]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

You should be able to unit test models that depend on snapshots! Many projects snapshot sources and build int/fct/dim tables off those. 

```
unit-tests:
  - name: test_is_valid_email_address # this is the unique name of the test
    model: my_model # name of the model I'm unit testing
    given: 
      - input: ref('snapshot_users') # a snapshot
        rows:
         - {user_id: 1, email: cool@example.com,     email_top_level_domain: example.com}
         - {user_id: 2, email: cool@unknown.com,     email_top_level_domain: unknown.com}
         - {user_id: 3, email: badgmail.com,         email_top_level_domain: gmail.com}
         - {user_id: 4, email: missingdot@gmailcom,  email_top_level_domain: gmail.com}
      - input: ref('top_level_domains')
        rows:
         - {tld: example.com}
         - {tld: gmail.com}
    expect: # required: the expected output given the inputs above
      - {user_id: 1, is_valid_email_address: true}
      - {user_id: 2, is_valid_email_address: false}
      - {user_id: 3, is_valid_email_address: false}
      - {user_id: 4, is_valid_email_address: false}
```

### Acceptance criteria

- add a test for unit testing a model that depends on a snapshot

### Impact to Other Teams

none

### Will backports be required?

none
