### ISSUE TITLE
[CT-3448] Conversion Metrics

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#9203]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

The Semantic Layer Team is adding `conversion` type metrics to [dbt-semantic-interfaces](https://github.com/dbt-labs/dbt-semantic-interfaces/) 0.4.latest and 0.5.0. Conversion metrics will be defined in YAML as the following
```yaml
metric:
  type: conversion # new MetricType
  type_params:
    conversion_type_params:
      entity: _entity_ # required
      calculation: _calculation_type_ # optional. default: conversion_rate. options: conversions(buys) or conversion_rate (buys/visits) + more to come
      base_measure: _measure_ # required
      conversion_measure: _measure_ # required
      window: _time_window_ # optional. default: inf. window to join the two events on. Follows similar format as time windows elsewhere (i.e. 7 days)
      constant_properties: # optional. List of constant properties default: None
        - base_property: _string_ # required. A reference to a dimension/entity of the semantic model linked to the base_measure
          conversion_property: _string_ # same as base above, but to the semantic model of the conversion_measure
```

### Acceptance criteria

People can specify `conversion` type metrics, which get parsed and output in the `semantic_manifest.json`. Additionally, metric `depends_on` values are determined via input measures in metrics, thus `base_measure` and `conversion_measure` needs to be fed into this.

### Impact to Other Teams

* Semantic Layer - The semantic layer can't publish about conversion metrics until we support it
* Cloud artifacts - This change will change the v11 manifest in 1.7

### Will backports be required?

Yes, the request is to backport it to 1.7

### Context

Depends on https://github.com/dbt-labs/dbt-semantic-interfaces/issues/210
