### ISSUE TITLE
interface changes to dbt-core, conversion metric spec changes

### ISSUE THREAD

**Issue by WilliamDee** [dbt-labs/dbt-core#9204]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

Add conversion metrics spec properties,
```yml
metric:
  ...
  type_params:
    ...
    conversion_type_params:
      entity: _entity_ # required
      base_measure: _measure_ # required
      conversion_measure: _measure_ # required
      calculation: _calculation_type_ # optional. default: conversion_rate. options: conversions(buys) or conversion_rate (buys/visits) + more to come
      window: _time_window_ # optional. default: inf. window to join the two events on. Follows similar format as time windows elsewhere (i.e. 7 days)
      constant_properties: # optional. List of constant properties default: None
        - base_property: _string_ # required. A reference to a dimension/entity of the semantic model linked to the base_measure
          conversion_property: _string_ # same as base above, but to the semantic model of the conversion_measure
```

### Acceptance criteria

- adds `conversion_type_params` under `Metric.type_params`
- add `CONVERSION` as a `MetricType`

### Impact to Other Teams

SL

### Will backports be required?

Yes, backport to 1.7 latest
