### ISSUE TITLE
[CT-3463] [Feature] Enable column level tests definitions separate from models/sources definitions

### ISSUE THREAD

**Issue by WesleyBatista** [dbt-labs/dbt-core#9226]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The feature request is about the current challenge of having tests for each column defined within the same YAML file as the column's definition, making the YAML file difficult to read and maintain as the number of columns and tests grows.

To address this, it's proposed splitting the tests into separate YAML files. This would allow for cleaner YAML files and easier test management.

However, the current implementation of dbt doesn't support this approach, and attempting to split the tests into separate files results in an error because dbt identifies two schema.yml entries for the same resource.

### Anything else?

As tests coverage of all columns for each model grows, it becomes unpleasant to read the yamls, and difficult to quickly grasp all the columns.

Please consider the following yaml file example:
```yaml
# my_schema.yml
version: 2

models:
  - name: large_table
    columns:
      - name: slightly_unreliable_column
        data_type: STRING
        description: | 
              Sed auctor volutpat faucibus. Proin vehicula gravida lacinia. 
              Fusce fermentum nulla sit amet erat fringilla fringilla.
              Phasellus vitae dictum metus. Nullam sit amet pulvinar metus. Aliquam sem lorem, hendrerit eu.
        tests:
          - unique:
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">10"
          - dbt_utils.relationships_where:
              to: ref('other_model_name')
              field: client_id
              from_condition: id <> '4ca448b8-24bf-4b88-96c6-b1609499c38b'
              to_condition: created_date >= '2020-01-01'
      - name: order_id
        data_type: STRING
        description: "Donec ac commodo massa, at ultrices mi. Duis at aliquet tortor. Phasellus nisi libero, finibus."
        tests:
          - not_null
          - unique:
              config:
                severity: error
                error_if: ">2000"
                warn_if: ">100"
          - relationships:
              to: ref('orders')
              field: id
      - name: my_column
        data_type: STRING
        description: "Duis at aliquet tortor. Phasellus nisi libero, finibus"
        tests:
          - accepted_values:
              values: ["a", "b", "c"]
              config:
                where: "date_column = current_date"

      # Picture 20 or 50 more columns, each with different number and shapes of tests block
```

For the `description` field there's the [Docs Blocks](https://docs.getdbt.com/docs/collaborate/documentation), which allows for writing documentation in a markdown file and later on reference them using `doc` Jinja function.

Similarly to that, it would be cool being able to have tests written somewhere and `dbt` carry on with finding and merging the models and tests for each column, effectively allowing for splitting the model definitions from the tests. Example:

```yaml
# my_schema_models.yml
version: 2

models:
  - name: large_table
    columns:
      - name: slightly_unreliable_column
        data_type: STRING
        description: '{{ doc("my_schema__large_table__slightly_unreliable_column") }}'
      - name: order_id
        data_type: STRING
        description: '{{ doc("my_schema__large_table__order_id") }}'
      - name: my_column
        data_type: STRING
        description: '{{ doc("my_schema__large_table__my_column") }}'
```

```yaml
# my_schema_models_tests.yml
version: 2

models:
  - name: large_table
    columns:
      - name: slightly_unreliable_column
        tests:
          - unique:
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">10"
          - dbt_utils.relationships_where:
              to: ref('other_model_name')
              field: client_id
              from_condition: id <> '4ca448b8-24bf-4b88-96c6-b1609499c38b'
              to_condition: created_date >= '2020-01-01'
      - name: order_id
        tests:
          - not_null
          - unique:
              config:
                severity: error
                error_if: ">2000"
                warn_if: ">100"
          - relationships:
              to: ref('orders')
              field: id
      - name: my_column
        tests:
          - accepted_values:
              values: ["a", "b", "c"]
              config:
                where: "date_column = current_date"
```

Final output of `my_schema_models.yml` is still not ideal due to the noise added by `doc()`, but here one can choose either leave the contents in the yaml or in markdown elsewhere, and depends on how you name each key's name.
Nonetheless, still an improvement as the number of tokens to be parsed by reader is reduced.

Regarding tests though, we currently don't have that option, and if we try with splitting out into separate files like above we currently get the following error:
```
$ dbt test
00:34:26  Running with dbt=1.7.3
00:34:26  target not specified in profile 'jaffle_shop', using 'default'
00:34:26  Registered adapter: duckdb=1.7.0
00:34:26  Encountered an error:
Compilation Error
  dbt found two schema.yml entries for the same resource named large_table. Resources and their associated columns may only be described a single time. To fix this, remove the resource entry for large_table in one of these files:
   - models/my_schema_models_tests.yml
  models/my_schema_models.yml
```

**Comment by dbeatty10** [comment]
> have tests written somewhere and `dbt` carry on with finding and merging the models and tests for each column, effectively allowing for splitting the model definitions from the tests.

This is an interesting idea @WesleyBatista ! 💡 Thank you for providing nice examples as well 🏆

While we can appreciate the problem you are trying to solve of making (large) YAML files easier to read, allowing them to be split into different files would create its own set of problems:
- if there are multiple YAML files relating to the `large_table` model, how would a user find which one contains the definitions they want to edit?
- if there are conflicts between two YAML files, which one "wins"?

Additionally, this would likely be a large lift for us to implement.

This is an intriguing idea, but not something we want to do at this time for the reasons above.

**Comment by vonbraunbates** [comment]
I think there's value in this beyond ease of reading.  I write many tests programmatically (which is almost the only way to do this at scale) and it's a real headache with the current constraint.

As a toy example, let's iterate over all columns in a relation and write a YAML file which includes testing `not_null` on _every column_.  There are already other things in that config file (the `model: ----` line for a start).  As long as you're just appending `column:` blocks, this works as long as you can write the entire file at once.  Now suppose you want to add `unique` tests to _some_ columns.  How do you update the existing file in _exactly_ those places you need the lines added?  It would be much easier to have two files, controlling the two different tests, for the same model.

@dbeatty10  Can you give an example of what two "conflicting" tests would be please?  Presumably is we can define a conflict, it would be possible to drop those contradictory tests and warn the user.  Isn't this what happens when there are conflicting model files?

**Comment by dbeatty10** [comment]
Here's an example @vonbraunbates:

`models/_my_model.yml`

```yaml
models:
  - name: my_model
    description: This is the YAML file I created first
```

`models/_my_model_conflict.yml`

```yaml
models:
  - name: my_model
    description: This is the YAML file I created second
```

Here's the error you will get if you run `dbt list`:
```
19:40:29  Encountered an error:
Compilation Error
  dbt found two schema.yml entries for the same resource named my_model. Resources and their associated columns may only be described a single time. To fix this, remove the resource entry for my_model in one of these files:
   - models/_my_model.yml
  models/_my_model_conflict.yml
```

So we don't currently support the same model name in two different YAML files, and we don't plan to.

We also don't plan to enable column-level tests _separately_ from models either.

### Adding tests programmatically

Can totally understand your desire to generate tests programmatically though!

While I haven't tried it myself, here is one idea for how to merge generated YAML into a pre-existing YAML file: https://github.com/dbt-labs/dbt-codegen/issues/73#issuecomment-1910941957

Would be interested to hear if you try this out and it works out for you!
