### ISSUE TITLE
[Feature] Model Inheritance / Partial Contracts

### ISSUE THREAD

**Issue by serene-capybara** [dbt-labs/dbt-core#9239]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I would like to see a concept of inheritance when defining contracted models. A contracted model could utilize partial table definitions for similar models and enforce constraints that apply to columns in that superclass. Example:
`partials.yaml`
```yaml
partial_models:
- name: some_partial
  columns:
  - name: id
    data_type: int
    constraints:
    - type: primary_key
  - name: fiscal_year
    data_type: int
    constraints:
    - type: check
      expr: fiscal_year between 1980 and 2100
```
And then a model could inherit this partial like so:
`some_model.yaml`
```yaml
models:
- name: some_model
  config:
    contract:
      enforced: true
      inherits:
      - some_partial
  columns:
  - ...Additional columns
```

Here, the `some_model` table would minimally need to have an `id` column that is unique and not null AND a `fiscal_year` column in which the values are in the range [1980, 2100].

### Describe alternatives you've considered

There might be limited ability to do something like this in the `dbt_project.yml` file - I can't say for sure. If it is possible, the amount of configuration would be pretty large for non-trivial applications.

### Who will this benefit?

This feature would be very useful for projects that contain models that share a similar structure. By factoring out repetitive contract patterns, this feature would result in a smaller, DRY-er codebase. Additionally, these partial definitions can offer a higher-level semantic description of the contracts that are enforced on the models.

### Anything else?

The closest analog to these partials would be an Abstract Base Class, which cannot be directly materialized, but whose definitions can be inherited.

I imagine that model yaml configs would "merge" with the configs of the interfaces it inherits, with an order of precedence going something like:
1. `config` blocks in SQL files
2. model yaml configs
3. inherited configs
4. `dbt_project.yml` configs

So, for instance, one could add/overwrite descriptions to the fields in the model yaml.
