### ISSUE TITLE
[CT-3505] [Bug] Unable to access global variables like schemas and database_schemas in dbt_project.yml on-run-end

### ISSUE THREAD

**Issue by gclarkjr5** [dbt-labs/dbt-core#9301]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am currently trying to grant usage for a user to all schemas. I have used the examples provided and have the following:

my macro **grants.sql**
```jinja
{% macro grant_usage_to_schemas(schemas, user) %} -- noqa: LT02
  {% for schema in schemas %}
    grant usage on schema {{ schema }} to {{ user }};
  {% endfor %}
{% endmacro %}
```

my **dbt_project.yml**
```yaml
models:
  warehouse:
    bv:
      +tags: 'core'
      +schema: 'bv'
      +grants:
        select: ['rds_readonly']
    source_core:
      +tags: 'core'
      +schema: 'sc'
      +grants:
        select: ['rds_readonly']
    unified_core:
      +tags: 'core'
      +schema: 'uc'
      +grants:
        select: [ 'rds_readonly' ]
    intermediate:
      +tags: 'core'
      +schema: 'int'
      +grants:
        select: [ 'rds_readonly' ]
  elementary:
    +tags: 'elementary'
    +schema: "elementary"
    +grants:
      select: [ 'rds_readonly' ]


on-run-end:
  - "{{ grant_usage_to_schemas(schemas, 'rds_readonly') }}"
  - "{{ grant_usage_to_schemas(['dbt_bv', 'dbt_sc', 'dbt_uc', 'dbt_int'], 'rds_readonly') }}"
```

while the 2nd on-run-end hook produces what i need, I would have expected the first one to do the same thing. But instead i get an empty output after running **dbt compile**

/target/compiled/warehouse/dbt_project.yml/hooks/warehouse-on-run-end-0.sql
```sql
 -- noqa: LT02
  

```

### Expected Behavior

after running **dbt compile**, I would have expected to see the compiled SQL of my **on-run-end** hooks. Instead, the one where i explicitly use the **schemas** object shows nothing, like in the above code block. However, I would have expected the following.

/target/compiled/warehouse/dbt_project.yml/hooks/warehouse-on-run-end-0.sql
```sql
 -- noqa: LT02
  
    grant usage on schema dbt_bv to rds_readonly;
  
    grant usage on schema dbt_sc to rds_readonly;
  
    grant usage on schema dbt_uc to rds_readonly;
  
    grant usage on schema dbt_int to rds_readonly;

```

/target/compiled/warehouse/dbt_project.yml/hooks/warehouse-on-run-end-1.sql
```sql
 -- noqa: LT02
  
    grant usage on schema dbt_bv to rds_readonly;
  
    grant usage on schema dbt_sc to rds_readonly;
  
    grant usage on schema dbt_uc to rds_readonly;
  
    grant usage on schema dbt_int to rds_readonly;
  
```

### Steps To Reproduce

My full dbt_project.yml

```yaml


name: 'warehouse'
version: '0.0.1'
config-version: 2

profile: 'warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  warehouse:
    bv:
      +tags: 'core'
      +schema: 'bv'
      +grants:
        select: ['rds_readonly']
    source_core:
      +tags: 'core'
      +schema: 'sc'
      +grants:
        select: ['rds_readonly']
    unified_core:
      +tags: 'core'
      +schema: 'uc'
      +grants:
        select: [ 'rds_readonly' ]
    intermediate:
      +tags: 'core'
      +schema: 'int'
      +grants:
        select: [ 'rds_readonly' ]
  elementary:
    +tags: 'elementary'
    +schema: "elementary"
    +grants:
      select: [ 'rds_readonly' ]


on-run-end:
  - "{{ grant_usage_to_schemas(schemas, 'rds_readonly') }}"
  - "{{ grant_usage_to_schemas(['dbt_bv', 'dbt_sc', 'dbt_uc', 'dbt_int'], 'rds_readonly') }}"

```

Create a test model for each schema. Then run **dbt compile**.

### Environment

```markdown
- OS: MacOS Sonoma 14.2
- Docker Container: Linux 6e14e43e7b7f 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 x86_64 GNU/Linux
- Docker Image: ghcr.io/dbt-labs/dbt-postgres:1.5.1
- Python: 3.11.2
- dbt: 1.5.1
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

I can attach the logs if there is no quick solution/the issue is immediately apparent to someone.

**Comment by dbeatty10** [comment]
Thanks for reaching out @gclarkjr5 !

It looks like you are using the [`schemas` variable within the context of an `on-run-end` hook](https://docs.getdbt.com/reference/dbt-jinja-functions/on-run-end-context).

Can you share more about your use-case why you're hoping to see these listed in `/target/compiled/warehouse/dbt_project.yml/hooks/warehouse-on-run-end-0.sql` following a `dbt compile`?

If you run `dbt run` (instead of `dbt compile`), you should see those grant statements show up in both that target file you mentioned as well as `logs/dbt.log`.

Here's a minimal example:

<details>

<summary>

### Minimal example
</summary>

`dbt_project.yml`

```yaml
name: "warehouse"
version: "1.0.0"
config-version: 2
profile: "warehouse"

models:
  warehouse:
    +schema: 'some_schema'

on-run-end:
  - "{{ grant_usage_to_schemas(schemas, 'rds_readonly') }}"
```

`models/my_model.sql`

```
select 1 as id
```

Compile-only first:
```shell
dbt compile
```

Examine the file (`target/compiled/warehouse/dbt_project.yml/hooks/my_project-on-run-end-0.sql`):

```shell
 -- noqa: LT02
  
```

Now actually run the model:
```shell
dbt run -s my_model
```

Examine the file again (`target/compiled/warehouse/dbt_project.yml/hooks/my_project-on-run-end-0.sql`):

```shell
 -- noqa: LT02
  
    grant usage on schema dbt_dbeatty_some_schema to rds_readonly;
  
```

You should see that same content within `logs/dbt.log` as well.

</details>
