### ISSUE TITLE
[CT-3509] [Bug] assets not being copied to target directory with `docs generate --project-dir`

### ISSUE THREAD

**Issue by hvignolo87** [dbt-labs/dbt-core#9308]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Having an `assets-path` defined in the `dbt_project.yml` file:

```yaml
...

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
docs-paths: ["docs"]
asset-paths: ["assets"]

...
```

The directory `assets` is not being copied to `target/assets` when running `dbt docs generate`, as mentioned [in the docs](https://docs.getdbt.com/reference/project-configs/asset-paths). Then, any attempt to load an image from that directory fails. It works fine with external links and when manually copying `assets` to `target/assets`.

### Expected Behavior

The `assets` directory is copied to `target/assets` and the images shown in the documentation

### Steps To Reproduce

1. Create a new dummy dbt project with `dbt init`
2. Complete credentials in `profiles.yml`
3. Add `asset-paths: ["assets"]` to the `dbt_project.yml` file, and create the directory
4. Place any image in the `assets` directory
5. Create a `models/properties.yml` file for the example model, and include a description [like this one](https://docs.getdbt.com/reference/resource-properties/description#include-an-image-from-your-repo-in-your-descriptions)
6. Run `dbt docs generate`
7. Run `dbt docs serve --port 8080 --browser`
8. Verify that no image is shown in your model's description

### Relevant log output

```shell
N/A
```

### Environment

```markdown
- OS: macOS Sonoma 14.2
- Python: 3.10.12
- dbt: 1.5.6
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

I'm running dbt in a virtual environment managed with poetry 1.6.1

**Comment by dbeatty10** [comment]
Thanks for reaching out and providing such a nice set of instructions @hvignolo87 🥇

I tried reproducing the issue you reported using `dbt-postgres==1.5.6`, and everything worked as described in the docs.

I wonder if something is accidentally misspelled or misconfigured in your project that can explain what is going on?

Could you try out the example below and see if it works for you or not?

<details>

<summary>
Example that worked for me
</summary>

### Project files

Here's my exact set of files:

`dbt_project.yml`

```yaml
name: "my_project"
version: "1.0.0"
config-version: 2
profile: "postgres"

asset-paths: ["assets"]
```

`models/customers.sql`

```sql
{{ config(materialized="table") }}

select 1 as customer_id
```

`models/properties.yml`

```yaml
version: 2

models:
  - name: customers
    description: "![dbt Logo](assets/dbt-logo.svg)"

    columns:
      - name: customer_id
        description: Primary key
```

### Commands

```shell
mkdir -p assets
curl -o assets/dbt-logo.svg https://docs.getdbt.com/img/dbt-logo.svg
dbt docs generate
ls -al target/assets
dbt docs serve --port 8080 --browser
```

### Output

```
(postgres_1.5) $ mkdir -p assets                    

(postgres_1.5) $ curl -o assets/dbt-logo.svg https://docs.getdbt.com/img/dbt-logo.svg

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3899  100  3899    0     0  12146      0 --:--:-- --:--:-- --:--:-- 12417
(postgres_1.5) $ dbt docs generate

02:01:57  Running with dbt=1.5.6
02:01:57  Registered adapter: postgres=1.5.6
02:01:57  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 307 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
02:01:57  
02:01:57  Concurrency: 5 threads (target='blue')
02:01:57  
02:01:57  Building catalog
02:01:57  Catalog written to /dbt-core-9308/target/catalog.json
(postgres_1.5) $ ls -al target/assets

total 8
drwxr-xr-x   3 dbeatty  staff    96 Dec 20 18:39 .
drwxr-xr-x  13 dbeatty  staff   416 Dec 20 19:01 ..
-rw-r--r--   1 dbeatty  staff  3899 Dec 20 19:01 dbt-logo.svg
```

<img width="436" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/cb315860-f693-484a-94d9-15af7ef3ac8d">

</details>
