### ISSUE TITLE
[Bug] Input following generic test name is ignored - hides incorrectly configured tests

### ISSUE THREAD

**Issue by d-cole** [dbt-labs/dbt-core#9358]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

For the not_null and unique generic tests, any value after the test name is ignored.

For example the two yamls below run the same test:

```yaml

- name: example_column
  description: "example column description"
  tests:
    - not_null anything_can_be_specified_here_and_ignored
```

```yaml

- name: example_column
  description: "example column description"
  tests:
    - not_null
```

This behaviour makes it easy for incorrectly specified test configs to go unnoticed. For example, if a user fails to specify a `:` before a test filter, the test filter will be ignored. In the example below, both tests will run but the `order_filter` will only be applied to the test for the `example_column_two_filter_applied` column. Since both tests run without warning or error it is easy for the missing `:` and associated filter to be undetected.
```yaml
models:
  - name: my_first_dbt_model
    config:
      order_filter: &order_filter
        config:
          where: "order_id > 21"
    columns:
      - name: example_column_filter_ignored
        tests:
          - not_null *order_filter
      - name: example_column_two_filter_applied
        tests:
          - not_null: *order_filter
```

### Expected Behavior

Warning or error when values after generic test name are ignored.

### Steps To Reproduce

1. Modify not_null or unique generic test specification to have any value after the test name
```yaml

- name: example_column
  description: "example column description"
  tests:
    - not_null anything_can_be_specified_here_and_ignored
```
2. `dbt test`

### Environment

```markdown
- OS: macOS Sonoma 14.2.1
- Python: 3.11.1
- dbt: 1.5.1 & (dbt-bigquery==1.5.3)
```

### Which database adapter are you using with dbt?

bigquery
