### ISSUE TITLE
[CT-3570] [Bug] `tests` -> `data_tests` rename misses model-level tests + tests defined on model versions

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#9411]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In https://github.com/dbt-labs/dbt-core/pull/9201 we renamed `tests` &rarr; `data_tests`, with validation/renaming to offer backwards compatibility for the tens of thousands of projects who have defined generic data tests as `tests`.

The validation/renaming logic works for generic data tests defined on `columns` of models, but it's missing:
- model-level tests
- `tests` defined on `versions` of a versioned model (model-level + column-level)

### Expected Behavior

All of the generic data tests are parsed successfully, as they are in dbt-core v1.7

### Steps To Reproduce

```sql
-- macros/my_cool_tests.sql
{% test my_cool_model_test(model) %}
  select * from {{ model }}
  limit 0
{% endtest %}

{% test my_cool_column_test(model, column_name) %}
  select {{ column_name }} from {{ model }}
  limit 0
{% endtest %}
```

```sql
-- models/my_model_v1.sql
select 1 as id
```
```sql
-- models/my_model_v2.sql
select 1 as id, 'blue' as new_in_v2
```
```yml
models:
  - name: my_model
    tests:
      - my_cool_model_test
    columns:
      - name: id
        tests:
          - my_cool_column_test
    versions:
      - v: 1
      - v: 2
        tests:
          - name: my_cool_versioned_model_test
            test_name: my_cool_model_test
            # this is the same test as above, just with a different name
            # for versioned models, there isn't any way to inherit/extend the tests on the 'base' model config
        columns:
          - name: new_in_v2
            description: "A column that I added in my_model_v2"
            tests:
              - name: my_cool_versioned_column_test
                test_name: my_cool_column_test
```

### Environment

```markdown
- OS: macOS 13.4.1
- Python: 3.10.11
- dbt: main
```
