### ISSUE TITLE
[Bug] materialized configuration parameter not respected when meta tag is used in model yaml file

### ISSUE THREAD

**Issue by carolsimone** [dbt-labs/dbt-core#9435]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Materialization in config parameter in the `.sql` file is not respected (only when meta tags are present in yaml file related to the model).

In code:

_model_a.sql_
```
{{ config(
    materialized = "table",
	dist='all',
	sort='name',
	tags= ['sched_daily',],
) }}

select 'someName' as name, getdate() as etl_updated
```

_schema.yaml_
```
version: 2

models:
  - name: model_a
    description: Hey, some description.
    meta:
      owner: data_team_name
    columns:
      - name: name
        description: a random name
      - name: etl_updated
        description: execution time
```

dbt creates a view instead of a table for unknown reasons. Removing the _meta>owner_ tag, resolve the issue.

### Expected Behavior

Expected behavior is that materialization type within the model is respected independently if there is or not the meta>owner tag in the yaml file.

### Steps To Reproduce

1) Application is containerized. Docker container (or linux container) has the following versioning of the libraries:
```
dbt-core==1.6.9
dbt-redshift==1.4.1
```
Python is the 3.9.18.

2. create `model_a.sql` as: 
```
{{ config(
    materialized = "table",
	dist='all',
	sort='name',
	tags= ['sched_d_1',],
) }}

select 'abc' as name, getdate() as etl_updated
```

The yaml related is: 
```
version: 2

models:
  - name: model_a
    description: Hey, some description.
    meta:
      owner: regulatory_reporting
    columns:
      - name: name
        description: a random name
      - name: etl_updated
        description: execution time
```

3. Running the model: `$ dbt run --select "model_a"`

4.  Log (and information schema) shows me that this is a view:
<img width="808" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/36207761/b0732552-b6ba-40c8-9f36-6f53ecc1951b">

5. Funny thing is that, removing the meta tag right after result in the right materialization type:
<img width="782" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/36207761/35f44cbb-db09-4565-8610-99faafae7b0b">
 

### Relevant log output

```shell
See above.
```

### Environment

```markdown
- OS: Linux 6.4.16-linuxkit (assuming you care the OS Docker is running on)
- Python: Python 3.9.18
- dbt-core==1.6.9
- dbt-redshift==1.4.1 (yep, Redshift is our DWH).
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

Our installation of dbt-core is quite usual. Perhaps, the only _less_ common design choice is that we override the `generate_schema_name` macro with our internal specific mapping (but I don't see how that can cause issues).

**Comment by carolsimone** [comment]
Hi @dbeatty10 , thank you very much for the fast reply.

I have just managed to test both the suggestions just now (dbt-core~=1.4.x with dbt-redshift==1.4.1 and dbt-redshift~=1.6.x with dbt-core==1.6.9). Still, the problem persists. Once I remove the `meta > owner`, in both the cases, the issues solves, hence the config is respected.

**Comment by dbeatty10** [comment]
@carolsimone I'm still not able to reproduce this, so I must either be missing something or there is something else not accounted for in your example.

Could you try reproducing the issue you reported in a fresh environment with no overrides of `generate_schema_name`, etc?

## Things to try

Here's two other things for you to try out:
1. Define `meta` within the `config()` Jinja macro within the model's SQL file
1. Use the `config` key explicitly within the YAML

### Define `meta` within the model's SQL file

```sql
{{ config(
    materialized = "table",
	dist='all',
	sort='name',
	meta={'owner': 'other_team_name'},
	tags= ['sched_d_1',],
) }}

select 'abc' as name, getdate() as etl_updated
```

### Use the `config` key explicitly within the YAML

Something else you can try is adding the `config` key explicitly:

```yaml
version: 2

models:
  - name: model_a
    description: Hey, some description.
    config:
      meta:
        owner: data_team_name
```

instead of:

```yaml
    meta:
      owner: data_team_name
```
