### ISSUE TITLE
[Feature] event time config

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9490]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

There are many use cases where it would be helpful to know the event time field of a given model:
- filtering your project to only run on the last X days of data ([sampling](https://github.com/dbt-labs/dbt-core/issues/8378))
- incremental extensions (lookback window, generate the "where" clause for you)
- intelligently set your clustering key
- etc.

This is similar to a handful of our current configs:
- [loaded_at_field](https://docs.getdbt.com/reference/resource-properties/freshness#loaded_at_field)
- [agg_time_dimension](https://docs.getdbt.com/docs/build/measures#:~:text=Optional-,agg_time_dimension,-The%20time%20field)
- [partition_by](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#partition-clause)
- [unique_key](https://docs.getdbt.com/docs/build/incremental-models#defining-a-unique-key-optional)

We believe this is distinct from your partition key, because it's likely you want to filter on something different (event_time) than what you’re partitioning on (processing_time) - [event time vs processing time](https://www.oreilly.com/library/view/spark-the-definitive/9781491912201/ch22.html#:~:text=At%20a%20higher%20level%2C%20in,processing%20system%20(processing%20time).&text=Event%20time%20is%20the%20time%20that%20is%20embedded%20in%20the%20data%20itself).

We should add a new config to allow folks to specify the event time field for a given model. 

[Notion doc](https://www.notion.so/dbtlabs/Oh-the-places-event-time-could-go-Incremental-models-revamp-3-f8a2a20ea0844c809bae2d58fc1c8826)

### Acceptance Criteria
- Create new config `event_time` that accepts SQL (name of a column, or SQL like `to_date(my_time_col)`; similar to `loaded_at_field`)
```
models:
  - name: my_model
     config:
       event_time: my_time_column
     columns: 
       - name: my_time_column
	 data_type: timestamp
	 ...
```
- config can be set in config block or in `dbt_project.yml` or in schema yml
- config can be set for models and sources

### YML design options

Option 1: field name field
```
models:
  - name: my_model
     config:
       event_time_field: my_time_field
     columns: 
       - name: my_time_field
	 data_type: timestamp
	 ...
	 granularity: day
```
| Pros | Cons |
|-----|------|
| can set in dbt_project.yml | duplicate column name in YML |
| reuse same data_type config block  | |
| could use any sql, like `loaded_at_field`  | |

Option 2: dictionary config
```
models:
  - name: my_model
     config:
       event_time: 
         field_name: my_time_field
         granularity: day
         ...
     columns: 
       - name: my_time_field
	 data_type: timestamp
```

### Open considerations

- What should the config be called? `event_time`, `event_time_field`, something else?
- Should we also support this configuration on other resource types (sources, snapshots, etc.)?

[Additional context here](https://www.notion.so/dbtlabs/Sampling-da9d7e44024b4745ac453a10c63fd781)

# Additional requirement
Add some document about how config on node and config in node.config works(code level implementation) while working on the ticket.
related issue https://github.com/dbt-labs/dbt-core/issues/7157
https://docs.getdbt.com/reference/configs-and-properties

**Comment by dbeatty10** [comment]
I keep a collection of terminology [here](https://github.com/dbeatty10/Phippy-Goes-Fact-Finding?tab=readme-ov-file#cross-walk-of-temporal-terminology). I should add those bi-temporal definitions for "event time" and "processing time" from _Spark: The Definitive Guide_ !

I have a hard time sorting out the differences between all these temporal dimensions and their implications, so that's why I created that repo. It's still hard for me to reason about 😅.

No matter which terminology we land on ("event_time", etc), we'll want to do a good job of explaining what it means and how it fits in.

**Comment by graciegoheen** [comment]
dummy example of what a future incremental model could look like where we automatically generate the `where` clause for you:
```
{{
    config(
        materialized='incremental',
        event_time = {field_name: 'event_time', granularity: 'day'}
        look_back_window = 3
    )
}}

select
    *,
    my_slow_function(my_column)

from raw_app_data.events
```

**Comment by dbeatty10** [comment]
The [dummy example](https://github.com/dbt-labs/dbt-core/issues/9490#issuecomment-1922389804) of `event_time` as a dictionary looks similar to the [`partition_by`](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#partition-clause) config for incremental models in dbt-bigquery:

```yaml
{
  "field": "<field name>",
  "data_type": "<timestamp | date | datetime | int64>",
  "granularity": "<hour | day | month | year>"

  # Only required if data_type is "int64"
  "range": {
    "start": <int>,
    "end": <int>,
    "interval": <int>
  }
}
```

The `range` portion looks similar to the `look_back_window` in the dummy example above.

Within the config, `partition_by` looks like [this](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#partitioning-by-a-date-or-timestamp):
```sql
{{ config(
    materialized='table',
    partition_by={
      "field": "created_at",
      "data_type": "timestamp",
      "granularity": "day"
    }
)}}
```

**Comment by graciegoheen** [comment]
@jtcohen6 and I discussed and believe Option 1 is the best path forward here.

### Acceptance Criteria
- Create new config `event_time` that accepts SQL (name of a column, or SQL like `to_date(my_time_col)`; similar to `loaded_at_field`)
```
models:
  - name: my_model
     config:
       event_time: my_time_column
     columns: 
       - name: my_time_column
	 data_type: timestamp
	 ...
```
- config can be set in config block or in `dbt_project.yml` or in schema yml
- config can be set for models and sources
