### ISSUE TITLE
[Bug] BigQuery labels in model and dbt_project.yml are not additive

### ISSUE THREAD

**Issue by moseleyi** [dbt-labs/dbt-core#9525]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When we set labels in `dbt_project.yml`
```
      finance: 
        +labels:
          domain: finance
          test: "yes"
```

and then extra ones in the model file

```
{{
  config(
    labels = {"type": "financial", "contains_pii": "yes"}
  )
}}
```

The configuration of the model gets overwritten, even though the labels are different.

![image](https://github.com/dbt-labs/dbt-core/assets/16131590/08d2f92f-1a38-410d-9c06-5f101c73bc35)

### Expected Behavior

I expected all labels to be applied and if a label is specified twice then for the single model configuration to take precedence.

### Steps To Reproduce

Create a sample model in folder `models/finance/finance_test.sql` and add the following configuration:

```
{{
  config(
    labels = {"type": "financial", "contains_pii": "yes"}
  )
}}
```

In `dbt_project.yml` add the following configuration:

```
models:
  project_name:
    finance:
      +labels:
        domain: finance
        test: yes
```

### Environment

```markdown
- OS: Windows 10
- Python: 3.8.4rc1
- dbt: 1.7.7
- dbt-bigquery: 1.7.4
```

### Which database adapter are you using with dbt?

bigquery

**Comment by Chr96er** [comment]
This is still an open issue in dbt-core `1.9.5` and dbt-bigquery `1.9.2`. 

It's actually much worse: labels aren't even addititive in different levels of `dbt_project.yml`. E.g. the following only applies `step: profile`:
```
models:
  monitoring:
    +labels:
      resource_creator: dbt
    profile:
      +labels:
        step: profile
```


However, this applies `resource_creator: dbt`:
```
models:
  monitoring:
    +labels:
      resource_creator: dbt
```
