### ISSUE TITLE
[Bug] dbt seed configuration not being applied when the config comes from a schema file

### ISSUE THREAD

**Issue by jsnb-devoted** [dbt-labs/dbt-core#9547]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm having trouble getting the column_type seed configuration to work when: 
the seed is in a nested directory (eg `<project-dir>/data/my_team/my_seeds/seed_table.csv` )
the configuration is in a schema file (as opposed to the dbt project file)
My files looks like:
`<project-dir>/data/my_team/my_seeds/schema.yml `
```
version: 2

seeds:
  - name: seed_table
    config:
      +column_types:
        id: string
```
and my csv `<project-dir>/data/my_team/my_seeds/seed_table.csv` looks like:
```
id
1
2
3
```
When I run `dbt seed -m seed_table --full-refresh` -- the seed command is inferring that the id field is an integer instead of recognizing the column_types configuration I made in the schema file.

There is a note in the docs that states To apply a configuration to one seed only, provide the full resource path (including the project name, and subdirectories) -- but I've tried updating the "name" field as well as putting my project under the seeds field in the yaml file.

Some flails I've tried are prepending the project name
```
version: 2

seeds:
  - name: my_project.seed_table
```
giving the fully qualified id as found in the manifest (`Did not find matching node for patch with name 'my_project.my_team.my_seeds.seed_table' in the 'seeds' section of file 'data/my_team/my_seeds/schema.yml'`):
```
version: 2

seeds:
  - name: my_project.my_team.my_seeds.seed_table
```
adding a key for every dir (this gave a malformed yaml saying `seeds` needs to be a list) 
```
version: 2

seeds:
  my_project:
    my_team:
      my_seeds:
      - name: seed_table
```

### Expected Behavior

I would expect that seed configuration above would get picked because the `name:` field in the schema file matches the file name of the seed.

### Steps To Reproduce

dbt seed -m <seed id> --full-refresh

### Environment

```markdown
- OS:Ubuntu 22.04.3 LTS
- Python: 3.9
- dbt: 1.6.7
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

This is the doc I referenced above
https://docs.getdbt.com/reference/seed-configs#apply-the-schema-configuration-to-one-seed-only 
I would expect to also be able to specify multiple seeds in this file and apply their `column_types`

**Comment by dbeatty10** [comment]
Thanks for reaching out @jsnb-devoted !

Did you try this, by any chance? (No `+` before `column_types`.)

`seeds/_seeds.yml`

```yaml
version: 2

seeds:
  - name: seed_table
    config:
      column_types:
        id: string
```
