### ISSUE TITLE
[Feature] Using multiple selectors

### ISSUE THREAD

**Issue by krisstinkou** [dbt-labs/dbt-core#9554]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

At the moment, dbt allows you to create only one file with selectors. I would like to offer the ability to use multiple selector files to separate selectors logically according to the criteria required by the project.

### Who will this benefit?

Projects with a large number of selectors.

### Are you interested in contributing this feature?

I would like to participate

**Comment by dbeatty10** [comment]
Thanks for reaching out @krisstinkou !

We're not planning on enabling selectors to be split across multiple files at this time. Instead, we're going to stick with just a single `selectors.yml`.

### Workaround

As a workaround, you can use `cat` to concatenate multiple files together like this:

```shell
cat selectors-default.yml selectors-1.yml selectors-2.yml > selectors.yml
```

Here's an example:

`selectors-default.yml`

```yaml
selectors:
  - name: default_selector
    default: true
    definition:
      method: fqn
      value: "*"
```

`selectors-nightly.yml`

```yaml
  - name: nightly
    definition:
      tag: nightly
```

`selectors-daily.yml`

```yaml
  - name: daily
    definition:
      tag: daily
```

Then you can do the following either locally or in CI:

```shell
cat selectors-default.yml selectors-nightly.yml selectors-daily.yml > selectors.yml
```
