### ISSUE TITLE
[Bug] Using filter list with Jinja on metrics and metric input measures causes error when running `dbt parse`

### ISSUE THREAD

**Issue by courtneyholcomb** [dbt-labs/dbt-core#9582]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When you define a metric or metric input measure with a filter list and include Jinja in the list, `dbt parse` triggers an error. Example YAML:
```
metrics:
  - name: new_customer
    description: Unique count of new customers.
    label: New Customers
    type: simple
    type_params:
      measure: customers_with_orders
    filter:
      - "{{ Dimension('customer__customer_type') }}  = 'new'"
```
Running `dbt parse` in a repo with that metric definition triggers this error:
```
Compilation Error
  Could not render {{ Dimension('customer__customer_type') }}  = 'new': 'Dimension' is undefined
```
Meanwhile, if you apply the same filter as a string (example below), no error will be triggered.
```
metrics:
  - name: new_customer
    description: Unique count of new customers.
    label: New Customers
    type: simple
    type_params:
      measure: customers_with_orders
    filter: "{{ Dimension('customer__customer_type') }}  = 'new'"
```

### Expected Behavior

Applying the filter in a list should have the same impact as applying it as a string. Currently this limitation will prevent users from using multiple filters on metrics and metric input measures.

### Steps To Reproduce

1. Add a list-type filter on a metric or a metric input measure in a dbt project
2. Run `dbt parse` in the repo

### Relevant log output

```shell
Output when running dbt parse:

21:05:56  Running with dbt=1.7.3
21:05:56  Registered adapter: duckdb=1.7.0
21:05:56  Encountered an error:
Compilation Error
  Could not render {{ Dimension('customer__customer_type') }}  = 'new': 'Dimension' is undefined
```

### Environment

```markdown
- OS: Mac OSX 13.4.1
- Python: 3.9.16
- dbt: 1.7.3
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

DuckDB
