### ISSUE TITLE
[Bug] parse-time validation when unit testing incremental model

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#9593]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Suppose a model includes the `is_incremental()` macro.

If a unit test is added for that model, then an override like the following is required or else an error will occur:

```yaml
    overrides:
      macros:
        is_incremental: true
```

### Acceptance Criteria

We should have a parse time error when:
- unit testing an incremental model but not providing an override for `is_incremental`
- unit testing an incremental model overriding `is_incremental: true` but NOT providing an input for `this`

### Steps To Reproduce

`models/my_model.sql`

```sql
-- is_incremental: {{ is_incremental() }}
select
    1 as id
```

`models/_unit_tests.yml`

```yaml
unit_tests:

  - name: demo_unit_test_overrides

    given: []

    model: my_model

    expect:
      format: csv
      rows: |
        id
        1
```

```shell
dbt run -s models/my_model.sql
dbt build -s models/my_model.sql
```

💥 See error log below.

In order to work, the following needs to be added within the unit test YAML above:

```yaml
    overrides:
      macros:
        is_incremental: true
```

### Relevant log output

```shell
21:41:03    Compilation Error in unit_test my_model__demo_unit_test_overrides (models/_unit_tests.yml)
  'None' has no attribute 'database'
```

### Environment

```markdown
- OS:
- Python:
- dbt: 1.8 beta
```
