### ISSUE TITLE
YAML Selector Intersection Requires Union

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#9594]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In [this thread](https://dbt-labs.slack.com/archives/C05FWBP9X1U/p1708118788721989) @lbenezra-FA reported an unintuitive behavior where an intersection in YAML selector syntax must be contained in a union, requiring the unnatural syntax:

```
- name: selector_example
    description: this is an example of a job
    definition: 
      union: 
        - intersection:
          - method: tag
            value: finance
          - union: 
            - method: path
              value: models/marts/marketing
            - method: path
              value: models/marts/finance
          - exclude: 
              - method: tag
                value: test_tag
```

The union here seems superfluous as it only contains one operand, the intersection. 

### Expected Behavior

The following should work equally well.

```
- name: selector_example
    description: this is an example of a job
    definition:  
      intersection:
        - method: tag
           value: finance
        - union: 
          - method: path
             value: models/marts/marketing
          - method: path
             value: models/marts/finance
        - exclude: 
            - method: tag
               value: test_tag
```

### Steps To Reproduce

.

### Environment

```markdown
- OS:
- Python:
- dbt:
```
