### ISSUE TITLE
ExposureType - custom extension of EnumType

### ISSUE THREAD

**Issue by daniel-bartley** [dbt-labs/dbt-core#9602]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In the wild, I'm seeing lots of spreadsheets with dependencies on the data warehouse. 
We like to register them as exposures for visibility.
How would we extend ExposureType to include "spreadsheet"? Is it possible without modifying dbt core?

### Describe alternatives you've considered

We use "application" but it's not intuitive. Feels pretentious.

### Who will this benefit?

report builders documenting downstream spreadsheets as dbt exposures.

### Are you interested in contributing this feature?

yes

**Comment by daniel-bartley** [comment]
what if the exposureType enum could be overridden by a variable in dbt_project.yml?

**Comment by shachibista** [comment]
Are there any updates on this issue?

**Comment by dbeatty10** [comment]
@shachibista We haven't done any further refinement on this proposal.

So the options for `type` remain `dashboard`, `notebook`, `analysis`, `ml`, `application`.

As a workaround, you can use the `meta` config to add whatever metadata you want though:

```yaml
exposures:
  - name: weekly_jaffle_metrics
    label: Jaffles by the Week
    type: application
    meta:
      expsoure_subtype: spreadsheet
    depends_on:
      - ref('some_model')
    owner:
      name: Callum McData
      email: data@jaffleshop.com
```
