### ISSUE TITLE
[Bug] can't override namespaced macros for unit testing

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9624]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have a model called `stg_payments` that uses `{{ dbt.current_timestamp() }}`:
```
with

source as (

    select * from {{ source('jaffle_shop',  'orders') }}

),

staged as (

    select 
        id as order_id,
        user_id as customer_id,
        order_date,
        datediff('day', order_date, {{ dbt.current_timestamp() }} ) as days_since_ordered
    from source

)

select * from staged
```

I try to unit test this model with an override for `current_timestamp`:
```
unit_tests:
  - name: test_days_since_ordered
    description: Test my datediff caluclation for days_since_ordered
    model: stg_orders
    overrides:
      macros:
        current_timestamp: "date('2023-01-15')"
    given:
      - input: source('jaffle_shop',  'orders')
        rows:
          - {order_date: 2023-01-01}
    expect:
      rows:
        - {order_date: 2023-01-01, days_since_ordered: 14}
```

My unit test fails because the `current_timestamp` macro is not overridden.

![Screenshot 2024-02-21 at 4 59 25 PM](https://github.com/dbt-labs/dbt-core/assets/53586774/e30aa1f7-5175-42a1-b75c-b6ca80884241)

I get the same failure when I try:
```
    overrides:
      macros:
        dbt.current_timestamp: "date('2023-01-15')"
```
### Current workaround

If I instead don't use `dbt.` in front of my `current_timestamp()` macro, the unit test succeeds as expected:
```
datediff('day', order_date, {{ current_timestamp() }} ) as days_since_ordered

# OR

{{ dbt.datediff('order_date', current_timestamp(), 'day') }} as days_since_ordered
```
![Screenshot 2024-02-21 at 5 01 37 PM](https://github.com/dbt-labs/dbt-core/assets/53586774/1bff7045-dda1-4b46-8461-e07079523aaa)

But this SQL goes against [our documentation](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#current_timestamp) which tells you to use the `current_timestamp()` macro within your dbt SQL files like this:
```
{{ dbt.current_timestamp() }}
```

This also prevents you from being able to override macros from other namespaces (like imported packages). :(

### Expected Behavior

I should be able to override namespaced macros (`dbt.`, `dbt_utils.`, etc.) in my unit test definition.

### Which database adapter are you using with dbt?

snowflake
