### ISSUE TITLE
[Spike+] can't unit test precision 

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9627]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have a `stg_payments` model:
```
with

source as (

    select * from {{ source('stripe',  'payment') }}

),

staged as (

    select
        id as payment_id,
        orderid as order_id,
        paymentmethod as payment_method,
        status,
        -- amount is stored in cents, convert it to dollars
        round(amount / 100, 2) as amount,
        created as created_at
    from source

)

select * from staged
```

I create a unit test to make sure my amount field is doing the proper conversion / rounding:
```
unit_tests:
  - name: test_dollar_conversion # this is the unique name of the test
    model: stg_payments # name of the model I'm unit testing
    given: # the mock data for your inputs
      - input: source('stripe',  'payment')
        rows:
         - {id: 1, amount: 1000}
         - {id: 2, amount: 50}
         - {id: 3, amount: 33.33}
    expect: # the expected output given the inputs above
      rows:
        - {payment_id: 1, amount: 10}
        - {payment_id: 2, amount: 0.5}
        - {payment_id: 3, amount: 0.3333}
```

This passes successfully even though `0.3333` is not technically equivalent to `0.33`. 

Which is surprising given:
![Screenshot 2024-02-21 at 3 33 03 PM](https://github.com/dbt-labs/dbt-core/assets/53586774/f3027a3e-0266-4ae4-8a36-4323386aca32)

Essentially what’s happening is dbt is converting `0.3333` to the output data type (?) to execute the unit test, so `0.33` = `0.33`:
```
try_cast('0.3333' as NUMBER(38,2))
     as amount
```

### Expected Behavior

My unit test should fail because `0.33` does not equal `0.3333`.
Time boxed spike to see if we can do this. If we can, let's complete the work with the spike.

### Steps To Reproduce

See above

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

snowflake (not unique to snowflake)

**Comment by MichelleArk** [comment]
> My hunch is the problem is in the [get_fixture_sql macro](https://github.com/dbt-labs/dbt-adapters/blob/bc3f8eb209abe09cbd26214a497f9a0f41c69e26/dbt/include/global_project/macros/unit_test_sql/get_fixture_sql.sql#L1).

I think it would likely be in [get_expected_sql](https://github.com/dbt-labs/dbt-adapters/blob/bc3f8eb209abe09cbd26214a497f9a0f41c69e26/dbt/include/global_project/macros/unit_test_sql/get_fixture_sql.sql#L47), since that applies casting to the 'expected' structure based on the sql of the model being tested. 

I think there are a couple ways we can approach a fix here: 
1. Explicit option for users to opt out of the automatic casting of `expect` values. E.g. something called '_dbt_skip_casting' or '_dbt_use_literal'. I think this option should only be valid on the `expect` rows as opposed to `input` ones, since there isn't any benefit to being able to test your model given a different input schema as those are fixed in production.
```
unit_tests:
  - name: test_dollar_conversion
    model: stg_payments
    given:
      - input: source('stripe',  'payment')
        rows:
         - {id: 3, amount: 33.3323}
         - {id: 4, amount: 33.3323}
         - {id: 5, amount: 33.3323}
         - {id: 6, amount: 0.55}
         - {id: 8, amount: 0.01111}
         - {id: 9, amount: 0.01111}
    expect:
      rows:
        - {payment_id: 3, dollar: .333}            # expected
        - {payment_id: 4, dollar: 0.333323, _dbt_skip_casting: ["dollar"]}    # explicit option to skip casting for the 'half' fixture, and use its value as a literal. this might mean that the user must provide a different value, e.g. "0.333323::numeric" 

2. Same as (1), but we do it under the hood for certain known warehouse types. e.g, if the type to cast to is numeric, don't safe cast and just plumb the literal value through. 
   * downside: different values may be valid for input/expected specs. e.g: you can just say '0.33' for the input fixture, but if that is not a valid numeric literal, you will need to do something like 0.33::numeric
```
