### ISSUE TITLE
[Feature] Make loader an inheritable property of the source that can also be configured at the source table level.

### ISSUE THREAD

**Issue by alexfetterman** [dbt-labs/dbt-core#9648]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We have a rather complex setup of sources in our project. Some source tables fall under the same general source, but the individual tables under that source have extraction/loading processes that are managed by different tools. As an example, we might have high-level Source 1, and under Source 1 we have Source Table A (loaded by databricks), Source Table B (powered by a legacy Snowflake task), and Source Table C (loaded by our in house ETL tooling).

As an established company migrating off of legacy processes and systems to a more streamlined approach, it would be great if:
1) loader as defined at the high-level Source trickled down to the Source Tables that fell under the Source umbrella
2) we had the ability to define loader at the Source Table level, and that would override however `loader` was defined at the Source.

I imagine in scenarios like the one we described, we would set `loader` as "Various" for Source, and then get specific in the YAML for each of the source tables.

We model project information using dbt project evaluator and dbt artifacts packages to help us keep track of our progress off of legacy systems and this would help.

### Describe alternatives you've considered

We thought of skipping the "loader" field at the Source level and just adding a loader item to the meta dictionary.

### Who will this benefit?

Please see initial comment.

**Comment by dbeatty10** [comment]
Thanks for making this proposal @alexfetterman !

If I understand correctly, you'd like to be able to use [`loader`](https://docs.getdbt.com/reference/resource-properties/loader) at the source table level in order to label source tables coming from different processes:

```yaml
sources:

  - name: source_1
    loader: various
    tables:
      - name: table_a
        loader: databricks
      - name: table_b
        loader: legacy Snowflake task
      - name: table_c
        loader: in-house ETL tooling
```

There's two different ways we'd suggest doing this instead:
1. Separate sources per loader
2. Using meta

I'm going to close this as "not planned" since there are a couple viable alternatives to accomplish the goal.

### 1. Separate sources per loader

```yaml
sources:

  - name: source_1a
    loader: databricks
    tables:
      - name: table_a

  - name: source_1b
    loader: legacy Snowflake task
    tables:
      - name: table_b

  - name: source_1c
    loader: in-house ETL tooling
    tables:
      - name: table_c
```

### 2. Using meta

```yaml
sources:
  - name: source_1
    config:
      meta: {loader: various}

    tables:
      - name: table_a
        config:
          meta: {loader: databricks}

      - name: table_b
        config:
          meta: {loader: legacy Snowflake task}

      - name: table_c
        config:
          meta: {loader: in-house ETL tooling}
```
