### ISSUE TITLE
`catalog.json` file does not contain sources with `dbt-postgres 1.7.8`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#9678]
_Originally posted by @bdtoole in https://github.com/dbt-labs/dbt-core/issues/9119#issuecomment-1965535821_

> @aranke I know this issue is ~3 months old, but I just encountered this problem with  `dbt-postgres 1.7.8`. I was able to revert to 1.6 and the sources were included in the catalog.json as expected, however moving back to 1.7.8 causes this problem to come back.
> 
> If this was resolved at one point within the past few months, could something have undone the fix?

**Comment by dbeatty10** [comment]
@bdtoole https://github.com/dbt-labs/dbt-core/pull/9493  is one possibility. It touched on the same code as this PR, and it fixed https://github.com/dbt-labs/dbt-core/issues/9161

By any chance, are you using a selector similar to this?

```shell
dbt docs generate --select something_other_than_sources
```

If so, what happens if you add [`resource_type:source`](https://docs.getdbt.com/reference/node-selection/methods#the-resource_type-method) like this?

```shell
dbt docs generate --select something_other_than_sources resource_type:source
```

**Comment by bdtoole** [comment]
Hey @dbeatty10 - great thought! I'm not using select criteria like that, but I did override the default selector while I build out our new dbt infrastructure:

```
selectors:
  - name: default_prod
    description: The default production selector
    default: true # Todo for future: Change to include target-aware logic
    definition:
      union:
        - method: fqn # Fully qualified name
          value: '*' # Everything
        - exclude:
            - method: fqn # Fully qualified name
              value: marts
            - method: fqn
              value: staging
```

When I change the default back to false, sources end up in the catalog as expected. When I keep default as true, sources do not end up in the catalog.

**Comment by dbeatty10** [comment]
Could you try adding this to your `selectors.yml`?

```yaml
        - method: resource_type
          value: source # Include sources
```

I tried out the following, and `dbt docs generate` included the sources for me:

`selectors.yml`

```yaml
selectors:
  - name: default_prod
    description: The default production selector
    default: true # Todo for future: Change to include target-aware logic
    definition:
      union:
        - method: fqn # Fully qualified name
          value: '*' # Everything
        - method: resource_type
          value: source # Include sources
        - exclude:
            - method: fqn # Fully qualified name
              value: marts
            - method: fqn
              value: staging
```
