### ISSUE TITLE
[Bug] Parsing Error in dbt Artifacts JSON Conversion of Source with Case-Sensitive Column Names in Filters for dbt freshness

### ISSUE THREAD

**Issue by jjose1508** [dbt-labs/dbt-core#9679]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When the dbt_artifacts.upload_results(results) function is called, an error occurs during the JSON conversion process for artifacts. This happens specifically for a source configuration in src_schema.yml that includes a filter with a case-sensitive column name within apostrophes, as in filter: datediff('day', "_etl_loaded_at", current_timestamp) < 2.  This filter is for dbt freshness checks . The presence of the apostrophe appears to disrupt the JSON parsing, resulting in a failure to upload artifacts.

### Expected Behavior

The dbt_artifacts.upload_results(results) function should process and upload artifacts without errors, even when the src_schema.yml contains filter expressions with case-sensitive column names within apostrophes. The JSON conversion process should handle these cases seamlessly to allow for successful artifact uploads.

### Steps To Reproduce

1. Define a source in src_schema.yml with a filter expression that includes a case-sensitive column name within an SQL function, for example:

```
- identifier: table
  name: table_name
  loaded_at_field: '"timestamp_column"::timestamp_ntz(9)'
  freshness:
    error_after:
      count: 36
      period: minute
    warn_after:
      count: 21
      period: minute
  filter: datediff('day', "_etl_loaded_at", current_timestamp) < 2
```

2. Run a dbt project that includes the dbt_artifacts.upload_results(results) call in an on-run-end hook.
3. Observe the error during the JSON conversion process when the artifact upload is attempted.

### Environment

```markdown
- OS: 
- Python: 3.10.10
- dbt: 1.7
```

### Which database adapter are you using with dbt?

snowflake
