### ISSUE TITLE
[Bug] Conversion metric with window fails on BigQuery

### ISSUE THREAD

**Issue by KayakinKoder** [dbt-labs/dbt-core#9745]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Conversion metrics without a window seem to work as expected with the bigquery adapter.

Adding a window e.g. `window: 7 days` causes the following error:

```
Encountered an error: error querying against the semantic layer: INVALID_ARGUMENT: [FlightSQL] [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: 400 Bad Request
POST https://bigquery.googleapis.com/bigquery/v2/projects/myproject/jobs
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "location": "q",
      "locationType": "parameter",
      "message": "No matching signature for operator > for argument types: TIMESTAMP, DATETIME. Supported signature: ANY > ANY at [46:11]",
      "reason": "invalidQuery"
    }
  ],
  "message": "No matching signature for operator > for argument types: TIMESTAMP, DATETIME. Supported signature: ANY > ANY at [46:11]",
  "status": "INVALID_ARGUMENT"
} (InvalidArgument; Prepare)
```

### Expected Behavior

No error occurs

### Steps To Reproduce

1. Create a simple conversion metric. Our exact metric:

```
- name: conv_completetrial_to_purchases
  description: "Conversion rate from completing trial to purchasing within 7 days"
  type: conversion
  label: Completed First Trial to Purchase Conversion Rate (7-day window)
  type_params:
    conversion_type_params:
      entity: customer
      base_measure:
        name: customers_firsttrialdt
      conversion_measure:
        name: customers_firstpurchdt
      window: 7 days
```

2. Query this metric, and you'll reproduce the error
3. Remove the window, and the query will be successful

### Environment

```markdown
dbt Cloud=1.7.8
Registered adapter: bigquery=1.7.6
```
