### ISSUE TITLE
[Bug] Test dependency not taken into account

### ISSUE THREAD

**Issue by lucianmoldovanu** [dbt-labs/dbt-core#9746]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

There is an issue with test dependencies not being considered in model orchestration/DAG building.
- model `dumb_left` has a FK to model `dumb_right` (using `dbt_snowflake` package in this case, but that's just a detail)
- the two models are orchestrated in different flows, thus I need to occasionally build only the left model (with its dependencies), i.e. `dbt build -m dumb_left`
- if `dumb_right` doesn’t exist or the structure of it has changed (impacting the FK columns), the DAG is not aware that it needs to build `dumb_right` first, and the test will fail

Even when running `dbt build -m +dumb_left+`, DBT DAG is completely unaware that the test definition implies a model dependency.

<img width="714" alt="Screenshot 2024-03-11 at 3 57 09 PM" src="https://github.com/dbt-labs/dbt-core/assets/7854275/7c7ab0b8-6faa-4f98-9f30-0f05b8325be5">

<img width="1616" alt="Screenshot 2024-03-11 at 4 01 25 PM" src="https://github.com/dbt-labs/dbt-core/assets/7854275/8b2e57d1-7faf-4177-9662-5fa9836daa75">

### Expected Behavior

`dbt build` would be able to infer that testing a model requires a specific dependency to another model, and make sure that the respective model is part of the DAG before the test is being executed (especially when the `+model` selector is used

### Steps To Reproduce

1. using dbt core (tested in 1.3 - 1.7) and the dbt_snowflake package
2. create the following models:
    dumb_left.sql
    ```
    select 'a' as what
    union all select 'b' as what
    ```
    
    dumb_left.yml
    ```
    version: 2
    models:
    - name: dumb_left
      columns:
      - name: what
        data_type: string
        tests:
        - dbt_constraints.foreign_key:
            pk_table_name: ref('dumb_right')
            pk_column_name: what
    ```
    
    dumb_right.sql
    ```
    select 'a' as what
    union all select 'b' as what
    union all select 'c' as what
    ```
3. run `dbt build -m +dumb_left`

### Relevant log output

```shell
13:53:42 On [x].dbt_constraints_foreign_key_dumb_left_what__what__ref_dumb_right_.1ff6806b82: Close
13:53:42 Database Error in test dbt_constraints_foreign_key_dumb_left_what__what__ref_dumb_right_ (models/marts/dumb/dumb_left.yml)
  002003 (42S02): SQL compilation error:
  Object '[x].DUMB_RIGHT' does not exist or not authorized.
  compiled Code at default/run/[x]/models/marts/dumb/dumb_left.yml/dbt_constraints_foreign_key_du_74e4f6530b43e3d490098bc4bc008ce9.sql
13:53:42 2 of 2 ERROR dbt_constraints_foreign_key_dumb_left_what__what__ref_dumb_right_ . [ERROR in 0.34s]
```

### Environment

```markdown
- OS: ubuntu 18 / macos latest
- Python: 3.9
- dbt: 1.3 - 1.7
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for writing up such a nice example @lucianmoldovanu ! 🤩

Could you try out adding either `--indirect-selection buildable` or set a `DBT_INDIRECT_SELECTION=buildable` environment variable?

### Short story

The default [indirect selection](https://docs.getdbt.com/reference/node-selection/test-selection-examples?indirect-selection-mode=buildable#indirect-selection) mode is `eager`, which indirectly selects a test if it touches **any** selected resource. However, the `buildable` mode only indirectly selects a test if **all** of its related resources are selected.
 
 ### Longer story

There's more detail [here](https://docs.getdbt.com/reference/global-configs/indirect-selection) and [here](https://docs.getdbt.com/reference/node-selection/test-selection-examples?indirect-selection-mode=buildable#indirect-selection).

My guess is that `buildable` is the best value for most dbt projects. But `eager` is the historical default, and we've left it that way to keep backwards-compatibility.

**Comment by dbeatty10** [comment]
### Visual examples of indirect selection

A DAG like the following will execute all model and test nodes when you run `dbt build`:

<img width="300" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/c6809e99-235e-4a61-a55d-aa9df74f1095">

See below for visual examples of how each of the four modes for [indirect selection](https://docs.getdbt.com/reference/node-selection/test-selection-examples?indirect-selection-mode=buildable#indirect-selection) will affect which nodes are executed when only `model_b` is selected:
1. eager (default)
1. buildable
1. cautious
1. empty

<details>
<summary>

### Project files
</summary>

`models/model_a.sql`

```sql
select 1 as id
```

`models/model_b.sql`

```sql
-- {{ ref("model_a") }}
select 1 as id
```

`models/model_c.sql`

```sql
-- {{ ref("model_b") }}
select 1 as id
```

`models/_models.yml`

```yaml
models:
  - name: model_a
    columns:
      - name: id
        tests:
          - not_null:
              name: test_a
          - relationships:
              name: test_ab
              to: ref("model_b")
              field: id
  - name: model_b
    columns:
      - name: id
        tests:
          - not_null:
              name: test_b
  - name: model_c
    columns:
      - name: id
        tests:
          - relationships:
              name: test_bc
              to: ref("model_b")
              field: id
```

</details>

### Eager (default)

```shell
dbt build -s model_b --indirect-selection eager
```

<img width="350" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/4356ccaa-1877-41cb-ac60-71ab0686a109">

### Buildable

```shell
dbt build -s model_b --indirect-selection buildable
```

<img width="350" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/1a5ffe75-b90d-46a5-8735-01d43b552d16">

### Cautious

```shell
dbt build -s model_b --indirect-selection cautious
```

<img width="350" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/354ce2d7-fdba-4db5-bbed-bfc2af08eddb">

### Empty

```shell
dbt build -s model_b --indirect-selection empty
```

<img width="350" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/f65f12b4-cd69-4973-a640-a02006bd45ca">
