### ISSUE TITLE
[Feature] allow for column-level case sensitivity

### ISSUE THREAD

**Issue by lbenezra-FA** [dbt-labs/dbt-core#9750]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Hello friendz! 
I have a client who is enforcing case-sensitivity on snowflake for column names. We'd like to add this into contracts. Something like: 
`config:
  contract:
    enforced: true
    column_case_sensitive: true | false`

### Describe alternatives you've considered

rebuilding their entire project structure without enforced case-sensitivity.

### Who will this benefit?

All users who enforce case-sensitivity on columns.

**Comment by dbeatty10** [comment]
Hello @lbenezra-FA 👋 !

Could try out the [`quote`](https://docs.getdbt.com/reference/resource-properties/quote) property and see if it works for you?

Our documentation related to quoting case-sensitive columns is spread across a lot of different pages, and we have this ticket to try to tie them together: https://github.com/dbt-labs/docs.getdbt.com/issues/3518.

### Example

Start with this model with a case-sensitive column name:

`models/my_model.sql`

```sql
select 1 as "Id"
```

Then add a contract and use the column-level `quote` property:

`models/_models.yml`

```yaml
models:
  - name: my_model
    config:
      materialized: table
      contract:
        enforced: true
    columns:
      - name: "Id"
        quote: true
        data_type: int
```

Run it, including enforcing the contract:
```shell
dbt build -s my_model
```
