### ISSUE TITLE
[Bug] Referencing a seed table is not working in dbt-core

### ISSUE THREAD

**Issue by hxue3** [dbt-labs/dbt-core#9771]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am trying to reference a seed table I created in dbt-core. I was able to insert the table to target schema. But when I tried to reference the table, it still compile the model with my source table instead of seed table. 

### Expected Behavior

It should return seed table, not source table

### Steps To Reproduce

1. In dbt-core 1.7.10, dbt-bigquery 1.7.6
2. My model named full_comments.sql: where {{ ref('test_full_comments') }} reference to the seed table I created
```
{{ config(materialized='table')}}


SELECT
  cbvdi_report_nbr,
  cbvdides_ent_time,
  cbvdides_ent_date,
  STRING_AGG(cbvdides_comment_x, ' ' ORDER BY cbvdides_seq_r) AS full_comments
FROM

  {{ ref('test_full_comments') }}
GROUP BY
  cbvdi_report_nbr,
  cbvdides_ent_time,
  cbvdides_ent_date
 ```

my schemal.yml file
```
version: 2

models:
  - name: full_comments
    description: "Aggregated comments from source."
    tests:
      - not_null:
          column_name: cbvdi_report_nbr
      - unique:
          column_name: cbvdi_report_nbr
      - dbt_utils.equality:
          compare_model: ref('full_comments_expected')
```

3. Run ``` dbt test -m full_comments ```

### Environment

```markdown
- OS:
- Python:
- dbt:
```
