### ISSUE TITLE
[Bug] indirect_selection in yaml selector definition doesn't work

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#9776]
### Current behavior

With a yaml selector in selectors.yml, indirect_selection doesn't work:
```
  - name: buildable_selector
    definition:
      union:
        - method: path
          value: models/some_output.sql
          children: false
          parents: true
          indirect_selection: buildable
```
If the same selector is defined using the CLI and --indirect-selection, it does work.

### Expected behavior

"indirect_selection" defined in a yaml selectors works as expected.

### Steps to reproduce

Create a selector with indirect_selection defined.

### Additional context

It looks like some code was added last year via a community contributor PR which doesn't function as expected for yaml selectors.

**Comment by ChenyuLInx** [comment]
We should write some brief docs about how selector works in general and have that added to the repo as a read me

**Comment by ChenyuLInx** [comment]
@gshank What I found is that the indirect selection in `selectors.yml` works, but you cannot overwrite it with args passed in from CLI.

So for this [jaffle shop model orders](https://github.com/dbt-labs/jaffle-shop/blob/c708c016d8990f382d4b9951bc72a636283f3cc4/models/marts/orders.yml#L18), I defined a selectors.yml looking like this
```yaml
selectors:
  - name: nodes_to_joy
    definition:
      union:
        - method: path
          value: models/marts/orders.sql
          children: false
          parents: false
          indirect_selection: buildable
```

And by changing the `indirect_selection` value and run `dbt ls --selector nodes_to_joy`, I found that the number of things being selected goes from 3 to 4, which means it works.
But if I try to run `dbt ls --selector nodes_to_joy --indirect-selection eager` with `buildable` as a value inside, I see effect of buildable indirect selection.
If I do not specify `indirect-selection` in the yaml selectors file, I see the effect of eager and can't overwrite it with CLI args.

This doesn't match this PR description but matches what Doug said in his issue. Thouths? Any issue with the way I test?
