### ISSUE TITLE
[Feature] Allow metrics in semantic layer filters

### ISSUE THREAD

**Issue by courtneyholcomb** [dbt-labs/dbt-core#9804]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Allow referencing metrics in filters for metrics, measures, and saved queries. See more detail in the DSI issue here: https://github.com/dbt-labs/dbt-semantic-interfaces/issues/273

Currently, only references to `Dimension`s are allowed within `filter`s like [this](https://docs.getdbt.com/docs/build/metrics-overview#ratio-metrics):
```yaml
metrics:
  - name: The metric name
    type: Categorical or Time or Aggregation
    type_params: specific type params 
    filter: |
      {{ Dimension('entity__name') }} > 0 and {{ Dimension(' entity__another_name') }} is not null
```

Afterwards, references to `Metrics` are also allowed like this:
```yaml
metrics:
  - name: The metric name
    type: Categorical or Time or Aggregation
    type_params: specific type params 
    filter: |
      {{ Metric('bookings', ['user']) }}
```
