### ISSUE TITLE
[Feature] document a materialization

### ISSUE THREAD

**Issue by salimmoulouel** [dbt-labs/dbt-core#9841]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

i want to be able to document a materialization in a yaml file
ex :
```
version: 1
materializations:
  - name: view_create_drop
    description: the doc of my materialization
```
when i execute
`dbt docs generate` and `dbt docs serve` i want to see my materialization documented

**Comment by dbeatty10** [comment]
Thanks for opening this @salimmoulouel !

Good news: there's already a way you can do this by [documenting a macro](https://docs.getdbt.com/faqs/Docs/documenting-macros). It also works in conjunction with [docs blocks](https://docs.getdbt.com/docs/collaborate/documentation#using-docs-blocks) so you don't have to repeat yourself.

The key insight is that for each of your custom materializations, dbt creates a macro in the following format:
```
materialization_{materialization_name}_{adapter}
```

See below for an example you can try out.

Since we already have the capability to document materializations, I'm going to close this as not planned. But any feedback on this capability is welcome.

### Example

`macros/my_materialization.sql`

```sql
{% materialization my_materialization_name, default %}
 -- the logic for your custom materialization is in here
{% endmaterialization %}

{% materialization my_materialization_name, adapter='xyz' %}
 -- if you need custom logic for the xyz adapter, then it is in here
{% endmaterialization %}
```

`macros/_macros.yml`

```yaml
version: 2

# Format of macros for materializations:
#   materialization_{materialization_name}_{adapter}

macros:
  - name: materialization_my_materialization_name_default
    description: '{{ doc("my_materialization") }}'

  - name: materialization_my_materialization_name_xyz
    description: '{{ doc("my_materialization") }}'
```

Generate your docs and launch the website:

```shell
dbt docs generate
dbt docs serve
```

Navigate the to the macros folder and click on one of the macros for your materialization:

<img width="1046" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/f69cd56f-1935-40b4-9d17-a2a7a05bf0e9">
