### ISSUE TITLE
Not able to get columns for source, when defining unit test on a model that depends on source

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9851]
@graciegoheen sure

I have built a dbt model (say `model_a`) which targets a database `_analysis` and depends on source table `source_b` in the database `_raw`. The model builds fine so I know that the model's not buggy but the unit test fails with the following error:

```
Compilation Error in model source_b (models/source.yml)
Not able to get columns for unit test 'source_b' from relation "_raw"."public"."source_b"

> in macro get_fixture_sql (macros/unit_test_sql/get_fixture_sql.sql)
> called by model source_b (models/source.yml)
```

```
- name: test_model_a
    description: "Test model_a model"
    model: model_a
    given: 
      - input: source('_raw', 'source_b')
        rows:
          - ...
      - input: ref('model_c')
        rows:
          - ...
    expect:
      rows:
        - ...
  ```

Additional Information:
- I don't have any unit tests defined for `source_b`
- `"_raw"."public"."source_b"` does exist on the database and is dbt profile is able to read from it (because the model get's built)
- the unit test works if I swap out `source_b` with a `table` materialized model of `source_b` in the unit test and the model for `model_a`. 

I'm happy to share more and/or contribute to resolving this ticket.

_Originally posted by @kd-nishanth in https://github.com/dbt-labs/dbt-core/issues/9686#issuecomment-2032609716_

**Comment by graciegoheen** [comment]
Hi @kd-nishanth - moved this conversation over to a new issue as I don't think this is related to the ephemeral model problem. The direct parents of the model that you’re unit testing (in your example, anything `model_a` depends on - `source_b` and `model_c`) need to exist in the warehouse before you can execute the unit test, because we need to know what field names and data types to use when constructing the unit test sql. 

Given that:
- your `source_b` does exist on the database and is dbt profile is able to read from it
- the unit test works if you swap out `source_b` with a table materialized model of `source_b` in the unit test and the model for `model_a`

this is quite perplexing!

Could you do two things:
- check if you're able to run `dbt docs generate` for `source_b`
- send an example of what your source yml definition looks like for `source_b`

**Comment by ronco** [comment]
Hi @graciegoheen ,

I'm running into this same problem (actually, with the same codebase @kd-nishanth was running into the problem with.  So I'm hoping there is something wrong with our source definition yml.

Here is what we have (anonymized):
```
  - name: _raw
    database: _raw
    schema: public
    description: raw data
    tables:
      - name: source_b
```

Also, I tried running docs for the source, and I keep getting this error (I'm not sure if it's related to our test issue):
```
    Warning: The database user "rwhite@adaction.com" has insufficient permissions to
    query the "svv_table_info" table. Please grant SELECT permissions on this table
    to the "rwhite@adaction.com" user to fetch extended table details from Redshift.
```

Thanks in advance!  It would be fantastic to unlock unit testing with source inputs.
