### ISSUE TITLE
Unit test fixture (csv) returns "" for empty value

### ISSUE THREAD

**Issue by leesiongchan** [dbt-labs/dbt-core#9881]
### Current Behavior

I have fixture with empty value, the unit test will convert them to "" instead of null. It looks like seeding is working by converting them to null but not the case for unit test.

<img width="456" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/324418/fec91b2b-1ace-40a1-970e-7e7f1760feb0">

### Expected Behavior

csv with empty value should be treating as null.

### Steps To Reproduce

1. create a unit test with fixture
2. in the fixture provide empty value
3. run dbt test
4. error - Database Error: invalid input syntax for integer: ""

### Environment

```markdown
- OS:
- Python: 3.12.2
- dbt: 1.8.0-b2 + redshift 1.8.0b2
```

### Which database adapter are you using with dbt?

redshift

**Comment by dbeatty10** [comment]
Thanks for trying out unit testing and reporting this @leesiongchan !

### How dbt seeds treat empty values

https://github.com/dbt-labs/docs.getdbt.com/issues/4867 describes how dbt [seeds](https://docs.getdbt.com/docs/build/seeds) handle empty strings by converting them to SQL `NULL` values.

> It also describes that there are two values that you can't load directly with CSV seeds:
> 
> 1. An empty / blank string (`""` / `''`)
> 1. A string with the value `"null"`

It totally makes sense that you'd expect CSV-formatted unit test fixtures to behave the same way as dbt seeds.

But we'll need to take another look at this and choose between a couple options for moving forward.

### Our options

What's your take on this @graciegoheen? We'd need to choose between one of these two options:

1. Update the behavior of blanks in CSV-formatted unit test fixtures to align with CSV-formatted seeds, accepting that it won't be possible to represent blank strings. Users that need to represent blank strings for unit tests will need to use `dict` rather than `csv` for the `format`.

1. Keep current behavior of blanks in CSV-formatted unit test fixtures, accepting that it is different than CSV-formatted seeds. We'd want to add appropriate caveats in our documentation.

To me the 1st option has more congruence and the 2nd option has more dissonance. What do you think, Grace?

<details>
<summary>

### Reprex
</summary>

`seeds/my_seed.csv`

```csv
animal,legs
duck,2
snake,""
```

`tests/fixtures/my_model_fixture.csv`

```csv
animal,legs
duck,2
snake,
```

`models/animals.sql`

```sql
select 'duck' as animal, 2 as legs union all
select 'snake' as animal, null as legs
```

`models/_unit.yml`

```yaml
unit_tests:

  - name: test_a_9881
    description: https://github.com/dbt-labs/dbt-core/issues/9881
    model: animals
    given: []
    expect:
      # This doesn't work as expected
      format: csv
      fixture: my_model_fixture

  - name: test_b_9881
    description: https://github.com/dbt-labs/dbt-core/issues/9881
    model: animals
    given: []
    expect:
      # But this works as expected
      rows:
        - {animal: duck, legs: 2}
        - {animal: snake, legs: null}
```

Run this command to see how seeds work with a blank value (a blank string `""` converts to a SQL `NULL`):

```shell
dbt show -s seeds/my_seed.csv --output json
```

Run this command and get an unexpected failure:

```shell
dbt build -s my_seed animals --full-refresh
```

</details>
