### ISSUE TITLE
[Unit Testing] Allow explicit precision testing in unit tests

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#9884]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

We cannot currently unit test precision.  The expected outputs get rounded to be the expected datatypes and therefore are not correctly parsed.

from @MichelleArk in #9627 

> I think it would likely be in [get_expected_sql](https://github.com/dbt-labs/dbt-adapters/blob/bc3f8eb209abe09cbd26214a497f9a0f41c69e26/dbt/include/global_project/macros/unit_test_sql/get_fixture_sql.sql#L47), since that applies casting to the 'expected' structure based on the sql of the model being tested.
> 
> I think there are a couple ways we can approach a fix here:
> 
> Explicit option for users to opt out of the automatic casting of expect values. E.g. something called '_dbt_skip_casting' or '_dbt_use_literal'. I think this option should only be valid on the expect rows as opposed to input ones, since there isn't any benefit to being able to test your model given a different input schema as those are fixed in production.

### Acceptance criteria

- A unit test can be written to test precision

### Suggested Tests

model.sql
```
with

source as (

    select * from {{ source('stripe',  'payment') }}

),

staged as (

    select
        id as payment_id,
        orderid as order_id,
        paymentmethod as payment_method,
        status,
        -- amount is stored in cents, convert it to dollars
        round(amount / 100, 2) as amount,
        created as created_at
    from source

)

select * from staged
```

failing unit test yaml
```
unit_tests:
  - name: test_dollar_conversion # this is the unique name of the test
    model: stg_payments # name of the model I'm unit testing
    given: # the mock data for your inputs
      - input: source('stripe',  'payment')
        rows:
         - {id: 2, amount: 50}
         - {id: 3, amount: 33.33}
    expect: # the expected output given the inputs above
      rows:
        - {payment_id: 2, amount: 0.5}
        - {payment_id: 3, amount: 0.3333}
```

passing unit test yaml
```
unit_tests:
  - name: test_dollar_conversion # this is the unique name of the test
    model: stg_payments # name of the model I'm unit testing
    given: # the mock data for your inputs
      - input: source('stripe',  'payment')
        rows:
         - {id: 2, amount: 50}
         - {id: 3, amount: 33.33}
    expect: # the expected output given the inputs above
      rows:
        - {payment_id: 2, amount: 0.50}
        - {payment_id: 3, amount: 0.33}
```

### Impact to Other Teams

none

### Will backports be required?

no

### Context

Outcome of spike in https://github.com/dbt-labs/dbt-core/issues/9627

This will required a change to the macros in `dbt-adapters` and tests in `dbt-core`.  The tests in `dbt-core` will not pass until a new version of `dbt-adapters` is released.

**Comment by ChenyuLInx** [comment]
@graciegoheen  Can you take a look at spike outcome [here](https://github.com/dbt-labs/dbt-core/issues/9627#issuecomment-2021536978)  and see whether you think this ticket is worth pursuing?

**Comment by ChenyuLInx** [comment]
We should document it do not work if we are not moving forward on this ticket.

**Comment by graciegoheen** [comment]
I think we should block this on https://github.com/dbt-labs/dbt-core/issues/8499, since it will likely affect the implementation

**Comment by graciegoheen** [comment]
I think:
- we should try to support this
- I'm not convinced the suggested interface
```
expect:
      rows:
        - {payment_id: 3, dollar: .333}            # expected
        - {payment_id: 4, dollar: 0.333323, _dbt_skip_casting: ["dollar"]}
```
is the best place to put this configuration

The configuration is:
- only relevant for `expect` (?)
- specific to X amount of columns

I'll sync with unit testing squad on what interface would be best here

**Comment by dbeatty10** [comment]
What would be the consequences if we cast the expected output to the widest scale/precision/character size for the relevant data type? i.e., `numeric` without precision and scale rather than `numeric(10, 2)`?

It might give a failing unit test the way that we are after.

My understanding is that we use "wide" data types by default when enforcing [model contracts](https://docs.getdbt.com/reference/resource-configs/contract). I'm not sure if there's prior art we could re-use here.

<details>
<summary>

### Code example
</summary>

`models/source_data.sql`

```sql
select 2 as id, 50 as amount union all
select 3 as id, 33.33 as amount
```

`models/stg_payments.sql`

```sql
with

source as (

    select * from {{ ref("source_data") }}

),

staged as (

    select
        id as payment_id,
        -- amount is stored in cents, convert it to dollars
        cast(round(amount / 100, 2) as numeric(10, 2)) as amount
    from source

)

select * from staged
```

`models/_unit.yml`

```yaml
unit_tests:
  - name: test_dollar_conversion
    model: stg_payments
    given:
      - input: ref("source_data")
        rows:
         - {id: 2, amount: 50}
         - {id: 3, amount: 33.33}
    expect:
      rows:
        - {payment_id: 2, amount: 0.5}
        - {payment_id: 3, amount: 0.3333}
```

```shell
dbt build
cp target/run/my_project/models/_unit.yml/models/test_dollar_conversion.sql analyses/test_dollar_conversion__current.sql
cp analyses/test_dollar_conversion__current.sql analyses/test_dollar_conversion__proposed.sql
```

Then modify `analyses/test_dollar_conversion__proposed.sql` like this:
```diff
55c55
<     cast(0.5 as numeric(10,2))
---
>     cast(0.5 as numeric)
63c63
<     cast(0.3333 as numeric(10,2))
---
>     cast(0.3333 as numeric)
```

```shell
dbt show -s analyses/test_dollar_conversion__current.sql
dbt show -s analyses/test_dollar_conversion__proposed.sql
```

</details>

### Experiment

I tried changing [this line](https://github.com/dbt-labs/dbt-adapters/blob/1557df2fcbf2705b6b4cd490d5d151a5813d8c80/dbt/include/global_project/macros/materializations/tests/unit.sql#L15) to be [`column.dtype`](https://github.com/dbt-labs/dbt-adapters/blob/1557df2fcbf2705b6b4cd490d5d151a5813d8c80/dbt/adapters/base/column.py#L18) instead of [`column.data_type`](https://github.com/dbt-labs/dbt-adapters/blob/1557df2fcbf2705b6b4cd490d5d151a5813d8c80/dbt/adapters/base/column.py#L41).

It worked when I tried it, but only if I quoted the `"0.50"` portion.

```yaml
    expect:
      rows:
        - {payment_id: 2, amount: "0.50"}
        - {payment_id: 3, amount: 0.33}
```

Otherwise, I got this error:

<img width="227" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/2c37e3c6-cafd-4d1a-8773-ee87405fe6cb">

I didn't try any other adapters other than dbt-postgres. The behavior might depend on the way each Python driver renders the value to a string 🤷.

Using the `sql` format like this also worked along with the `data_type` -> `dtype` change:

```yaml
    expect:
        format: sql
        rows: |
          select 2 as payment_id, cast(0.50 as numeric(10, 2)) as amount union all
          select 3 as payment_id, cast(0.33 as numeric(10, 2)) as amount
```
