### ISSUE TITLE
[Feature] Allow whitespace-formatted csv in the new unit tests

### ISSUE THREAD

**Issue by khaledh** [dbt-labs/dbt-core#9893]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The new unit tests capability allows specifying mocked inputs/expected rows using csv. It seems it's strict about whitespace in the csv data, so it's not possible to align the csv columns for readability.

For example, the following works:

```yaml
unit_tests:
  - name: test_demo
    model: demo
    given:
      - input: ref('shops')
        format: csv
        rows: |
          shop_id,country_code
          1,US
          2,US
          3,CA
    expect:
      format: csv
      rows: |
        country_code,number_of_shops
        US,2
        CA,1
```

but the following fails:

```yaml
unit_tests:
  - name: test_demo
    model: demo
    given:
      - input: ref('shops')
        format: csv
        rows: |
          shop_id,country_code
          1,      US
          2,      US
          3,      CA
    expect:
      format: csv
      rows: |
        country_code,number_of_shops
        US,          2
        CA,          1
```

```
actual differs from expected:

@@,country_code,number_of_shops
→ ,US→␣␣␣␣␣␣US ,2
→ ,CA→␣␣␣␣␣␣CA ,1
```

### Describe alternatives you've considered

The alternative is to stick to the condensed csv format, but it hurts readability.

### Who will this benefit?

Users who will rely on the new built-in unit tests.
