### ISSUE TITLE
[Feature] Pass config values to sources in dbt_project.yml 

### ISSUE THREAD

**Issue by holly-evans** [dbt-labs/dbt-core#9990]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In the `dbt_project.yml` file you can pass specific config values to models based on the folder structure. This is extremely useful so that you are not forced to pass in the same value in individual file configs. This pattern however doesn't work for sources. A project.yml section that I would expect to work is as follows:

```yaml
name: 'dbt'
version: '1.0.0'

config-version: 2

...

# This works
models:
  dbt:
    dir1:
      +tags:
        - fancy_tag1
      sub_dir1:
        +enabled: false
      sub_dir2:
        +materialized: ephemeral

    dir2:
      +tags:
        - fancy_tag2

# This doesn't cause an error but doesn't actually work
sources:
  dbt:
    dir1:
      +database:
        - database_1
      sub_dir1:
        +loaded_at_field: col_1
      sub_dir2:
        +description: Sub_dir2 sources live here

    dir2:
      +loader:
        - Kafka
```

### Describe alternatives you've considered

Just specifying the config in each source schema file

### Who will this benefit?

Presumably any dbt users who have sources in separate files but those sources share config elements.

### Are you interested in contributing this feature?

Potentially? If you get me started on which classes to work on

### Anything else?

This is a duplicate of https://github.com/dbt-labs/dbt-core/issues/2542, but it's already closed (this is not implemented as far as I can tell).
